Fix broken Upgrade logic to allow altering of SpySat=Yes
Phobos-developers/Phobos pull request #1062
Opened 2023-05-11 13:31 UTC by DOOMGUY2K

Upgrades in Vanilla can not affect

[SpySat]

This fixes that. 

[Rules]md.ini

[Building] 
PowersUp.Buildings=NARADR
PowersUpBuilding=NARADR
PowersUpToLevel=-1
SpySat=yes

[ParentBuilding]
Upgrades=1

2023-05-11 13:59 UTC, Metadorius requested changes

2023-05-11 13:59 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +            if (pUpGrade && pUpGrade->SpySat)
```suggestion
    if (!pBuilding->Type->SpySat)
    {
        for (const auto& pUpgrade : pBuilding->Upgrades)
        {
            if (pUpGrade && pUpgrade->SpySat)
```

2023-05-11 13:59 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +
```suggestion
DEFINE_HOOK(0x508F82, HouseClass_AI_CheckSpySat_IncludeUpgrades, 0x6)
{
```

2023-05-11 13:59 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +// Fixes broken Upgrade logic to allow SpySat=Yes Code=Otamma / Tested DOOM3DGUY
Code authorship should be put in credits, along with mentions in what's new and docs.

2023-05-11 18:16 UTC, Starkku commented
Calling it 'fixing broken upgrade logic' is bit misleading because there wasn't any handling for upgrade logic ever added beyond power drain/output, SuperWeapons and turrets/weapons, i.e what was used in Tiberian Sun.

2023-05-13 20:33 UTC, Metadorius commented on docs/Whats-New.md
> +
```suggestion
- Upgrade logic to allow altering of SpySat status (by Otamaa)
```

2023-05-13 20:33 UTC, Metadorius commented on CREDITS.md
> +  - Fixed broken Building Upgrade logic for SpySat=yes
```suggestion
  - Upgrade logic to allow altering of SpySat status
```

2023-05-13 20:33 UTC, Metadorius approved these changes

2023-05-13 20:33 UTC, merged