Custom locomotor example implementation
Phobos-developers/Phobos pull request #1069
Opened 2023-05-29 10:16 UTC by Metadorius

New locomotor code is `{74FC2B59-C2D3-47D7-9D10-93436A34EBB9}`.

![wheeee](https://cdn.discordapp.com/attachments/773636942775582720/1112559027835117608/GIF_29.05.2023_4-49-09.gif)

- [ ] Initial working locomotor impl
- [ ] Save/load
- [ ] `IPiggyback`
- [ ] Docs
- [ ] Credits/changelog

Reviews in progress are welcome.

2023-06-10 21:33 UTC, Metadorius commented
Testing is welcome, to test IPiggy some sort of locomotion inflictor/infliction stopper must be made. cc @Starkku @MortonPL @chaserli

2023-06-10 21:34 UTC, Metadorius commented
Also wouldn't mind a review of @CCHyper @tomsons26 on the COM code.

2023-06-11 19:14 UTC, Metadorius commented
Builds now and works w/o issues it seems.

Warheads now have `InflictLocomotor` and `RemoveInflictedLocomotor` boolean tags in order to be able to test IPiggyback. Specify correct `Locomotor` and one of the tags for it to work. Note that due to how it works internally currently it's only usable for the test locomotor.

1. What to do with the locomotor?
2. What to do with the warhead?

Revieeeeeeews and further thoughts please. cc @Starkku @chaserli @MortonPL

2023-06-13 09:08 UTC, Starkku requested changes
Not familiar enough with locomotor logic or COM stuff to comment much on the technical side but it looks correct to me? Assuming it all works correctly. The Warhead stuff is fine too, assuming the same, could look into expanding it to work with other locomotors in future (well, the ones that support piggybacking at least) and/or integration with AE perhaps.

The Warhead feature could technically warrant docs but since it currently only works for testing purposes, I am not sure.

There's a couple of small things that caught my eye though, other than that I guess it is fine.

2023-06-13 09:08 UTC, Starkku commented on src/Locomotion/TestLocomotionClass.cpp
> +		coord.X += radius * std::sin(Angle);
Gives a build warning `'+=': conversion from 'double' to 'T', possible loss of data`

2023-06-13 09:08 UTC, Starkku commented on src/Locomotion/TestLocomotionClass.cpp
> +		coord.Y += radius * std::cos(Angle);
Same as above.

2023-06-13 09:08 UTC, Starkku commented on src/Locomotion/TestLocomotionClass.cpp
> +
Something going on with indentation and newlines here.

2023-06-13 11:08 UTC, Belonit commented
What about semantic tag support for new locomotives?

2023-06-15 13:09 UTC, Starkku approved these changes
LGTM.

2023-06-15 14:05 UTC, MortonPL approved these changes
No comments either.

2023-06-15 14:26 UTC, merged