Add Chronoshift to Enemy Base AI script action
Phobos-developers/Phobos pull request #1077
Opened 2023-06-14 15:44 UTC by Starkku

This is basically bastard child of script actions `53 Gather at Enemy Base` and `56/57 Chronoshift to Enemy Building/Target Type` 

Functions for Chronoshifting team to a specific target as well as acquiring the enemy base gather cell are separate so they can potentially be reused in future for something else if needed.

----------------------------------

##### `10104` Chronoshift to Enemy Base

- Chronoshifts the members of the TeamType using first available `Type=Chronosphere` superweapon to a location within `[General]` -> `AISafeDistance` (plus the additional distance defined in parameter, can be negative) cells from enemy house's base. The superweapon must be charged up to atleast `[General]` -> `AIMinorSuperReadyPercent` percentage of its recharge time to be available for use by this action.

In `aimd.ini`:
```ini
[SOMESCRIPTTYPE]  ; ScriptType
x=10104,n         ; integer, additional distance in cells
```

2023-06-15 14:51 UTC, MortonPL requested changes

2023-06-15 14:51 UTC, MortonPL commented on src/Ext/Script/Body.cpp
> +	}
These logging commands are large and repetitve, maybe you could create texts once and use formatting to insert just the reason for failure?

2023-06-15 15:36 UTC, Starkku commented on YRpp
Yeah probably. Most if not all applications in the game itself use it as negative, there's two constants for it (one which is the result of this formula, another is 1 divided by it) and both of them are negative too.

2023-06-15 15:36 UTC, Starkku commented on src/Ext/House/Body.cpp
> +	double radians = (((atan - Math::HalfPi) * (1.0 / Math::BinaryAngleMagic)) - 0X3FFF) * Math::BinaryAngleMagic;
Fair enough on the constant.

It is pretty much just direct port of the reverse-engineered code for action 53. Might be possible to optimize it but I didn't do much simply cause I suck at math.

2023-06-15 15:37 UTC, Starkku commented on src/Ext/Script/Body.cpp
> +	}
I'll look into it.

2023-07-08 16:07 UTC, MortonPL approved these changes
Looks good, just needs conflict resolution.

2023-07-08 17:50 UTC, merged