Hit bright
Phobos-developers/Phobos pull request #1078
Opened 2023-06-15 15:20 UTC by Super-StarX

same as iron curtain or force shield be hit
now only on shield, enhance if needed.

2023-07-08 16:40 UTC, MortonPL requested changes
Considering that this is effect is referred to as ["Flash" in Ares](https://ares-developers.github.io/Ares-docs/new/warheads/ironcurtain.html#iron-curtain-flash), this should be renamed to remain consistent.

Add an entry in credits, documentation and "What's New".

2023-07-08 16:40 UTC, MortonPL commented on src/New/Type/ShieldTypeClass.h
> +	Valueable<CoordStruct> HitBright;
Use `ColorStruct` instead of `CoordStruct` to store color information.

2023-07-08 16:40 UTC, MortonPL commented on src/New/Type/ShieldTypeClass.h
> +		, HitBright { {0,0,0} }
Use empty initializer list unless you provide a non-zero default value.

2024-07-06 15:58 UTC, Starkku commented
Implemented in more comprehensive way in 7cbffda, so closing this.

2024-07-06 15:58 UTC, closed without merging