Custom wake anim
Phobos-developers/Phobos pull request #1082
Opened 2023-06-18 09:45 UTC by Super-StarX

custom the wake anim when unit on water

2023-06-18 14:01 UTC, Metadorius reviewed
I assume the PR is in progress, it would be better to mark it as draft. Left some recommendations.

2023-06-18 15:54 UTC, Super-StarX commented on src/Ext/TechnoType/Body.cpp
> +AnimTypeClass* TechnoTypeExt::GetWakeAnim(LocomotionClass* pLoco)
but I cant find LinkedTo in it

2023-06-18 16:54 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +AnimTypeClass* TechnoTypeExt::GetWakeAnim(LocomotionClass* pLoco)
Hmm you're right, nevermind then. I was under impression some getter for LinkedTo exists for `ILocomotion`.

2023-07-08 16:24 UTC, MortonPL requested changes
Found two style issues. Please add credits, documentation and "What's New" for this feature.

2023-07-08 16:24 UTC, MortonPL commented on src/Ext/TechnoType/Hooks.cpp
> +	}
```suggestion
    const auto pLoco = static_cast<LocomotionClass*>(pILoco);
    if (!pLoco)
        return 0;
    
    const auto pAnim = TechnoTypeExt::GetWakeAnim(pLoco);
    if (!pAnim)
        return 0;

	R->EDX(pAnim);
	return R->Origin() + 0xC;
```

Avoid nesting blocks if possible. Use `const` when possible.

2023-07-08 16:24 UTC, MortonPL commented on src/Ext/TechnoType/Body.cpp
> +				return pAnim;
Nested braceless blocks are not allowed within braceless blocks. Avoid nesting blocks if possible. Use `const` when possible.

2024-07-07 13:26 UTC, Metadorius commented
Closing in favor of #1258 containing an improved version.

2024-07-07 13:26 UTC, closed without merging