Units AutoDeploy/DeployBlock on Ammo depletion
Phobos-developers/Phobos pull request #1086
Opened 2023-06-24 14:29 UTC by Fryone

Requires units to have:
'Ammo' > 0;
'IsSimpleDeployer=yes';
'Convert.Deploy='.

Parameters
'OnAmmoDepletion_AutoDeploy=true' - uses Deploy command on unit when Ammo gets 0.
'OnAmmoDepletion_DeployUnlockAmount=a' - all Deploy commands on unit will turn into AreaGuard/Guard if Ammo not equals a.

2023-07-08 17:26 UTC, MortonPL requested changes
Looks good, a few minor style and documentation issues remain.

2023-07-08 17:26 UTC, MortonPL commented on src/Ext/TechnoType/Body.cpp
> +	this->OnAmmoDepletion_DeployUnlockAmount.Read(exINI, pSection, "OnAmmoDepletion_DeployUnlockAmount");
```suggestion
	this->OnAmmoDepletion_AutoDeploy.Read(exINI, pSection, "OnAmmoDepletion.AutoDeploy");
	this->OnAmmoDepletion_DeployUnlockAmount.Read(exINI, pSection, "OnAmmoDepletion.DeployUnlockAmount");
```

Replace underscores with dots for INI entries.

2023-07-08 17:26 UTC, MortonPL commented on src/Ext/Unit/Hooks.Unload.cpp
> +	}
```suggestion
		return Ignore;

```

2023-07-08 17:26 UTC, MortonPL commented on src/Ext/Unit/Hooks.Unload.cpp
> +	}
```suggestion
		return Ignore;

```

2023-07-08 17:26 UTC, MortonPL commented on src/Ext/Unit/Hooks.Unload.cpp
> +//#include <Ext/Techno/Body.h>
```suggestion
```

2023-07-08 17:26 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +OnAmmoDepletion_AutoDeploy=true         ; boolean
```suggestion
[SOMEVEHICLE]                          ; VehicleType
OnAmmoDepletion_DeployUnlockAmount=0   ; integer, unit will be allowed to undeploy only if it has at least this much ammo
OnAmmoDepletion_AutoDeploy=true        ; boolean, whether this unit should automatically deploy after running out of ammo
```

2023-07-08 17:26 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +- `OnAmmoDepletion_AutoDeploy` if set, converts/deploys vehicle when ammo is depleted. This feature requires ARES `Convert.Deploy` tag to work correctly.
```suggestion
- `OnAmmoDepletion_AutoDeploy` if set, converts/deploys vehicle when ammo is depleted.
```

2023-07-08 17:26 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +
```suggestion
```
This feature requires `Convert.Deploy` from [Ares’ Type Conversion](https://ares-developers.github.io/Ares-docs/new/typeconversion.html).
```
```

2023-07-08 17:26 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +
(GitHub doesn't like fenced code blocks inside suggestion blocks)

2023-07-08 17:36 UTC, MortonPL approved these changes

2023-08-31 13:16 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +
> (GitHub doesn't like fenced code blocks inside suggestion blocks)

for that you can use 4 ticks instead of 3 ticks

2023-08-31 13:21 UTC, Metadorius reviewed
It would also be good to have this feature at both "sides" of the ammo count, as in instead of
specifying the minimal required amount you can also specify the maximum.

2023-08-31 19:38 UTC, Metadorius approved these changes

2023-09-01 12:09 UTC, merged