Сustomizing Electric Bolt Arcs
Phobos-developers/Phobos pull request #1088
Opened 2023-06-24 17:03 UTC by Fryone

By default, Electric Bolt has 8 Arcs. Now it can be customized per weapon with `IsElectricBolt=yes`
Here is example of Tesla Coil using 1 arc for primary and 32 for secondary weapon.

https://github.com/Phobos-developers/Phobos/assets/30149531/7a88a52c-e26d-44e3-b812-5e698ec0e639

Created with big help from Kerbiter

2023-06-24 17:16 UTC, MortonPL requested changes
Please add an entry in credits, "What's New" and "Fixes & Improvements".

2023-06-24 17:16 UTC, MortonPL commented on src/Ext/WeaponType/Hook.EBolt.cpp
> +	GET_STACK(int, plotIndex, STACK_OFFSET(0x408, -0x3E0))
```suggestion
	GET_STACK(EBolt*, pBolt, 0x40);
	GET_STACK(int, plotIndex, STACK_OFFSET(0x408, -0x3E0));
	BoltTemp::pType = BoltTemp::boltWeaponTypeExt.get_or_default(pBolt);
```

In most cases we group GET macros together.

2023-06-27 10:56 UTC, mevitar commented
If default value is 8, then i think i the documentation should have Bolt.Arcs=8 instead Bolt.Arcs=32 as an example. I'm pretty sure all other entries in the doc follow that formula.

BTW, is there a maximum value? I set Bolt.Arcs=64 and even went into several hundreds, expecting to get something crazy, but couldn't really see any difference. The only noticeable differences are between 0, 1 and default, with anything in between hardly noticeable, and anything beyond default not noticeable at all.

2023-07-08 16:45 UTC, MortonPL approved these changes
Looks good, just needs one more small change in documentation.

2023-07-08 16:45 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +Bolt.Arcs=32
```suggestion
IsElectricBolt=true    ; boolean, vanilla tag
Bolt.Arcs=8            ; integer, number of arcs in a bolt
```

2023-07-08 16:50 UTC, Metadorius approved these changes

2023-07-08 16:50 UTC, merged

2023-07-08 16:51 UTC, Fryone reviewed
I approve