Cloak Enchancement
Phobos-developers/Phobos pull request #1095
Opened 2023-07-04 00:10 UTC by NetsuNegi

In rulesmd.ini:
[CombatDamage]
Cloak.KickOutParasite=boolean (as the default value of technotype)

[AudioVisual]/[TechnoType]
CloakAnim=animation (when start cloaking, this anim will create)
DecloakAnim=animation (when stop cloak, this anim will create)
Cloak.KickOutParasite=boolean (this determines can cloaker kick out parasite if start cloaking, Ares make it always kick out, now we can select it)

2023-07-04 04:40 UTC, NetsuNegi commented
did someone test this ?

2023-07-08 09:21 UTC, mevitar commented
Animations seem to work fine, for inherent and warhead-induced cloak. Haven't tried parasites.

2023-07-08 15:44 UTC, MortonPL requested changes
Please add a credits, documentation and "What's New" entry. I've already edited the description to match the current INI documentation standard.

Left a few comments and one question about a peculiar pointer access.

2023-07-08 15:44 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +	TechnoClass* const pThis = reinterpret_cast<TechnoClass*>(R->ESI<int>() - 0x9C);
What is this magic offseting for?

2023-07-08 15:44 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +	if (const auto pAnimType = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType())->CloakAnim.Get(RulesExt::Global()->CloakAnim))
```suggestion
    const auto pExt = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType());
    if (!pExt )
        return 0;
	if (const auto pAnimType = pExt->CloakAnim.Get(RulesExt::Global()->CloakAnim))
```

If we fail to find TechnoTypeExt (for some reason), we'll try to access null and crash.

2023-07-08 15:44 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +	if (const auto pAnimType = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType())->DecloakAnim.Get(RulesExt::Global()->DecloakAnim))
```suggestion
    const auto pExt = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType());
    if (!pExt )
        return 0;
	if (const auto pAnimType = pExt->CloakAnim.Get(RulesExt::Global()->DecloakAnim))
```

Same as above. If we fail to find TechnoTypeExt (for some reason), we'll try to access null and crash.

2023-07-08 15:44 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +	GET(bool, bRemoved, EBX);
```suggestion
	GET(bool, removed, EBX);
```

Do not use Hungarian notation for anything other than a pointer.

2023-07-08 16:24 UTC, NetsuNegi commented on src/Ext/Techno/Hooks.cpp
> +	TechnoClass* const pThis = reinterpret_cast<TechnoClass*>(R->ESI<int>() - 0x9C);
I just use the same way as Ares 0.A

2023-07-08 16:25 UTC, NetsuNegi commented on src/Ext/Techno/Hooks.cpp
> +	if (const auto pAnimType = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType())->CloakAnim.Get(RulesExt::Global()->CloakAnim))
OK

2023-07-08 16:26 UTC, NetsuNegi commented
> Please add a credits, documentation and "What's New" entry. I've already edited the description to match the current INI documentation standard.
> 
> Left a few comments and one question about a peculiar pointer access.

I'll fix docs tomorrow

2023-07-09 12:23 UTC, mevitar commented
A minor nitpick: in the documentation, the comments about tag entries aren't perfectly aligned like they are for other tags.

2023-07-09 12:28 UTC, NetsuNegi commented
> 

fixed

2023-07-09 12:28 UTC, NetsuNegi commented
> A minor nitpick: in the documentation, the comments about tag entries aren't perfectly aligned like they are for other tags.

fixed

2023-07-09 12:33 UTC, mevitar commented
> fixed
Not for the english version, though. :P

2023-07-09 13:16 UTC, mevitar commented
Maybe my browser simply didn't update its cache last time, but now it looks properly even for the english version.

2024-09-17 21:22 UTC, mevitar commented
Does something here needs testing or is it waiting for fixes?

2024-09-18 02:02 UTC, NetsuNegi commented
> Does something here needs testing or is it waiting for fixes?

Probably not, it just seems like it's just forgotten.

2024-09-18 21:37 UTC, mevitar commented
Everything seems to be working fine.

2024-09-18 21:52 UTC, mevitar commented
Documentation needs more info, specifically, the tags applicable to TechnoTypes, what value they default to.

```
CloakAnim=                   ; Animation
DecloakAnim=                 ; Animation
```
should be:
```
CloakAnim=                   ; Animation, defaults to [AudioVisual]->CloakAnim
DecloakAnim=                 ; Animation, defaults to [AudioVisual]->DecloakAnim
```

`Cloak.KickOutParasite=       ; boolean`
should be:
`Cloak.KickOutParasite=       ; boolean, defaults to [CombatDamage]->Cloak.KickOutParasite`

2026-08-27 07:10 UTC, Coronia approved these changes

2026-08-28 06:56 UTC, merged