Added "VoiceCreated" for units as alternative to CreateSound
Phobos-developers/Phobos pull request #1101
Opened 2023-07-09 12:12 UTC by Fryone

Plays unit's "VoiceCreated" sound entry at it position after being trained/built.

2023-07-09 12:50 UTC, brsajo commented
What's the advantage of using this instead of CreateSound? Or is it just an alias?

2023-07-09 12:53 UTC, Metadorius commented
Think it's played only for the player who built it.

2023-07-09 17:42 UTC, MortonPL reviewed
Looks fine as it is, but I think it'd be a good idea to either play the sound globally (but only to the player) by default or add a toggle for that, because this is how it works in most other RTS games, including later C&C titles.

2023-07-09 17:42 UTC, MortonPL commented on docs/New-or-Enhanced-Logics.md
> +- When unit is created, at it's position `VoiceCreated` will be played.
```suggestion
- When a unit is created, sound specified in `VoiceCreated` will be played for the unit owner.
```

2023-07-09 17:46 UTC, Fryone commented on docs/New-or-Enhanced-Logics.md
> +- When unit is created, at it's position `VoiceCreated` will be played.
Well, I can add toggle to make it global, but with global `VoiceCreated` sound I need to disable EVA's `UnitReady` to prevent 
mess

2023-08-05 07:56 UTC, mevitar commented
I'd like to test the newest build here but can't since it didn't build. :D

2023-08-05 12:23 UTC, Flactine commented
That's great! I like listen "Kirov Reporting" when I have Kirov while my enemies can't heard it.

2023-08-05 12:31 UTC, Fryone commented
> I'd like to test the newest build here but can't since it didn't build. :D

Needs YRPP update with "EVA_UnitReady", that's why it's not building.

2023-08-05 13:30 UTC, Metadorius commented
> > I'd like to test the newest build here but can't since it didn't build. :D
> 
> Needs YRPP update with "EVA_UnitReady", that's why it's not building.

You have to push your YRpp update to a branch too and PR it to YRpp, then it'll build.

2023-08-05 14:47 UTC, Fryone commented
> > > I'd like to test the newest build here but can't since it didn't build. :D
> > 
> > 
> > Needs YRPP update with "EVA_UnitReady", that's why it's not building.
> 
> You have to push your YRpp update to a branch too and PR it to YRpp, then it'll build.

https://github.com/Phobos-developers/YRpp/pull/16

2023-08-07 19:06 UTC, mevitar commented
Seems to work fine.
However, is IsVoiceCreatedGlobal=yes really necessary? Putting Type=global on sound's entry in SoundMD.ini does exactly the same thing.

2023-08-09 21:00 UTC, Fryone commented
> Seems to work fine. However, is IsVoiceCreatedGlobal=yes really necessary? Putting Type=global on sound's entry in SoundMD.ini does exactly the same thing.

When it does not set as global, it also plays "EVA_UnitReady", after creating, like in original

2023-08-09 21:14 UTC, mevitar commented
Ah, right, the doc says that it plays instead of that one.

2023-08-24 17:30 UTC, MortonPL requested changes

2023-08-24 18:23 UTC, MortonPL approved these changes

2023-08-24 18:24 UTC, Metadorius commented on src/Ext/House/Hooks.UnitFromFactory.cpp
> +	return 0x4FB649;
```suggestion

	return 0x4FB649;
```

2023-08-24 18:25 UTC, Metadorius commented on src/Ext/House/Hooks.UnitFromFactory.cpp
> +	if(!RulesExt::Global()->IsVoiceCreatedGlobal.Get())
```suggestion
	if (!RulesExt::Global()->IsVoiceCreatedGlobal.Get())
```

2023-08-31 13:13 UTC, merged