Offline power plant indicator
Phobos-developers/Phobos pull request #1104
Opened 2023-07-16 10:42 UTC by Fryone

If `DrawPowerOffline` is set `true`, `POWEROFF.SHP` indicator will appear on power plants when being infiltrated or drained.
`DrawPowerOffline.Offset` is used to vertically adjust position of indicator.

Uploading poweroff-lowpower.mp4…

2023-08-08 13:42 UTC, MortonPL requested changes

2023-08-08 13:42 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		}
```suggestion
		if (!RulesExt::Global()->DrawPowerOffline)
		{
			R->ESI(pRect);
			return 0x6F534E;
		}
```

2023-08-08 13:42 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		}
```suggestion
		if (!showLowPower || MapClass::Instance->GetCellAt(pBld->GetMapCoords())->IsShrouded())
		{
			R->ESI(pRect);
			return 0x6F534E;
		}

		Point2D nPoint;
		TacticalClass::Instance->CoordsToClient(pBld->GetRenderCoords(), &nPoint);

		nPoint.Y += 22; // wrench offset
		nPoint.Y -= RulesExt::Global()->DrawPowerOffline_Offset;

		const int speed = max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
		const int frame = (FileSystem::POWEROFF_SHP->Frames * (Unsorted::CurrentFrame % speed)) / speed;
		DSurface::Temp->DrawSHP(FileSystem::MOUSE_PAL, FileSystem::POWEROFF_SHP, frame, &nPoint, pRect, BlitterFlags(0xE00), 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
```

2023-08-08 13:42 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +#include <TacticalClass.h>
Why was this added?

2023-08-08 14:17 UTC, Fryone commented on docs/Whats-New.md
> +- Additional sync logging in case of desync errors occuring (by Starkku)
there was conflict

2023-08-08 14:17 UTC, Fryone commented on src/Ext/Techno/Hooks.cpp
> +#include <TacticalClass.h>
not sure - removed

2023-08-08 14:18 UTC, Fryone commented on docs/Fixed-or-Improved-Logics.md
> +- If `DrawPowerOffline` is set, `POWEROFF.SHP` indicator will appear on power plants when being infiltrated or drained.
actually works with force shield too, since it's draining power

2023-08-08 14:25 UTC, Fryone commented on docs/Whats-New.md
> +- Additional sync logging in case of desync errors occuring (by Starkku)
it was moved in 0.3.0.1 later, that's why its duplicated - now fixed

2023-08-26 18:35 UTC, MortonPL requested changes

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Techno/Hooks.cpp
> +
```suggestion
```

2023-08-26 18:35 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +- `DrawPowerOffline.Offset` is used to vertically adjust position of indicator.
I would suggest to add offset on both axes, so that `DrawPowerOffline.Offset=X,Y`

2023-08-26 18:35 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +DrawPowerOffline.Offset=0       ; integer, vertical offset,
```suggestion
DrawPowerOffline.Offset=0       ; integer, vertical offset
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +	{
```suggestion
	auto exit = [pRect]()
	{
		R->ESI(pRect);
		return 0x6F534E
	};
	
	const auto pBld = abstract_cast<BuildingClass*>(pThis)
	if (!pBld)
		return exit();
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		}
```suggestion
		if (!RulesExt::Global()->DrawPowerOffline)
			return exit();
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		}
```suggestion
		if (!showLowPower || MapClass::Instance->GetCellAt(pBld->GetMapCoords())->IsShrouded())
			return exit();
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +	return 0x6F534E;
```suggestion

	return exit();
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +//Addition to Ares' Extras
```suggestion
// Addition to Ares' Extras
```

2023-08-26 18:35 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
Considering that it's not a real animation with `Rate` available, it'd be nice if modders could control the delay between frames.

2023-08-28 14:28 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
Any reason it's not a real animation?

2023-08-28 14:29 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
Because if it's not a real animation but animates like so - it seems to me like reinventing the wheel.

2023-08-28 14:32 UTC, Fryone commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
I used same mechanic as wrench/ivanbomb. I thought to use only POWEROFF at first.
Is it better to use something that would be put in art.ini?

2023-08-28 14:33 UTC, Metadorius requested changes

2023-08-28 14:33 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +	Point2D pict_offset = RulesExt::Global()->DrawPowerOffline_Offset;
We use `camelCase` for locals, not `snake_case`

2023-08-28 14:33 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		DSurface::Temp->DrawSHP(pPalette, pSHP, frame, &nPoint, pRect, BlitterFlags(0xE00), 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
Not exactly sure, but those flags were mapped out somewhere so we don't have to resort to magic numbers.

2023-08-28 14:36 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
Ah, that's why. Well I am not exactly sure why did Westwood decide to use simple SHPs instead of animation types. IMO anims have way more flexibility, like one for example may make an anim that would damage the power plants, and you won't be reinventing the wheel this way, although the handling may be a bit more complex.

2023-08-28 14:38 UTC, Fryone commented on src/Ext/Building/Hooks.cpp
> +		}
Morton suggested lambda-funcs here, but it doesn't compile with "R->", at least for me.

2023-08-28 14:40 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		}
Yeah I am not talking about that, look at different indentation offset
![image](https://github.com/Phobos-developers/Phobos/assets/17500545/c9a1eaf1-d013-4a79-9e16-fe56da5b57fd)

2023-08-28 14:40 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		DSurface::Temp->DrawSHP(pPalette, pSHP, frame, &nPoint, pRect, BlitterFlags(0xE00), 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
What about 1000?

2023-08-28 15:16 UTC, Fryone commented on src/Ext/Building/Hooks.cpp
> +		DSurface::Temp->DrawSHP(pPalette, pSHP, frame, &nPoint, pRect, BlitterFlags(0xE00), 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
`ZGradient::Ground, 1000, 0` here? It's brightness, standart, I think

2023-08-31 11:18 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		DSurface::Temp->DrawSHP(pPalette, pSHP, frame, &nPoint, pRect, BlitterFlags(0xE00), 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
We should add a wrapper over DrawSHP, most arguments are left default in most cases, so it'd be good to hide them.

2023-08-31 11:23 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
Using animations would be much heavier on CPU and more complex IMO, you'd have to worry about attaching/removing whenever power goes on and off, so I didn't suggest it.

2023-08-31 11:35 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
How much heavier on CPU? IMO that's just adding flexibility and extra stuff people can do. Unless the current approach does show only for the owner.

2023-08-31 11:50 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +		const int speed = Math::max(GameOptionsClass::Instance->GetAnimSpeed(14) / 4, 2);
At least 10-20+ anims (*much* more with i.e. MO campaign megamaps) with vanilla+Ares+Phobos logic (warheads, weapons, translucency in particular) every time you hit low power compared to just blitting frames manually.
Of course performance would have to be measured, but so should the need for flexibility in the first place.

2024-12-21 07:56 UTC, closed without merging