Mobile Refinery Logic
Phobos-developers/Phobos pull request #1111
Opened 2023-07-22 16:17 UTC by NetsuNegi

Just like reopen PR#707

Techno can convert the ore under its feet into cash in real time, like GDI's EPIC unit MARV in Command & Conquer 3 Kane's Wrath. It also work on airforce unit.
This logic cannot work on buildings.
Just copying similar logic in MARV in C&C 3.

in `rulesmd.ini`
```
[SOMETECHNO]                          ; InfantryType, UnitType or AircraftType
MobileRefinery=no                     ; boolean
MobileRefinery.TransRate=30           ; unsigned int, how many frames are there between two conversions
MobileRefinery.CashMultiplier=1.0     ; float, it's multiplier of the final cash.
MobileRefinery.AmountPerCell=0        ; unsigned int, how many ore can be convert at one time in each cell
MobileRefinery.FrontOffset=           ; list of double, use cell as unit, multiple values mean that they are effective in multiple cells at the same time
MobileRefinery.LeftOffset=            ; list of double, use cell as unit, multiple values mean that they are effective in multiple cells at the same time
MobileRefinery.Display=yes            ; boolean, should it display translated cash ?
MobileRefinery.DisplayColor=57,197,187; RGB color
MobileRefinery.Anims=                 ; list of animations, if set 8 animations, it will select by techno's body facing, other amount will random select
MobileRefinery.AnimMove=yes           ; should the anim move as techno ?
```
![mobile-refinery](https://github.com/Phobos-developers/Phobos/assets/71598172/f50b2ffb-65ba-42d7-b320-c047aabd9f42)

2023-07-23 14:13 UTC, mevitar commented
The game seems to be ignoring anything i put under MobileRefinery.TransRate= and MobileRefinery.AmountPerCell=. Only defaults are used.

2023-07-23 14:16 UTC, NetsuNegi commented
> The game seems to be ignoring anything i put under MobileRefinery.TransRate= and MobileRefinery.AmountPerCell=. Only defaults are used.

I'll check it later

2023-07-24 01:03 UTC, NetsuNegi commented
> The game seems to be ignoring anything i put under MobileRefinery.TransRate= and MobileRefinery.AmountPerCell=. Only defaults are used.

Sorry, I provided a wrong ini flag XD

2023-07-24 01:04 UTC, NetsuNegi commented
> The game seems to be ignoring anything i put under MobileRefinery.TransRate= and MobileRefinery.AmountPerCell=. Only defaults are used.

Correct flags is "TransDelay"

2023-07-24 22:27 UTC, mevitar commented
I still can't get MobileRefinery.AmountPerCell= to work. MobileRefinery.Display.Houses= also does nothing, "none" and "enemies" still display cash for the owner.
All other tags seem to work fine.

2023-07-26 01:28 UTC, NetsuNegi commented
> I still can't get MobileRefinery.AmountPerCell= to work. MobileRefinery.Display.Houses= also does nothing, "none" and "enemies" still display cash for the owner. All other tags seem to work fine.

Display.House is correctly flag, docs has fixed. AmontPerCell is tiberium amount, not the money amont. How much did you set ?

2023-07-26 20:09 UTC, mevitar commented
> AmontPerCell is tiberium amount, not the money amont. How much did you set ?

1. And 3. And 16. And 100. And 160. Yet no matter what i set, the display still shows the same amount of cash.

2023-07-27 00:09 UTC, NetsuNegi commented
> > AmontPerCell is tiberium amount, not the money amont. How much did you set ?
> 
> Well, 1. And 3. And 16. And 100. And 160. Yet no matter what i set, the display still shows the same amount of cash (as if harvested 1 stage of tiberium).

It should be fixed now.

2023-07-27 13:02 UTC, mevitar commented
Everything seems to be working now.

2023-08-24 18:01 UTC, MortonPL requested changes
Besides commented documentation changes, `MobileRefinery.TransDelay` should be renamed to something clear, like Interval or just Delay.

I disagree with how `MobileRefinery.FrontOffset` and `MobileRefinery.LeftOffset` is used to mark cells used for mining. What's the point of using floating point numbers, when posisiton is rounded to the nearest cell anyway? Moreover, I think that having a pair of X and Y lists (with, say `MobileRefinery.CellN=X,Y`) instead of a list of X,Y pairs complicates configuration and is error-prone.

2023-08-26 20:22 UTC, mevitar commented on docs/New-or-Enhanced-Logics.md
> +MobileRefinery.AnimMove=yes        ; should the anim move as techno ?
> ; list of animations, if set 8 animations, it will select by techno's body facing, other amount will random select

That part is important for the tag's functionality, so i don't think it should be changed to just "; list of animations".

2024-09-17 21:26 UTC, mevitar commented
I guess this one is stuck in limbo since nothing seems to be happening with it? :(

2024-09-18 02:04 UTC, NetsuNegi commented
> I guess this one is stuck in limbo since nothing seems to be happening with it? :(

It just be forgotten for a long time.

2024-09-18 02:05 UTC, NetsuNegi commented
> I guess this one is stuck in limbo since nothing seems to be happening with it? :(

Since it is needed, I will take some time to improve and perfect it later

2024-09-18 07:19 UTC, NetsuNegi commented
I'll resolve all conflict first, then improve it when I got time.

2024-09-18 07:27 UTC, NetsuNegi commented
This PR cannot work now, dont test it

2024-09-18 22:28 UTC, mevitar commented
Everything seems to be working fine.
Although the documentation needs to be updated, as it still says it uses cells for offsets, not leptons.

2024-09-18 22:45 UTC, mevitar commented
Everything seems to be working fine.

Is the offset supposed to be integer or cells? The documentation says cells, and it works as cells ingame, but this one says @NetsuNegi
[offset is integer now](https://github.com/Phobos-developers/Phobos/pull/1111/commits/a6edde9011a3e1ef0aa24340e0248e34523a966e)

2024-09-19 02:57 UTC, NetsuNegi commented
> Everything seems to be working fine.
> 
> Is the offset supposed to be integer or cells? The documentation says cells, and it works as cells ingame, but this one says [offset is integer now](https://github.com/Phobos-developers/Phobos/pull/1111/commits/a6edde9011a3e1ef0aa24340e0248e34523a966e)

same meaning

2024-09-19 12:01 UTC, mevitar commented
So it should be full cells now, and that is why it is integers?
If so, documentation should be changed, because it still says "double" not "integer".

2024-09-19 13:47 UTC, NetsuNegi commented
> So it should be full cells now, and that is why it is integers? If so, documentation should be changed, because it still says "double" not "integer".

done

2025-02-02 07:10 UTC, closed without merging