Infantry and Units health bar customizations
Phobos-developers/Phobos pull request #1113
Opened 2023-07-22 20:31 UTC by Fryone

HealthBar.Sections=17           -     sections in health bar
HealthBar.Border=PIPBRD      -     filename in .shp format
HealthBar.BorderFrame=0      -     frame index of border
HealthBar.BorderAdjust=0      -     horizontal position adjustment

![image](https://github.com/Phobos-developers/Phobos/assets/30149531/55695729-7758-4aef-a848-586ee4043274)

2023-07-22 21:06 UTC, Metadorius requested changes

2023-07-22 21:06 UTC, Metadorius commented on src/Ext/Techno/Hooks.Shield.cpp
> +DEFINE_HOOK(0x6F6846, TechnoClass_DrawHealthBar_CustomHealthBar, 0x6)
Jokes aside, at this point wouldn't it be better to reimplement the whole function to handle whatever other bars a techno might have (like shields) in one place in a unified manner? @Starkku @MortonPL @chaserli whatcha think

2023-07-22 21:06 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +	this->HealthBar_BorderAdjust.Read(exINI, pSection, "HealthBar.BorderAdjust");
How about a `PipBarType`? Like DigitalDisplayType, so you could define the wanted bar once and then specify using `HealthBar=SOMEPIPBARTYPE` for example. Look into DigitalDisplayType for example implementation.

2023-07-22 21:06 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.Border=PIPBRD           ; filename in .shp format without `.shp` extension
A corresponding `Palette` and an ability to specify remappability (not sure if we do this already somewhere? @Starkku) would be delightful.

2023-07-22 21:06 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.BorderAdjust=0          ; integer, horizontal position adjustment
Probably should be vertical, not horizontal.

2023-07-22 21:06 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.Sections=17             ; integer, sections in health bar
Pretty sure it isn't 17 for infantry.

2023-07-22 21:06 UTC, Metadorius commented
Custom Health Bar

2023-07-22 21:46 UTC, Fryone commented on src/Ext/TechnoType/Body.cpp
> +	this->HealthBar_BorderAdjust.Read(exINI, pSection, "HealthBar.BorderAdjust");
I thought about it, but made it per type to get multiple bar lengths for different units width. And stuff like border and/or frame can be used separately, so that multiple units can have changed, just frameindex for example, get same width bar with different borders.

2023-07-22 21:50 UTC, Fryone commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.BorderAdjust=0          ; integer, horizontal position adjustment
It's horizontal. Since you can have multiple length borders in one file, this will help to align border frame to drawn bar. Similar used originally for infantry health bar.

2023-07-22 21:51 UTC, Fryone commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.Sections=17             ; integer, sections in health bar
17, is like default for everything that is not `InfantryType`. 8 is for Infantry.

2023-07-22 21:53 UTC, Fryone commented on src/Ext/Techno/Hooks.Shield.cpp
> +DEFINE_HOOK(0x6F6846, TechnoClass_DrawHealthBar_CustomHealthBar, 0x6)
I think, I can try to put last part of health bar drawing, where actual health is used.

2023-07-22 23:01 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.BorderAdjust=0          ; integer, horizontal position adjustment
meant there's a discrepancy between the text above that and this comment

2023-07-23 09:07 UTC, Fryone commented on docs/Fixed-or-Improved-Logics.md
> +HealthBar.BorderAdjust=0          ; integer, horizontal position adjustment
got it

2023-07-29 11:43 UTC, Metadorius commented
Reposting my ramblings from Discord so they aren't lost.

what I was thinking of for units
```ini
[SOMEPIPBARTYPE]
Section=PIP
Section.Palette=palette.pal
Section.UseRemap=false
Section.FrameGreen=0
Section.FrameYellow=1
Section.FrameRed=2
Section.Count=17
Section.Offset=1,0

Border=PIPBRD
Border.Palette=palette.pal
Border.UseRemap=false
Border.Frame=0
```

This doesn't account the building health bars though:
- length is dynamic (can't specify sections and the border wouldn't work)
- location is dynamic

2023-08-28 14:19 UTC, Metadorius commented
Any further progress? @Fryone

2023-08-28 14:26 UTC, Fryone commented
> Any further progress? @Fryone

now yet, I'm on 1104 right now

2024-09-26 17:55 UTC, closed without merging