Change target Owner on warhead impact
Phobos-developers/Phobos pull request #1118
Opened 2023-08-01 14:43 UTC by Fryone

[SOMEWARHEAD]                         ; Warhead
IsOwnerChanger = yes                  ; boolean
IsOwnerChanger.SetAsMindControl = no  ; boolean, sets control as PermanentMindControl
IsOwnerChanger.ControlAnim = SOMEANIM ; animation on target
IsOwnerChanger.AffectElites = yes     ; boolean, sets if elite veterancy units can be affected to owner change.
IsOwnerChanger.HealthThreshold = 1.0  ; float, target minimal health percentage to have owner changed.

2024-02-23 17:16 UTC, brsajo commented
The `IsOwnerChanger.ControlAnim` anim doesn't follow the unit around like the normal mindcontrol animation as I would have expected. If not a bug, could this be added as an option?

![image](https://github.com/Phobos-developers/Phobos/assets/86821333/dc0ed352-d5e6-44ae-b21b-8c1c7761d03c)

2024-02-23 18:25 UTC, Fryone commented
> The `IsOwnerChanger.ControlAnim` anim doesn't follow the unit around like the normal mindcontrol animation as I would have expected. If not a bug, could this be added as an option?
> 
weird, can you please provide settings for owner changer? As I tested, my anim is following techno as should

2024-02-24 01:44 UTC, chaserli commented
It's a bit messed up.
If this is supposed to be a generic house change, fine, but do not mess up with existing MindControl or permanent mind control logic.
Even if it's for a generic house change, a simple ownership change vtbl call is not sufficient. I would suggest you look at how it's done for permanent mind control in YR and Ares in the first place.
Same issue with all your other pr.
btw it seems the bot is triggered upon every commit, so plz don't just merge from upstream constantly

2024-02-24 08:10 UTC, Fryone commented
I'm not touching MC, instead I'm using PermaMC as it's much simpler. The only issue is that ownerchanged units without PermaMC set, allowed to enter in transports, makes their attached animation (if its looping) dissapear on leaving transport. So I'll just drop it for ares' attached anim instead.

2024-02-25 16:22 UTC, brsajo commented
> weird, can you please provide settings for owner changer? As I tested, my anim is following techno as should

The nightly build seems to be failing so I can't test your latest changes but here's what I have
```
[Controller]
AnimList=YURICNTL
; MindControl=yes
Verses=100%,100%,100%,100%,100%,100%,0%,0%,0%,100%,100%
IsOwnerChanger=yes
IsOwnerChanger.SetAsMindControl=yes
IsOwnerChanger.ControlAnim=MINDANIM
IsOwnerChanger.AffectElites=yes
IsOwnerChanger.HealthThreshold=1.0
```
```
[MINDANIM]
LoopCount=-1
Rate=300
```
I also tested with EMP_FX01 and MINDANIMR (unchanged from vanilla).

2024-02-25 17:08 UTC, Fryone commented
Yep, as I thought, now 'ControlAnim' changed to 'MindControlAnim' and will follow target as it should.

2025-11-25 07:51 UTC, TaranDahl requested changes
Fix the following things, then this can be merged.

2025-11-25 07:51 UTC, TaranDahl commented on src/Ext/WarheadType/Detonate.cpp
> +		if ((GeneralUtils::GetWarheadVersusArmor(this->OwnerObject(), armorType) != 0.0) && (!pTarget->IsMindControlled()))
No need to check for versus, since `CanAffectTarget` will check it.

2025-11-25 07:51 UTC, TaranDahl commented on src/Ext/WarheadType/Detonate.cpp
> +						pOwnerAnim->Owner = pHouse;
Not sure if this is correct. Vanilla MC does not set this.

2025-11-25 07:51 UTC, TaranDahl commented on src/Ext/WarheadType/Body.cpp
> +	this->ChangeOwner_Threshold.Read(exINI, pSection, "IsOwnerChanger.HealthThreshold");
`AffectsBelowPercent` and `AffectsAbovePercent` have already done that.

2025-11-25 07:51 UTC, TaranDahl commented on src/Ext/WarheadType/Body.cpp
> +	this->ChangeOwner_AffectElites.Read(exINI, pSection, "IsOwnerChanger.AffectElites");
This should be another general checker in `WarheadTypeExt::ExtData::CanAffectTarget`.

2025-12-16 10:17 UTC, Coronia commented
changed tag names to `ChangeOwner` and removed repetitive versus and health check

I'm not sure about whether the elite check should be removed tho. There're only a few warhead effects which really need it, so maybe it don't have to be a general check

2025-12-17 03:20 UTC, Fryone commented
maybe `ChangeOwner.MindControlAnim` should be renamed to `ChangeOwner.ControlAnim` too

2025-12-18 15:05 UTC, Coronia approved these changes
removed ChangeOwner.AffectElites due to the introduction of generic veterancy filter: https://github.com/Phobos-developers/Phobos/pull/2008

2025-12-18 15:48 UTC, Fryone commented
Is it worth to add timed control, similar to Dune's Deviator?

2025-12-18 16:04 UTC, Coronia commented
I think it could be useful, but we should also think about how to deal with the interaction of multiple ChangeOwner warheads and other owner changer effects (mind control, capture etc). Maybe it's an easier way to just make the timer be interrupted by another change house event (there's existing hook for that too)

2025-12-22 17:03 UTC, Fryone commented
I thought of something like levels, basic integer that orders different changers (change if new one is higher)

2026-07-25 18:10 UTC, Coronia commented
ChangeOwner.Duration is removed for now cuz it's difficult to handle the scenarios when multiple house changing events are involved. Make it a one time change again until we figure out a better interaction

2026-07-26 07:03 UTC, merged