Customizing whether members are kicked out when an aircraft fires
Phobos-developers/Phobos pull request #1151
Opened 2023-09-08 07:59 UTC by ststl-s

- In yuri's revenge, if aircraft has passengers, aircraft force kick out it's passengers when firing but not fire weapons.
- Now you can decide aircraft kick out it's passengers or not when firing.

In `rulesmd.ini`
```ini
[SOMEWEAPON]
KickOutPassenger=true  ; boolean 
```

2023-09-11 18:19 UTC, itsyuribri commented
Weapon code = 

[LaserGun]
Damage=120
ROF=20
Range=8
Projectile=InvisibleLaser
Speed=100
Report=Laser
Warhead=LaserGunWH
Bright=yes
IsHouseColor=false
LaserInnerColor=200,0,0
LaserOuterColor=200,0,0
LaserDuration=10
IsLaser=true
Burst=2
Anim=LASMUZ
Ammo=1
KickOutPassenger=false



[snapshot-20230911-141542.zip](https://github.com/Phobos-developers/Phobos/files/12579225/snapshot-20230911-141542.zip)

2023-09-11 18:25 UTC, itsyuribri commented
https://drive.google.com/file/d/150L4gLWvvgZ54WaRU8wgJyBIxXi0T3Oq/view?usp=drive_link

2023-09-12 04:46 UTC, ststl-s commented
I con't download that, please send email to `ststl-s@outlook.com`.

> https://drive.google.com/file/d/150L4gLWvvgZ54WaRU8wgJyBIxXi0T3Oq/view?usp=drive_link

2023-09-13 14:45 UTC, MortonPL requested changes

2023-09-13 14:45 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +- Now you can decide aircraft kick out it's passengers or not when firing.
```suggestion
- You can now customize whether aircraft will forcefully eject passengers (vanilla behavior) or fire its weapon when attempting to fire.
```

2023-09-13 14:45 UTC, MortonPL commented on docs/Fixed-or-Improved-Logics.md
> +KickOutPassenger=true  ; boolean
```suggestion
KickOutPassengers=true  ; boolean
```

2023-09-13 14:45 UTC, MortonPL commented on src/Ext/WeaponType/Body.h
> +			, KickOutPassenger { true }
```suggestion
			, KickOutPassengers { true }
```

2023-09-13 14:45 UTC, MortonPL commented on src/Ext/WeaponType/Body.h
> +		Valueable<bool> KickOutPassenger;
```suggestion
		Valueable<bool> KickOutPassengers;
```

2023-09-13 14:45 UTC, MortonPL commented on src/Ext/WeaponType/Body.cpp
> +		.Process(this->KickOutPassenger)
```suggestion
		.Process(this->KickOutPassengers)
```

2023-09-13 14:45 UTC, MortonPL commented on src/Ext/WeaponType/Body.cpp
> +	this->KickOutPassenger.Read(exINI, pSection, "KickOutPassenger");
```suggestion
	this->KickOutPassenger.Read(exINI, pSection, "KickOutPassengers");
```

2023-09-13 14:45 UTC, MortonPL commented on src/Ext/Aircraft/Hooks.cpp
> +	return KickOutPassenger;
```suggestion
	if (!pThis->Passengers.GetFirstPassenger())
		return Fire;

	const auto pWeapon = pThis->GetWeapon(weaponIdx);
	if (!TechnoExt::IsActive(pThis) || !pWeapon)
		return KickOutPassengers;

	const auto pWeaponTypeExt = WeaponTypeExt::ExtMap.Find(pWeapon->WeaponType);
	if (!pWeaponTypeExt)
		return KickOutPassengers;

	return pWeaponExt->KickOutPassengers ? KickOutPassengers : Fire;
```

2023-09-14 06:16 UTC, ststl-s commented
Please test the latest version. If a fatal error occurs again, send me an email. Thank you. @itsyuribri

2023-09-14 20:22 UTC, itsyuribri commented
> Please test the latest version. If a fatal error occurs again, send me an email. Thank you. @itsyuribri [Phobos-pr1151-86ad0acc.zip](https://github.com/Phobos-developers/Phobos/files/12605452/Phobos-pr1151-86ad0acc.zip)

Nope, still crashes

[LaserGun]
Damage=120
ROF=20
Range=8
Projectile=InvisibleStorm
Speed=100
Report=Laser
Warhead=LaserGunWH
Bright=yes
IsHouseColor=false
LaserInnerColor=200,0,0
LaserOuterColor=200,0,0
LaserDuration=10
IsLaser=true
Burst=2
Anim=LASMUZ
Ammo=1
KickOutPassenger=false

dump link 
https://drive.google.com/file/d/1Id0jmLCNThpzZhy8gLHqIRybYkEZV0Nj/view?usp=drive_link

2023-09-15 04:03 UTC, ststl-s commented
> > Please test the latest version. If a fatal error occurs again, send me an email. Thank you. @itsyuribri [Phobos-pr1151-86ad0acc.zip](https://github.com/Phobos-developers/Phobos/files/12605452/Phobos-pr1151-86ad0acc.zip)
> 
> Nope, still crashes
> 
> [LaserGun] Damage=120 ROF=20 Range=8 Projectile=InvisibleStorm Speed=100 Report=Laser Warhead=LaserGunWH Bright=yes IsHouseColor=false LaserInnerColor=200,0,0 LaserOuterColor=200,0,0 LaserDuration=10 IsLaser=true Burst=2 Anim=LASMUZ Ammo=1 KickOutPassenger=false
> 
> dump link https://drive.google.com/file/d/1Id0jmLCNThpzZhy8gLHqIRybYkEZV0Nj/view?usp=drive_link

2023-09-15 04:08 UTC, ststl-s commented
There is no dump file in this link, and it seems like the one you tested on September 11th before. @itsyuribri

2023-09-15 20:42 UTC, itsyuribri commented
> There is no dump file in this link, and it seems like the one you tested on September 11th before. @itsyuribri

It still crashes, and the same weapon code is used, I downloaded the latest one that you sent me. 

https://drive.google.com/file/d/16UonpqpE6sDwMrW6eYDEux4wxamg0IqZ/view?usp=drive_link

2023-09-15 20:43 UTC, itsyuribri commented
It still crashes, and the same weapon code is used, I downloaded the latest
one that you sent me.

https://drive.google.com/file/d/16UonpqpE6sDwMrW6eYDEux4wxamg0IqZ/view?usp=drive_link

On Fri, Sep 15, 2023 at 12:08 AM ststl ***@***.***> wrote:

> There is no dump file in this link, and it seems like the one you tested
> on September 11th before. @itsyuribri <https://github.com/itsyuribri>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Phobos-developers/Phobos/pull/1151#issuecomment-1720501935>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6NUQURWAO3JIK6L6TA6EPDX2PIFVANCNFSM6AAAAAA4P7ZZKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-25 06:41 UTC, ststl-s commented
This dump file can't find reason, but other 3 testers and I didn't crash with YR or Mental Omega or other mods.

2024-07-06 15:10 UTC, Starkku commented
Rebased on develop to fix merge conflicts, amended the hook to remove some unnecessary checks / clean it up. Good to go now so merging.

2024-07-06 15:10 UTC, merged