Reset timer for Super Weapons
Phobos-developers/Phobos pull request #1153
Opened 2023-09-10 10:48 UTC by FS-21

- When this super weapon is clicked forces a countdown restart.
- To make `Warhead or Weapon detonation at target cell` tags work with this feature is needed to set `SW.FirstClickRestartsTimer.AutoFire.ForceDetonations=yes`.
- The cost of the super weapon can be substracted in the first click by setting `SW.FirstClickRestartsTimer.Cost` so `Money.Amount` isn't recommended here.
- `SW.FirstClickRestartsTimer.AutoFire` launchs the super weapon at the end of the first counter restart. Don't use the tag `SW.AutoFire`.
- Designed with upgrades (or research) in mind, simplifiyng the number of workarounds. Probably some Ares tags are still recommended for this job.

In `rulesmd.ini`:

[SOMESW]                                        ; Super Weapon
SW.FirstClickRestartsTimer=no                   ; boolean
SW.FirstClickRestartsTimer.AutoFire=no          ; boolean
SW.FirstClickRestartsTimer.ForceDetonations=no  ; boolean
SW.FirstClickRestartsTimer.Cost=0               ; integer, always substract money
Message.InsufficientFunds=                      ; CSF entry key
Message.RestartedTimer=                         ; CSF entry key
EVA.RestartedTimer=                             ; EVA entry

2023-09-10 10:56 UTC, FS-21 commented
Example in action of what I'm going to use in my case (Once upgraded all units will be converted into the new model and the old version will be replaced in the sidebar thanks to the "LimboDelivery" tags):

[LimboUpgrade_SW01]
UIName=NAME:LimboUpgrade_SW01
UIDescription=UID:LimboUpgrade_SW01
Name=Devout upgrade
SidebarPCX=limboupgrade_sw01.pcx
IsPowered=false
DisableableFromShell=no
FlashSidebarTabFrames=0
RechargeTime=5
SW.InitialReady=yes
Type=GenericWarhead
Action=Custom
AIDefendAgainst=no
SW.CreateRadarEvent=no
ShowTimer=no
Range=1
LineMultiplier=1
EVA.Ready=EVA_UpgradeComplete
Text.Ready=NOSTR:
Text.Preparing=NOSTR:
RechargeVoice=;
ChargingVoice=;
ImpatientVoice=; 
EVA.Impatient=EVA_UpgradeInProgress
SuspendVoice=;
SW.MaxCount=1
SW.Shots=1
SW.UseAITargeting=yes
SW.AITargeting.Constraints=none
SW.AITargeting=Self
Cursor=GenericGreen ; No cursor will be used here!
NoCursor=NoGenericGreen ; No cursor will be used here!
SW.FireIntoShroud=yes
; Make new upgraded object the new default unit in the sidebar
LimboDelivery.Types=LIMBOUPGRADE_01   ; List of BuildingTypes that will use in "Prerequisites" tag the new upgraded unit
LimboDelivery.IDs=1
;LimboDelivery.RollChances=100%
SW.NegBuildings=LIMBOUPGRADE_01 ; Once upgraded this can't be upgraded again using this SW
; Convert existing old objects in the battlefield
Convert.From=DEVOUT ; Old unit
Convert.To=DEVOUT2 ; New unit
Convert.AffectedHouses=owner
; Tags related to SW timer reset
SW.FirstClickRestartsTimer=yes
SW.FirstClickRestartsTimer.AutoFire=yes
SW.FirstClickRestartsTimer.Cost=-10000 ; Pay for starting the upgrade process...
Message.InsufficientFunds=;
Message.RestartedTimer=;
EVA.RestartedTimer=EVA_UpgradeInProgress

2023-09-10 11:03 UTC, Metadorius commented
> `SW.FirstClickRestartsTimer.AutoFire.ForceDetonations=yes`
holy mother of god

2023-09-10 11:04 UTC, FS-21 commented
> > `SW.FirstClickRestartsTimer.AutoFire.ForceDetonations=yes`
> 
> holy mother of god

Mistake, I left it as  `SW.FirstClickRestartsTimer.ForceDetonations=yes` in the code

2023-09-10 22:44 UTC, FS-21 commented on src/Ext/SWType/FireSuperWeapon.cpp
> -	if (!MapClass::Instance->CoordinatesLegal(mapCoords))
I don't see that case because I didn't trigger such crashes.
Nevermind, the purpose of the feature is giving support to LimboLaunch & Convert features that are commonly used by upgrades, this was an extra so I'll remove the tag and if somebody in the future wants to expand the feature feel free to do it :-)

2023-09-13 16:47 UTC, MortonPL requested changes
* Use `false` instead of `no` in documentation.
* `SW.FirstClickRestartsTimer.Cost` should accept both negative and positive values, like in vanilla (also positive/negative refunds).
* `EVA.RestartedTimer`, `Message.InsufficientFunds` and `Message.RestartedTimer` should be mentioned in the documentation.

2023-09-13 21:29 UTC, FS-21 commented
Applied feedback.

2024-02-07 15:21 UTC, FS-21 commented
I'll close this pull request because there is a desync I can't fix in the hook at 0x6CBCD4 .

2024-02-07 15:21 UTC, closed without merging