Option to draw insiginas only when unit is selected.
Phobos-developers/Phobos pull request #1195
Opened 2024-01-21 12:24 UTC by Fryone

```
[AudioVisual]
DrawInsigniaOnlyOnSelected=true
```

2024-07-08 19:08 UTC, Metadorius requested changes

2024-07-08 19:08 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +  - `Promote.EliteAnimation` is used when unit or structure is promoted to elite. If `Promote.EliteAnimation` is not defined, `Promote.VeteranAnimation` will play instead when unit or structure is pr
I don't think elite promotion anim should be inherited from veteran one, because it's a different thing compared to inheriting weapons from lower stage, for example.

2024-07-09 17:41 UTC, Fryone commented on docs/New-or-Enhanced-Logics.md
> +  - `Promote.EliteAnimation` is used when unit or structure is promoted to elite. If `Promote.EliteAnimation` is not defined, `Promote.VeteranAnimation` will play instead when unit or structure is pr
separated

2024-07-10 09:34 UTC, Metadorius approved these changes

2024-07-10 09:35 UTC, Metadorius commented on docs/Whats-New.md
> +- Insignias visibility and position adjustments (by Fryone, Kerbiter)
```suggestion
- Insignias visibility and position adjustments (by Fryone)
```

Thanks but I have not participated in the feature implementation, only reviewed it :) so far we haven't added reviewers to the credits, maybe that should change but I think that's not in scope of this PR

2024-07-10 09:36 UTC, Metadorius approved these changes

2024-07-10 09:37 UTC, merged