Fix map tint not affecting unit palette objects and tiberiums
Phobos-developers/Phobos pull request #1202
Opened 2024-02-11 18:03 UTC by MortonPL

- Fixed units, buildings and tiberiums not being affected by map lighting color tint (can be disabled with `FixLightingTint=false` under `[General]` in `rulesmd.ini`).
-

2024-02-18 14:30 UTC, MortonPL commented
TODO: Fix a new bug which breaks all lamp posts until a map retint action is fired.

2024-06-01 09:33 UTC, Sovietianqi approved these changes

2024-06-09 15:41 UTC, chaserli requested changes
Is there a way to incorporate the save/load fix #529?

2024-06-09 15:41 UTC, chaserli commented on src/Misc/Hooks.MapTint.cpp
> +	std::unique_ptr<LightConvertClass> TiberiumLightDrawer;
`LightConvertClass` has a virtual destructor, you might end up allocating with dll new but deallocating with exe delete. Besides unique_ptr does not seem to increase safety in this case.
```suggestion
	LightConvertClass* TiberiumLightDrawer;
```

2024-06-09 15:41 UTC, chaserli commented on src/Misc/Hooks.MapTint.cpp
> +	MapTintFix::TiberiumLightDrawer = std::make_unique<LightConvertClass>(LightConvertClass(
```suggestion
	MapTintFix::TiberiumLightDrawer = GameCreate<LightConvertClass>(
```

2024-06-09 15:41 UTC, chaserli commented on src/Misc/Hooks.MapTint.cpp
> +	MapTintFix::TiberiumLightDrawer.release();
```suggestion
	GameDelete(MapTintFix::TiberiumLightDrawer);
```

2025-01-05 14:29 UTC, closed without merging