New & restored TerrainType features
Phobos-developers/Phobos pull request #1241
Opened 2024-04-06 19:05 UTC by Starkku

## Animated TerrainTypes

- Length of the animation can now be customized by setting `AnimationLength` as well, defaulting to half (or quarter if damaged frames are enabled) the number of frames in TerrainType's image.

In `rulesmd.ini`:
```ini
[SOMETERRAINTYPE]  ; TerrainType
AnimationLength=   ; integer, number of frames
```

## Damaged frames and crumbling animation

- By default game shows damage frame only for TerrainTypes alive at only 1 point of health left. Because none of the original game TerrainType assets were made with this in mind, the logic is now locked behind a new key `HasDamagedFrames`.
  - Instead of showing at 1 point of HP left, TerrainTypes switch to damaged frames once their health reaches `[AudioVisual]` -> `ConditionYellow.Terrain` percentage of their maximum health. Defaults to `ConditionYellow` if not set.
- In addition, TerrainTypes can now show 'crumbling' animation after their health has reached zero and before they are deleted from the map by setting `HasCrumblingFrames` to true.
  - Crumbling frames start from first frame after both regular & damaged frames and ends at halfway point of the frames in TerrainType's image.
    - Note that the number of regular & damage frames considered for this depends on value of `HasDamagedFrames` and for `IsAnimated` TerrainTypes, `AnimationLength`. Exercise caution and ensure there are correct amount of frames to display.
  - Sound event from `CrumblingSound` (if set) is played when crumbling animation starts playing.
  - Destroy animation & sound only play after crumbling animation has finished.

In `rulesmd.ini`:
```ini
[AudioVisual]
ConditionYellow.Terrain=  ; floating-point value

[SOMETERRAINTYPE]         ; TerrainType
HasDamagedFrames=false    ; boolean
HasCrumblingFrames=false
CrumblingSound=           ; Sound
```

## Custom palette

- You can now specify custom palette for TerrainTypes in similar manner as TechnoTypes can.
  - Note that this palette behaves like an object palette and does not use tint etc. that have been applied to the tile the TerrainType resides on like a TerrainType using tile palette would.

In `artmd.ini`:
```ini
[SOMETERRAINTYPE]  ; TerrainType
Palette=           ; filename - excluding .pal extension and three-character theater-specific suffix
```

2024-04-24 07:37 UTC, chaserli requested changes
haven't looke into the impl yet, only a few codestyle issues

2024-04-24 07:37 UTC, chaserli commented on src/Ext/TerrainType/Hooks.cpp
> +		MapClass::Instance->Logics.get().AddObject(pThis, false);
```suggestion
		MapClass::Instance->Logics->AddObject(pThis, false);
```

2024-04-24 07:37 UTC, chaserli commented on src/Ext/TerrainType/Body.cpp
> +		GameCreate<AnimClass>(pAnimType, coords);
I see you are a fan of `Nullable` everything that defaults to null, which is unnecessary. Parsing failure for Valueable leads to nullptr for pointer types and -1 to idx types by default.

2024-04-24 07:37 UTC, chaserli commented on src/Ext/TerrainType/Hooks.cpp
> +			MapClass::Instance->Logics.get().Remove(pThis);
```suggestion
			MapClass::Instance->Logics->Remove(pThis);
```

2024-04-24 07:37 UTC, chaserli commented on src/Ext/TerrainType/Hooks.cpp
> +		MapClass::Instance->Logics.get().AddObject(pThis, false);
```suggestion
		MapClass::Instance->Logics->AddObject(pThis, false);
```

2024-06-16 09:27 UTC, chaserli requested changes
will look into details later

2024-06-16 09:27 UTC, chaserli commented on src/Ext/TerrainType/Body.h
> +		void PlayDestroyEffects(CoordStruct coords);
```suggestion
		void PlayDestroyEffects(const CoordStruct& coords);
```

2024-06-16 09:27 UTC, chaserli commented on src/Ext/TerrainType/Hooks.cpp
> +			MapClass::Instance->Logics->Remove(pThis);
`Logics` is static so the `Instance->` is not needed. Best way is to remove that from MapClass and move to LogicClass in yrpp, and then name it `LogicClass::Instance`

2024-06-16 09:27 UTC, chaserli commented on src/Ext/TerrainType/Hooks.cpp
> +		VocClass::PlayIndexAtPos(pTypeExt->CrumblingSound.Get(-1), pThis->GetCoords());
Given that the default value for ValueableIdx is -1, NullableIdx is not necessary since you only used .Get(-1). Same for other occurrences in existing code such as DetachedReport in AnimTypeExt.

2024-06-19 15:54 UTC, Starkku commented
Fixed the issues pointed out in reviews so far.

2024-08-28 19:44 UTC, merged