Map events 604-605 for checking if a specific Techno enters in a cell
Phobos-developers/Phobos pull request #1250
Opened 2024-04-26 12:28 UTC by FS-21

- 604: Checks if the techno that entered in the cell has the same ID specified in the event.
- 605: Checks if the techno that entered in the cell appears in the selected list in `AITargetTypes`.
- `HouseIndex` can be customized to focus in a specified house.

In `mycampaign.map`:
```ini
[Events]
...
ID=EventCount,...,604,2,[HouseIndex],[TechnoType],...
ID=EventCount,...,605,2,[HouseIndex],[AITargetTypes index#],...
...
```

| *House Index* | *Description*                              |
| :-----------: | :----------------------------------------: |
| >= 0          | The index of the current House in the map  |
| -1            | This value is ignored (any house is valid) |
| -2            | Pick the owner of the map trigger          |

2024-05-02 16:04 UTC, Sovietianqi approved these changes

2024-07-07 15:44 UTC, Starkku requested changes
Some code style nitpicks.

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +		return false;
Is there a realistic chance that this is ever `nullptr`?

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +		return false;
Multiline if statements require brackets per code style guide.

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +		return false;
Add empty line before if statement.

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +		return false;
Same thing with the `nullptr` here.

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +	if (!pDesiredType)
Spacing.

2024-07-07 15:44 UTC, Starkku commented on src/Ext/TEvent/Body.cpp
> +		return false;
Spacing again.

2024-07-12 04:56 UTC, FS-21 commented on src/Ext/TEvent/Body.cpp
> +		return false;
ALMOST ALWAYS, as soon a techno enters into the cell pObject gets a value so the code execution can continue.

2024-07-12 04:58 UTC, FS-21 commented on src/Ext/TEvent/Body.cpp
> +		return false;
I didn't notice, thnx!

2024-07-12 04:59 UTC, FS-21 commented on src/Ext/TEvent/Body.cpp
> +		return false;
As mentioned before this is mandatory, only gets value when an object enters into the cell.

2024-07-12 05:04 UTC, FS-21 commented on src/Ext/TEvent/Body.cpp
> +	if (!pDesiredType)
Not necessary due to the code style guide, no? :-/
![image](https://github.com/user-attachments/assets/b585fa0a-b16b-4907-9ac8-0de37bb41535)

2024-07-12 05:04 UTC, FS-21 commented on src/Ext/TEvent/Body.cpp
> +		return false;
![image](https://github.com/user-attachments/assets/32d68916-0115-44ea-ab9b-09654a1e0192)

2024-07-12 09:46 UTC, Starkku approved these changes

2024-07-12 09:46 UTC, Starkku commented
Fix the merge conflicts and it is good to go.

2024-07-12 10:40 UTC, merged