Customizable Rocker Amplitude & Wake Anim
Phobos-developers/Phobos pull request #1258
Opened 2024-05-09 06:27 UTC by Coronia

Help TwinkleStar to finish his 2 pull requests, with proper docs this time
https://github.com/Phobos-developers/Phobos/pull/1080
https://github.com/Phobos-developers/Phobos/pull/1082

The rocker amplitude of warheads with `Rocker=yes` used to be determined by `Damage` value of the weapon. You can now specify it separately.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]       ; WarheadType
Rocker.Damage=      ; integer
```

You can now specify the `Wake` anim per TechnoType to override default rules value.

In `rulesmd.ini`:
```ini
[SOMETECHNO]         ; TechnoType
Wake=                ; Anim (played when Techno moving on the water), default to [General] Wake
```

2024-05-14 11:36 UTC, Metadorius approved these changes
No complaints about code style, probably would be better to use Nullable here tho.

2024-05-14 11:36 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +
Wouldn't it be better to use Nullable here too?

2024-05-14 12:03 UTC, chaserli requested changes
Apparently you missed the wakes for squids and crashed units.
rebase/force push the branch plz
Do not abuse sanity check when it's pointless

2024-05-14 12:04 UTC, Metadorius commented
> rebase/force push the branch plz

I already merged the latest dev and fixed the build.

2024-05-18 20:34 UTC, FS-21 commented on src/Ext/TechnoType/Body.cpp
> +	const auto pExt = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType());
should be called pTypeExt instead of pExt

2024-06-18 04:24 UTC, Coronia commented
TwinkleStar has completed the customized wake settings for Squid parasite and sinking as well

In `rulesmd.ini`:
```ini
[SOMETECHNO]         ; TechnoType
Wake.Grapple=        ; Anim (played when Techno being parasited on the water), default to [General] Wake
Wake.Sinking=        ; Anim (played when Techno sinking), default to [General] Wake
```

2024-07-07 16:07 UTC, Metadorius commented
Took the liberty of splitting off mergeable changes and merging them with correct credit.

As for the `Rocker`, I think there are some improvements to be done.

```ini
[SOMEWH]                        ; WarheadType
Rocker.AmplitudeMultiplier=1.0  ; float
Rocker.FixedAmplitude=          ; integer
```

The first tag would multiply the regular damage if the user wants it to scale with damage, the second one would just override the damage with a fixed one. Also better naming.

2024-07-07 16:08 UTC, Metadorius commented
GH screw off, I didn't want to close this

2024-08-10 07:51 UTC, Coronia commented
> Took the liberty of splitting off mergeable changes and merging them with correct credit.
> 
> As for the `Rocker`, I think there are some improvements to be done.
> 
> ```ini
> [SOMEWH]                        ; WarheadType
> Rocker.AmplitudeMultiplier=1.0  ; float
> Rocker.FixedAmplitude=          ; integer
> ```
> 
> The first tag would multiply the regular damage if the user wants it to scale with damage, the second one would just override the damage with a fixed one. Also better naming.

added the suggested change. The second tag is named as Rocker.AmplitudeOverride

2024-08-11 11:04 UTC, merged