Two new trajectories with enhanced straight trajectory
Phobos-developers/Phobos pull request #1261
Opened 2024-05-16 12:08 UTC by CrimRecya

New Disperse trajectory and Engrave trajectory with enhanced Straight trajectory.

  - `Trajectory.Straight.PassDetonate` enables extra detonations when the projectile is traveling.
  - `Trajectory.Straight.PassDetonateDelay` controls the maximum value of the extra detonations timer. When the timer goes back to 0, it will detonate a warhead defined by `Trajectory.Straight.Warhead`.
  - `Trajectory.Straight.PassDetonateTimer` controls the initial value of the extra detonations timer. It can be set to a negative integer as initial delay.
  - `Trajectory.Straight.PassDetonateLocal` controls whether the extra detonations are always at ground level.
  - `Trajectory.Straight.LeadTimeCalculate` controls whether the projectile need to calculate the lead time of the target when firing. Note that this will not affect the facing of the turret.
  - `Trajectory.Straight.OffsetCoord` controls the offsets of the target. Projectile will aim at this position to attack. It also supports `Inaccurate=yes` and `Trajectory.Straight.LeadTimeCalculate=true` on this basis.
  - `Trajectory.Straight.MirrorCoord` controls whether `Trajectory.Straight.OffsetCoord` need to mirror the lateral value to adapt to the current burst index.
  - `Trajectory.Straight.ProximityImpact` controls the initial proximity fuse times. When there are enough remaining times and the projectile approaches another valid target, it will detonate a warhead defined by `Trajectory.Straight.Warhead` on it. If the times is about to run out, it will detonate itself on the last attempt. This function can be cancelled by setting to 0. A negative integer means unlimited times.
  - `Trajectory.Straight.ProximityRadius` controls the range of proximity fuse. Never counted units in the air. It can NOT be set as a negative integer. This function only can be cancelled by setting `Trajectory.Straight.ProximityImpact` to 0.
  - `Trajectory.Straight.ProximityAllies` controls the damage ratio if the target of proximity fuse is ally. It will not detonate at allies by setting as 0. Note that this is not related to whether the warhead itself affect allies.
  - `Trajectory.Straight.ThroughVehicles` controls whether the projectile will not be obstructed by vehicles or aircrafts on the ground. When it is obstructed, it will be directly detonated at the obstacle. It will be forcibly Enabled by setting `Trajectory.Speed` above 256.
  - `Trajectory.Straight.ThroughBuilding` controls whether the projectile will not be obstructed by buildings. When it is obstructed, it will be directly detonated in situ. It will be forcibly Enabled by setting `Trajectory.Speed` above 256.
  - `Trajectory.Straight.Warhead` defined the warhead detonated by `Trajectory.Straight.PassDetonate` and `Trajectory.Straight.ProximityImpact`.
  - `Trajectory.Straight.Damage` defined the damage caused by `Trajectory.Straight.Warhead`.
  - `Trajectory.Straight.EdgeAttenuation` controls the edge attenuation ratio of projectile damage, includes `Trajectory.Straight.Damage`. Can NOT be set to a negative integer.
  - `Trajectory.Straight.SubjectToGround` controls whether the projectile should explode when it hits the ground.
  - `Trajectory.Straight.ConfineAtHeight` controls the height above ground that projectile will try to travel as it can. It can not move down from the cliff by setting `SubjectToCliffs=yes`. It can be cancelled by setting as a non positive integer. It will be forcibly cancelled by setting `Trajectory.Speed` above 256.

In `rulesmd.ini`:
```ini
[SOMEPROJECTILE]                                ; Projectile
Trajectory=Straight                             ; Trajectory type
Trajectory.Straight.PassDetonate=false          ; boolean
Trajectory.Straight.PassDetonateDelay=1         ; integer
Trajectory.Straight.PassDetonateTimer=0         ; integer
Trajectory.Straight.PassDetonateLocal=false     ; boolean
Trajectory.Straight.LeadTimeCalculate=false     ; boolean
Trajectory.Straight.OffsetCoord=0,0,0           ; integer - Forward,Lateral,Height
Trajectory.Straight.MirrorCoord=true            ; boolean
Trajectory.Straight.ProximityImpact=0           ; integer
Trajectory.Straight.ProximityRadius=0.7         ; floating point value
Trajectory.Straight.ProximityAllies=0           ; floating point value
Trajectory.Straight.ThroughVehicles=true        ; boolean
Trajectory.Straight.ThroughBuilding=true        ; boolean
Trajectory.Straight.Warhead=                    ; WarheadType
Trajectory.Straight.Damage=0                    ; integer
Trajectory.Straight.EdgeAttenuation=1.0         ; floating point value
Trajectory.Straight.SubjectToGround=false       ; boolean
Trajectory.Straight.ConfineAtHeight=0           ; integer
```

- Its trajectory looks a bit like a `ROT`, but its settings are more flexible. It also has a unique trajectory. And as its name suggests, it can even spread out more weapons.
  - `Trajectory.Disperse.UniqueCurve` controls whether to enable simulated Qian Xuesen trajectory. After enabling this, it will NOT respect the following 12 items and `Trajectory. Speed`.
  - `Trajectory.Disperse.PreAimCoord` controls the initial flight direction of the projectile, and after reaching this coordinate, it will begin to turn towards the target direction. When it is set to 0,0,0 , it will directly face the target.
  - `Trajectory.Disperse.LaunchSpeed` controls the initial flight speed of the projectile, it will be directly reduced to this value if it exceeds `Trajectory. Speed`.
  - `Trajectory.Disperse.Acceleration` controls the acceleration of the projectile's flight speed, increasing the speed per frame according to this value, the final speed will not exceed `Trajectory. Speed`.
  - `Trajectory.Disperse.RateofTurning` controls the turning speed of the projectile and can determine the turning radius of the projectile. The turning speed will increase with the increase of speed.
  - `Trajectory.Disperse.LockDirection` controls whether after reaching `Trajectory.Disperse.PreAimCoord` and completing the first turn, the projectile will lock the direction of motion without further adjustment.
  - `Trajectory.Disperse.CruiseEnable` controls whether after reaching `Trajectory.Disperse.PreAimCoord` and completing the first turn, the projectile will maintain altitude while moving towards the target.
  - `Trajectory.Disperse.CruiseUnableRange` controls how far away it is from the target to end the cruise phase, no longer maintaining the cruise altitude, and begins to move directly towards the target. If the distance is already below this value by the time `Trajectory.Disperse.PreAimCoord` is reached, the cruise phase will be skipped.
  - `Trajectory.Disperse.LeadTimeCalculate` controls whether the projectile need to calculate the lead time of the target during motion.
  - `Trajectory.Disperse.TargetSnapDistance` controls the maximum distance in cells from intended target the projectile can be at moment of detonation to make the projectile 'snap' on the intended target. Set to 0 to disable snapping.
  - `Trajectory.Disperse.RetargetAllies` controls whether the projectile chooses allies as its target when searching for new targets after losing its original target.
  - `Trajectory.Disperse.RetargetRadius` controls the radius of the projectile to search for a new target after losing its original target. If the initial turn is not completed, the last coordinate of the original target is taken as the center of the searching circle. If the initial turn has been completed, the coordinate of the distance in front of the projectile is taken as the center of the circle. Set to 0 indicates that this function is not enabled, and it will self explode after moving forward in a straight line for about 16 frames. If it is set to a negative number, it will directly self explode in place.
  - `Trajectory.Disperse.SuicideAboveRange` controls the projectile to self destruct directly after reaching the flight distance. Set to 0 to disable suicide.
  - `Trajectory.Disperse.SuicideIfNoWeap [...]

2024-05-16 13:47 UTC, Metadorius commented on src/Ext/Bullet/Hooks.cpp
> +		return 0;
Isn't this going to disable the laser trails on *all* the trajectories, not just your Engrave one?

2024-05-16 13:49 UTC, Metadorius commented on src/Ext/Bullet/Hooks.cpp
> +		return 0;
Also is there maybe a way to reuse the laser trail type somehow instead of re-defining new parameters on trajectory itself? I haven't looked deeply into the code yet though.

2024-05-16 14:02 UTC, CrimRecya commented on src/Ext/Bullet/Hooks.cpp
> +		return 0;
Not so. Let it skip drawing here and instead let them be drawn after the Trajectory‘s OnAI() because if I don't do this, the laser trails will be drawn before the calculation of changing the velocity direction in each frame. This will cause the laser trails to be drawn in the wrong position too early, resulting in a visual appearance resembling a "bouncing". I haven't come up with a better solution yet.

2024-05-16 14:15 UTC, FS-21 commented on src/Ext/Bullet/Hooks.cpp
>  			return SkipSetCoordinate;
With multiline IFs put brackets please.

2024-05-16 14:15 UTC, FS-21 commented on src/Ext/Bullet/Hooks.cpp
>  			return SkipCheck;
With multiline IFs put brackets please.

2024-05-16 14:17 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		.Process(this->RateofTurning)
Shouldn't be called ROT ?

2024-05-16 14:19 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		.Process(this->RateofTurning)
As mentioned above I recommend ROT instead of RateofTurning

2024-05-16 14:21 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +				RotateAngle = Math::atan2(pBullet->TargetCoords.Y - TheSource.Y , pBullet->TargetCoords.X - TheSource.X);
Brackets in "else" because you started with brackets in "if"

2024-05-16 14:22 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			else
Put the else in brackets.

2024-05-16 14:26 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		this->SuicideAboveRange -= BulletSpeed;
Put a blank line for separating the brackets and the new code.

2024-05-16 14:29 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	if (Check)
You can reduce in 1 level if you write:

if (!Check)
    return false;

Everything else what was inside the "if (Check)"

2024-05-16 14:32 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	if (Check)
Sicne is a large block inside the "if (Check)" You could reduce 1 level if:

if (!Check)
    return false;
    
And there here everything else, including the return false of the end;

2024-05-16 14:33 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +
Remove this gap

2024-05-16 14:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +
Maybe is better if these 2 lines are together without a gap

2024-05-16 14:37 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +
Remove the gap

2024-05-16 14:43 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			pLaser->Thickness = 3;//LaserThickness
If is a leftover from old code remove this, if not put a little gap please.

2024-05-16 14:43 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		//	Bolt.Color1,Bolt.Color2,Bolt.Color3
Remember remove the old code if you finished this block of code

2024-05-16 14:45 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		//	pRadBeam->Period = ;//Beam.Duration
Remember delete old commented code.

2024-05-16 14:54 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +	if (this->CheckTimesLimit < 0)
Since "else" has brackets this "if" too

2024-05-16 14:55 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +	else//SetLocation() seems to work wrong if I put this part into OnAIVelocity().
Just for easy lecture put a little separation in the coment please

2024-05-16 14:56 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +			else
if "if" has brackets then "else" must have brackets too

2024-05-16 14:58 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +
remove this little gap

2024-05-16 14:59 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +void EngraveTrajectory::OnAIPreDetonate(BulletClass* pBullet){}//do nothing
Just for easy lecture put a little separation in the coment after the "else" please (Nothing personal :-D )

2024-05-16 15:08 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +void EngraveTrajectory::OnAIPreDetonate(BulletClass* pBullet){}//do nothing
Thank you for your comment. I have made all these changes OvO.

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +		}
```suggestion
		else if (this->ConfineAtHeight > 0)
		{
			if (PassAndConfineAtHeight(pBullet, StraightSpeed))
				return true;
		}
```

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +		return true;
```suggestion
	if (!this->PassThrough && this->DetonationDistance > 0
		&& pBullet->TargetCoords.DistanceFrom(pBullet->Location) < this->DetonationDistance)
	{
		return true;
	}
```

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +	if (StraightSpeed < 512.0)
Reduce 1 level if

if (StraightSpeed >= 512.0)
	return;

Here all the code that was inside the "if (StraightSpeed < 512.0)"

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +			}
```suggestion
			if (LocationDistance < StraightSpeed)
				VelocityCheck = 2;
```

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +				if (pTechno)
You can reduce 1 level if you write:

if (!pTechno)
	continue;

And after that Here the rest of the "if (pTechno)" code.

2024-05-16 15:34 UTC, FS-21 commented on src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
> +
Remove the gap bewteen if & else

2024-05-16 15:40 UTC, CrimRecya commented on src/Ext/Bullet/Hooks.cpp
> +		return 0;
I tried to rewrite the comments for these two lines. This is a modification made for all trajectories. The purpose is to draw the laser trails after the velocity calculation for this frame is completed, so as not to draw to the position before the velocity calculation due to drawing one frame earlier. Apologize for my poor English, I think this translation software has helped me express myself clearly.

2024-05-16 15:42 UTC, Metadorius commented on src/Ext/Bullet/Hooks.cpp
> +		return 0;
It is fine, your English is pretty good from what I've seen. We will do a detailed review later. Thanks for your contribution!

2024-05-16 16:01 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	}
Thank you very much for your correction.

2024-05-18 17:22 UTC, FS-21 commented
By the way, what is exactly a "engrave" trajectory? because I don't get the concept in the documentation. Maybe if I was an English native I could understand.

If possible I would put the right gif you created in the right place documentation for easy understanding :-/
I only recognice the disperse trajectory in the gifs because it works like a shotgun.

For example what trajectory was used in the last gif that remembers me the Protoss Colossus dual weapon
<img width="254" alt="image" src="https://github.com/Phobos-developers/Phobos/assets/1371539/7b89715e-fbdc-4513-8ecf-b49d0f9adeee">

2024-05-18 17:32 UTC, FS-21 reviewed
I think the latest changes are well written so I have no complains with the code.

Another story is all tags were tested in online for hunting a possible desync.

2024-05-18 17:34 UTC, CrimRecya commented
> By the way, what is exactly a "engrave" trajectory? because I don't get the concept in the documentation. Maybe if I was an English native I could understand.
> 
> If possible I would put the right gif you created in the right place documentation for easy understanding :-/ I only recognice the disperse trajectory in the gifs because it works like a shotgun.
> 
> For example what trajectory was used in the last gif that remembers me the Protoss Colossus dual weapon <img alt="image" width="254" src="https://private-user-images.githubusercontent.com/1371539/331819154-7b89715e-fbdc-4513-8ecf-b49d0f9adeee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNTM2ODcsIm5iZiI6MTcxNjA1MzM4NywicGF0aCI6Ii8xMzcxNTM5LzMzMTgxOTE1NC03Yjg5NzE1ZS1mYmRjLTQ1MTMtOGVjZi1iNDlkMGY5YWRlZWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MThUMTcyOTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQyZjdiYzljODgzYWVjZTcwNDA5YTc4MDhmMGVkZjM4ODZkOTNmMmYxZDYwMmRjYjc2MGYxZWVkMDJlMGFmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fI6Gbsv4xoX_SCeS3Lw8WhlPI9nCZLbpy_qM1nPBUs4">

Apologize for my poor English. The Last gif is the "engrave" trajectory. And thank you for your suggestion. I will create a few more GIF images these days and place them appropriately.

2024-05-21 18:47 UTC, CrimRecya commented
Updated introduction. The resources from mod MO3 are for display purposes only.

2024-06-21 03:42 UTC, chaserli requested changes
Impressive work. The quantity is so huge that I'm afraid it's almost impossible to review and merge all of these on 1 single PR. imo I suggest detach these into several commits:
* The "engrave" one
* The "disperse" one
* As for the straight trajectory one, see if it's possible to incorporate the "inaccurate" part of #1246. The biggest concern I noticed is that vector of  "Causality" thing you made: Are you sure the technos always live longer than your bullet? If not then pointer invalidation will be quite a big trouble for perf. Try to see if there's a simpler way

2024-06-21 04:54 UTC, CrimRecya commented
> Impressive work. The quantity is so huge that I'm afraid it's almost impossible to review and merge all of these on 1 single PR. imo I suggest detach these into several commits:
> 
> * The "engrave" one
> * The "disperse" one
> * As for the straight trajectory one, see if it's possible to incorporate the "inaccurate" part of [Trajectory projectiles enhancement #1246](https://github.com/Phobos-developers/Phobos/pull/1246). The biggest concern I noticed is that vector of  "Causality" thing you made: Are you sure the technos always live longer than your bullet? If not then pointer invalidation will be quite a big trouble for perf. Try to see if there's a simpler way

Okay. But I have a question about splitting here that whether [the state of mutual reference between my Trajectories, such as Disperse using Straight's ‘UseDisperseBurst’ tag, or Disperse, Straight, and Engrave using CheckSubjectToGround() in Hooks.Obstacles’s at the same time] may cause splitting problems.
And for the ‘Inaccurate’ part of Straight, I already have the corresponding part here, and the issue of null pointers in the Casualty part is actually no longer returning Vector during Merge step, which has passed hundreds of tests in game and no need to worry about this anymore :).

2024-06-21 06:37 UTC, chaserli commented
> Okay. But I have a question about splitting here that whether [the state of mutual reference between my Trajectories, such as Disperse using Straight's ‘UseDisperseBurst’ tag, or Disperse, Straight, and Engrave using CheckSubjectToGround() in Hooks.Obstacles’s at the same time] may cause splitting problems. And for the ‘Inaccurate’ part of Straight, I already have the corresponding part here, and the issue of null pointers in the Casualty part is actually no longer returning Vector during Merge step, which has passed hundreds of tests in game and no need to worry about this anymore :).

Got a point. Excuse me for the oversight, I'll have a look later on this one.

2024-06-25 14:24 UTC, closed without merging