New AutoDeath condition & convert when AutoDeath
Phobos-developers/Phobos pull request #1264
Opened 2024-05-19 04:31 UTC by Coronia

1 - added the following AutoDeath conditions:
- `MoneyExceed` / `MoneyBelow`: The object will die if its owner house has credits greater / smaller than (or equal to) set value.
- `LowPower` / `FullPower`: The object will die if its owner house is in low / full power.
- `PassengerExceed` / `PassengerBelow`: The object will die if its current passenger amount is greater / smaller than (or equal to) set value.

2 - instead of firing AutoDeath when any condition is met, you can now set `ContentIfAnyMatch` to false to make it trigger only when all conditions are met

3 - AutoDeath now support `convert` behavior. If the object is a **unit**, it will be changed into the TechnoType in `Convert.AutoDeath` instead of destroyed.

In `rulesmd.ini`:
```ini
[SOMETECHNO]                                   ; TechnoType
AutoDeath.Behavior=                            ; enumeration (kill | vanish | sell | convert), default not set
AutoDeath.MoneyExceed=-1                       ; integer
AutoDeath.MoneyBelow=-1                        ; integer
AutoDeath.LowPower=false                       ; boolean
AutoDeath.FullPower=false                      ; boolean
AutoDeath.PassengerExceed=-1                   ; integer
AutoDeath.PassengerBelow=-1                    ; integer
AutoDeath.ContentIfAnyMatch=true               ; boolean

Convert.AutoDeath=                             ; TechnoType
```

2024-05-19 13:20 UTC, mbnq commented
Would be nice if there was also:
`AutoDeath.IsAI=`
That would work when owner of techno isn't human player.

2024-05-19 13:42 UTC, Coronia commented
> ```ini
> AutoDeath.OwnedByPlayer
> ```

2024-05-23 15:21 UTC, MortonPL requested changes

2024-05-23 15:21 UTC, MortonPL commented on src/Ext/Techno/Body.Update.cpp
This whole bit should be rearranged IMO. There's many repeated condition checks and calls.

2024-05-26 15:43 UTC, chaserli requested changes
Your intention seems to make it an autonomous trigger event/action system, at this point we might need to redesign the whole thing instead of stacking things up.

One way is to regroup it into the AttachEffect system, so that you can apply an AE under a given condition. That might be a huge change to the code structure.

Another easier way is to develop such condition-consequence system, which sounds already much simpler. 

To start with, you can wrap all these, including the old ones, into a standalone entity.

2024-05-26 16:15 UTC, Metadorius commented
> One way is to regroup it into the AttachEffect system, so that you can apply an AE under a given condition. That might be a huge change to the code structure.

Why not just fire a weapon on itself instead?

2024-08-09 18:06 UTC, closed without merging