Map action 507 for printing a message with the remaining map objects
Phobos-developers/Phobos pull request #1266
Opened 2024-05-19 17:02 UTC by FS-21

- A message will be printed with a list of alive map objects.
- If no `CSFKey` is mentioned (value `0`) it will use the default header text `Remaining: `.
- `HouseIndex` points to any house index of the map. Multiplayer 4475-4482 & 8997 indexes are valid.
- If `HouseIndex` is set `-1` then `[AIHousesListsIndex]` will be used as index of a list of countries in the `[AIHousesList]` section located in `rulesmd.ini`. If any map object match the ownership with one of the list it will be counted.
- `[AITargetTypesIndex]` is the index of an entry in the `[AITargetTypes]` section located in `rulesmd.ini`. Each alive map object listed here will be counted.
- If `[AITargetTypesIndex]` is negative this value will be evaluated as a positive index in `[AITargetTypesIndex]` but instead of printing a list of alive map objects and the respective count it will appear as an unique global count of all the alive map objects listed in `[AITargetTypes]`.
- `MesageDelay` is the time (in minutes) of the message displayed. If the value is 0 then the duration of the message will be the default `MesageDelay` value specified in `rulesmd.ini`.
- Be aware a message can't show more than 6 lines so if `[AITargetTypes]` contains more than 5 map objects then the first lines won't appear.

In `mycampaign.map`:
```ini
[Actions]
...
ID=ActionCount,[Action1],507,4,[CSFKey],[HouseIndex],[AIHousesListsIndex],[AITargetTypesIndex],[MesageDelay],A,[ActionX]
...
```

2024-05-23 14:40 UTC, MortonPL requested changes
I don't think this is ready to be used as of now. Refer to review comments and compiler warnings.

2024-05-23 14:40 UTC, MortonPL commented on src/Ext/TAction/Body.cpp
> +			housesList = RulesExt::Global()->AIHousesLists.at(listIdx);
What if index is bigger than the number of elements?

2024-05-23 14:40 UTC, MortonPL commented on docs/AI-Scripting-and-Mapping.md
> +- If `[AITargetTypesIndex]` is negative this value will be evaluated as a positive index in `[AITargetTypesIndex]` but instead of printing a list of alive map objects and the respective count it will
Can't say I'm a fan of controlling behavior like that. IMO it's better to have multiple actions with different behavior and well defined parameters.

2024-07-10 09:29 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +	}
Adding something simple like this?

`else if (!HouseClass::Array->GetItem(pThis->Param3))
{
	Debug::Log("Map action %d: Invalid house index '%d'. This action will be skipped.\n", (int)pThis->ActionKind, pThis->Param3);
	return true;
}`

2024-07-10 09:45 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +	std::vector<HouseClass*> pHousesList;
I addressed that mistake and all compilation warnings you mentioned at the beginning. Thanks a lot for using your time here :-)

2024-07-10 09:48 UTC, FS-21 commented on src/Ext/Rules/Body.cpp
> +	const char* sectionAIHousesList = "AIHousesList";
Probably because that section started in another PR for that AI fuction and later expanded to simple a list of any house.

Should be renamed? (for making the same change in those PR's it was used)

2024-07-10 09:56 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +		|| RulesExt::Global()->AITargetTypesLists[listIdx].size() == 0)
If my memmory isn't wrong from that test I did it simply was skipped or returned 0 (that "wrong" listIdx had zero elements).

I should re-test it for make it sure.

2024-07-10 11:38 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +		for (const auto pTechno : *TechnoClass::Array)
> "for each type for all technos" will have many more unnecessary iterations than "for all technos for each type".
It also checks if matchs the owner so it only counts instances of TechnoTypes.

2024-07-10 11:43 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +				}
I'm blind, thanks!

2024-07-10 12:00 UTC, FS-21 commented on docs/AI-Scripting-and-Mapping.md
> +- If `[AITargetTypesIndex]` is negative this value will be evaluated as a positive index in `[AITargetTypesIndex]` but instead of printing a list of alive map objects and the respective count it will
If is for the sake of a better map editor integration then I'll split it.

2024-07-11 04:31 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +	}
I think now I covered the case.

2024-07-11 04:32 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +			housesList = RulesExt::Global()->AIHousesLists.at(listIdx);
Already updated with a small check.

2024-07-11 05:05 UTC, FS-21 commented on src/Ext/TAction/Body.cpp
> +			housesList = RulesExt::Global()->AIHousesLists.at(listIdx);
I think I addressed this.

2024-07-11 09:34 UTC, FS-21 commented on docs/AI-Scripting-and-Mapping.md
> +- If `[AITargetTypesIndex]` is negative this value will be evaluated as a positive index in `[AITargetTypesIndex]` but instead of printing a list of alive map objects and the respective count it will
I was thinking in these 2 cases so I could remove the necesity of negative values:

; Param3 "HouseIndex" of a house used in the map for the technos counts.
; Param4 "isGlobalCount" for sum all the selected technos into only 1 count or make each techno its own count.
; Param5 "[AITargetTypes Index]" points to a list of technos in the rulesmd.ini section [AITargetTypes].
ID=ActionCount,[Action1],507,4,[CSFKey],[HouseIndex],[isGlobalCount],[AITargetTypes Index],[MesageDelay],A,[ActionX]

; Param3 "AIHousesLists Index" points to a list of countries in the rulesmd.ini section [AIHousesLists], if any of the houses used in the map is of the same type they will be included in the technos counts.
; Param4 "isGlobalCount" for sum all the selected technos into only 1 count or make each techno its own count.
; Param5 "[AITargetTypes Index]" points to a list of technos in the rulesmd.ini section [AITargetTypes].
ID=ActionCount,[Action1],508,4,[CSFKey],[AIHousesLists Index],[isGlobalCount],[AITargetTypes Index],[MesageDelay],A,[ActionX]

2026-08-31 15:05 UTC, closed without merging