New Infotypes and New display method
Phobos-developers/Phobos pull request #1287
Opened 2024-06-23 15:41 UTC by CrimRecya

New InfoType: ROF timer, Reload timer, Spawn timer, Gattling timer, Produce cash timer, Passenger kill timer, Auto death timer, SW timer.
If `Shape.PercentageFrame` set to true, it will only draw one frame that corresponds to total frames by percentage.

In `rulesmd.ini`:
```ini
InfoType=Health                         ; Displayed value enumeration (health|shield|ammo|mindcontrol|spawns|passengers|tiberium|experience|occupants|gattlingstage|ROF|Reload|SpawnTimer|GattlingTimer|ProduceCash|PassengerKill|AutoDeath|SuperWeapon)
Shape.PercentageFrame=false             ; boolean
```

2024-06-23 16:07 UTC, chaserli commented
I get the idea of having visuals of misc info on the techno. I would like to elaborate the plan/vision on "custom healthbar" here.  We may want to choose between a bar or a digital display, or even to keep both.
The idea is to redirect the drawhealthbar vtbl call completely, and draw both the bars and the "digital displays" there. We need to redesign a system with minimum overhead for this.
I wonder if you can get the idea and help working on it

2024-06-23 16:38 UTC, CrimRecya commented
> I get the idea of having visuals of misc info on the techno. I would like to elaborate the plan/vision on "custom healthbar" here. We may want to choose between a bar or a digital display, or even to keep both. The idea is to redirect the drawhealthbar vtbl call completely, and draw both the bars and the "digital displays" there. We need to redesign a system with minimum overhead for this. I wonder if you can get the idea and help working on it

That's really good!
Although I also really want to join, I haven't had much time in these months. So I only have these little features to share. Besides, I really don't know much about decompilation yet, so even if I have time, I'm afraid I won't be able to help much. Waiting the news of your success :)

2024-06-23 19:11 UTC, Metadorius commented
> That's really good! Although I also really want to join, I haven't had much time in these months. So I only have these little features to share. Besides, I really don't know much about decompilation yet, so even if I have time, I'm afraid I won't be able to help much. Waiting the news of your success :)

Are you on our Discord channel? I am sure we can collaborate on that :)

2024-06-24 04:25 UTC, CrimRecya commented
> > That's really good! Although I also really want to join, I haven't had much time in these months. So I only have these little features to share. Besides, I really don't know much about decompilation yet, so even if I have time, I'm afraid I won't be able to help much. Waiting the news of your success :)
> 
> Are you on our Discord channel? I am sure we can collaborate on that and help you :)

I really want to join, but due to some special reasons, even if I use my VPN, I still cannot connect to Discord's server ;-(
It seems like I need to change my VPN in the future when I have more time

2024-06-30 08:18 UTC, chaserli commented
> That's really good! Although I also really want to join, I haven't had much time in these months. So I only have these little features to share. Besides, I really don't know much about decompilation yet, so even if I have time, I'm afraid I won't be able to help much. Waiting the news of your success :)

No it's just a framework we need to establish and I think it would be better if you can help working on that rather than patching this one. 
Do you need some hint for what I was saying?
Basically if you look into TechnoClass::DrawHealthBar you'll see there were too much overhead, the idea is that you use its nature of being virtual and rewrite 4 functions for 4 final technoclasses.
For example
```
void __fastcall BuildingClass_DrawHealthbar_New(BuildingClass* self,void*,Point2D* loc, RectangleStruct* bounds, bool disguise)
{
Draw healthbar
Draw shieldbar
Draw ic bar
Draw temporal bar
Draw other bars...
Draw digital displays...
All these shit managed by a new framework

if(....)
drawpipscalepips
}
DEFINE_JUMP(VTABLE,0x7E4308, BuildingClass_DrawHealthbar_New)
```

2024-06-30 10:51 UTC, CrimRecya commented
> > That's really good! Although I also really want to join, I haven't had much time in these months. So I only have these little features to share. Besides, I really don't know much about decompilation yet, so even if I have time, I'm afraid I won't be able to help much. Waiting the news of your success :)
> 
> No it's just a framework we need to establish and I think it would be better if you can help working on that rather than patching this one. Do you need some hint for what I was saying? Basically if you look into TechnoClass::DrawHealthBar you'll see there were too much overhead, the idea is that you use its nature of being virtual and rewrite 4 functions for 4 final technoclasses. For example
> 
> ```
> void __fastcall BuildingClass_DrawHealthbar_New(BuildingClass* self,void*,Point2D* loc, RectangleStruct* bounds, bool disguise)
> {
> Draw healthbar
> Draw shieldbar
> Draw ic bar
> Draw temporal bar
> Draw other bars...
> Draw digital displays...
> All these shit managed by a new framework
> 
> if(....)
> drawpipscalepips
> }
> DEFINE_JUMP(VTABLE,0x7E4308, BuildingClass_DrawHealthbar_New)
> ```

Oh yes, I see what you mean. But I'm sorry I can't be of any help. As I mentioned before, I currently don't have so much time to finish a completely new function, so I just built these on what already have.

2025-02-20 09:23 UTC, Speederovsky commented
Any updates on this?

2025-02-25 09:12 UTC, Speederovsky commented
ValueAsTimer seems to work quite nicely.

2025-02-25 20:10 UTC, Starkku requested changes
Couple of questions and one small thing that could be changed.

Some of the code is also very long / verbose but unsure if there's much that can do about that, maybe split into smaller functions if can find a logical way to do so.

2025-02-25 20:10 UTC, Starkku commented on src/Ext/Techno/Body.Internal.cpp
> +
What is this for? Why are you explicitly setting `RearmTimer` on techno creation?

2025-02-25 20:10 UTC, Starkku commented on src/Ext/Techno/Body.Visuals.cpp
> +			return;
Superfluous check, ownerless techno would crash game very quickly elsewhere so there's rarely if ever point for verifying it.

2025-02-26 06:10 UTC, CrimRecya commented on src/Ext/Techno/Body.Internal.cpp
> +
Before the techno fires for the first time, `RearmTimer` is not set, which will not display anything.

2025-05-23 09:19 UTC, Speederovsky commented
Found no new issues so far. How's this looking?

2025-06-09 17:05 UTC, Starkku approved these changes
LGTM, removed merge conflicts and merging. The function `TechnoExt::GetValuesForDisplay()` is very long but there's little I can think of to reduce that length. If someone comes up with something it can be addressed later.

2025-06-09 17:05 UTC, merged