Projectile subject to ground check before firing
Phobos-developers/Phobos pull request #1291
Opened 2024-06-25 14:16 UTC by CrimRecya

This is a feature split from #1261 .
It may have similarities with other parts.

If set `SubjectToGround` to true ,it will predict will predict the height of the connecting straight line from the bullet's source coordinates to target coordinates. If the predicted height is lower than the ground height of the current predicted position, the firer will also consider targets blocked by such obstacles as out of range and will attempt to reposition themselves.

In `rulesmd.ini`:
```ini
[SOMEPROJECTILE]              ; Projectile
SubjectToGround=false         ; boolean
```

2024-08-15 10:13 UTC, Coronia requested changes

2024-08-15 17:30 UTC, CrimRecya commented on docs/New-or-Enhanced-Logics.md
> +- As for `SubjectToGround`, if set it to true ,it will predict will predict the height of the connecting straight line from the bullet's source coordinates to target coordinates. If the predicted hei
Get this.

2024-08-15 17:39 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Firing.cpp
> +			currentPassenger = abstract_cast<FootClass*>(currentPassenger->NextObject);
I think it's not necessary because it's only one line here and it's clear enough

2025-03-07 06:08 UTC, Coronia commented on src/Ext/Bullet/Hooks.Obstacles.cpp
> +			subjectToGround = false;
is there a need to prohibit air unit and target from using this?

2025-03-07 06:08 UTC, Coronia commented on src/Ext/Bullet/Hooks.Obstacles.cpp
> +		auto subjectToGround = BulletTypeExt::ExtMap.Find(pWeapon->Projectile)->SubjectToGround.Get(); // Make AI search for suitable attack locations.
not need to use Get() here since Valueable always has a valid value

2025-03-07 14:07 UTC, CrimRecya commented on src/Ext/Bullet/Hooks.Obstacles.cpp
> +		auto subjectToGround = BulletTypeExt::ExtMap.Find(pWeapon->Projectile)->SubjectToGround.Get(); // Make AI search for suitable attack locations.
Without this, compilation would not be possible because `Valueable<bool>` cannot be passed as `bool&`

2025-03-17 13:31 UTC, CrimRecya commented on src/Ext/Bullet/Hooks.Obstacles.cpp
> +			subjectToGround = false;
Updated.
When the air force is in use, they cannot find a suitable location normally. When the target is the air force, I think there is no need to make additional calculations.

2025-03-20 12:04 UTC, merged