New Engrave trajectory
Phobos-developers/Phobos pull request #1293
Opened 2024-06-25 14:20 UTC by CrimRecya

This is a feature split from #1261 .
It may have similarities with other parts.

- Visually, like the thermal lance. Calling it 'trajectory' may not be appropriate. It does not read the settings on the weapon.
  - `Trajectory.Engrave.SourceCoord` controls the starting point of engraving line segment. Taking the target as the coordinate center. Specifically, it will start from the firing position when set to 0,0 . The height of the point will always at ground level.
  - `Trajectory.Engrave.TargetCoord` controls the end point of engraving line segment. Taking the target as the coordinate center. The height of the point will always at ground level.
    - `Trajectory.Engrave.MirrorCoord` controls whether `Trajectory.Engrave.SourceCoord` and `Trajectory.Engrave.TargetCoord` need to mirror the lateral value to adapt to the current FLH.
    - `Trajectory.Engrave.TheDuration` controls the duration of the entire engrave process. Set to 0 will automatically use `Trajectory.Engrave.SourceCoord` and `Trajectory.Engrave.TargetCoord` to calculate the process duration.
  - `Trajectory.Engrave.IsLaser` controls whether laser drawing is required.
    - `Trajectory.Engrave.IsSupported` controls whether the engrave laser will be brighter and thicker. Need to set `Trajectory.Engrave.IsHouseColor` or `Trajectory.Engrave.IsSingleColor` to true.
    - `Trajectory.Engrave.IsHouseColor` controls whether set the engrave laser to draw using player's team color. These lasers respect `Trajectory.Engrave.LaserThickness` and `Trajectory.Engrave.IsSupported`.
    - `Trajectory.Engrave.IsSingleColor` controls whether set the engrave laser to draw using only `Trajectory.Engrave.LaserInnerColor`. These lasers respect `Trajectory.Engrave.LaserThickness` and `Trajectory.Engrave.IsSupported`.
    - `Trajectory.Engrave.LaserInnerColor` controls the inner color of the engrave laser.
    - `Trajectory.Engrave.LaserOuterColor` controls the outer color of the engrave laser.
    - `Trajectory.Engrave.LaserOuterSpread` controls the spread color of the engrave laser.
    - `Trajectory.Engrave.LaserThickness` controls the thickness of the engrave laser. Need to set `Trajectory.Engrave.IsHouseColor` or `Trajectory.Engrave.IsSingleColor` to true.
    - `Trajectory.Engrave.LaserDuration` controls the duration of the engrave laser.
    - `Trajectory.Engrave.LaserDelay` controls how often to draw the engrave laser.
  - `Trajectory.Engrave.DamageDelay` controls how often to detonate warheads.

In `rulesmd.ini`:
```ini
Trajectory=Engrave                             ; Trajectory type
Trajectory.Engrave.SourceCoord=0,0             ; integer - Forward,Lateral
Trajectory.Engrave.TargetCoord=0,0             ; integer - Forward,Lateral
Trajectory.Engrave.MirrorCoord=true            ; boolean
Trajectory.Engrave.TheDuration=0               ; integer
Trajectory.Engrave.IsLaser=true                ; boolean
Trajectory.Engrave.IsSupported=false           ; boolean
Trajectory.Engrave.IsHouseColor=false          ; boolean
Trajectory.Engrave.IsSingleColor=false         ; boolean
Trajectory.Engrave.LaserInnerColor=0,0,0       ; integer - Red,Green,Blue
Trajectory.Engrave.LaserOuterColor=0,0,0       ; integer - Red,Green,Blue
Trajectory.Engrave.LaserOuterSpread=0,0,0      ; integer - Red,Green,Blue
Trajectory.Engrave.LaserThickness=3            ; integer
Trajectory.Engrave.LaserDuration=1             ; integer
Trajectory.Engrave.LaserDelay=1                ; integer
Trajectory.Engrave.DamageDelay=2               ; integer
```

```{note}
- It's best not to let it be intercepted.
```

2025-02-11 09:06 UTC, Coronia requested changes
I can't tell if it's 100% correct, so I could only point out some minor problems for now. Hope others could take a look at it as well

2025-02-11 09:27 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +	const auto pTarget = pBullet->Target;
This is unnecessary because I only used it as the value of the pointer.

2025-02-11 09:33 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +			const auto pathCrd = targetCrd - this->StartCoord;
I think the compiler will solve this for me, here I just declare what it is first.

2025-02-18 23:04 UTC, mevitar commented
Engrave doesn't work in the newest build anymore. Was something changed, or is this just github nonsense?

2025-02-19 18:04 UTC, CrimRecya commented
> Engrave doesn't work in the newest build anymore. Was something changed, or is this just github nonsense?

There have only been some minor fixes recently.

2025-03-05 06:50 UTC, Coronia commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +		this->TheCasualty[pFirer->UniqueID] = 20;
how about making this value customizable? Think modders might want to make different damage rate for different weapons

2025-03-05 06:57 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/EngraveTrajectory.cpp
> +		this->TheCasualty[pFirer->UniqueID] = 20;
There is an oversight in my statement. If the unit is obtained again within 20 frames, the timer will be refreshed. From the design perspective, this value is only intended to prevent the warhead from repeatedly damaging the same target. :)

2025-03-18 15:15 UTC, CrimRecya commented
Has been completely rewrited.

2025-03-18 15:16 UTC, closed without merging