New Disperse trajectory
Phobos-developers/Phobos pull request #1295
Opened 2024-06-25 14:23 UTC by CrimRecya

This is a feature split from #1261 .
It may have similarities with other parts.

- Its trajectory looks a bit like a `ROT`, but its settings are more flexible. It also has a unique trajectory. And as its name suggests, it can even spread out more weapons.
  - `Trajectory.Disperse.UniqueCurve` controls whether to enable simulated Qian Xuesen trajectory. After enabling this, it will NOT respect the following 19 items and `Trajectory.Speed`.
  - `Trajectory.Disperse.PreAimCoord` controls the initial flight direction of the projectile, and after reaching this coordinate, it will begin to turn towards the target direction. When it is set to 0,0,0 , it will directly face the target.
    - `Trajectory.Disperse.RotateCoord` controls whether to rotate the projectile's firing direction within the angle bisector of `Trajectory.Disperse.PreAimCoord` according to the weapon's `Burst`. Set to 0 to disable this function.
    - `Trajectory.Disperse.MirrorCoord` controls whether `Trajectory.Disperse.PreAimCoord` need to mirror the lateral value to adapt to the current burst index. At the same time, the rotation direction calculated by `Trajectory.Disperse.RotateCoord` will also be reversed, and the rotation angle between each adjacent projectile on each side will not change as a result.
    - `Trajectory.Disperse.FacingCoord` controls whether the forward direction in `Trajectory.Disperse.PreAimCoord` is depending on the orientation of the firer. By default, it will depend on the vector between the firer and the target.
    - `Trajectory.Disperse.ReduceCoord` controls whether `Trajectory.Disperse.PreAimCoord` defines the initial movement coordinates when the attack distance is 10 cells, and the actual initial movement coordinates will change with the length of the attack distance. It can be simply understood as an optimization term aimed at ensuring hits at close range.
    - `Trajectory.Disperse.UseDisperseBurst` controls whether the calculation of `Trajectory.Disperse.RotateCoord` is based on its superior's `Trajectory.Disperse.WeaponBurst` of the dispersed trajectory, rather than `Burst` of the weapon. If this value is not appropriate, it will result in unsatisfactory visual displays.
    - `Trajectory.Disperse.AxisOfRotation` controls the rotation axis when calculating `Trajectory.Disperse.RotateCoord`. The axis will rotates with the unit orientation or the vector that from target position to the source position.
  - `Trajectory.Disperse.LaunchSpeed` controls the initial flight speed of the projectile, it will be directly reduced to this value if it exceeds `Trajectory.Speed`.
  - `Trajectory.Disperse.Acceleration` controls the acceleration of the projectile's flight speed, increasing the speed per frame according to this value, the final speed will not exceed `Trajectory.Speed`.
  - `Trajectory.Disperse.ROT` controls the turning speed of the projectile and can determine the turning radius of the projectile. The turning speed will increase with the increase of speed.
  - `Trajectory.Disperse.LockDirection` controls whether after reaching `Trajectory.Disperse.PreAimCoord` and completing the first turn, the projectile will lock the direction of motion without further adjustment.
  - `Trajectory.Disperse.CruiseEnable` controls whether after reaching `Trajectory.Disperse.PreAimCoord` and completing the first turn, the projectile will maintain altitude while moving towards the target.
    - `Trajectory.Disperse.CruiseUnableRange` controls how far away it is from the target to end the cruise phase, no longer maintaining the cruise altitude, and begins to move directly towards the target. If the distance is already below this value by the time `Trajectory.Disperse.PreAimCoord` is reached, the cruise phase will be skipped.
  - `Trajectory.Disperse.LeadTimeCalculate` controls whether the projectile need to calculate the lead time of the target during motion.
  - `Trajectory.Disperse.TargetSnapDistance` controls the maximum distance in cells from intended target the projectile can be at moment of detonation to make the projectile 'snap' on the intended target. Set to 0 to disable snapping.
  - `Trajectory.Disperse.RetargetRadius` controls the radius of the projectile to search for a new target after losing its original target. If it hasn't arrived `Trajectory.Disperse.PreAimCoord` yet, the last coordinate of the original target is taken as the center of the searching circle. Otherwise, the coordinate of the distance in front of the projectile is taken as the center of the circle. Set to 0 indicates that this function is not enabled, and it will still attempt to attack the original target's location. If it is set to a negative value, it will directly self explode in place.
    - `Trajectory.Disperse.RetargetAllies` controls whether the projectile chooses allies as its target when searching for new targets after losing its original target.
  - `Trajectory.Disperse.SuicideShortOfROT` controls whether the projectile will explode when it detected its insufficient turning ability.
  - `Trajectory.Disperse.SuicideAboveRange` controls the projectile to self destruct directly after reaching the flight distance. Set to 0 to disable suicide.
  - `Trajectory.Disperse.SuicideIfNoWeapon` controls whether the projectile will self destruct after the number of times it spreads the weapon has been exhausted. If `Trajectory.Disperse.WeaponCount` set to 0, this will not be enabled.
  - `Trajectory.Disperse.Weapons` defined the dispersal weapons of the projectile.
    - `Trajectory.Disperse.WeaponBurst` defined how many corresponding weapons each time the projectile will fire. When the quantity is lower than `Trajectory.Disperse.Weapons`, it will use the last value.
    - `Trajectory.Disperse.WeaponCount` controls how many times the projectile can spread the weapon. Set to a negative value means unlimited times.
    - `Trajectory.Disperse.WeaponDelay` controls the delay for dispersing the weapons defined by `Trajectory.Disperse.Weapons`.
    - `Trajectory.Disperse.WeaponTimer` controls the initial delay for dispersing the weapons defined by `Trajectory.Disperse.Weapons`.
    - `Trajectory.Disperse.WeaponScope` controls the weapon dispersing timer to start counting only within this distance of reaching the target. Set to 0 to disable this function. Set to a negative value means it will only disperse the weapon at most once before detonation.
    - `Trajectory.Disperse.WeaponSeparate` controls whether the projectile no longer fire all the weapons in `Trajectory.Disperse.Weapons` at once and instead fire a group of weapons in the list order, following `Trajectory.Disperse.WeaponBurst`.
    - `Trajectory.Disperse.WeaponRetarget` controls whether the dispersed weapons will find new targets on their own. Using the range of weapons to search new targets.
    - `Trajectory.Disperse.WeaponLocation` controls whether the dispersed weapons will search for new targets at the center of the spreading position, otherwise they will focus on the original target. If a suitable target cannot be found, it will randomly attack the ground.
    - `Trajectory.Disperse.WeaponTendency` controls whether the dispersed weapons will choose the original target as the first new target in each group of weapons.
    - `Trajectory.Disperse.WeaponToAllies` controls whether the dispersed weapons will choose allies as targets when searching for new targets.
    - `Trajectory.Disperse.WeaponToGround` controls whether the dispersed weapons will only choose the ground as their targets.

In `rulesmd.ini`:
```ini
Trajectory=Disperse                             ; Trajectory type
Trajectory.Disperse.UniqueCurve=false           ; boolean
Trajectory.Disperse.PreAimCoord=0,0,0           ; integer - Forward,Lateral,Height
Trajectory.Disperse.RotateCoord=0               ; floating point value
Trajectory.Disperse.MirrorCoord=true            ; boolean
Trajectory.Disperse.FacingCoord=false           ; boolean
Trajectory.Disperse.ReduceCoord=true [...]

2024-09-19 13:45 UTC, chaserli requested changes
This one is fully decoupled and can/should go first among all these 3 new trajectories. I might have a few concerns about potential overhead in BulletRetargetTechno but it should be fine in game.

2024-09-19 13:45 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	this->PreAimCoord = pType->PreAimCoord;
I wonder if these can be done in its constructor, because OnUnlimbo is called right after that.

2024-09-19 13:45 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			if (AnimClass* const pAnim = GameCreate<AnimClass>(pWeapon->Anim[animIndex], pBullet->Location))
sanity check only on the type. In GameCreate, allocation failure leads directly to game crash.

2024-09-19 13:45 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		const int reportIndex = pWeapon->Report.GetItem(ScenarioClass::Instance->Random.RandomRanged(0 , pWeapon->Report.Count - 1));
Sound effects use the other rng

2024-09-19 16:47 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	this->PreAimCoord = pType->PreAimCoord;
I can only say that I am not sure about this. But thousands of games have proven that this is not necessary, and this is also what the sample trajectory template tells me.

2024-09-19 16:49 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			if (AnimClass* const pAnim = GameCreate<AnimClass>(pWeapon->Anim[animIndex], pBullet->Location))
I'm sorry I didn't understand what you meant. Can you clearly tell me what needs to be modified?

2024-09-19 16:50 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		const int reportIndex = pWeapon->Report.GetItem(ScenarioClass::Instance->Random.RandomRanged(0 , pWeapon->Report.Count - 1));
What does this need to be replaced with?

2024-09-20 09:04 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			if (AnimClass* const pAnim = GameCreate<AnimClass>(pWeapon->Anim[animIndex], pBullet->Location))
I have tried to make modifications to it. If I misunderstood your meaning, please point it out.

2024-09-23 13:23 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			if (AnimClass* const pAnim = GameCreate<AnimClass>(pWeapon->Anim[animIndex], pBullet->Location))
I mean you don't need to check if result of GameCreate is null

2024-09-23 13:24 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +		const int reportIndex = pWeapon->Report.GetItem(ScenarioClass::Instance->Random.RandomRanged(0 , pWeapon->Report.Count - 1));
Check how the game handles weapon reports, it's not this rng. Using this might lead to desync, dunno

2024-09-23 14:45 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +			if (AnimClass* const pAnim = GameCreate<AnimClass>(pWeapon->Anim[animIndex], pBullet->Location))
Get it. Changed.

2024-09-23 14:51 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	this->PreAimCoord = pType->PreAimCoord;
I tried using `template <typename T> void Serialize(T& Stm);` like other ext classes, Although there were no issues with using it in `Load`, there were red wavy lines that I couldn't solve when using it in `Save`. :(

2024-09-23 14:55 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.cpp
> +	this->PreAimCoord = pType->PreAimCoord;
May I ask how I should proceed?

2024-09-23 15:08 UTC, chaserli requested changes
If I understand this correctly

2024-09-23 15:08 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +	DisperseTrajectory() : PhobosTrajectory(TrajectoryFlag::Disperse)
This one is used for s/l

2024-09-23 15:08 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
and this one is used for creation in CreateInsanstance which is right before Unlimbo, so you can initialize the values here with pType

2024-09-23 15:23 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
Thank you so much. I'll have a try.

2024-09-23 16:17 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
it's a constructor, you know for sure your pType is DisperseTrajectoryType const*. Just do it in those {}

btw I've updated the boilerplate

2024-09-23 16:18 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
Get it.

2024-09-27 15:44 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
not like that. The fact is no one touched these boilerplates until you do. You could have just think for yourself and don't have to follow the wrong example. The boilerplates were not entirely handy. It leads to your confusing impl here, for example:

* You copied lots of Type properties into trajectory, are they ever changed? if not then why not just copy the type instance or pointer?
* You passed PhobosTrajectoryType* as arg for ctor rather than DisperseTrajectoryType*, for no reason
* You initialized all those properties and then reset again in ctor, for no reason

If you find something global was written in a strange way then you can just change it, provided that you understand what it does

2024-09-27 15:47 UTC, Metadorius commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
I feel like you're being a bit too harsh, how can a newcomer figure how it is supposed to work if all they have is a not very correct example?

2024-10-02 15:52 UTC, chaserli commented on src/Ext/Bullet/Trajectories/DisperseTrajectory.h
> +		, UniqueCurve { false }
> I feel like you're being a bit too harsh, how can a newcomer figure how it is supposed to work if all they have is a not very correct example?

I just updated the boilerplate again, but as expected that's far from enough and should require a lot of work on it. Problem is neither of us maintainers has time and energy for it.
So I think if @CrimRecya keep working on these he could try fixing them first before proceed.
For example, I demoed how to fix type ptr swizzle in a236394. There's a lot more to do. At the end of the day raw traj(type) pointers should be no longer in use.

2025-01-13 14:04 UTC, TaranDahl commented
I use this as a substitute for the ROT projectile. It performs well in local tests and solves many problems caused by the design defects of the ROT projectile.

2025-03-18 15:15 UTC, CrimRecya commented
Has been completely rewrited.

2025-03-18 15:15 UTC, closed without merging