Animation transparency customization settings
Phobos-developers/Phobos pull request #1304
Opened 2024-07-11 13:41 UTC by Starkku

Split from #1300 

-------------

### Customizable animation transparency settings

- `Translucency.Cloaked` can be used to override `Translucency` on animations attached to currently cloaked TechnoTypes.
- Properties of the three transparency stages used by `Translucent=true`can now be customized per animation type.
  - `Translucent.StageX.Percent` controls at what percentage through the animation's frames the applicable translucency stage becomes active.
    - If `Translucent.StageX.Frame` is set, this explicit frame value is used instead.
  - `Translucent.StageX.Translucency` controls the transparency level for the stage.

In `artmd.ini`:
```ini
[SOMEANIM]                          ; AnimationType
Translucency.Cloaked=               ; integer - only accepted values are 75, 50, 25 and 0.
Translucent.Stage1.Percent=0.2      ; floating point value, percents or absolute
Translucent.Stage1.Frame=           ; integer, 0-based frame index
Translucent.Stage1.Translucency=25  ; integer - only accepted values are 75, 50, 25 and 0.
Translucent.Stage2.Percent=0.4      ; floating point value, percents or absolute
Translucent.Stage2.Frame=           ; integer, 0-based frame index
Translucent.Stage2.Translucency=50  ; integer - only accepted values are 75, 50, 25 and 0.
Translucent.Stage3.Percent=0.6      ; floating point value, percents or absolute
Translucent.Stage3.Frame=           ; integer, 0-based frame index
Translucent.Stage3.Translucency=75  ; integer - only accepted values are 75, 50, 25 and 0.
```

2024-09-29 21:44 UTC, Starkku commented
Now uses @Metadorius's `Animatable` template that allows defining arbitrary keyframe animations in INI.

Might require testing to see if there's a noticeable performance overhead from the template.

2024-09-29 22:02 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +}
I think you can collapse all that by defining a primitive interpolation or two, say, on double, and routing all other specializations to that. Although I would probably make interpolation mode a template param (not sure on that?) and write different functions per each interpolation, and have a single function that dispatches stuff. Could also make it a separate file for clarity, this file is getting quite big.

2024-09-29 22:11 UTC, Metadorius commented on src/Ext/Anim/Hooks.cpp
> +			flags |= pTypeExt->Translucent_Keyframes.Get(static_cast<double>(currentFrame) / frames);
Isn't there a timer somewhere that will happily already give you a percentage?

2024-09-29 22:11 UTC, Metadorius commented on src/Ext/Anim/Hooks.cpp
> +				flags |= BlitterFlags::TransLucent25;
Not sure if we should hardcode that?

2024-09-29 22:16 UTC, Starkku commented on src/Ext/Anim/Hooks.cpp
> +				flags |= BlitterFlags::TransLucent25;
This is the default `Translucent` behaviour used if the keyframes are not in place.

2024-09-29 22:17 UTC, Starkku commented on src/Ext/Anim/Hooks.cpp
> +			flags |= pTypeExt->Translucent_Keyframes.Get(static_cast<double>(currentFrame) / frames);
No. `StageClass` deals with integer increments.

2024-09-29 22:20 UTC, Starkku commented on src/Ext/Anim/Hooks.cpp
> +					flags |= BlitterFlags::TransLucent50;
No, not 75.

2024-09-29 22:21 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +  - Keyframes should be listed in ascending order with no duplicate percentages / frames across different keyframes. Failure to do so can produce unpredictable results.
Sure if you can think of a way to check for this without adding another massive layer of complexity.

2024-09-29 22:28 UTC, Starkku commented on src/Ext/Anim/Hooks.cpp
> +			return ReturnFromFunction;
Reverse-engineered game code. `translucencyLevel` is some sort of stage/timer thing set on building anims when they need to be drawn at certain transparency when they are normally not, contrary to the YRpp description seems to go from 0 to 15 and is directly copied from the parent building's field `0x6ED`. Rest is just mapping the `Translucency` integer to correct blitter flags.

Perhaps, the translucency stages are basically self-explanatory though and this is probably the only place where whatever the shit `translucencyLevel` is supposed to mean is used.

2024-09-29 22:30 UTC, Metadorius commented on src/Ext/Anim/Hooks.cpp
> +			return ReturnFromFunction;
could leave a comment where stuff is reversed and where custom additions start and we're gucci I htink?

2024-09-29 22:31 UTC, Metadorius commented on src/Ext/Anim/Hooks.cpp
> +				flags |= BlitterFlags::TransLucent25;
oh, a comment explaining that would be good in this case

2024-09-29 22:36 UTC, Starkku commented on src/Utilities/TemplateDef.h
> +}
Honestly I question the need for interpolation modes beyond none and linear in the first place anyway.

2024-09-29 23:27 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +}
It depends on the use case. Although I can agree that the specific use cases I am thinking of are rather niche.

What I had in mind was a buildup anim/deploy techno attachment FLH translation, for instance, or maybe just movable FLH/TurretOffset for animated units.

2024-09-29 23:28 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +}
It is probably still good to lay out the ground for easier extensibility while we're at it.

2024-10-09 19:42 UTC, Starkku commented on src/Utilities/TemplateDef.h
> +}
> I think you can collapse all that by defining a primitive interpolation or two, say, on double, and routing all other specializations to that

This is heavily case-specific. It works for numeric values like integers (can just truncate the double result) but pretty much anything else does not work like that. ColorStruct, one of the examples I added in wouldn't work like this for an example - you can't just create the color data out of thin air from a floating point value.

2024-11-11 07:04 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +Translucent.Interpolation=none      ; Interpolation mode (none|linear)
```suggestion
Translucent.KeyframeN.Value=        ; integer - only accepted values are 75, 50, 25 and 0.
Translucent                         ; animatable translucency value - only accepted values are 75, 50, 25 and 0.
```

This way we only need to update one place when we update the template. Also need to add a link to animatable template description.

Accepting ideas on better syntax in the code block.

2024-11-11 07:04 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +		_snprintf_s(flagName, sizeof(flagName), pBaseFlag, i, "%s");
I am pretty sure I used `%%` somewhere around here? Just in case, it was not a typo, it's just a way to escape the `%` character because we do formatting twice and need it in the second formatting pass.

2024-11-11 07:06 UTC, Metadorius commented on CREDITS.md
> +  - Animation transparency customization settings
Could you add us as authors of animatable template too?

2024-11-11 07:07 UTC, Starkku commented on src/Utilities/TemplateDef.h
> +		_snprintf_s(flagName, sizeof(flagName), pBaseFlag, i, "%s");
Yeah but it didn't actually work

2024-11-11 07:12 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +		_snprintf_s(flagName, sizeof(flagName), pBaseFlag, i, "%s");
:isothonk:

That's weird because the docs say it's the correct way to escape... oh well

2024-11-11 07:16 UTC, Starkku commented on src/Utilities/TemplateDef.h
> +		_snprintf_s(flagName, sizeof(flagName), pBaseFlag, i, "%s");
You don't need to escape it in the args, only in the format specifier if you actually want it to include % as a character. Having double % in the args was causing it to print it twice in the buffer so parsing didn't work.

2025-03-28 09:07 UTC, Starkku commented
Updated credits & docs, ready for another review pass and/or further testing if needed, if not then merge.

2025-06-23 10:19 UTC, Coronia commented
tested and worked

2025-11-09 12:53 UTC, Starkku commented
This is actually complete and has been for a while. If @Metadorius wants to give a quick check that all the issues brought up in previous comment are addressed and/or otherwise give it a glance I'd say it is good to merge after that.

2025-11-09 17:01 UTC, Metadorius requested changes
@Starkku @ZivDero @CrimRecya What do you think of robustness of the design for the use of multiflag vectors with LaserTrailDataEntry, for example? And other multiflag vectors if you can think of any.

LGTM otherwise

2025-11-09 17:01 UTC, Metadorius commented on src/Ext/Anim/Hooks.cpp
> +		if (pTypeExt->Translucent_Keyframes.KeyframeData.size() > 0)
I do think we should make a shortcut function to check whether the template values are set

2025-11-09 17:01 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +	// Thing is still far from lightweight as searching for the correct items requires going through the vector.
I do think making a cache LUT on the fly based on results of calculation would be a smart idea, just like voxel caching is done.

2025-11-09 17:01 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +void __declspec(noinline) MultiflagValueableVector<T, TExtraArgs...>::Read(INI_EX& parser, const char* const pSection, const char* const pBaseFlag, TExtraArgs&... extraArgs)
I wonder whether it is a good idea to add a `.ResetList=true/false` subflag (not serialized, just controls the behavior) here for overriding in map files? If not set - list entries replace the old ones one by one, if set - keyframes are re-set and it's read anew.

2025-11-09 17:01 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +	this->KeyframeData.Read(parser, pSection, flagName, absoluteLength);
I propose to add a shortcut of `BaseFlag=value` reading if the `KeyframeData` is empty. It will populate it with 1 keyframe with no interpolation, effectively allowing to use the template the same as a simple `Valueable<T>` if user wishes, effectively making it a drop-in extension for the latter and allowing to animate anything.

This will also work nice with `.ResetData` subflag if the user wishes to redefine to a simple value.

2025-11-09 17:01 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +	absoluteTemp.Read(parser, pSection, flagName);
We probably should check whether absoluteLength is not 0 and if it is 0 then not read absolute at all

2025-11-09 17:03 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +	this->KeyframeData.Read(parser, pSection, flagName, absoluteLength);
Also remind me, what does the template return if there's no values? It probably should return the default for T?

2025-12-03 21:15 UTC, ZivDero commented on src/Utilities/Interpolation.h
> +		return first;
This needs to throw some kind of warning at the user so that they know they're missing an implementation.

2025-12-04 03:40 UTC, Starkku commented
Updated with feedback addressed.

The translucency customization code has been refactored a bit, instead of keyframes affecting `Translucent` it is now tied to `Translucency` to be more consistent with how the template works with animatable values. `Translucency.Cloaked` can also now be keyframed.

2026-04-28 12:58 UTC, Metadorius approved these changes
LGTM

2026-04-28 13:59 UTC, Metadorius submitted a review, later dismissed

2026-04-28 13:59 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +		T dataEntry {};
rules:
```ini
Some0.Bull=1
Some0.Shit=2
Some1.Bull=3
Some1.Shit=4
```

map:
```ini

Some1.Bull=0
```

expected result:
```ini
Some0.Bull=1
Some0.Shit=2
Some1.Bull=0
Some1.Shit=4
```

I think it currently will result in
```ini
Some0.Bull=1
Some0.Shit=2
Some1.Bull=0
Some1.Shit=<default>
```

which is not expected

I propose to change the vector to not create a new `T dataEntry {}` always but use the existing one if it exists, and to add `.ResetValue` but per each entry; the only thing it would do is force `T dataEntry {}` always.

Also should move the whole vector ResetValues here from Animatable

2026-04-29 20:09 UTC, Starkku commented
Implemented following changes:

- Rename `ResetData`  to `ResetValues` and move from `Animatable` to `MultiflagValueable/NullableVector`
- Make `MultiflagValueable/NullableVector` retain existing values on further parsing passes if unchanged unless explicitly reset.
- Clean up repetitive code in  `MultiflagValueable/NullableVector` with helper functions.
- Disallow < 0 values for `KeyFrameData.Percentage `, throw fatal error on parsing if present.
- Allow parsing `KeyFrameData` on further parsing passes if `Percentage` was parsed on previous pass but not on current.
- Fix base flag name getting cut on the Animatable parsing error fatal error message box.
- Place sorted keyframes in separate vector from parsed values, recalculate on every parsing pass to ensure data correctness.

Note about the sorting change: I did explore other solutions but they basically boiled down to the following and every single one of them had in my opinion more issues than the chosen approach.
1.  Sort once on first call to `Get()`: Clean but adds runtime during game itself and not just to loading screen.
2. Sort once after all parsing passes are done: Identifying the final parsing pass reliably is not easily doable, it can be up to 4 times (rules, non-client gamemode INI, map file, `tmcj4f.ini` if the cheat option is on) but at the minimum it is 1.
3. Sort once manually on some kind of 'finalize' function: Manually keeping track of all `Animatable` instances, adding some mechanism after all parsing has been done etc. would be way too much work and potentially way more annoying for devs to use as well.
4. Remove binary search: A possibility but ironically enough linear search solutions that are not terrible for performance are harder to understand and read.

And in case it wasn't clear why this had to be changed to begin with, sorting the parsed data always after each parsing pass was causing problems with the data if re-parsed (e.g keyframe indices no longer match originals, possibly)

2026-06-16 12:21 UTC, Starkku commented
Merging, latest changes were approved elsewhere.

2026-06-16 12:21 UTC, merged