Extra warhead multiplier for different houses
Phobos-developers/Phobos pull request #1307
Opened 2024-07-14 15:02 UTC by CrimRecya

- Warheads are now able to define the extra damage multiplier for owner house, ally houses and enemy houses. The values in warheads are default to respective `[CombatDamage]` -> `DamageXXMultiplier`, which all default to 1.0 .Note that this will not affect damage with ignore defenses.

In `rulesmd.ini`:
```ini
[CombatDamage]
DamageOwnerMultiplier=1.0     ; floating point value
DamageAlliesMultiplier=1.0    ; floating point value
DamageEnemiesMultiplier=1.0   ; floating point value

[SOMEWARHEAD]                 ; Warhead
DamageOwnerMultiplier=        ; floating point value
DamageAlliesMultiplier=       ; floating point value
DamageEnemiesMultiplier=      ; floating point value
```

2024-07-30 14:52 UTC, Sovietianqi approved these changes

2024-08-14 17:51 UTC, Coronia requested changes
since Phobos already has an extra warhead logic, suggest to rename this one a bit. 'damage multiplier for different houses' perhaps

2024-08-14 17:51 UTC, Coronia commented on src/Ext/Techno/Hooks.Shield.cpp
> +		}
the current implementation will make those global multipliers being omitted if warhead multipliers set to 1.0, which seems to be wrong. Also you can't just use Nullable variable before asserting if it's set or not. In fact you could just remove the if statement here and let Get function do the job, since it'll pick the default 1.0 if it's not set

		if (pHouse == args->SourceHouse)
			calculateDamage = static_cast<int>(*args->Damage * pWHExt->DamageOwnerMultiplier.Get(RulesExt::Global()->DamageOwnerMultiplier));
		else if (pHouse->IsAlliedWith(args->SourceHouse))
			calculateDamage = static_cast<int>(*args->Damage * pWHExt->DamageAlliesMultiplier.Get(RulesExt::Global()->DamageAlliesMultiplier));
		else
			calculateDamage = static_cast<int>(*args->Damage * pWHExt->DamageEnemiesMultiplier.Get(RulesExt::Global()->DamageEnemiesMultiplier));

2024-08-14 18:05 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Shield.cpp
> +		}
My mistake, get it.

2024-08-15 16:22 UTC, Coronia requested changes
think it'd better not to be blocked by IgnoreDefenses in order to be consistent with other firepower multipliers. The shield part can be kept as it was

2024-08-15 17:13 UTC, CrimRecya commented on docs/New-or-Enhanced-Logics.md
> +- Warheads are now able to define the extra damage multiplier for owner house, ally houses and enemy houses. The values in warheads are default to respective `[CombatDamage]` -> `DamageXXMultiplier`,
Okay, I see.

2024-08-16 10:29 UTC, Coronia approved these changes

2025-02-20 10:20 UTC, TaranDahl commented
I hope there can be an independent flag control to make the friendly damage modifier ineffective for the main target. If possible. There is such a need: I hope that a certain unit will not take out nearby friendly forces together when attacking the enemy, but in some cases, forced attacks on friendly forces will be required (for example, when an AI's building blocks the road).

2025-02-24 14:04 UTC, merged