Hotkey to select captured units
Phobos-developers/Phobos pull request #1314
Opened 2024-07-15 14:22 UTC by TaranDahl

A new hotkey to select the units within the current screen that are captured by non-permanent mind-controller.
- Select the units within the current screen that are captured by non-permanent mind-controller.
- If selected any unit, `MSG:SelectCaptured` is logged on the left-top of the screen, otherwise `MSG:NothingSelected` is logged.
- For localization add `MSG:SelectCaptured`, `TXT_SELECT_CAPTURED` and `TXT_SELECT_CAPTURED_DESC` into your `.csf` file.

This may be useful when you want to make the captured units enter a grinder or charge forward of your own forces.

2024-08-22 13:04 UTC, CrimRecya requested changes

2024-08-22 13:17 UTC, TaranDahl commented on src/Commands/SelectCaptured.cpp
> +			if (screenArea.Width >= coordInScreen.X && screenArea.Height >= coordInScreen.Y && coordInScreen.X >=0 && coordInScreen.Y >= 0 && // the unit is in the current screen
fixed

2024-08-22 13:49 UTC, CrimRecya approved these changes

2025-03-12 10:30 UTC, TaranDahl commented
What is the topic to be discussed then? @Coronia

2025-03-12 11:21 UTC, Coronia commented
> What is the topic to be discussed then? @Coronia

https://github.com/Phobos-developers/Phobos/issues/1496 it's still about these hotkeys can't really be hidden in the Keyboard setting page, making players able to see them no matter if a mod uses it or not. So either we should resolve this issue first, or discuss whether a hotkey is generally accepted by modders before merging it

2025-03-12 11:26 UTC, Metadorius commented
Can we move the hotkey registration to after reading rules? Then we would be able to remove disabled hotkeys.

2025-03-12 11:35 UTC, TaranDahl commented
> Does double pressing the hotkey select units across the whole map, like vanilla hotkeys do?-----------谷歌翻译-----------双重按键在整个地图上选择单元是否像香草热键一样？

At present, this has not been made. In addition, in actual use, I feel that this is not very necessary.

2026-07-26 07:17 UTC, merged