Jumpjet Climbing Logic Enhancement
Phobos-developers/Phobos pull request #1318
Opened 2024-07-18 14:37 UTC by CrimRecya

In vanilla game, the jumpjet unit would stop horizontal movement as it rose to a relatively high altitude. Here are two options to change this.
- You can now let the jumpjets increase their height earlier by set `JumpjetClimbPredictHeight` to true or simply let them skip the stop check by set `JumpjetClimbWithoutCutOut` to true.

In `rulesmd.ini`:
```ini
[General]
JumpjetClimbPredictHeight=false  ; boolean
JumpjetClimbWithoutCutOut=false  ; boolean
```

2024-08-14 17:25 UTC, Coronia requested changes
some comments on how certain 'magic number' coming out would be nice, for example:

	if (pCell->FindTechnoNearestTo(Point2D::Empty, false))
		height += 85;
why 85 here?

			const int checkStep = (largeStep >> 7) + ((largeStep & 0x7F) ? 2 : 1);
and what's this for?

2024-08-14 17:25 UTC, Coronia commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +		pObject = pObject->NextObject;
while (pObject && pObject->WhatAmI() != AbstractType::Building)
	{
		pObject = pObject->NextObject;
	}

2024-08-14 17:56 UTC, CrimRecya commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +		pObject = pObject->NextObject;
I add the notes, and change the last one.

2024-08-24 11:30 UTC, CrimRecya commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +	if (!pCell)
Oh, you're right, this was my negligence. I will modify it to TryGetCellAt later, thx for pointing it out.

2025-01-08 10:30 UTC, TaranDahl commented
Tested locally. Doing good.

2025-01-08 10:30 UTC, TaranDahl approved these changes

2025-03-07 08:55 UTC, Coronia commented
Doc needs more details about the behaviors of these 2 tags. For example: when'll the aircraft height change if `JumpjetClimbWithoutCutOut` set to true, what'll happen if an aircraft stop during the process of earlier height changing, and what'll happen if these 2 tags being used at the same time

2025-03-12 20:40 UTC, mevitar commented
Didn't find any issues. Didn't try in multiplayer.

2025-08-09 13:39 UTC, Coronia approved these changes

2025-08-16 17:19 UTC, merged