Spawn returning optimization
Phobos-developers/Phobos pull request #1333
Opened 2024-07-31 15:13 UTC by TaranDahl

Buildings with foundation bigger than 1x1 can now recycle spawned correctly.
A new flag `Spawner.RecycleRange` allow the spawner can recycle spawns in long-range.
A new flag `Spawner.RecycleAnim` allow playing an anim when the spawned is recycled.

2024-08-14 17:08 UTC, Coronia requested changes
the doc is incomplete. Should add description for Spawner.RecycleOnTurret and Spawner.FLH (should be Spawner.RecycleFLH probably?)

2024-08-14 17:08 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +	auto spawnerCrd = pSpawner->GetCoords();
if (!pThis)
		return 0;

	auto pSpawner = pThis->Owner;

	if (!pSpawner || !pSpawned)
		return 0;

	auto const pSpawnerType = pSpawner->GetTechnoType();
	auto spawnedMapCrd = pSpawned->GetMapCoords();

	if (!pSpawnerType)
		return 0;

	auto const pSpawnerExt = TechnoTypeExt::ExtMap.Find(pSpawnerType);

	if (!pSpawnerExt)
		return 0;

	auto spawnerCrd = pSpawner->GetCoords();

2024-08-14 17:08 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +	}
int recycleRange = pSpawnerExt->Spawner_RecycleRange;

	if (recycleRange < 0 && deltaCrd.Z < 20)
	{
		if (pSpawner->WhatAmI() == AbstractType::Building)
		{
			shouldRecycleSpawned = deltaCrd.X <= 182 && deltaCrd.Y <= 182;
		}
		else
		{
			shouldRecycleSpawned = spawnedMapCrd == *pSpawnerMapCrd;
		}
	}

2024-08-14 17:08 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +	if (!shouldRecycleSpawned)
else
	{
		shouldRecycleSpawned = deltaCrd.Magnitude() <= recycleRange;
	}

	if (!shouldRecycleSpawned)

2024-08-14 17:08 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +		pSpawned->SetLocation(spawnerCrd);
if (pSpawnerExt->Spawner_RecycleAnim)
		{
			GameCreate<AnimClass>(pSpawnerExt->Spawner_RecycleAnim, spawnedCrd);
		}

		pSpawned->SetLocation(spawnerCrd);

2024-08-17 03:38 UTC, TaranDahl commented
> the doc is incomplete. Should add description for Spawner.RecycleOnTurret and Spawner.FLH (should be Spawner.RecycleFLH probably?)

It's not the doc, it's the code. I once planned the recycle flh to be impl recently, but it seems that it is not as simple as I thought.
gamemd will act the following codes if the spawnee is not close enough to the spawner. The spawnee will target the spawner rather than the spawner's coords. I don't know how to apply flh on this.
I will make the unfinished flags comment. I may impl them when I have an idea.
```
pSpawnee->SetDestination(pSpawnee, this->Owner, 1);
pSpawnee->SetTarget(pSpawnee, 0);
pSpawnee->QueueMission(pSpawnee, Mission_Move, 0);
```

2024-08-17 03:49 UTC, TaranDahl commented on src/Ext/Techno/Hooks.Misc.cpp
> +	auto spawnerCrd = pSpawner->GetCoords();
All of the code style problems are fixed.

2025-02-24 17:05 UTC, TaranDahl commented
This pr is completed and ready to be reviewed. I think.

2025-02-25 17:58 UTC, CrimRecya reviewed
Currently working well, and there are some minor issues in the code that can be modified.

2025-02-25 17:58 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		return 0;
These have all been used, I think there is no need to do sanity check.

2025-02-25 17:58 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		return 0;
When the pointer is determined to be `Techno`, the result of `GetTechnoType()` should not need to be checked again. `TechnoTypeExt` is the same. Just like the hook you did behind.

2025-02-25 17:58 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +	if (!shouldRecycleSpawned)
I think you can encapsulate this function.

2025-02-25 17:58 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +	}
```suggestion
	auto const pCarrier = pThis->Owner;
	auto const pCarrierTypeExt = TechnoTypeExt::ExtMap.Find(pCarrier->GetTechnoType());
	auto const spawnerCrd = pSpawner->GetCoords();

	auto shouldRecycleSpawned = [&]()
	{
		auto const recycleCrd = TechnoExt::GetFLHAbsoluteCoords(pCarrier, pCarrierTypeExt->Spawner_RecycleFLH, pCarrierTypeExt->Spawner_RecycleOnTurret);
		auto const deltaCrd = spawnerCrd - recycleCrd;
		const int recycleRange = pCarrierTypeExt->Spawner_RecycleRange;

		if (recycleRange < 0)
		{
			// This is a fix to vanilla behavior. Buildings bigger than 1x1 will recycle the spawner correctly.
			// 182 is √2/2 * 256. 20 is same to vanilla behavior.
			if (pCarrier->WhatAmI() == AbstractType::Building && deltaCrd.X <= 182 && deltaCrd.Y <= 182 && deltaCrd.Z < 20)
				return true;

			if (pCarrier->WhatAmI() != AbstractType::Building && pSpawner->GetMapCoords() == *pCarrierMapCrd && deltaCrd.Z < 20)
				return true;
		}
		else if (deltaCrd.Magnitude() <= recycleRange)
		{
			return true;
		}

		return false;
	};

	if (shouldRecycleSpawned())
	{
		if (pCarrierTypeExt->Spawner_RecycleAnim)
			GameCreate<AnimClass>(pCarrierTypeExt->Spawner_RecycleAnim, spawnerCrd);

		pSpawner->SetLocation(pCarrier->GetCoords());
		R->EAX(pCarrierMapCrd);
	}

	return 0;
```

2025-02-25 17:58 UTC, CrimRecya commented on CREDITS.md
> +  - Recycle the spawner on other FLH (by TaranDahl)
Remember to remove the repeated name here. :P

2025-02-26 07:12 UTC, CrimRecya approved these changes

2025-02-26 13:50 UTC, CrimRecya commented
The use of buildings may differ from real FLH, as `GetRenderCoords()` is used for buildings, while `TechnoExt::GetFLHAbsoluteCoords` called here will use `GetCoords()`. Of course, this will effectively avoid the problem of Z-axis being below 0.
Meanwhile, since the turret of the building uses `PrimaryFacing`, using this function is unlikely to rotate regardless of whether there is a turret or not.

2025-03-04 04:16 UTC, CrimRecya requested changes
The recent testing has raised my concerns about the performance of this feature.

2025-03-04 04:16 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +	return 0;
Can it be split into two hooks and avoid duplicate calculations? This hook still make it do the useless check in its original position.

2025-03-04 04:16 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		return false;
```suggestion
		if (recycleRange < 0)
		{
			// This is a fix to vanilla behavior. Buildings bigger than 1x1 will recycle the spawner correctly.
			// 182 is √2/2 * 256. 20 is same to vanilla behavior.
			return (pCarrier->WhatAmI() == AbstractType::Building)
				? (deltaCrd.X <= 182 && deltaCrd.Y <= 182 && deltaCrd.Z < 20)
				: (pSpawner->GetMapCoords() == *pCarrierMapCrd && deltaCrd.Z < 20);
		}

		return deltaCrd.Magnitude() <= recycleRange;
```

2025-03-04 04:16 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		auto const recycleCrd = TechnoExt::GetFLHAbsoluteCoords(pCarrier, pCarrierTypeExt->Spawner_RecycleFLH, pCarrierTypeExt->Spawner_RecycleOnTurret);
```suggestion
		auto const FLH = pCarrierTypeExt->Spawner_RecycleFLH.Get();
		auto const recycleCrd = FLH != CoordStruct::Empty
			? TechnoExt::GetFLHAbsoluteCoords(pCarrier, FLH, pCarrierTypeExt->Spawner_RecycleOnTurret)
			: pCarrier->GetCoords();
```

2025-03-07 14:57 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		auto deltaCrd = TechnoExt::GetFLHAbsoluteCoords(pCarrier, pCarrierTypeExt->Spawner_RecycleFLH, pCarrierTypeExt->Spawner_RecycleOnTurret) - pCarrier->GetCoords();
There is also a similar minor issue here.
```suggestion
		auto const& FLH = pCarrierTypeExt->Spawner_RecycleFLH.Get();

		if (FLH != CoordStruct::Empty)
			*pDestCrd += TechnoExt::GetFLHAbsoluteCoords(pCarrier, FLH, pCarrierTypeExt->Spawner_RecycleOnTurret) - pCarrier->GetCoords();
```

2025-03-07 15:03 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +		*pDestCrd += deltaCrd;
There is also a similar minor issue here.
```suggestion
		auto const& FLH = pCarrierTypeExt->Spawner_RecycleFLH.Get();

		if (FLH != CoordStruct::Empty)
			*pDestCrd += TechnoExt::GetFLHAbsoluteCoords(pCarrier, FLH, pCarrierTypeExt->Spawner_RecycleOnTurret) - pCarrier->GetCoords();
```

2025-03-08 02:59 UTC, TaranDahl commented on src/Ext/Techno/Hooks.Misc.cpp
> +	return 0;
I have changed the return location. Please check again.

2025-03-09 16:06 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +			GameCreate<AnimClass>(pCarrierTypeExt->Spawner_RecycleAnim, spawnerCrd);
suggest to add `SetAnimOwnerHouseKind` and `SetInvoker` here, to allow it able to do more thing with anim weapon/warhead

2025-03-10 02:53 UTC, Coronia commented
gonna merge https://github.com/Phobos-developers/Phobos/pull/1349 first. Please check if these 2 functions are compatible with each other

2025-03-10 03:15 UTC, TaranDahl commented
> gonna merge #1349 first. Please check if these 2 functions are compatible with each other-----------谷歌翻译-----------首先要合并＃1349。请检查这两个功能是否彼此兼容

There should be no conflict.

2025-03-11 10:28 UTC, TaranDahl commented
The tester confirmed that there is no conflict with the existing functions.

2025-03-11 13:22 UTC, Coronia reviewed
so far out test with VerySleepy shows that SpawnManagerClass_Update_RecycleSpawned hook is not perf consuming, but not sure about the other

2025-03-11 13:22 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +		auto const& FLH = pCarrierTypeExt->Spawner_RecycleFLH.Get();
same as above

2025-03-11 13:22 UTC, Coronia commented on src/Ext/TechnoType/Body.h
> +		Valueable<AnimTypeClass*> Spawner_RecycleAnim;
what's the reason that this is not a Nullable?

2025-03-11 13:22 UTC, Coronia commented on src/Ext/TechnoType/Body.h
> +			, Spawner_RecycleAnim { nullptr }
doesn't need to specify nullptr

2025-03-11 13:22 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +DEFINE_HOOK(0x4D962B, FootClass_SetDestination_RecycleFLH, 0x5)
just asking: when'll this hook be called? We've tested with VerySleepy but didn't see any call with it

2025-03-11 15:23 UTC, TaranDahl commented on src/Ext/Techno/Hooks.Misc.cpp
> +DEFINE_HOOK(0x4D962B, FootClass_SetDestination_RecycleFLH, 0x5)
When the spawner returns, it will `SetDestination` to the carrier. This hook sets its destination to RecycleFLH instead of the destination of the carrier.

2025-03-12 03:05 UTC, Coronia reviewed
other than the Lepton thing, the code logic should be fine. But we still need to discuss how these tags should be arranged

2025-03-12 03:05 UTC, Coronia commented on src/Ext/TechnoType/Body.cpp
> +	this->RecycleOnTurret.Read(exArtINI, pArtSection, "RecycleOnTurret");
I'm not sure if these 2 tags should be put into art, need some other feedbacks @CrimRecya @Metadorius 

btw, if it's an art tag, then it could keep the previous `RecycleFLH` name. `RecycleCoord` (don't use plural here) is suggested only if it's a rules tag

2025-03-12 03:05 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +		const int recycleRange = pCarrierTypeExt->Spawner_RecycleRange * Unsorted::LeptonsPerCell;
these warning won't appear if proper Lepton definition is used

2025-03-15 14:24 UTC, Coronia approved these changes
there're still some minor issues on the docs, but I'll fix it later

2025-03-15 14:35 UTC, merged