Voxel Lighting Customization
Phobos-developers/Phobos pull request #1336
Opened 2024-08-05 16:16 UTC by Metadorius

TODO
- [ ] transform into world coords
- [ ] docs

Allows customizing the direction of voxel light in order to provide better visuals ingame.

In `rulesmd.ini`
```ini
[AudioVisual]
VoxelLightSource=0.02,-0.69,0.36
VoxelShadowLightSource=0.02,-0.69,0.36
```

The values are unset by default. The example values are according to the convo in Discord where @thomassneddon and CCrisp mentioned that those coords correspond are used to produce the following (apparently in radians? not sure)

> This is the value of projected light source direction i mentioned above, and as a result, the world space direction of YR VXL light is approx 0.20, -0.91, -0.36

On stock voxels, VPL, palette this looks like this, vanilla vs the above:

![vanilla](https://github.com/user-attachments/assets/074058b8-6a7c-4eda-af03-1877b871e64f)
![tweaked](https://github.com/user-attachments/assets/24c4d434-3a7d-4c24-9308-2447d4a05cdf)

2024-08-05 17:41 UTC, Metadorius commented
![image](https://github.com/user-attachments/assets/6db3bad9-de05-46d2-8cbb-954a087e22ac)

2024-08-06 20:04 UTC, Starkku requested changes
Looks good to me for most part.

2024-08-06 20:04 UTC, Starkku commented on docs/Fixed-or-Improved-Logics.md
> +VoxelLightSource= ; X,Y,Z - position of the light
The value description probably needs to be something more descriptive than just this, at the very least it should mention that they're floating point values.

2024-08-06 20:06 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +VoxelLightSource= ; X,Y,Z - position of the light
```suggestion
VoxelLightSource=  ; X,Y,Z - position of the light, floating point values
```

2024-08-06 20:08 UTC, Starkku approved these changes

2024-08-06 20:10 UTC, merged