Terror drone return fix
Phobos-developers/Phobos pull request #1342
Opened 2024-08-08 09:33 UTC by TaranDahl

Fix the bug that parasite will vanish if it missed its target when its previous cell is occupied.

2024-08-14 16:30 UTC, Coronia requested changes
remember the following code styles:
- leave one blank line before and after if/switch sections, same for loop sections
- use a bracket {} to cover the loop sections, even if there's only 1 line in it
- add a const to variables that won't be modified

2024-08-14 16:30 UTC, Coronia commented on src/Misc/Hooks.BugFixes.cpp
> +				false, false, true, CellStruct::Empty, false, false);
auto pParasiteTechno = pParasite->Owner;

	if (bIsReturnSuccess || !pParasiteTechno)
		return 0;

	const auto pType = pParasiteTechno->GetTechnoType();

	if (!pType)
		return 0;

	auto cell = MapClass::Instance->NearByLocation(pParasiteTechno->LastMapCoords,
				pType->SpeedType, -1, pType->MovementZone, false, 1, 1, false,
				false, false, true, CellStruct::Empty, false, false);

2024-08-17 02:34 UTC, TaranDahl commented on src/Misc/Hooks.BugFixes.cpp
> +				false, false, true, CellStruct::Empty, false, false);
Fixed.

2024-08-17 21:23 UTC, mevitar commented
Without this fix, Terror Drones are destroyed if they miss and the previous space is occupied. After this fix, they respawn in the nearest free spot, unoccupied by buildings or units.
It seems to work fine, didn't notice any issues. Didn't test in multiplayer, though.

2024-08-22 13:13 UTC, CrimRecya requested changes

2024-08-22 13:13 UTC, CrimRecya commented on src/Misc/Hooks.BugFixes.cpp
> +	bool bIsReturnSuccess = (BYTE)((WORD)(dwdIsReturnSuccess));
I think this can simply change to `GET(bool, bIsReturnSuccess, EAX);` ?

2024-08-22 15:26 UTC, TaranDahl commented on src/Misc/Hooks.BugFixes.cpp
> +	bool bIsReturnSuccess = (BYTE)((WORD)(dwdIsReturnSuccess));
Changed. Didn't tested, though.

2024-08-30 10:32 UTC, CrimRecya approved these changes

2025-02-09 15:02 UTC, merged