Enable waypoint for buildings and aircrafts
Phobos-developers/Phobos pull request #1343
Opened 2024-08-08 15:29 UTC by TaranDahl

### Waypoint for buildings and aircrafts

- In vanilla, buildings and aircrafts is forbiddened to use waypoint. Now you can turn it on by the following flags.
- P.S.: We have no idea about the reason why ww turn this off. In fact this has **not** been tested throughly. So, use it with caution.

In `rulesmd.ini`:
```ini
[General]
BuildingWaypoint = false    ; boolean
AircraftWaypoint = false    ; boolean
```

2024-08-08 21:16 UTC, Metadorius requested changes

2024-08-08 21:16 UTC, Metadorius commented on src/Ext/Techno/Hooks.Misc.cpp
> +	Patch::Apply_RAW(0x465915, { 0xC3 });
Why do you need to apply raw patches in hook?

2024-08-08 21:16 UTC, Metadorius commented on src/Ext/Techno/Hooks.Misc.cpp
> +	}
You can simply R->AL(RulesExt::Global()->BuildingWaypoint.Get()) or something like that

2024-08-08 21:16 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +AircraftWaypoint = false    ; boolean
```suggestion
BuildingWaypoint=false    ; boolean
AircraftWaypoint=false    ; boolean
```

2024-08-09 02:28 UTC, TaranDahl commented on src/Ext/Techno/Hooks.Misc.cpp
> +	Patch::Apply_RAW(0x465915, { 0xC3 });
I once thought hooking a jumping code would cause abnormal behavior. 
nvm, it's changed for now.

2024-08-09 02:31 UTC, TaranDahl commented on src/Ext/Techno/Hooks.Misc.cpp
> +	}
changed.

2024-08-09 06:22 UTC, chaserli commented
The current impl is too simplified and doesn't take other factors like radio links or the planning path itself into consideration.

2024-08-09 15:26 UTC, TaranDahl commented
> The current impl is too simplified and doesn't take other factors like radio links or the planning path itself into consideration.

我不是很懂RadioClass的作用，能否请您说得更详细点😂我这里测试在单机情况下是基本正常工作的，也能正常存档读档（最开始忘了写存档了，现在已经补了）。不过我不是特别懂测试，可能有边界情况没考虑周全，而且也没有条件测试联机情况。希望您能讲得更详细一些我好修改🙇‍

2024-08-09 15:37 UTC, Metadorius commented
Please, the language we use is English. English is not my native language either, yet I don't communicate with my mates in Russian here. At the very least provide a machine translation using something like deepl.com like what I edited in so others can understand you too.

2024-08-09 15:41 UTC, TaranDahl commented
> Please, the language we use is English. English is not my native language either, yet I don't communicate with my mates in Russian here. At the very least provide a machine translation using something like deepl.com like what I edited in so others can understand you too.

Copy that.

2024-12-29 09:41 UTC, TaranDahl commented
CrimRecya在已经合并的pr里进行了大量飞机行为的增强（包括路径点），因此我们在这里只处理建筑的路径点。我认为这个pr目前应该没有任何需要改进的了？
CrimRecya has made a large number of enhancements to aircraft behavior (including waypoints) in the already merged pr. Therefore, we only handle the waypoints of buildings here. I think there should be nothing that needs improvement in this pr for now?

2024-12-29 10:50 UTC, chaserli approved these changes

2025-02-09 14:46 UTC, CrimRecya approved these changes

2025-02-09 14:48 UTC, merged