Weapon range finding in cylinder
Phobos-developers/Phobos pull request #1345
Opened 2024-08-09 04:13 UTC by TaranDahl

### Range finding in cylinder

- In vanilla, technos in air will ignore the distance in Z axis when checking if the target is in range. Now you can use the following flags to make technos always range finding like that.
- `[General]->AlwaysCylinderRangefinding` controls this globally, and can be customized per weapon type.
- Mind that set the flags to `false` meaning "use default" rather than "disable". Technos in air will always range finding in cylinder like vanilla, despite what you set.

In `rulesmd.ini`:
```ini
[General]                         ; WeaponType
AlwaysCylinderRangefinding=false  ; boolean

[SOMEWEAPON]                      ; WeaponType
AlwaysCylinderRangefinding=       ; boolean
```

2024-08-14 16:16 UTC, Coronia reviewed
Perhaps we don't need to add an Always to the tag name. CylinderRangefinding would be clear enough I think

2024-08-14 16:16 UTC, Coronia commented on src/Ext/Techno/Hooks.Misc.cpp
> +	return ret;
auto const pWeaponExt = WeaponTypeExt::ExtMap.Find(pWeaponType);
	bool bAlwaysCylinderRangefinding = RulesExt::Global()->AlwaysCylinderRangefinding;

	if (pWeaponExt)
		bAlwaysCylinderRangefinding = pWeaponExt->AlwaysCylinderRangefinding.Get(bAlwaysCylinderRangefinding);

	if (bAlwaysCylinderRangefinding)
		R->AL(true);
	else
		R->AL(pThis->IsInAir()); // vanilla check

	return ret;

2024-08-14 16:18 UTC, Coronia requested changes
forget to mark it as request changes

2024-08-15 17:31 UTC, Fryone reviewed
Looks fine logically. Also, can be named `UseCylinderRangefinding` for weapontypes

2024-08-15 17:47 UTC, TaranDahl commented
Todo: check if there is any Phobos function that has its own range-finding impl.
I was working on the DamageArea-related works last day and found that Phobos has its own cellspread function for some effects.
Need to check if this is happening on weapon range finding.

2024-08-16 06:07 UTC, TaranDahl commented
> Perhaps we don't need to add an Always to the tag name. CylinderRangefinding would be clear enough I think

Changed.

2024-08-16 06:08 UTC, TaranDahl commented
> Looks fine logically. Also, can be named `UseCylinderRangefinding` for weapontypes

Renamed to `CylinderRangefinding`

2024-08-22 13:47 UTC, CrimRecya approved these changes

2024-08-29 08:31 UTC, TaranDahl commented
Only handles the vanilla weapon rangefinding, at least for now.
Other rangefinding operations should be considered later, if necessary.

2025-02-09 14:34 UTC, TaranDahl commented
There is currently a bug suspected to be caused by this feature, which can cause misbehavior in judging the distance when the firing unit is located on the bridge.

2025-03-31 16:00 UTC, CrimRecya approved these changes

2026-02-02 10:10 UTC, TaranDahl commented
Going to merge this in 24h if no one has further issues.

2026-02-04 03:57 UTC, merged