Two skirmish AI behavior dehardcoded and a minor improvement
Phobos-developers/Phobos pull request #1350
Opened 2024-08-12 15:53 UTC by TaranDahl

### Skirmish AI behavior dehardcode

- In vanilla, there is a hardcoded behavior that when an skirmish AI player has no factory and has not taken damage for a while, it will sell its buildings and set its units to hunt. This can be customized now.
  - `[General]->AISellAllOnLastLegs` and `[General]->AIAllInOnLastLegs` control whether the AI will act selling and hunting respectively.
  - `[General]->AISellAllDelay` defines a timer, it will only work if `[General]->AISellAllOnLastLegs` is set to `true`. When the first time the AI reaches the trigger condition of vanilla behavior, the timer starts and prevents the selling behavior from happening until the timer is expired.
  - You can use these flags to make the AIs "all in" before they are defeated.
- Another hardcoded behavior is that, when the AI deploys a MCV, it will regroup all of its forces to that place. This can be toggle off now.
  - `[General]->RegroupWhenMCVDeploy` controls this behavior.

In `rulesmd.ini`:
```ini
[General]
AISellAllOnLastLegs=true   ; boolean
AISellAllDelay=0           ; integer, number of frames
AIAllInOnLastLegs=true     ; boolean
RegroupWhenMCVDeploy=true  ; boolean
```
### Global setting for `RepairBaseNodes`

- Self-evident.

2024-08-14 16:06 UTC, Coronia requested changes
The tags are not very understandable, suggest to change them to the names that being universally accepted by modders

AISellAllOnLastLegs -> AIFireSale
AISellAllDelay -> AIFireSaleDelay
AIAllInOnLastLegs -> AIAllToHunt
RegroupWhenMCVDeploy -> GatherWhenMCVDeploy

2024-08-16 05:46 UTC, TaranDahl commented
> The tags are not very understandable, suggest to change them to the names that being universally accepted by modders
> 
> AISellAllOnLastLegs -> AIFireSale AISellAllDelay -> AIFireSaleDelay AIAllInOnLastLegs -> AIAllToHunt RegroupWhenMCVDeploy -> GatherWhenMCVDeploy

Changed.

2024-08-22 13:43 UTC, CrimRecya requested changes

2024-08-22 13:43 UTC, CrimRecya commented on src/Ext/House/Hooks.cpp
> +	auto const pExt = HouseExt::ExtMap.Find(pThis);
this `pExt` seems like you can put it inside the next `if` after check `pRules->AIFireSale` is true.

2024-08-22 13:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Misc.cpp
> +	if (!pRules->GatherWhenMCVDeploy)
I think we need a blank line before this `if`.
In addition, you can just merge these into one line `return RulesExt::Global()->GatherWhenMCVDeploy ? 0 : SkipRegroup;`

2024-08-22 15:00 UTC, TaranDahl commented on src/Ext/House/Hooks.cpp
> +	auto const pExt = HouseExt::ExtMap.Find(pThis);
Both have been fixed.

2024-08-22 15:12 UTC, CrimRecya approved these changes

2024-09-25 15:23 UTC, MortonPL approved these changes

2024-09-25 15:23 UTC, MortonPL commented on src/Ext/Techno/Hooks.Misc.cpp
> +		return DoNotSkipRegroup;
```suggestion
	 return pRules->GatherWhenMCVDeploy ? DoNotSkipRegroup : SkipRegroup;
```

2024-09-26 10:43 UTC, MortonPL approved these changes

2024-09-26 10:43 UTC, MortonPL commented on docs/Whats-New.md
> +- Skirmish AI "gather when MCV deploy" behavior dehardcode (by 航味麻酱)
```suggestion
- Skirmish AI "sell all buildings and set all technos to hunt" behavior dehardcode (by TaranDahl/航味麻酱)
- Skirmish AI "gather when MCV deploy" behavior dehardcode (by TaranDahl/航味麻酱)
```

2024-09-26 10:44 UTC, merged

2024-09-27 15:25 UTC, chaserli reviewed
On the inconsistency of modifying the existing logic

2024-09-27 15:25 UTC, chaserli commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
I don't know how practical would it be to still have 3 here if you have to create a global one.  I think 1 should be sufficient and just let countries' default to that.

If not then the way you shouldn't have parsed them there with such "method"

2024-09-27 15:25 UTC, chaserli commented on docs/AI-Scripting-and-Mapping.md
> +MCVRedeploysInCampaign=false  ; boolean
do you really need to make a 3rd new tag doing the exact same thing? wouldn't `[Basic]` section is parsed in rules as well as the included files? One of these 2 should be removed.

2024-09-27 15:25 UTC, chaserli commented on docs/Whats-New.md
> +- Skirmish AI "sell all buildings and set all technos to hunt" behavior dehardcode (by TaranDahl/航味麻酱)
you and your avatar?

2024-09-27 15:28 UTC, Metadorius commented on docs/Whats-New.md
> +- Skirmish AI "sell all buildings and set all technos to hunt" behavior dehardcode (by TaranDahl/航味麻酱)
> you and your avatar?

elaborate

2024-09-27 15:29 UTC, Metadorius commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
what's wrong with having this togglable per difficulty?

2024-09-27 15:33 UTC, chaserli commented on docs/Whats-New.md
> +- Skirmish AI "sell all buildings and set all technos to hunt" behavior dehardcode (by TaranDahl/航味麻酱)
it looks like 2 people

2024-09-27 15:33 UTC, chaserli commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
> what's wrong with having this togglable per difficulty?

it explictly ruined my poka-yoke back then. If they were to differ, under different difficulties, allies and enemies houses should have different values

2024-09-27 15:45 UTC, Metadorius commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
> allies and enemies houses should have different values
you do realize "ally" and "enemy" for different players mean different things, leading to a desync? this can't be physically done unless you're in SP, which would be an exception that is kinda pointless to have. besides, params per difficulty is a normal thing to do

2024-09-27 15:52 UTC, chaserli commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
> you do realize "ally" and "enemy" for different players mean different things, leading to a desync? this can't be physically done unless you're in SP, which would be an exception that is kinda pointless to have. besides, params per difficulty is a normal thing to do

It's overriding my existing tags, written right below that. And yes, it's for *campaign mode only*.
It has nothing to do with difficulty.

2024-09-28 01:25 UTC, TaranDahl commented on docs/AI-Scripting-and-Mapping.md
> +MCVRedeploysInCampaign=false  ; boolean
The document states that the tag needs to be written in the map file. I haven't tested whether it can be written in rulesmd. If it works,  the new tag is unnecessary then.

2024-09-28 01:31 UTC, TaranDahl commented on docs/AI-Scripting-and-Mapping.md
> +RepairBaseNodes=false,false,false  ; list of 3 booleans indicating whether AI repair basenodes in Easy / Normal / Difficult game diffculty.
> I don't know how practical would it be to still have 3 here if you have to create a global one. I think 1 should be sufficient and just let countries' default to that.
> 
> If not then the way you shouldn't have parsed them there with such "method"

I just don't want to write it on every map and every house, so I added the same global tag to control it.
Reduce to 1 value is sufficient for me.