Fix Insignia.Weapon failed to parse in map & Insignia.Passengers
Phobos-developers/Phobos pull request #1365
Opened 2024-08-25 06:01 UTC by Coronia

previous Insignia(.Frame/.Frames).WeaponN settings can't be read or overridden from maps, which is fixed now

also added insignia based on current passenger size: Normal insignia can be overridden when its current passenger size reaches a certain amount by setting `Insignia(.Frame/.Frames).PassengersN` where `N` stands for the current passenger size amount. If not set, defaults to non-passenger specific insignia settings. Will be overridden by weapon mode insignia settings, if set.

In `rulesmd.ini`:
```ini
Insignia.PassengersN=                    ; filename - excluding the .shp extension
Insignia.PassengersN.Rookie=             ; filename - excluding the .shp extension
Insignia.PassengersN.Veteran=            ; filename - excluding the .shp extension
Insignia.PassengersN.Elite=              ; filename - excluding the .shp extension
InsigniaFrame.PassengersN=-1             ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrame.PassengersN.Rookie=-1      ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrame.PassengersN.Veteran=-1     ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrame.PassengersN.Elite=-1       ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrames.PassengersN=-1,-1,-1      ; int, frames of insignia shp (zero-based) or -1 for default
```

an example:
```ini
[ARMA]
Passengers=9
Insignia.Passengers0.Rookie=insnull1
Insignia.Passengers0.Veteran=insnull2
Insignia.Passengers0.Elite=insnull3
Insignia.Passengers1.Rookie=insfull1
Insignia.Passengers1.Veteran=insfull2
Insignia.Passengers1.Elite=insfull3
Insignia.Passengers2.Rookie=insfull2
Insignia.Passengers2.Veteran=insfull3
Insignia.Passengers2.Elite=insfull1
Insignia.Passengers3.Rookie=insfull3
Insignia.Passengers3.Veteran=insfull1
Insignia.Passengers3.Elite=insfull2
Insignia.Passengers4=insengi
Insignia.Passengers6=insnull2
Insignia.Passengers8=insnull3
Insignia.Passengers9=insengi
```

2024-09-16 12:54 UTC, Starkku requested changes
Mostly fine, a couple of questions about some things though.

2024-09-16 12:54 UTC, Starkku commented on src/Ext/TechnoType/Body.cpp
> +			this->Insignia_Passengers[i] = insignia;
Not sure what happens here currently if the value is not found but ideally it shouldn't be reset if you redefine only some of the keys. Same for weapon insignia as well.

2024-09-16 12:54 UTC, Starkku commented on docs/Fixed-or-Improved-Logics.md
> +  - Normal insignia can be overridden when its current passenger size reaches a certain amount by setting `Insignia(.Frame/.Frames).PassengersN` where `N` stands for the current passenger size amount
>  where `N` stands for the current passenger size amount

Is this actually the case given that the parsing code starts from 0 and loops until passenger count?

2024-09-16 12:54 UTC, Starkku commented on CREDITS.md
> +  - Custom insignias
Could maybe mention it is the passenger-based insignia here but it is kinda inconsistent currently across any multi-author features so not a big deal.

2024-09-17 11:24 UTC, Coronia commented on docs/Fixed-or-Improved-Logics.md
> +  - Normal insignia can be overridden when its current passenger size reaches a certain amount by setting `Insignia(.Frame/.Frames).PassengersN` where `N` stands for the current passenger size amount
It is, it could work with passenger amount from 0 (empty) to its upper limit. Clarified this a bit in the doc

2024-09-17 11:26 UTC, Coronia commented on src/Ext/TechnoType/Body.cpp
> +			this->Insignia_Passengers[i] = insignia;
changed InsigniaFrames into Nullable<Vector3D<int>> and use isset() for condition instead of equal to (-1, -1, -1). Works fine for now but not sure if it'll accidentally break something

2025-02-25 08:45 UTC, Coronia commented
![image](https://github.com/user-attachments/assets/f877ece0-2c28-4d37-ab29-309d7f5de87f)
Since there're tons of tags for Insignia already, I'm thinking of removing the old tags for Passengers while only keeping its InsigniaType, would like some feedbacks from others to see if that's proper tho

Also @Metadorius could you list what should be modified for Insignia Type at here again, now that the old pull request has been closed?

2025-04-22 14:29 UTC, CrimRecya approved these changes
Overall, LGTM. Only some minor things.

2025-04-22 14:29 UTC, CrimRecya commented on src/Ext/Techno/Body.Visuals.cpp
> +		if (frames!= Vector3D<int>(-1, -1, -1))
`if (frames != Vector3D<int>(-1, -1, -1))`

2025-04-28 13:03 UTC, merged