Optimize aircrafts actions
Phobos-developers/Phobos pull request #1366
Opened 2024-08-25 07:19 UTC by CrimRecya

- Now, when a `stop` command (S) is issued to an aircraft, the aircraft will immediately return to the airport. When a `guard` command (G) is issued, the aircraft will search for targets around the current location and return immediately when target is not found, target is destroyed or ammos are depleted (Note that if the target is destroyed but ammos are not depleted yet, it will also return because the aircraft's command is one-time). When a `attack move` command (Ctrl+Shift) is issued, the aircraft will move towards the destination and search for nearby targets on the route for attack. Once ammos are depleted or the destination is reached, it will return (Note that if the  automatically selected target is destroyed but ammos are not depleted yet during the process, the aircraft will continue to go to the destination). When a `target guard` command (Ctrl+Alt) is issued, it's like a combination of the attack move command and the guard command - on its way to its destination, when the first automatically selected target is destroyed (Though its ammos may not depleted yet) or ammos are depleted, it will return.

2024-08-25 07:39 UTC, Coronia commented
suggest to make these guard behaviors compatible with `GuardRange` instead of always tying to weapon ranges, just like infantry and units did

2024-08-25 08:29 UTC, CrimRecya commented
> suggest to make these guard behaviors compatible with `GuardRange` instead of always tying to weapon ranges, just like infantry and units did

Only the attack move action will use the weapon's range to reduce the range that search the valid target.

2024-09-16 12:28 UTC, Metadorius requested changes

2024-09-16 12:28 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +}
Can you please explain what is the purpose of those hooks? Preferably in comments.

2024-09-16 12:28 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +		pThis->unknown_bool_5D1 = false;
Could you please name and adjust the virtual table entries and fields in YRpp here and in other places?

2024-09-16 12:28 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(TechnoClass*, TargetFlags, CoordStruct*, bool)>(0x6F8DF0)(pThis, targetFlags, pSelectCoords, onlyTargetHouseEnemy);
For all the function addresses that you call we added YRpp definitions, and also adjusted TargetFlags (which are correctly named TargetType). Please use those in YRpp.

2024-09-16 12:28 UTC, ZivDero submitted a review, later dismissed

2024-09-16 12:31 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +		return flying ? 1 : reinterpret_cast<int(__thiscall*)(FootClass*)>(0x4D6AA0)(pThis);
Or better, you can just call the YRpp function with that address that I added for you.

2024-09-16 14:23 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(TechnoClass*, TargetFlags, CoordStruct*, bool)>(0x6F8DF0)(pThis, targetFlags, pSelectCoords, onlyTargetHouseEnemy);
Get this, will change these soon. And I'm sure that is `TargetFlags`, not `TargetType`.

2024-09-16 14:30 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +		//	if (!flying && pThis->Target) // This is what vanilla do, but now there is no need to do so
Seems like this approach is not popular, I will change it soon.

2024-09-16 15:02 UTC, CrimRecya commented
TechnoClass
unknown_bool_418 -> bool IsTether
unknown_bool_419 -> bool IsAlternativeTether

FootClass
unknown_5A0 -> AbstractClass* Follow
unknown_int_5C4 -> Mission MegaMission
unknown_5C8 -> AbstractClass* MegaDestination
unknown_5CC -> AbstractClass* MegaTarget
unknown_bool_5D1 -> bool HaveAttackMoveTarget

TechnoClass_vtbl
bool TargetAndEstimateDamage(DWORD dwUnk, DWORD dwUnk2) -> bool TargetAndEstimateDamage(CoordStruct* pSelectCrd, TargetFlags targetFlags)
CellClass* SelectAutoTarget(TargetFlags TargetFlags, int CurrentThreat, bool OnlyTargetHouseEnemy) -> AbstractClass* SelectAutoTarget(TargetFlags targetFlags, CoordStruct* pSelectCrd, bool onlyTargetHouseEnemy)

vt_entry_3B4 -> bool InAuxiliarySearchRange(AbstractClass* pTarget)
vt_entry_3E8 -> int GetSecondaryWeaponIndex()
vt_entry_47C -> void SetFollowTarget(AbstractClass* pFollow)
vt_entry_4A4 -> Mission RespondMegaEventMission(EventClass* pRespondTo)
vt_entry_4A8 -> void ClearMegaMissionData()
vt_entry_4AC -> bool HaveMegaMission()
vt_entry_4B0 -> bool HaveAttackMoveTarget()
vt_entry_4B4 -> Mission GetMegaMission()
vt_entry_4B8 -> CoordStruct* GetAttackMoveCoords(CoordStruct* pBuffer)
vt_entry_4C4 -> bool MegaMissionIsAttackMove()
vt_entry_4C8 -> bool ContinueMegaMission()
vt_entry_4CC -> void UpdateAttackMove()
vt_entry_4D0 -> bool RefreshMegaMission()

2024-09-16 15:54 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(TechnoClass*, TargetFlags, CoordStruct*, bool)>(0x6F8DF0)(pThis, targetFlags, pSelectCoords, onlyTargetHouseEnemy);
No, I mean that the names were renamed to be closer to how Westwood named them, not that the type is different.

2024-09-16 17:04 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(TechnoClass*, TargetFlags, CoordStruct*, bool)>(0x6F8DF0)(pThis, targetFlags, pSelectCoords, onlyTargetHouseEnemy);
So I need to change the name of the variable `targetFlags` ?

2024-11-09 09:54 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +DEFINE_HOOK(0x414D4D, AircraftClass_Update_ClearTargetIfNoAmmo, 0x6)
Could you please provide details of the circumstances under which this problem was encountered?

2024-12-10 06:56 UTC, CrimRecya commented
> Didn't try paradrop aircraft, but regular combat aircraft appear to be working fine. CanPassiveAquire= and CanRetaliate= tags also work.
> 
> However, using guard mode reveals another issue (probably the reason why guard mode was disabled): when set to guard, AircraftTypes will search _the entire map_ for other AircraftTypes to attack, no matter the distance. Reducing GuardRange changes nothing here.

Thank you for the feedback. I will fix it later.

2024-12-10 15:45 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +DEFINE_HOOK(0x414D4D, AircraftClass_Update_ClearTargetIfNoAmmo, 0x6)
Are you referring to "Type=ParaDrop" or "Type=AmerParaDrop" SW? I have not received any feedback on this. So I tested both of these again and there was no such issue. The plane flew away after dropping the troops normally.

2024-12-10 16:33 UTC, mevitar commented
AircraftTypes no longer hunt for enemy AircraftTypes on the other side of the map when in guard mode. All target types now need to be within GuardRange radius.

However, unlike the previous build, AirportBound=no buildable AircraftTypes will now try to return to their Dock= every time they aren't on an attack mission.
In that build they did it only when they destroyed their target or were set to guard but there was no target within range (and no enemy AircraftType on map), now they also do that each time they finish movement.

AirportBound=yes AircraftTypes appear to be still working without issues. Didn't notice any problem for spawnable (aircraft carrier style) aircraft either.

2024-12-10 21:11 UTC, mevitar commented
All seems to be fine now.
And I can't get paradrop planes in MO to bug out the way Otamaa says, they all work fine with the newest build.

2024-12-12 01:07 UTC, mevitar commented
I'm not sure if i missed this behavior in previous build, but now my AirportBount=no aircraft's behavior on Stop and Guard command is inconsistent. Sometimes it tries to return to its Dock= building, and sometimes it stays in place instead (tries to land if it can). And it's not because of enemies nearby, both can happen over empty fields.
The only consistent thing is that repeatedly pressing Stop will eventually make it stay instead of returning.

Fortunately, it doesn't try to return to Dock= after every move order like it did several builds ago.

Regular AirportBound=yes aircraft appear to be still working fine.

2024-12-12 06:04 UTC, CrimRecya commented
> I'm not sure if i missed this behavior in previous build, but now my AirportBound=no aircraft's behavior on Stop and Guard command is inconsistent. Sometimes it tries to return to its Dock= building, and sometimes it stays in place instead (tries to land if it can). And it's not because of enemies nearby, it happens over empty fields. The only consistent thing is that repeatedly pressing Stop will eventually make it stay instead of returning.
> 
> Fortunately, it doesn't try to return to Dock= after every move order like it did several builds ago.
> 
> Regular AirportBound=yes aircraft appear to be still working fine.

Get it. theoretically speaking, this removing do nothing with these, it only hands over a bug to another PR for handling, which is about using stop commands on planes at the airport can make them stackable and unable to reload ammo. I will double check the `AirportBound=no` aircrafts behavior.

2024-12-12 06:08 UTC, CrimRecya commented
> > I'm not sure if i missed this behavior in previous build, but now my AirportBound=no aircraft's behavior on Stop and Guard command is inconsistent. Sometimes it tries to return to its Dock= building, and sometimes it stays in place instead (tries to land if it can). And it's not because of enemies nearby, it happens over empty fields. The only consistent thing is that repeatedly pressing Stop will eventually make it stay instead of returning.
> > Fortunately, it doesn't try to return to Dock= after every move order like it did several builds ago.
> > Regular AirportBound=yes aircraft appear to be still working fine.
> 
> Get it. theoretically speaking, this removing do nothing with these, it only hands over a bug to another PR for handling, which is about using stop commands on planes at the airport can make them stackable and unable to reload ammo. I will double check the `AirportBound=no` aircrafts behavior.

Additionally, after this removal, if set `ExpandAircraftMission` to false, it will restore all vanilla behavior.

2024-12-12 07:45 UTC, CrimRecya commented
> I'm not sure if i missed this behavior in previous build, but now my AirportBound=no aircraft's behavior on Stop and Guard command is inconsistent. Sometimes it tries to return to its Dock= building, and sometimes it stays in place instead (tries to land if it can). And it's not because of enemies nearby, it happens over empty fields. The only consistent thing is that repeatedly pressing Stop will eventually make it stay instead of returning.
> 
> Fortunately, it doesn't try to return to Dock= after every move order like it did several builds ago.
> 
> Regular AirportBound=yes aircraft appear to be still working fine.

I also found this issue using the dev's nightly build. The specific manifestation is that aircraft manufactured from the airport with 'AirportBound=no' generated from the first position will set its 'tether' (TechnoClass::bool_418) to false (may be caused by the `RadioCommand::NotifyUnlink`) when it leave the airport and will return to the airport every time they receive a stop command. However, aircraft generated from other locations do not have this issue, but they simply ignore the stop command and continue to move towards their destination. I think it should be a vanilla existing issue.

2024-12-12 15:43 UTC, mevitar commented
> I also found this issue using the dev's nightly build. The specific manifestation is that aircraft manufactured from the airport with `AirportBound=no` generated from the first position will set its `Tether` (TechnoClass::bool_418) to false (may be caused by the `RadioCommand::RequestUntether`) when it leave the airport and will return to the airport every time they receive a stop command. However, aircraft generated from other locations do not have this issue, but they simply ignore the stop command and continue to move towards their destination. I think it should be a vanilla existing issue.

If it matters, I've been testing it with an aircraft delivered by an SW, not actually buildable from an airpad. Dock= is only so that after finishing it returns to the base after destroying its target instead of flying to the edge of the map.

2024-12-12 16:38 UTC, CrimRecya commented
> > I also found this issue using the dev's nightly build. The specific manifestation is that aircraft manufactured from the airport with `AirportBound=no` generated from the first position will set its `Tether` (TechnoClass::bool_418) to false (may be caused by the `RadioCommand::RequestUntether`) when it leave the airport and will return to the airport every time they receive a stop command. However, aircraft generated from other locations do not have this issue, but they simply ignore the stop command and continue to move towards their destination. I think it should be a vanilla existing issue.
> 
> If it matters, I've been testing it with an aircraft delivered by an SW, not actually buildable from an airpad. Dock= is only so that after finishing it returns to the base after destroying its target instead of flying to the edge of the map.

I think everything we mentioned before should be fine now. :)
Additionally, there is still an unresolved issue, but is not directly related to the content of this PR. It's about: aircrafts cannot move directly above the water, which may mainly affect the planning paths (Because in vanilla, moving to places above water can be solved by double clicking).

2024-12-12 17:00 UTC, mevitar commented
Tried the newest build, the inconsistency issues appear to be fixed.
If nobody else notices issues here then i think can be marked as finished.

2024-12-26 02:21 UTC, Metadorius requested changes
From a brief glance I like the code and it seems you know what you are doing (apologies for not checking this in more detail). I left some minor comments on style though.

Can you submit the YRpp corrections I asked about as a PR for YRpp though? You can do them all together from what you discovered and used in the PRs so we don't need to burden you with extra PRs. Let's get it merged after this. cc @chaserli so you know we'll be merging this. I also think it is OK with having this and #1449 be merged in one PR since they seem to be complementary.

2024-12-26 02:21 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +- Now, when a `stop` command (S) is issued to an aircraft, the aircraft will immediately return to the airport. When a `guard` command (G) is issued, the aircraft will search for targets around the c
```suggestion
- Now, when a `stop` command (`[S]` by default) is issued to an aircraft, the aircraft will immediately return to the airport. When a `guard` command (`[G]` by default) is issued, the aircraft will search for targets around the current location and return immediately when target is not found, target is destroyed or ammos are depleted (Note that if the target is destroyed but ammos are not depleted yet, it will also return because the aircraft's command is one-time). When a `attack move` command (Ctrl+Shift) is issued, the aircraft will move towards the destination and search for nearby targets on the route for attack. Once ammo is depleted or the destination is reached, it will return (Note that if the automatically selected target is destroyed but ammo is not depleted yet during the process, the aircraft will continue to go to the destination).
```

2024-12-26 02:21 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		Valueable<bool> ExpandAircraftMission;
I propose to name this `ExtendedAircraftMissions`.

2024-12-26 02:21 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +- Fixed `MovementZone=Subterannean` harvesters being unable to find docks if in area enclosed by water, cliffs etc.
Is this one related to the pull request?

2024-12-26 02:21 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	return (RulesExt::Global()->ExpandAircraftMission && pThis->WhatAmI() == AbstractType::Aircraft && (!pThis->Ammo || pThis->GetHeight() < Unsorted::CellHeight)) ? SkipGameCode : 0;
Long conditions like this are better to be split into multiple bool variables or at least lines. I also think it's better to leave the `? ... : ...;` part on the next line so it is more readable, since we read the code from the left to right.

2024-12-26 02:21 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	if (distance > std::max((pType->SlowdownDistance >> 1), (2048 / pType->ROT)))
Could you please leave a comment explaining what is happening here?

2024-12-26 05:26 UTC, CrimRecya commented
I modified the above content and merged the branch #1449.
But I don't know how to pull request for YRpp. Should I create a branch in YRpp or just the same from Phobos?

2024-12-26 05:30 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	if (distance > std::max((pType->SlowdownDistance >> 1), (2048 / pType->ROT)))
All changes completed. :)

2024-12-26 10:59 UTC, Metadorius commented
> I modified the above content and merged the branch #1449.
> But I don't know how to pull request for YRpp. Should I create a branch in YRpp or just the same from Phobos?

To do that you have to create a branch in YRpp, then you can push it and submit a pull request to YRpp repository.

When you cloned Phobos recursively - you also cloned YRpp as a submodule. Basically submodules are just nested repositories. You can open it like any other repository, so the changes can be synchronized to Phobos and you don't need to rename stuff by hand.

What I suggest to do is: in Visual Studio (regular or Code) rename fields and functions using `Rename...` feature (`[F2]` by default), then you will have two "levels" of changes displayed in your Git client:
- for Phobos repository - changes in the Phobos code (as regular changes) and changes to YRpp (as one submodule change)
- for YRpp repository - changes to the field names and function names in YRpp as regular changes.

At this point you have to create a branch in YRpp repository (create a fork of it if you didn't yet), commit and push the changes and submit it as a pull request. After pushing it you have two options in Phobos repository:
- wait until it's accepted, checkout YRpp at the newest commit, then commit and push - this will save you having to commit and push multiple times, but you won't be able to get a nightly build for people to test;
- don't wait for YRpp changes to be merged, commit and push right after you pushed the YRpp changes to your YRpp branch - you will have an up-to-date build on Phobos pull request this way. Note that you must do it only after you committed to and pushed your YRpp branch, otherwise the build system won't know what are the changes as they are not exposed to the world, only available to you locally.

After the YRpp pull request gets accepted you will need to switch to the latest commit that was merged (you do that in the submodule), verify that it compiles like normal, and then commit and push it to your Phoboa branch that you made for the pull request.

2024-12-27 22:19 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +DEFINE_HOOK(0x414D4D, AircraftClass_Update_ClearTargetIfNoAmmo, 0x6)
@Otamaa if you ever find the conditions that caused to reproduce it - feel free to bring it up as a bug report, for now I will be resolving this.

2024-12-27 22:36 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(FootClass*, ThreatType, CoordStruct*, bool)>(0x4D9920)(pThis, threatType, pSelectCoords, onlyTargetHouseEnemy);
This one seems to be not updated with YRpp one.

2024-12-27 22:41 UTC, Metadorius approved these changes
It all looks good to me except one thing. I also took the liberty of helping you out with documentation. Please review the changes and the question and let's get this merged.

2024-12-27 22:55 UTC, Metadorius commented
It seems I am not able to push to this branch. Could you please enable "Allow edits by maintainers" on your pull requests so we can submit improvements without creating additional pull requests?

2024-12-28 02:14 UTC, CrimRecya commented
> It seems I am not able to push to this branch. Could you please enable "Allow edits by maintainers" on your pull requests so we can submit improvements without creating additional pull requests? I will push my doc/spelling improvements then.

It seems that `Allow edits and access to secrets by maintainers` is always on. I turned it off and then on again. You can try again.

2024-12-28 02:15 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	return reinterpret_cast<AbstractClass*(__thiscall*)(FootClass*, ThreatType, CoordStruct*, bool)>(0x4D9920)(pThis, threatType, pSelectCoords, onlyTargetHouseEnemy);
Get it, I will add it.

2024-12-28 15:02 UTC, Metadorius commented
I think there's some configuration that prevents me from directly pushing. I have submitted a PR: https://github.com/CrimRecya/Phobos/pull/2

2024-12-28 15:08 UTC, CrimRecya commented
> I think there's some configuration that prevents me from directly pushing. I have submitted a PR: [CrimRecya#2](https://github.com/CrimRecya/Phobos/pull/2)

Thank you for your correction. I have merged it.

2024-12-28 20:03 UTC, Metadorius approved these changes

2024-12-28 20:04 UTC, merged

2024-12-29 12:50 UTC, chaserli commented
Excuse me for being unable to test when it was a PR, but it seems an aircraft still has some trouble proceeding to the next planning waypoint. For example it will try to contact the airport first. Is this intended?

2024-12-29 12:59 UTC, CrimRecya commented
> Excuse me for being unable to test when it was a PR, but it seems an aircraft still has some trouble proceeding to the next planning waypoint. For example it will try to contact the airport first. Is this intended?

No, judging from the mission of the aircraft, there will be 1-2 frames trying to contact the airport before entering the next planning waypoint, but this should not prevent it from continuing to the next waypoint. Is this a problem caused by the aircraft ammunition upper limit is greater than 2 and the ammunition is not 0 but less than half of the upper limit?

2024-12-29 13:09 UTC, chaserli commented
I don't have much clue either. I once tried avoiding it via flyloco methods such as 4CFA70, but it no longer works with your code here.

2024-12-29 13:25 UTC, chaserli commented on src/Ext/Aircraft/Hooks.cpp
> +	pThis->EnterIdleMode(false, true);
For example a nasty way to "avoid" is to add remaining waypoints check before enteridlemode. But apparently it's not correct

2024-12-29 13:30 UTC, CrimRecya commented
> I don't have much clue either. I once tried avoiding it via flyloco methods such as 4CFA70, but it no longer works with your code here.

At present, the return purpose of one or two frames is not a big problem, at least they will continue to the next waypoint. One more thing, ww hard coded that the aircraft cannot move directly to the water surface, which is also a problem. But anyway, I will try to solve these two problems and submit a new fix later.

2024-12-29 13:34 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	pThis->EnterIdleMode(false, true);
Normally `bool __thiscall EnterIdleMode(FootClass *this, bool construction, bool nextPlanningPath)` should have handled the next waypoint, but I don't understand why it didn't take effect. I'll check it carefully.

2024-12-30 07:56 UTC, CrimRecya commented
> > I don't have much clue either. I once tried avoiding it via flyloco methods such as 4CFA70, but it no longer works with your code here.
> 
> At present, the return purpose of one or two frames is not a big problem, at least they will continue to the next waypoint. One more thing, ww hard coded that the aircraft cannot move directly to the water surface, which is also a problem. But anyway, I will try to solve these two problems and submit a new fix later.

I fixed these two problems in #1484. Please check them in your own time.