Rewrite frame CRC generation
Phobos-developers/Phobos pull request #1369
Opened 2024-08-30 08:19 UTC by Starkku

Reimplements game's frame CRC generation function, only change logic-wise is that it excluded `AnimClass` and `ParticleClass` objects that are purely visual.

2024-08-30 08:34 UTC, FS-21 commented
What kind of tests should be done here if you want feedback?

2024-08-30 16:33 UTC, chaserli requested changes
If you're rewriting these completely, it would be better to hash these in a more modern way for better readability and extensibility

2024-08-30 16:33 UTC, chaserli commented on src/Misc/SyncLogging.cpp
> +		auto const pAnim = abstract_cast<AnimClass*>(pObj);
```suggestion
		auto const pAnim = static_cast<AnimClass*>(pObj);
```

2024-08-30 16:33 UTC, chaserli commented on src/Misc/SyncLogging.cpp
> +		auto const pParticle = abstract_cast<ParticleClass*>(pObj);
```suggestion
		auto const pParticle = static_cast<ParticleClass*>(pObj);
```

2024-08-30 16:33 UTC, chaserli commented on src/Misc/SyncLogging.cpp
> +	auto& GameCRC = EventClass::CurrentFrameCRC.get();
```suggestion
	auto& GameCRC = EventClass::CurrentFrameCRC();
```

2024-09-15 13:51 UTC, ZivDero requested changes

2024-09-15 13:51 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +static bool __forceinline ObjectNonCRCHashable(ObjectClass const* pObj)
```cpp
class ObjectClassFake : public ObjectClass
{
	inline bool _IsCRCHashable();
}

bool ObjectClassFake::_IsCRCHashable
{
...
}
```

2024-09-15 13:51 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +DEFINE_HOOK(0x64DAB0, ComputeFrameCRC, 0x6)
Please reimplement the whole function as a normal (non-hook) function and patch it with a simple jump for cleanliness.

2024-09-15 13:51 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +#ifdef FRAMECRC_HASH_INI
No.

2024-09-15 14:03 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +static bool __forceinline ObjectNonCRCHashable(ObjectClass const* pObj)
Instead of creating global functions where one would normally create a class method, you could create a "fake" class descending from ObjectClass, allowing you to effectively add new (non-virtual, of course) class methods, with access to `this`.

2024-09-15 14:06 UTC, Metadorius commented on src/Misc/SyncLogging.cpp
> +#ifdef FRAMECRC_HASH_INI
No.

2024-09-15 14:58 UTC, Starkku commented
The wrapper may be good idea in theory but the current implementation mostly just obfuscates what gets hashed and for what type of object. The benefits would be more obvious if there was a realistic chance for new properties that need hashing to be added for, say, TechnoClass and derivatives in the future but as it stands this is *very* unlikely. If you can think of a way to do it without extra overhead or the obfuscating nature while reducing repeated code be my guest, but the previous implementation was not it so I've elected to revert it. I do hold a local copy of it for now still just in case though.

I'm not even going to repeat the point about the rules hash check in Phobos anymore, should be obvious by now that it does not belong here.

I did do some minor cleanup to the first iteration.

2024-09-15 16:29 UTC, secsome commented on docs/Whats-New.md
> +- Purely visual animations and particles excluded from sync checks (by Starkku)
I feel like this PR is more like a `Vanilla Fix` instead of a `New Feature`

2024-09-19 13:28 UTC, chaserli commented
> If you can think of a way to do it without extra overhead or the obfuscating nature while reducing repeated code be my guest
It only wrapped a DWORD and serves for hash the object on creation and do the hash combine operation. I bet it makes less overhead than your current method. It also allows you to know the "sum" at compile time. But anyway these are small things
 and make literally no difference

2025-03-28 09:02 UTC, Starkku commented
Rebased on develop and applied some of the feedback. This is ready for further testing and another review pass.

2025-04-08 06:06 UTC, Coronia commented
no desync or other issue occured in our testing so far

2026-04-29 16:08 UTC, ZivDero approved these changes
A couple nitpicks but looks good, see no issues.

2026-04-29 16:08 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +		auto const pAnim = static_cast<AnimClass*>((ObjectClass*)this);
Uh.... use `reinterpret_cast`? Or two `static_cast`, not a C cast.

2026-04-29 16:08 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +
Any real need for `__forceinline`? Just mark it `inline`, should be more than enough. High chance it will get inlined even without either.

2026-04-29 17:23 UTC, Metadorius commented on src/Misc/SyncLogging.cpp
> +
doesn't `inline` have different semantcis nowadays?

2026-04-29 19:47 UTC, ZivDero commented on src/Misc/SyncLogging.cpp
> +
Like what? Not that I'm aware.

2026-04-29 20:04 UTC, Metadorius commented on src/Misc/SyncLogging.cpp
> +
> The original intent of the inline keyword was to serve as an indicator to the optimizer that inline substitution of a function is preferred over function call, that is, instead of executing the function call CPU instruction to transfer control to the function body, a copy of the function body is executed without generating the call. This avoids overhead created by the function call (passing the arguments and retrieving the result) but it may result in a larger executable as the code for the function has to be repeated multiple times.

> Since inline substitution is unobservable in the standard semantics, compilers are free to use inline substitution for any function that's not marked inline, and are free to generate function calls to any function marked inline. Those optimization choices do not change the rules regarding multiple definitions and shared statics listed above.

> Because the meaning of the keyword inline for functions came to mean "multiple definitions are permitted" rather than "inlining is preferred" since C++98, that meaning was extended to variables.

2026-04-29 20:18 UTC, Starkku commented on src/Misc/SyncLogging.cpp
> +
Realistically could probably remove both keywords and let the compiler do its thing. As if I know better than it.

2026-05-03 17:03 UTC, merged