Drop Crate on Death
Phobos-developers/Phobos pull request #1371
Opened 2024-08-31 10:07 UTC by FS-21

- Ìf `DropCrate` is declared then the specified crate will be spawned when the object is destroyed.

In `rulesmd.ini`:
```ini
[SOMETECHNO]  ; TechnoType
DropCrate=    ; Powerup crate type enum (money|unit|healbase|cloak|explosion|napalm|squad|reveal|armor|speed|firepower|icbm|invulnerability|veteran|ionstorm|gas|tiberium|pod)
```

Also, a new map action (see the documentation) allows the overwrite of this behaviour (disbale, enable or set a new crate) if the trigger is attached to technos.

Tested in online games so this doesn't desync.

2024-09-24 20:06 UTC, MortonPL reviewed
Won't collecting this new crate spawn a new one according to random crate logic?

2025-04-22 07:56 UTC, Coronia requested changes

2025-04-22 07:56 UTC, Coronia commented on src/Ext/Techno/Hooks.cpp
> +
the entire section should be put under a proper techno death handling hook in `Hooks.ReceiveDamage`, otherwise it might have the chance to miss or duplicate the crate

2025-05-19 06:33 UTC, FS-21 commented on src/Ext/Techno/Hooks.cpp
> +
First of all, why all the code calling this feature was moved from the hook "DEFINE_HOOK(0x701DFF, TechnoClass_ReceiveDamage_FlyingStrings, 0x7)" (initial commit I created) to "DEFINE_HOOK(0x4DB218, FootClass_GetMovementSpeed_SpeedMultiplier, 0x6)" (current commit)...

Now I understand the code started to drop random instead of a specific one stuff some time ago.
Originally it was as you mentioned Coronia. I'll push a fix moving the code to the original hook.

2025-05-19 07:03 UTC, FS-21 commented on src/Ext/Techno/Hooks.cpp
> +
Now should be fixed

2025-05-19 07:41 UTC, TaranDahl requested changes
Two concerns.

2025-05-29 08:24 UTC, FS-21 commented on src/Ext/Techno/Body.h
> +		int DropCrate; // Drop crate on death, modified by map action
Ehh, this PR has map actions that modify the behaviour of drop crates enabling/disabling and modifying the current value

2025-06-13 12:40 UTC, Starkku commented
Is there any existing vanilla function that is suitable for finding available cells for crate spawning instead of implementing your own code?

2026-07-30 02:10 UTC, TaranDahl approved these changes

2026-08-01 05:35 UTC, Coronia approved these changes

2026-08-01 05:46 UTC, merged