AE Bonus & Bound for received damage and speed
Phobos-developers/Phobos pull request #1372
Opened 2024-09-01 04:55 UTC by Coronia

- `FirepowerBonus`, `ArmorBonus`, `SpeedBonus` and `ROFBonus` can also be used to modify the object's stats, but in the way of increasing/decreasing a fixed value to them. Will be calculated after all sort of multipliers.
    - `FirepowerBonus` and `SpeedBonus` add a value to the object's firepower and speed, respectively.
    - `ArmorBonus` can be set on both techno and attached effect. It decreases the damage taken by a fixed value. This is applied before armor type.
    - `ROFBonus` decreases weapon reload rate by a fixed value. Can't be reduced to value below 1.
- `ReceivedDamage.Minimum` and `ReceivedDamage.Maximum` control the minimum and maximum amount of damage that can be dealt to object in a single hit. This is applied after armor type.
    - If the object has `ReceivedDamage.Minimum` by itself or is affected by multiple attached effects with `ReceivedDamage.Minimum`, the maximum amount of these would be used.
    - If the object has `ReceivedDamage.Maximum` by itself or is affected by multiple attached effects with `ReceivedDamage.Maximum`, the minimum amount of these would be used.
- `Speed.Minimum` and `Speed.Maximum` control the minimum and maximum speed that the object could have.
    - If the object has `Speed.Minimum` by itself or is affected by multiple attached effects with `Speed.Minimum`, the maximum amount of these would be used.
    - If the object has `Speed.Maximum` by itself or is affected by multiple attached effects with `Speed.Maximum`, the minimum amount of these would be used.

In `rulesmd.ini`:
```ini
[SOMEATTACHEFFECT]                             ; AttachEffectType
FirepowerBonus=0                               ; integer
ArmorBonus=0                                   ; integer
SpeedBonus=0.0                                 ; floating point value
ROFBonus=0                                     ; integer
ReceivedDamage.Minimum=-2147483648             ; integer
ReceivedDamage.Maximum=2147483647              ; integer
Speed.Minimum=0.0                              ; floating point value
Speed.Maximum=2147483647.0                     ; floating point value

[SOMETECHNO]                                   ; TechnoType
ArmorBonus=0                                   ; integer
ReceivedDamage.Minimum=-2147483648             ; integer
ReceivedDamage.Maximum=2147483647              ; integer
Speed.Minimum=0.0                              ; floating point value
Speed.Maximum=2147483647.0                     ; floating point value
```

2025-03-02 08:34 UTC, CrimRecya requested changes

2025-03-02 08:34 UTC, CrimRecya commented on src/New/Entity/AttachEffectClass.h
> +		, Speed_Maximum { INT32_MAX }
Missing `AttachEffectClass.cpp`.

2025-03-02 08:34 UTC, CrimRecya commented on src/Ext/Techno/Hooks.AttachEffect.cpp
> +			Math::min(pTypeExt->Speed_Maximum, pExt->AE.Speed_Maximum)));
I think `TechnoExt::GetCurrentSpeedMultiplier()` also need this.

2025-03-02 08:34 UTC, CrimRecya commented on src/Ext/Techno/Hooks.AttachEffect.cpp
> +	damage = static_cast<int>(damage * pExt->AE.FirepowerMultiplier) + pExt->AE.FirepowerBonus;
This is also different from dev now.
`DEFINE_HOOK(0x469EC0, BulletClass_Logics_AirburstWeapon, 0x6)`
and
`void StraightTrajectory::OnUnlimbo(BulletClass* pBullet, CoordStruct* pCoord, BulletVelocity* pVelocity)`
also need this now.
Perhaps we can consider encapsulating it as a function for easy use.

2025-03-02 08:34 UTC, CrimRecya commented on src/Misc/Hooks.BugFixes.cpp
> +			Math::min(pTypeExt->Speed_Maximum, pExt->AE.Speed_Maximum)));
You can consider encapsulating it as a function, so that these will not seem to be so long.

2025-03-12 11:36 UTC, Coronia commented
The cost (more perf tax for AE) doesn't really march what it can provide. 'Bonus' has rather limited usage and can be replaced by proper 'Multiplier' setting in many times. It would also be chaotic when AEs with different 'bound' apply together, the maximum/minimum rule is unintuitive and doesn't fit some certain demand

Though, if someone has the need to make ReceiveDamage/Speed bounds for Techno, I could make a smaller PR for that

2025-03-12 11:36 UTC, closed without merging