New Parabola trajectory
Phobos-developers/Phobos pull request #1374
Opened 2024-09-04 09:55 UTC by CrimRecya

- As the name says, this is a completely reset `Arcing` with different enhanced functions. Without doubt, It supported linkage with `Trajectory=Disperse`.
  - `Trajectory.Parabola.DetonationDistance` controls the maximum distance in cells from intended target (checked at start of each game frame, before the projectile moves) at which the projectile will be forced to detonate. Set to 0 to disable forced detonation.
  - `Trajectory.Parabola.TargetSnapDistance` controls the maximum distance in cells from intended target the projectile can be at moment of detonation to make the projectile 'snap' on the intended target. Set to 0 to disable snapping.
  - `Trajectory.Parabola.OpenFireMode` controls how should the projectile be launched. This has the following 6 modes.
    - 0 - Automatic calculation mode with fixed horizontal velocity, using `Trajectory.Speed` and target coordinates as calculation conditions, i.e. the flight time of the projectile is permanently fixed.
    - 1 - Automatic calculation mode with fixed maximum height, useing `Trajectory.Parabola.ThrowHeight` and target coordinates as calculation conditions, i.e. the detonation time of the projectile is relatively fixed.
    - 2 - Automatic calculation mode with fixed fire angle, useing `Trajectory.Parabola.LaunchAngle` and target coordinates as calculation conditions. In this mode, the performance consumption is high, and may have no solution. It is not recommended to enable `SubjectToCliffs` or enable `AA` with a smaller `MinimumRange` when using this mode.
    - 3 - Fixed horizontal velocity and maximum height mode, using `Trajectory.Speed` and `Trajectory.Parabola.ThrowHeight` as calculation conditions, i.e. the trajectory will only undergo altitude changes with the height of the target.
    - 4 - Fixed maximum height and fire angle mode, using `Trajectory.Parabola.ThrowHeight` and `Trajectory.Parabola.LaunchAngle` as calculation conditions, i.e. the trajectory will change horizontally with the height of the target.
    - 5 - Fixed horizontal velocity and fire angle mode, using `Trajectory.Speed` and `Trajectory.Parabola.LaunchAngle` as calculation conditions, i.e. the trajectory will be permanently fixed.
  - `Trajectory.Parabola.ThrowHeight` controls the maximum height of the projectile and is only used for modes 1, 3, or 4. The specific height will be determined by taking the larger of the launch height and the target height then increasing this value. Non positive numbers are not supported.
  - `Trajectory.Parabola.LaunchAngle` controls the fire angle of the projectile and is only used for modes 2, 4, or 5. Only supports -90.0 ~ 90.0 (Cannot use boundary values) in Mode 2 or 5, and 0.0 ~ 90.0 (Cannot use boundary values) in Mode 4.
  - `Trajectory.Parabola.LeadTimeCalculate` controls whether the projectile need to calculate the lead time of the target when firing. Note that this will not affect the facing of the turret.
    - `Trajectory.Parabola.LeadTimeSimplify` controls whether only perform simplified calculations when calculate the lead time. You can simply consider this as another calculation mode.
    - `Trajectory.Parabola.LeadTimeMultiplier` is an additional lead time multiplier, it will affect the aiming position. You can use this to reduce the errors caused by target speed and target distance.
  - `Trajectory.Parabola.DetonationAngle` controls when the angle between the projectile in the current velocity direction and the horizontal plane is less than this value, it will detonate prematurely. Taking effect when the value is at -90.0 ~ 90.0 (Cannot use boundary values).
  - `Trajectory.Parabola.DetonationHeight` controls when the projectile is in a descending state and below the height of the launch position plus this value, it will detonate prematurely. Taking effect when it is set to non negative value.
  - `Trajectory.Parabola.BounceTimes` controls how many times can it bounce back when the projectile hits the ground or cliff. Be aware that excessive projectile speed may cause abnormal operation. And `Trajectory.Parabola.DetonationDistance` do not conflict with this and will take effect simultaneously. So if you want to explode the bullet only after the times of bounces is exhausted, you should set `Trajectory.Parabola.DetonationDistance` to a non positive value.
    - `Trajectory.Parabola.BounceOnWater` controls whether it can bounce on the water surface.
    - `Trajectory.Parabola.BounceDetonate` controls whether it detonates the warhead once extra during each bounce.
    - `Trajectory.Parabola.BounceAttenuation` controls the attenuation coefficient of projectile bounce damage, that is, how many times the next damage after each bounce is the damage just caused. This will also affect the damage of the final detonation.
    - `Trajectory.Parabola.BounceCoefficient` controls the attenuation coefficient of projectile bounce elasticity, that is, how many times the speed after each bounce is the speed before bouncing.
  - `Trajectory.Parabola.OffsetCoord` controls the offsets of the target. Projectile will aim at this position to attack. It also supports `Inaccurate=yes` and `Trajectory.Parabola.LeadTimeCalculate=true` on this basis.
    - `Trajectory.Parabola.RotateCoord` controls whether to rotate the projectile's firing direction within the angle bisector of `Trajectory.Parabola.OffsetCoord` according to the weapon's `Burst`. Set to 0 to disable this function.
    - `Trajectory.Parabola.MirrorCoord` controls whether `Trajectory.Parabola.OffsetCoord` need to mirror the lateral value to adapt to the current burst index. At the same time, the rotation direction calculated by `Trajectory.Parabola.RotateCoord` will also be reversed, and the rotation angle between each adjacent projectile on each side will not change as a result.
    - `Trajectory.Parabola.UseDisperseBurst` controls whether the calculation of `Trajectory.Parabola.RotateCoord` is based on its superior's `Trajectory.Disperse.WeaponBurst` of the dispersed trajectory, rather than `Burst` of the weapon. If this value is not appropriate, it will result in unsatisfactory visual displays.
    - `Trajectory.Parabola.AxisOfRotation` controls the rotation axis when calculating `Trajectory.Parabola.RotateCoord`. The axis will rotates with the unit orientation or the vector that from target position to the source position.

In `rulesmd.ini`:
```ini
Trajectory=Parabola                             ; Trajectory type
Trajectory.Parabola.DetonationDistance=0.4      ; floating point value
Trajectory.Parabola.TargetSnapDistance=0.5      ; floating point value
Trajectory.Parabola.OpenFireMode=0              ; integer - Six different modes
Trajectory.Parabola.ThrowHeight=600             ; integer
Trajectory.Parabola.LaunchAngle=30              ; floating point value
Trajectory.Parabola.LeadTimeCalculate=no        ; boolean
Trajectory.Parabola.LeadTimeSimplify=no         ; boolean
Trajectory.Parabola.LeadTimeMultiplier=1.0      ; floating point value
Trajectory.Parabola.DetonationAngle=-90.0       ; floating point value
Trajectory.Parabola.DetonationHeight=-1         ; integer
Trajectory.Parabola.BounceTimes=0               ; integer
Trajectory.Parabola.BounceOnWater=no            ; boolean
Trajectory.Parabola.BounceDetonate=no           ; boolean
Trajectory.Parabola.BounceAttenuation=0.8       ; floating point value
Trajectory.Parabola.BounceCoefficient=0.8       ; floating point value
Trajectory.Parabola.OffsetCoord=0,0,0           ; integer - Forward,Lateral,Height
Trajectory.Parabola.RotateCoord=0               ; floating point value
Trajectory.Parabola.MirrorCoord=yes             ; boolean
Trajectory.Parabola.UseDisperseBurst=no         ; boolean
Trajectory.Parabola.AxisOfRotation=0,0,1        ; integer - Forward,Lateral,Height
```

```{note}
- Compared to vanilla `Arcing`, this can also be used for aircrafts and airburst weapon.
- Certainly, `Gravity` can also affect the trajectory.
```

What is `Trajectory=Disperse` -> #1295 

` [...]

2024-09-05 04:36 UTC, secsome requested changes
Looks good in general, but additional code comments are needed. The `mode` related code can be considered for switching to enums

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +void ParabolaTrajectory::CalculateBulletVelocityLeadTime(BulletClass* pBullet, CoordStruct* pSourceCoords, double gravity)
Maybe this function needs an explanation about how all modes are working here, about the logical behind all modes.

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +void ParabolaTrajectory::CalculateBulletVelocityRightNow(BulletClass* pBullet, CoordStruct* pSourceCoords, double gravity)
So does this function needs the explanation, or you could put all explanations at the beginning of this file.

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +			factor = Vector2D<double>{ 0.3763770469559380854890894443664, 0.9264665771223091335116047861327 };
The magic numbers here needs explanation.

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +			return BulletVelocity{ 0.8944271909999158785636694674925 * reverseSgnX, 0.4472135954999579392818347337463 * reverseSgnY, 0.0 };
Magic numbers need explanation

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +
It's a good idea to put all logic explanation stuffs here. For details check the comment below.

Also for magic numbers you could use `constexpr` to give them a meaningful name.

2024-09-05 04:36 UTC, secsome commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +
The explanation is required so we can understand how does this trajectory work easier.

2024-09-05 08:51 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +
All changed.

2024-09-05 09:00 UTC, Metadorius commented on src/Ext/Bullet/Trajectories/PhobosTrajectory.h
> +	Parabola = 4
@secsome is not aware of the other two trajectories pull requests. That is a valid reason to skip enum numbers.

2024-09-10 16:47 UTC, secsome requested changes
Just fix the document.

2024-09-10 16:47 UTC, secsome commented on docs/New-or-Enhanced-Logics.md
> +Trajectory.Parabola.OpenFireMode=0              ; ParabolaFireMode value enumeration (speed|height|angle|speedandheight|heightandangle|speedandangle)
Just a suggestion: Would it be better to change the naming convention for enumeration to start with capital letters?

2024-09-10 16:47 UTC, secsome commented on docs/New-or-Enhanced-Logics.md
> +Trajectory.Parabola.OpenFireMode=0              ; ParabolaFireMode value enumeration (speed|height|angle|speedandheight|heightandangle|speedandangle)
**CHANGE REQUESTED**:
The doc here should be fixed, `OpenFireMode=speed` or any other mode instead of `=0` here

2024-09-10 18:01 UTC, CrimRecya commented on docs/New-or-Enhanced-Logics.md
> +Trajectory.Parabola.OpenFireMode=0              ; ParabolaFireMode value enumeration (speed|height|angle|speedandheight|heightandangle|speedandangle)
Get this. Fixed now. As for the issue of capitalization, although I also like to capitalize the first letter, in reality, capitalization does not affect the reading of the game. :)

2024-09-18 13:14 UTC, secsome commented
Resolve the conflict and we can merge it

2024-09-19 13:23 UTC, chaserli reviewed
not quite related with the pr itself, 2 general questions for the maintainers

2024-09-19 13:23 UTC, chaserli commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
Is it possible to find a way to reduce code duplication for Load/Save? Like what other classes do.

2024-09-19 13:23 UTC, chaserli commented on src/Utilities/TemplateDef.h
> +	inline bool read<ParabolaFireMode>(ParabolaFireMode &value, INI_EX &parser, const char *pSection, const char *pKey)
I doubt if the enum will be used elsewhere, maybe the enum and its parsing template specialization should be defined in-place (I mean in ParabolaTrajectory.h/cpp)

2024-09-19 16:43 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
I think this is not necessary. You can see that the type is saved using false, which is different from the default situation. This was initially informed to me by the sample trajectory template, and I am not sure what problems modifying this item may cause, so I chose to keep it as it is.

2024-09-19 16:44 UTC, CrimRecya commented on src/Utilities/TemplateDef.h
> +	inline bool read<ParabolaFireMode>(ParabolaFireMode &value, INI_EX &parser, const char *pSection, const char *pKey)
Get it.

2024-09-23 14:52 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
I tried using template <typename T> void Serialize(T& Stm); like other ext classes, Although there were no issues with using it in Load, there were red wavy lines that I couldn't solve when using it in Save. :(

2024-09-23 15:06 UTC, chaserli commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
Have you checked why the`RegisterForChange` was explicitly set to false in Load? I think it might be unnecessary. Say if you have a pointer in your class you'll still need to swizzle it, don't you?Just like what you did in your disperse one for the weapons. If it's normal POD nothing gets "swizzled" as expected.

2024-09-23 15:11 UTC, Metadorius commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
POD = Plain Old Data, I don't think this fits though. @chaserli meant a type without pointers I think.

2024-09-23 15:59 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
Seems like the `bool Traj::Save(PhobosStreamWriter& Stm) const`'s `const` makes me cannot use the `void Serialize(T& Stm)`. :(

2024-09-23 16:19 UTC, Metadorius commented on src/Ext/Bullet/Trajectories/ParabolaTrajectory.cpp
> +		.Process(this->DetonationDistance, false)
> Seems like the `bool Traj::Save(PhobosStreamWriter& Stm) const`'s `const` makes me cannot use the `void Serialize(T& Stm)`. :(

@CrimRecya please see the new commit:  https://github.com/Phobos-developers/Phobos/commit/29efd60311a3be770eb46d4a49295c54eba7e615

2025-02-09 13:24 UTC, merged