[Minor] Randomized anims for several behaviors
Phobos-developers/Phobos pull request #1380
Opened 2024-09-16 06:48 UTC by Coronia

Allow several Phobos anim logic to display one of the random anims in the list, instead of one fixed anim. Most of them are related to destroy/take damage behaviors. You can either use their old tags to input the list directly, or use the following new tags in plural forms to override them.

In `rulesmd.ini`:
```ini
[SOMESHIELDTYPE]                            ; ShieldType name
BreakAnim=                                  ; list of Animation
BreakAnims=                                 ; list of Animation, overrides BreakAnim
HitAnim=                                    ; list of Animation
HitAnims=                                   ; list of Animation, overrides HitAnim

[SOMEWARHEAD]                               ; WarheadType
Shield.BreakAnim=                           ; list of Animation
Shield.BreakAnims=                          ; list of Animation, overrides Shield.BreakAnim
Shield.HitAnim=                             ; list of Animation
Shield.HitAnims=                            ; list of Animation, overrides Shield.HitAnim

[SOMETECHNO]                                   ; TechnoType
PassengerDeletion.Anim=                         ; list of Animation
PassengerDeletion.Anims=                        ; list of Animation, overrides PassengerDeletion.Anim
AutoDeath.VanishAnimation=                     ; list of Animation
AutoDeath.VanishAnimations=                    ; list of Animation, overrides AutoDeath.VanishAnimation

[SOMEANIM]                             ; AnimationType
CreateUnit.SpawnAnim=                  ; list of Animation
CreateUnit.SpawnAnims=                 ; list of Animation, overrides CreateUnit.SpawnAnim

[SOMETERRAINTYPE]  ; TerrainType
DestroyAnim=       ; list of Animation
DestroyAnims=      ; list of Animation, overrides DestroyAnim
```

2024-09-16 12:59 UTC, Starkku commented
Add a function to create random anim from `std::vector<AnimTypeClass*>` in `AnimExt` or something instead of copypasting the same thing across the place.

2024-09-24 13:29 UTC, MortonPL requested changes
Please add an entry in the changelog and credits as well.

2024-09-24 13:29 UTC, MortonPL commented on src/Ext/Anim/Body.cpp
> +AnimClass* AnimExt::CreateRandomAnim(std::vector<AnimTypeClass*> AnimList, CoordStruct coords, TechnoClass* pTechno, HouseClass* pHouse, bool invoker)
```suggestion
AnimClass* AnimExt::CreateRandomAnim(const std::vector<AnimTypeClass*>& AnimList, CoordStruct coords, TechnoClass* pTechno, HouseClass* pHouse, bool invoker)
```

Since we're only accessing elements, this vector should be passed as an immutable reference.

2025-04-07 09:43 UTC, Coronia commented
remove those duplicated 'Anims' tags, despite it might be a bit weird to not using plural for a list, it should remain backward compatibility and clearness. Also add random anim support for `WakeAnim` and `Spawner.RecycleAnim`

2025-04-22 13:17 UTC, CrimRecya requested changes

2025-04-22 13:17 UTC, CrimRecya commented on src/New/Entity/ShieldClass.cpp
>  }
This will result in data being modified. If you only need to replace the animation to be played when it is empty, then you should use `const` like this:
```
void ShieldClass::WeaponNullifyAnim(const std::vector<AnimTypeClass*>& pHitAnim)
{
	if (this->AreAnimsHidden)
		return;

	AnimExt::CreateRandomAnim((pHitAnim.empty() ? this->Type->HitAnim : pHitAnim), this->Techno->GetCoords(), this->Techno, nullptr, true, true);
}
```

2025-04-22 13:17 UTC, CrimRecya commented on src/New/Entity/ShieldClass.cpp
> +		AnimExt::CreateRandomAnim(pBreakAnim, this->Techno->Location, this->Techno, nullptr, true, true);
Same as above.

2025-04-22 13:17 UTC, CrimRecya commented on src/New/Entity/ShieldClass.h
> +	void BreakShield(std::vector<AnimTypeClass*>& pBreakAnim, WeaponTypeClass* pBreakWeapon = nullptr);
Remember to modify several parts of the header file as well.

2025-08-24 08:54 UTC, Coronia commented
The definition of customizable `WarpAway` in Phobos seems to be wrong, as it should be the anim that the techno is erased by `Temporal` warheads rather than the anim used by Chronoshift, which should still use `WarpIn` and `WarpOut`. But here it hooks out Chronoshift's WarpOut anim and make it become the customize WarpAway.

Not sure if these tag definitions should be changed now that they might be made use by mods already, and I'm thinking if the WarpIn/Out of Chronoshift still deserves a customization. As of now I might keep them as they are while adding the random anim feature for them, but if there's an idea about how to sort out these tags then I could also try to implement them in this pull request

2025-09-06 04:07 UTC, Coronia commented
> The definition of customizable `WarpAway` in Phobos seems to be wrong, as it should be the anim that the techno is erased by `Temporal` warheads rather than the anim used by Chronoshift, which should still use `WarpIn` and `WarpOut`. But here it hooks out Chronoshift's WarpOut anim and make it become the customize WarpAway.
> 
> Not sure if these tag definitions should be changed now that they might be made use by mods already, and I'm thinking if the WarpIn/Out of Chronoshift still deserves a customization. As of now I might keep them as they are while adding the random anim feature for them, but if there's an idea about how to sort out these tags then I could also try to implement them in this pull request

Fixed this in this PR already

2025-09-06 04:36 UTC, merged