Exclusive SuperWeapon Sidebar
Phobos-developers/Phobos pull request #1384
Opened 2024-09-18 17:02 UTC by NetsuNegi

- It is possible to put sw cameos on the left of screen like C&C3 when `ExclusiveSuperWeaponSidebar` is true.
- In theory, it should be compatible with Ares.
- Cameos arranged in a pyramid shape.
- `ExclusiveSuperWeaponSidebar.Max` controls the maximum number of icons on the leftmost side, which also depends on the current game resolution.

In `uimd.ini`:
```ini
[Sidebar]
ExclusiveSuperWeaponSidebar=false  ; boolean
ExclusiveSuperWeaponSidebar.Max=0 ; integer
```

In `rulesmd.ini`
```ini
[SuperWeapon]
AllowInExclusiveSidebar=true  ; boolean
```
![exclusive-sw-sidebar](https://github.com/user-attachments/assets/f8bb777f-4d62-4550-99e9-4ded2d5101d4)

2024-09-20 09:34 UTC, NetsuNegi commented
looks like nobody interested for this, so it won't change again until somebody notice it.

2024-09-20 10:11 UTC, FS-21 commented
Due to the big number of SW that can stack in that side of the screen can be added a button for show/hide this SuperWeapon Sidebar ?

2024-09-20 10:12 UTC, Metadorius commented
> looks like nobody interested for this, so it won't change again until somebody notice it.

That's not really true, we're just yet to give feedback, and the situation with you and @CrimRecya working on the same feature is a bit... odd

1) Maybe you and @CrimRecya could cooperate and implement a unified way which includes best of both worlds? Your implementation looks better in terms of internal, but his is more feature-full.
2) Is there a reason you don't inherit from ControlClass? Per @ZivDero ToggleClass has different functionality that is not useful to your implementation.

2024-09-20 10:33 UTC, Starkku commented
As useful as this may seem to some I still think both this and #1379 are infinitely less desirable than an additional sidebar tab for superweapons. I know there are some potential challenges in trying to implement that but maybe there's some sort of shortcut to 'fake it' rather than trying to plug it into the existing tab system e.g a button that changes the tab display to something that looks like it but isn't and only display's SW's. If I had more time and energy I would help you guys in the research but alas no can do.

2024-09-20 11:07 UTC, Metadorius commented
I think that a separate sidebar can also be an alternative option, doesn't have to choose either or.

2024-09-20 12:39 UTC, NetsuNegi commented
> 看起来不错，但由于屏幕那一侧可以堆叠的大量软件可以添加一个按钮来显示/隐藏这个 SuperWeapon 侧边栏？

of course

2024-09-20 12:40 UTC, NetsuNegi commented
> > looks like nobody interested for this, so it won't change again until somebody notice it.
> 
> That's not really true, we're just yet to give feedback, and the situation with you and @CrimRecya working on the same feature is a bit... odd
> 
> 1. Maybe you and @CrimRecya could cooperate and implement a unified way which includes best of both worlds? Your implementation looks better in terms of internal, but his is more feature-full.
> 2. Is there a reason you don't inherit from ControlClass? Per @ZivDero ToggleClass has different functionality that is not useful to your implementation.

There's no special reason, it's just because I don't know it well enough

2024-09-20 13:09 UTC, NetsuNegi commented
this PR's YRpp has been broken

2024-09-25 14:54 UTC, ZivDero reviewed
Overall, I am happy with this implementation. Looking at the new button, it looks well implemented to me. Kudos.

It's a shame we have to reimplement all this Ares crap, but eh, not much that can be done.

2024-09-25 14:54 UTC, ZivDero commented on src/Ext/Sidebar/TacticalButtonClass.cpp
> +		this->IsPressed = false;
IIRC when you handle an input, you should exlude it before passing it on.
So `flags &= ~GadgetFlag::LeftRelease` or smth.

2024-09-25 14:54 UTC, ZivDero approved these changes
Just don't forget to resolve conflics and update docs.

2024-09-25 14:59 UTC, NetsuNegi commented
> If you wanna make it even better, maybe take out the static stuff outside of TacticalButtonClass, and into some new "SWSidebarClass". It's a bit weird to have it in the button itself, even if this is the only purpose of the button. Just don't forget to resolve conflics and update docs.

Actually, I don't know how to handle conflicts outside of the browser

2024-09-25 15:02 UTC, ZivDero commented
> > If you wanna make it even better, maybe take out the static stuff outside of TacticalButtonClass, and into some new "SWSidebarClass". It's a bit weird to have it in the button itself, even if this is the only purpose of the button. Just don't forget to resolve conflics and update docs.
> 
> Actually, I don't know how to handle conflicts outside of the browser

You need to rebase your branch onto the latest develop. Then you'll get conflicts inside the files, and you can resolve them in VS/VS Code/other diff program.

2024-09-25 15:06 UTC, NetsuNegi commented
> > > If you wanna make it even better, maybe take out the static stuff outside of TacticalButtonClass, and into some new "SWSidebarClass". It's a bit weird to have it in the button itself, even if this is the only purpose of the button. Just don't forget to resolve conflics and update docs.
> > 
> > 
> > Actually, I don't know how to handle conflicts outside of the browser
> 
> You need to rebase your branch onto the latest develop. Then you'll get conflicts inside the files, and you can resolve them in VS/VS Code/other diff program.

idk how to do it :(

2024-09-26 16:50 UTC, CrimRecya commented
Thank you very much for your creation and for putting in so much effort to improve this implement.
Since I am currently unable to conduct direct testing, I plan to ask you a few questions based on my previous PR #1379 :

1. Can the mouse operations on the background be blocked, not responded to by various other operations.
2. Can the keys directly display on the cameo to replace "ready" text when the SW is ready.
3. Is there an another button that can be clicked besides the shortcut key switch.
4. Can the SW be released directly at the mouse position by pressing the shortcut key (may not need to be directly included in this feature, but is indeed related)

Praise You!

I see that you are also a Chinese contributor, so I directly write the original Chinese version for your understanding :

非常感谢你的创作，并花费如此精力改进这个功能。
由于我现在没有办法直接进行测试，所以我想基于 pr #1379 的已有功能，询问几个问题：

1、对于图标后的背景，鼠标在其之上进行的操作是否能够被屏蔽，也就是说不会被各种其他操作所响应。
2、在超级武器准备完毕的时候，也就是图标上会显示“就绪”文本的时候，能否将这个文本改成其快捷键的键位。
3、除了快捷键开关之外，是否能有一个可以点击的图标开关。
4、（可能并不需要直接包含在这个功能里，但确实相关的功能）能否通过直接按下快捷键，让超级武器直接在鼠标所在的位置释放

称赞.gif

2024-09-27 09:48 UTC, Metadorius commented
A bit off-topic, but I appreciate you guys providing both English version of messages for understanding of others and Chinese to understand each other better, this is optimal for everyone participating 👍

2024-09-27 15:54 UTC, NetsuNegi commented
TODO:
Make the keys directly display on the cameo to replace "ready" text when the SW is ready.
Add a button that can be clicked besides the shortcut key switch.

2024-09-28 01:16 UTC, NetsuNegi commented
I hate load game :(

2024-09-28 05:59 UTC, NetsuNegi commented
There's an unresolveable error after load game.

2024-09-28 06:10 UTC, NetsuNegi commented
I tried many times, it always crash.
I'm too tired

2024-09-28 09:57 UTC, Metadorius commented
I don't think you ever need to save/load anything in the sidebar. The game just recreates the sidebar on each load, so you could do the same

2024-09-28 15:16 UTC, NetsuNegi commented
> TODO: Make the keys directly display on the cameo to replace "ready" text when the SW is ready. Add a button that can be clicked besides the shortcut key switch.

I will do that in next 2 days.

2024-09-28 15:17 UTC, NetsuNegi commented
> I don't think you ever need to save/load anything in the sidebar. The game just recreates the sidebar on each load, so you could do the same.

But I still need to save/load the superIndex per buttons I think.

2024-09-28 15:32 UTC, Metadorius commented
> But I still need to save/load the superIndex per buttons I think.

I don't think you need to. Just treat loading as you will treat starting a new game.

I haven't looked in depth at how you implemented it, but what I would do is add the superweapon to the SuperWeapon Sidebar when the same superweapon is added to the main sidebar, so you will automatically keep them in sync.

Keep in mind that I didn't check in depth how it works, so this is only in theory.

2024-09-28 16:05 UTC, NetsuNegi commented
> > But I still need to save/load the superIndex per buttons I think.
> 
> I don't think you need to. Just treat loading as you will treat starting a new game.
> 
> I haven't looked in depth at how you implemented it, but what I would do is add the superweapon to the SuperWeapon Sidebar when the same superweapon is added to the main sidebar, so you will automatically keep them in sync.
> 
> Keep in mind that I didn't check in depth how it works, so this is only in theory.

It seems that the game did not re add cameos after reading the save file.
Or I just didn't find it.

2024-09-29 02:21 UTC, NetsuNegi commented
> Thank you very much for your creation and for putting in so much effort to improve this implement. Since I am currently unable to conduct direct testing, I plan to ask you a few questions based on my previous PR #1379 :
> 
> 1. Can the mouse operations on the background be blocked, not responded to by various other operations.
> 2. Can the keys directly display on the cameo to replace "ready" text when the SW is ready.
> 3. Is there an another button that can be clicked besides the shortcut key switch.
> 4. Can the SW be released directly at the mouse position by pressing the shortcut key (may not need to be directly included in this feature, but is indeed related)
> 
> Praise You!
> 
> I see that you are also a Chinese contributor, so I directly write the original Chinese version for your understanding :
> 
> 非常感谢你的创作，并花费如此精力改进这个功能。 由于我现在没有办法直接进行测试，所以我想基于 pr #1379 的已有功能，询问几个问题：
> 
> 1、对于图标后的背景，鼠标在其之上进行的操作是否能够被屏蔽，也就是说不会被各种其他操作所响应。 2、在超级武器准备完毕的时候，也就是图标上会显示“就绪”文本的时候，能否将这个文本改成其快捷键的键位。 3、除了快捷键开关之外，是否能有一个可以点击的图标开关。 4、（可能并不需要直接包含在这个功能里，但确实相关的功能）能否通过直接按下快捷键，让超级武器直接在鼠标所在的位置释放
> 
> 称赞.gif

It should be finished now.
应该都完成了。

2024-09-29 22:25 UTC, Metadorius reviewed
Not full review, just randomly stumbled upon something to change.

2024-09-29 22:25 UTC, Metadorius commented on src/Commands/FireTacticalSW.h
> +	return ret;
I think instead all of this `class to_string_t` you could just use formatted print via `_snwprintf_s`.

2024-09-29 22:26 UTC, Metadorius commented on src/Commands/FireTacticalSW.h
> +	return ret;
While at it you can also replace the same constructs in the code you took the example from, it would be appreciated.

2024-09-30 00:52 UTC, NetsuNegi commented on src/Commands/FireTacticalSW.h
> +	return ret;
alright, that's just copy from FrameStep.h

2024-09-30 05:06 UTC, Metadorius commented on src/Commands/FireTacticalSW.h
> +	return ret;
it's OK, that's why I said you can replace it there too :)

2024-09-30 09:33 UTC, CrimRecya reviewed
I took a brief look and haven't test yet.
我简单看了下，还没测试。

2024-09-30 09:33 UTC, CrimRecya commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +		sprintf_s(buffer, "SW Sidebar Shortcuts Num %02d", idx);
I think you forgot to change this to the shortcut key name you defined.
我想你应该是忘记把这里改成你所定义的快捷键名称了。

2024-09-30 09:33 UTC, CrimRecya commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +		sprintf_s(buffer, "SW Sidebar Shortcuts Num %02d", idx);
The same.
同上。

2024-09-30 09:33 UTC, CrimRecya commented on src/Ext/Side/Body.h
> +		Valueable<SHPStruct*> ExclusiveSWSidebar_ToggleShape;
I think it would be better if the switch could use different images in the on/off state.
我想如果开关能在开/关状态下可以使用不同的图像会更好。

2024-09-30 17:01 UTC, ZivDero commented on src/Misc/PhobosToolTip.cpp
> +		if (const auto button = SWSidebarClass::Global()->CurrentButton)
Questionable syntax, avoid assignments inside if blocks (aside from dynamic_cast, perhaps)

2024-09-30 17:02 UTC, ZivDero commented on src/Commands/ToggleSWSidebar.cpp
> +		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_INVISIBLE", L"Set exclusive SW sidebar invisible."), RulesClass::Instance->MessageDelay, HouseClass::Cu
Please have someone proofread your default strings.

2024-09-30 17:03 UTC, ZivDero commented on src/Commands/Commands.cpp
> +	MakeCommand<FireTacticalSWCommandClass<9>>();
This should be enough for commands to appear in the settings and save/load in/from keyboard.ini. Why the other fluff?

2024-09-30 17:35 UTC, Metadorius commented on src/Commands/ToggleSWSidebar.cpp
> +		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_INVISIBLE", L"Set exclusive SW sidebar invisible."), RulesClass::Instance->MessageDelay, HouseClass::Cu
That's kinda what we are for :P

2024-09-30 17:36 UTC, Metadorius commented on src/Misc/PhobosToolTip.cpp
> +		if (const auto button = SWSidebarClass::Global()->CurrentButton)
It's a shorthand for a null check and is actually quite convenient. There is no risk here because you assign a variable and not compare. We do that often in Phobos.

2024-09-30 17:44 UTC, ZivDero requested changes

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/FireTacticalSW.h
> +	_snwprintf_s(Phobos::wideBuffer, Phobos::readLength, L"Fire tactical SW %d\0", Index);
```suggestion
	_snwprintf_s(Phobos::wideBuffer, Phobos::readLength, L"Fire Super Weapon %d", Index);
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/FireTacticalSW.h
> +	_snprintf_s(Phobos::readBuffer, Phobos::readLength, "FireTacticalSW %d\0", Index);
```suggestion
	_snprintf_s(Phobos::readBuffer, Phobos::readLength, "FireTacticalSW%d", Index);
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/FireTacticalSW.h
> +	_snwprintf_s(Phobos::wideBuffer, Phobos::readLength, L"Fire tactical SW %d\0", Index);
```suggestion
	_snwprintf_s(Phobos::wideBuffer, Phobos::readLength, L"Fires Super Weapon %d.", Index);
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/ToggleSWSidebar.cpp
> +	return GeneralUtils::LoadStringUnlessMissing("TXT_TOGGLE_SW_SIDEBAR", L"Toggle SuperWeapon Sidebar");
```suggestion
	return GeneralUtils::LoadStringUnlessMissing("TXT_TOGGLE_SW_SIDEBAR", L"Toggle Super Weapon Sidebar");
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/ToggleSWSidebar.cpp
> +	return GeneralUtils::LoadStringUnlessMissing("TXT_TOGGLE_SW_SIDEBAR_DESC", L"Toggle SuperWeapon Sidebar.");
```suggestion
	return GeneralUtils::LoadStringUnlessMissing("TXT_TOGGLE_SW_SIDEBAR_DESC", L"Toggles the Super Weapon Sidebar.");
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/ToggleSWSidebar.cpp
> +		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_VISIBLE", L"Set exclusive SW sidebar visible."), RulesClass::Instance->MessageDelay, HouseClass::Curren
```suggestion
		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_VISIBLE", L"Super Weapon Sidebar Enabled."), RulesClass::Instance->MessageDelay, HouseClass::CurrentPlayer->ColorSchemeIndex, true);
```

2024-09-30 17:44 UTC, ZivDero commented on src/Commands/ToggleSWSidebar.cpp
> +		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_INVISIBLE", L"Set exclusive SW sidebar invisible."), RulesClass::Instance->MessageDelay, HouseClass::Cu
```suggestion
		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_BAR_INVISIBLE", L"Super Weapon Sidebar Disabled."), RulesClass::Instance->MessageDelay, HouseClass::CurrentPlayer->ColorSchemeIndex, true);
```

2024-09-30 17:46 UTC, ZivDero commented on src/Misc/PhobosToolTip.cpp
> +		if (const auto button = SWSidebarClass::Global()->CurrentButton)
I would prefer not doing this since it's not transformative (a dynamic_cast would at least give you something else, in this case you can just repeat this thing 3 times inside which is fine IMO, or declare a variable inside the block. Unjustified use.

2024-09-30 17:57 UTC, Metadorius commented on src/Misc/PhobosToolTip.cpp
> +		if (const auto button = SWSidebarClass::Global()->CurrentButton)
Well either way my point is that it's not necessarily bad. This is a personal preferences territory in this case IMO.

2024-09-30 18:05 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
I added HouseClass::AISupers() for you.

2024-10-01 02:33 UTC, NetsuNegi commented on src/Ext/Side/Body.h
> +		Valueable<SHPStruct*> ExclusiveSWSidebar_ToggleShape;
Yes it can, the on/off state will use different frame index.
是的它可以，开/关状态下会使用不同的帧。

2024-10-01 02:36 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWColumnClass.cpp
> +		if (!Phobos::UI::ExclusiveSWSidebar || Unsorted::ArmageddonMode)
0x6A630C

2024-10-01 03:23 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWColumnClass.cpp
> +}
Because I want it to block mouse action.

2024-10-01 03:24 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWColumnClass.cpp
> +}
Buttons click has been blocked by Column's, so I manually check it.

2024-10-01 03:25 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
This just copy from PR#1379

2024-10-01 03:25 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
OK.

2024-10-01 03:33 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
But how can I get the hotkey of the command?

2024-10-01 11:05 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
You shouldn't need to get the hotkey of the command, the command is self-sufficientr (just does everything in ::Execute)

2024-10-01 11:12 UTC, CrimRecya commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> You shouldn't need to get the hotkey of the command, the command is self-sufficientr (just does everything in ::Execute)

This is not for us to execute, this is for players to see.

2024-10-01 11:28 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> This is not for us to execute, this is for players to see.

Alright, we see now.

I have not looked in depth at the algorithm you do, but what I know is that in the hotkey configuration window the game already writes the key combination like `Alt+A` for example. What I think we should do: when writing the label at the cameo of superweapon, see the order of it in the sidebar, look up the corresponding hotkey from the global array of registered hotkeys (by type) and transform the key combination that is used for that hotkey into a string, then print it.

2024-10-01 12:42 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> > This is not for us to execute, this is for players to see.
> 
> Alright, we see now.
> 
> I have not looked in depth at the algorithm you do, but what I know is that in the hotkey configuration window the game already writes the key combination like `Alt+A` for example. What I think we should do: when writing the label at the cameo of superweapon, see the order of it in the sidebar, look up the corresponding hotkey from the global array of registered hotkeys (by type) and transform the key combination that is used for that hotkey into a string, then print it.

So how can I do that?

2024-10-01 13:38 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> So how can I do that?

@ZivDero is currently in process of adding stuff to YRpp so you can accomplish that, please wait a bit.

2024-10-22 20:35 UTC, ZivDero requested changes
Almost there

2024-10-22 20:35 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWColumnClass.cpp
> +	AnnounceInvalidPointer(SWSidebarClass::Global()->CurrentButton, *it);
`it` is a weird choice. Maybe `button`?

2024-10-22 20:35 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
This could use the vanilla functions that provide the name of the key, but one would need to add it it YRpp first. For now I guess it's not a big deal, although perhaps maybe it could be taken out of here and into some place as a util?

2024-10-22 20:35 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
Please utilize HouseClass::AISuper()

2024-10-22 20:35 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +void SWSidebarClass::Init_Clear()
```suggestion
void SWSidebarClass::InitClear()
```

2024-10-22 20:35 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +		sprintf_s(buffer, "SW Sidebar Shortcuts Num %02d", idx);
I'm not 100% on what's up here, please verify if the string you make is what you intended.

2024-10-22 20:41 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> but one would need to add it it YRpp first

@ZivDero didn't you already do exactly that?

2024-10-22 20:41 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +}
> > but one would need to add it it YRpp first
> 
> @ZivDero didn't you already do exactly that?

I encountered some issues the details of which I don't recall and I don't think it ever got to completion, no.

2024-10-23 03:30 UTC, CrimRecya commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +		sprintf_s(buffer, "SW Sidebar Shortcuts Num %02d", idx);
> I'm not 100% on what's up here, please verify if the string you make is what you intended.

This should be the `Name` of the command class.
This is when loading/saving shortcut keys. Finding the newly added SW shortcut keys by comparing the names, extract their shortcut key codes and translate to text through that huge map. Finally display them conveniently on the screen for players.
However, the game originally had a function to display shortcut key text in the settings interface, but I couldn't find it, so this became a form of separate recording and self translation.

2024-10-23 10:53 UTC, ZivDero commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +		sprintf_s(buffer, "SW Sidebar Shortcuts Num %02d", idx);
> > I'm not 100% on what's up here, please verify if the string you make is what you intended.
> 
> This should be the `Name` of the command class. This is when loading/saving shortcut keys. Finding the newly added SW shortcut keys by comparing the names, extract their shortcut key codes and translate to text through that huge map. Finally display them conveniently on the screen for players. However, the game originally had a function to display shortcut key text in the settings interface, but I couldn't find it, so this became a form of separate recording and self translation.

`61EF70` is the function.
`void WWUI::Get_Keyboard_Key_String(int key, wchar_t *buffer)`

2024-10-26 01:28 UTC, NetsuNegi commented
The AI_Super() does not exist in my local repository. And I cannot resolve conflict.

2024-11-03 04:49 UTC, NetsuNegi commented
I don't have enough ability and information to complete this PR.

2024-11-03 22:38 UTC, Metadorius commented
@NetsuNegi @CrimRecya can you provide the default sprites for the superweapon sidebar background and buttons?

2024-11-04 00:01 UTC, NetsuNegi commented
> @NetsuNegi @CrimRecya can you provide the default sprites for the superweapon sidebar background and buttons?

what's the 'sprites' ?

2024-11-04 00:02 UTC, NetsuNegi commented
Unfortunately, I cannot fetch changes to my local repo :(

2024-11-04 00:03 UTC, ZivDero commented
> > @NetsuNegi @CrimRecya can you provide the default sprites for the superweapon sidebar background and buttons?
> 
> what's the 'sprites' ?

Shapes. You should be able to zip them up and upload right here by dragging the archive into the message box.

2024-11-04 00:04 UTC, ZivDero approved these changes

2024-11-04 00:33 UTC, NetsuNegi commented
> > > @NetsuNegi @CrimRecya can you provide the default sprites for the superweapon sidebar background and buttons?
> > 
> > 
> > what's the 'sprites' ?
> 
> Shapes. You should be able to zip them up and upload right here by dragging the archive into the message box.

alright

2024-11-04 09:34 UTC, CrimRecya commented
> > > @NetsuNegi @CrimRecya can you provide the default sprites for the superweapon sidebar background and buttons?
> > 
> > 
> > what's the 'sprites' ?
> 
> Shapes. You should be able to zip them up and upload right here by dragging the archive into the message box.

This is what I used in #1379
[SWbackground.zip](https://github.com/user-attachments/files/17616176/SWbackground.zip)

2024-11-04 15:54 UTC, Metadorius commented
> Unfortunately, I cannot fetch changes to my local repo :(

@NetsuNegi assuming you haven't done any local changes, you can either hard reset it to remote branch, or delete the local branch and re-fetch it from the remote.

2024-11-09 19:32 UTC, Metadorius commented
@NetsuNegi there seems to be a problem as per MigEater's testing: 
![image](https://github.com/user-attachments/assets/da2ccb95-4cb6-4975-a210-7f4956db4e5f)

2024-11-10 01:43 UTC, NetsuNegi commented
> @NetsuNegi there seems to be a problem as per MigEater's testing: ![image](https://private-user-images.githubusercontent.com/17500545/384638674-da2ccb95-4cb6-4975-a210-7f4956db4e5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDMxNTEsIm5iZiI6MTczMTIwMjg1MSwicGF0aCI6Ii8xNzUwMDU0NS8zODQ2Mzg2NzQtZGEyY2NiOTUtNGNiNi00OTc1LWEyMTAtN2Y0OTU2ZGI0ZTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDAxNDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MzJlNGU0OTQzZGQ2ZjhmMDI3MGVjODZkOGUxMTc5MDFmNmQ0MzY3OGZjZTIxOGJjZWViZjYwMzgwNDM1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NwSAnlAKgPM6SvdudClYJ0HtHoxSzFGVY4wPjMaNdiQ)

it should be fixed now, but I still cannot process with conflicts

2024-11-10 01:45 UTC, NetsuNegi commented
It always dont show any conflict when a push changes

2024-11-10 02:14 UTC, Metadorius commented
Do you mean that GitHub-issued notification that says you have merge conflicts? You need to merge develop into your branch in order for the conflicts to be shown.

2024-11-10 02:47 UTC, NetsuNegi commented
> Do you mean that GitHub-issued notification that says you have merge conflicts? You need to merge develop into your branch in order for the conflicts to be shown.

I cannot understand Ares Helper's changes for now

2024-11-10 02:50 UTC, NetsuNegi commented
> Do you mean that GitHub-issued notification that says you have merge conflicts? You need to merge develop into your branch in order for the conflicts to be shown.

I don't want to deal with this tricky thing

2024-11-10 04:45 UTC, NetsuNegi commented
I have tried use lastest Ares Interface, but it cannot work, so I cannot finished by myself.

2024-11-10 15:23 UTC, Metadorius commented
What doesn't work?

2024-11-10 15:48 UTC, NetsuNegi commented
> What doesn't work?

I need call Ares function SWTypeExt::ExtMap() and SWTypeExt::IsTargetConstraintsEligible()

2024-11-10 15:49 UTC, NetsuNegi commented
> What doesn't work?

and I dont know how to call it with latest Ares interface.

2024-11-10 16:46 UTC, chaserli commented
```cpp
class SuperClass;
class SWStateMachine;
class SuperWeaponTypeClass;

struct AresSWTypeExt
{
	
};
class AresFunctions
{
public:
	static std::vector<SWStateMachine* const>* StateMachines;
	static bool(__thiscall* IsTargetConstraintsEligible)(AresSWTypeExt* , HouseClass* , bool );
	static AresSWTypeExt* (__thiscall* SWTypeExtMapFind)(void*,SuperWeaponTypeClass*);
private:
	static void* SWTypeExtMap;
};
void AresFunctions::InitAres3_0p1()
{
	NOTE_ARES_FUN(StateMachines, 0xC31B8);
	NOTE_ARES_FUN(SWTypeExtMapFind, 0x058900);
	NOTE_ARES_FUN(SWTypeExtMap, 0x0C2C50);
	NOTE_ARES_FUN(IsTargetConstraintsEligible, 0x032AF0);
}
```

2024-11-11 02:15 UTC, NetsuNegi commented
> ```c++
> class SuperClass;
> class SWStateMachine;
> class SuperWeaponTypeClass;
> 
> struct AresSWTypeExt
> {
> 	
> };
> class AresFunctions
> {
> public:
> 	static std::vector<SWStateMachine* const>* StateMachines;
> 	static bool(__thiscall* IsTargetConstraintsEligible)(AresSWTypeExt* , HouseClass* , bool );
> 	static AresSWTypeExt* (__thiscall* SWTypeExtMapFind)(void*,SuperWeaponTypeClass*);
> private:
> 	static void* SWTypeExtMap;
> };
> void AresFunctions::InitAres3_0p1()
> {
> 	NOTE_ARES_FUN(StateMachines, 0xC31B8);
> 	NOTE_ARES_FUN(SWTypeExtMapFind, 0x058900);
> 	NOTE_ARES_FUN(SWTypeExtMap, 0x0C2C50);
> 	NOTE_ARES_FUN(IsTargetConstraintsEligible, 0x032AF0);
> }
> ```

got it, I'll try it later

2024-11-11 03:05 UTC, NetsuNegi commented
YRpp...

2024-11-11 03:11 UTC, NetsuNegi commented
alright, I cannot fix YRpp

2024-11-11 05:50 UTC, Metadorius commented
What is the problem?

2024-11-11 05:53 UTC, Metadorius commented
Can you at least describe what is the problem clearly right away? When you post "can't fix" - every time I have to ask you what is the problem exactly in order to help.

2024-11-11 05:57 UTC, NetsuNegi commented
> Can you at least describe what is the problem clearly right away? When you post "can't fix" - every time I have to ask you what is the problem exactly in order to help.

missed changes of YRpp in commit 4637167

2024-12-06 16:59 UTC, Metadorius commented
@NetsuNegi so, what is the status on this one?

2024-12-06 17:03 UTC, NetsuNegi commented
> @NetsuNegi so, what is the status on this one?

a conflict with YRpp about commit https://github.com/Phobos-developers/Phobos/commit/4637167010d5525ec9049e741d163efa48db2e86
`UnitClass::IsFollowerCar`

2024-12-07 10:18 UTC, Aephiex commented
I solved the conflict.

[https://github.com/NetsuNegi/Phobos/pull/3](https://github.com/NetsuNegi/Phobos/pull/3)

Merge my pull request and this one will be mergable.

2024-12-07 10:38 UTC, NetsuNegi commented
> I solved the conflict.
> 
> [NetsuNegi#3](https://github.com/NetsuNegi/Phobos/pull/3)
> 
> Merge my pull request and this one will be mergable.

thanks

2024-12-07 10:56 UTC, Aephiex commented
`[.gitmodules](https://github.com/Phobos-developers/Phobos/pull/1384/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584)` was accedently modified when I try to fix the YRpp conflict. I don't know if there will be a side effect changing the url from HTTPS to SSH. Hopefully you can edit it?

2024-12-07 10:57 UTC, NetsuNegi commented
> [](https://github.com/Phobos-developers/Phobos/pull/1384/files#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584)在我尝试修复 YRpp 冲突时被修改。我不知道将 url 从 HTTPS 更改为 SSH 是否会有副作用。希望你能编辑它吗？

what?

2024-12-07 10:58 UTC, Aephiex commented
![image](https://github.com/user-attachments/assets/7368d31e-a398-4ac6-913b-6eff473c0487)
I mean, this file. The change was not intended, and I don't know if there will be a side effect.

2024-12-07 10:58 UTC, NetsuNegi commented
> ![image](https://private-user-images.githubusercontent.com/34618932/393504217-7368d31e-a398-4ac6-913b-6eff473c0487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk0MDAsIm5iZiI6MTczMzU2OTEwMCwicGF0aCI6Ii8zNDYxODkzMi8zOTM1MDQyMTctNzM2OGQzMWUtYTM5OC00YWM2LTkxM2ItNmVmZjQ3M2MwNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEwNTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTdjMmRjYWZiYTJmNTgwYjBkMGNiMDZmMmE3MzgyY2ViODlkY2I5YzAxZDBlNmYyNTBjZDc0N2FhMjE4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbJQgrSlmXlPc5IVl_OIKVR6HxCVcQ1RHO4K5s2duDA) I mean, this file. The change was not intended, and I don't know if there will be a side effect.

idk too

2024-12-07 10:59 UTC, NetsuNegi commented
> ![image](https://private-user-images.githubusercontent.com/34618932/393504217-7368d31e-a398-4ac6-913b-6eff473c0487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk0MDAsIm5iZiI6MTczMzU2OTEwMCwicGF0aCI6Ii8zNDYxODkzMi8zOTM1MDQyMTctNzM2OGQzMWUtYTM5OC00YWM2LTkxM2ItNmVmZjQ3M2MwNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEwNTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTdjMmRjYWZiYTJmNTgwYjBkMGNiMDZmMmE3MzgyY2ViODlkY2I5YzAxZDBlNmYyNTBjZDc0N2FhMjE4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbJQgrSlmXlPc5IVl_OIKVR6HxCVcQ1RHO4K5s2duDA) I mean, this file. The change was not intended, and I don't know if there will be a side effect.

I hope it can still work fine

2024-12-07 11:00 UTC, Aephiex commented
> > ![image](https://private-user-images.githubusercontent.com/34618932/393504217-7368d31e-a398-4ac6-913b-6eff473c0487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk0MDAsIm5iZiI6MTczMzU2OTEwMCwicGF0aCI6Ii8zNDYxODkzMi8zOTM1MDQyMTctNzM2OGQzMWUtYTM5OC00YWM2LTkxM2ItNmVmZjQ3M2MwNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEwNTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTdjMmRjYWZiYTJmNTgwYjBkMGNiMDZmMmE3MzgyY2ViODlkY2I5YzAxZDBlNmYyNTBjZDc0N2FhMjE4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbJQgrSlmXlPc5IVl_OIKVR6HxCVcQ1RHO4K5s2duDA) I mean, this file. The change was not intended, and I don't know if there will be a side effect.
> 
> idk too

Hopefully you can edit it? Change the URL back to the original.

2024-12-07 11:02 UTC, NetsuNegi commented
> > > ![image](https://private-user-images.githubusercontent.com/34618932/393504217-7368d31e-a398-4ac6-913b-6eff473c0487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1Njk0MDAsIm5iZiI6MTczMzU2OTEwMCwicGF0aCI6Ii8zNDYxODkzMi8zOTM1MDQyMTctNzM2OGQzMWUtYTM5OC00YWM2LTkxM2ItNmVmZjQ3M2MwNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEwNTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZTdjMmRjYWZiYTJmNTgwYjBkMGNiMDZmMmE3MzgyY2ViODlkY2I5YzAxZDBlNmYyNTBjZDc0N2FhMjE4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fbJQgrSlmXlPc5IVl_OIKVR6HxCVcQ1RHO4K5s2duDA) I mean, this file. The change was not intended, and I don't know if there will be a side effect.
> > 
> > 
> > idk too
> 
> Hopefully you can edit it? Change the URL back to the original.

idk how to do it, submodule is a big problem for me, it always very hard to process when I need to change something.
I hate it

2024-12-07 11:07 UTC, Aephiex commented
Oh, never mind, it is as easy as editing the file, and the file is only an URL refering to a submodule.

The HTTPS and the git@ are both valid URL references, and the file `.gitmodule` was not what caused the conflict. And the conflict is gone for good.

Anyway, I made another pull request to change the file back, so you don't need to touch it yourself.

2024-12-07 11:08 UTC, NetsuNegi commented
> Oh, never mind, it is as easy as editing the file, and the file is only an URL refering to a submodule.
> 
> The HTTPS and the git@ are both valid URL references, and the file was not what caused the conflict. And the conflict is gone for good.`.gitmodule`
> 
> Anyway, I made another pull request to change the file back, so you don't need to touch it yourself.

ok

2024-12-07 11:10 UTC, Aephiex commented
https://github.com/NetsuNegi/Phobos/pull/4

2024-12-07 12:26 UTC, Aephiex commented
https://github.com/NetsuNegi/Phobos/pull/5

Hello, fixed nightly build error.

2024-12-07 14:19 UTC, NetsuNegi commented
> [NetsuNegi#5](https://github.com/NetsuNegi/Phobos/pull/5)
> 
> 您好，很抱歉再次打扰您，修复了夜间构建错误。
> 
> 我的本地构建通过此更新成功，我可以在屏幕左侧看到超级武器侧边栏。

thanks again

2024-12-08 03:05 UTC, NetsuNegi commented
> @NetsuNegi so, what is the status on this one?

it looks ok for now

2024-12-10 03:08 UTC, NetsuNegi commented
`ExclusiveSWSidebar`, `ExclusiveSidebar` now all changed to `SuperWeaponSidebar`

2024-12-10 03:19 UTC, Metadorius requested changes
Great work overall. I'll help you with docs later. Minor stuff left to deal with.

2024-12-10 03:19 UTC, Metadorius commented on src/Commands/ToggleSWSidebar.cpp
> +		MessageListClass::Instance->PrintMessage(GeneralUtils::LoadStringUnlessMissing("TXT_EX_SW_SIDEBAR_DISABLE", L"Super Weapon Sidebar Disabled."), RulesClass::Instance->MessageDelay, HouseClass::Curre
Adding a message seems unneeded to me, I mean the sidebar will appear and you will see the result of the press.

2024-12-10 03:19 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +	const bool unstopable = pSuper->Type->UseChargeDrain && pSuper->ChargeDrainState == ChargeDrainState::Draining && pSWExt->SW_Unstoppable;
typo, `unstoppable` should be written with double `p`

2024-12-10 03:19 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +bool SWButtonClass::LaunchSuper() const
Not necessarily a request, but a question. Is this maybe possible to somehow access the original superweapon icon click function and call it? This would save a lot of reimplementation and will 100% guarantee the same behavior.

2024-12-10 03:19 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +ToggleSWButtonClass::ToggleSWButtonClass(unsigned int id, int x, int y, int width, int height)
I think this belongs in a separate file, same for the `.h` part.

2024-12-10 03:19 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +		VocClass::PlayGlobal(RulesClass::Instance->GUIBuildSound, 0x2000, 1.0);
Is this the correct sound? The same sound which gets when the sidebar tabs are getting clicked?

2024-12-10 03:19 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
> +	enum { Nothing = 0x6925FC };
Maybe it's better to name `DoNothing` instead?

2024-12-10 03:19 UTC, Metadorius commented on src/Misc/PhobosToolTip.cpp
> +			R->EAX(button->Y + 27);
What does the number mean here?

2024-12-10 03:19 UTC, Metadorius commented on src/Phobos.INI.cpp
> +		const int screenHeight = GameOptionsClass::Instance->ScreenHeight - 192;
and here?

2024-12-10 03:19 UTC, Metadorius commented on src/Phobos.INI.cpp
> +			Phobos::UI::ExclusiveSWSidebar_Max = screenHeight / 48;
and here?

2024-12-10 03:19 UTC, Metadorius commented on src/Utilities/AresAddressTable.cpp
Hmm this shouldn't show up here in full. I'll check later

2024-12-10 03:19 UTC, Metadorius commented on src/Phobos.INI.cpp
> +int Phobos::UI::ExclusiveSWSidebar_MaxColumn = INT32_MAX;
I think `MaxColumns` is more correct here.

2024-12-10 04:31 UTC, NetsuNegi commented on docs/User-Interface.md
> +ExclusiveSWSidebar.ToggleShape=     ; filename - including the .shp extension
no reason, just use that
I'll change it to use SHP

2024-12-10 05:02 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +bool SWButtonClass::LaunchSuper() const
see `0x6AAED5`
the activation steps of a sw are not a separate function, at least idk how to implement

2024-12-10 05:13 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +		VocClass::PlayGlobal(RulesClass::Instance->GUIBuildSound, 0x2000, 1.0);
yes, see `6AAEC5`

2024-12-10 05:15 UTC, NetsuNegi commented on src/Phobos.INI.cpp
> +			Phobos::UI::ExclusiveSWSidebar_Max = screenHeight / 48;
48 is height of cameo

2024-12-10 05:26 UTC, NetsuNegi commented on src/Misc/PhobosToolTip.cpp
> +			R->EAX(button->Y + 27);
it's a magic number to align tooltip's top as cameo's

2024-12-10 05:28 UTC, NetsuNegi commented on src/Phobos.INI.cpp
> +		const int screenHeight = GameOptionsClass::Instance->ScreenHeight - 192;
this is because I want to reserve space to prevent overlapping

2024-12-10 11:18 UTC, Metadorius commented on docs/User-Interface.md
> +ExclusiveSWSidebar.ToggleShape=     ; filename - including the .shp extension
aren't PCX more convenient in this case?

2024-12-12 01:20 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +bool SWButtonClass::LaunchSuper() const
I see. I guess your implementation also contains the whatever Ares has done to it too then.

2024-12-12 01:22 UTC, Metadorius commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +		VocClass::PlayGlobal(RulesClass::Instance->GUIBuildSound, 0x2000, 1.0);
`0x6AAEC5` is for when you click at the cameo. This is a ToggleSWButton which hides or shows the sidebar though.

2024-12-12 01:37 UTC, Metadorius commented on src/Misc/PhobosToolTip.cpp
> +			R->EAX(button->Y + 27);
Not sure I understood, but such things should be set as constants either in YRpp classes/namespaces (if it is from vanilla game) or in your classes/namespaces (if it is only relevant to the new code). Same for all other magic numbers.

2024-12-12 04:57 UTC, NetsuNegi commented on docs/User-Interface.md
> +ExclusiveSWSidebar.ToggleShape=     ; filename - including the .shp extension
but other buttons in sidebar and bottombar usually use SHP

2024-12-14 03:26 UTC, NetsuNegi commented
> I see. I guess your implementation also contains the whatever Ares has done to it too then.
 

yes

2024-12-14 03:27 UTC, NetsuNegi commented on src/Ext/Sidebar/SWSidebar/SWButtonClass.cpp
> +bool SWButtonClass::LaunchSuper() const
yes

2024-12-20 01:21 UTC, NetsuNegi commented on src/Misc/PhobosToolTip.cpp
> +			R->EAX(button->Y + 27);
done

2024-12-20 01:24 UTC, NetsuNegi commented
@Metadorius could you review this again ?

2024-12-27 01:08 UTC, NetsuNegi commented
e

2024-12-28 21:05 UTC, Aephiex commented
https://github.com/NetsuNegi/Phobos/pull/7

Hello, merged YRPP for you. The latest YRPP changed something you refered to, namely the function `unknown_11AC`, see https://github.com/Phobos-developers/YRpp/commit/1e9fac90aa646255496138ddde5fef414a6f3528 for details.

2025-01-19 18:17 UTC, Starkku requested changes
There are issues to be fixed.

-  There has been a report of some kind of issue with responsiveness of the superweapon sidebar, it does not react to mouse enter/leave at same speed as regular sidebar.
- I have had a case where the icon at the 'top of the pyramid' (rightmost icon with columns > 1) does not register mouse hover at all.
- Tooltips appear to be drawn twice, as with reduced background opacity they appear more opaque than the other tooltips.
- The adding / sorting order of icons in the superweapon sidebar does not appear to follow any easily discernible rules, at the very least if you constrain the number of columns. The normal sidebar sorts them based on recharge time (from shortest to longest) and by `UIName` in case of a tie. At the very least there needs to be some control over this.
- There has been at least one report of 'Select target' EVA announcement not playing when activating SW from superweapon sidebar but I was not able to reproduce this.

2025-02-15 12:20 UTC, Speederovsky commented
More bugs on the most recent version.

![left-bugs](![left-bugs](https://github.com/user-attachments/assets/aa506edf-cf0d-4401-8a7a-265b0dd420ab))
- The tooltips are weirdly aligned on the left, regardless of whether they're basic or extended tooltips. The anchored tooltips setting does not affect them at all, when it definitely should.
- A more serious issue: if you hover over a SW cameo on the left and see its tooltip, then you use a **hotkey** to close the left sidebar when the tooltip is still visible, once you reopen the left sidebar the tooltip will continue to display until you hover over the cameo again. There is a big chance this will make you unable to place any buildings on the map, launch SWs or use RMB to move the battlefield until you make this incorrectly displayed tooltip go away or close the sidebar again. This happens with basic, extended and anchored tooltips all the same.
- If you browse tooltips on the right while this issue is still "active", tooltips on the right are no longer anchored if you use that feature. They become anchored again once you "fix" the issue.
- If you trigger this issue while moving the battlefield with your mouse cursor (mouse cursor over a cameo on the left), there is a chance weird things will happen with the cursor like getting a 'right direction' cursor on anything on the right sidebar even when you're not moving the battlefield.
- EVA still does not say "Select target" when it should once a SW is chosen. I tested this in SP, skirmish, original and new factions, does not happen for anything that's on the left.

2025-02-22 02:43 UTC, NetsuNegi commented
> There are issues to be fixed.
> 
> * There has been a report of some kind of issue with responsiveness of the superweapon sidebar, it does not react to mouse enter/leave at same speed as regular sidebar.
> * I have had a case where the icon at the 'top of the pyramid' (rightmost icon with columns > 1) does not register mouse hover at all.
> * Tooltips appear to be drawn twice, as with reduced background opacity they appear more opaque than the other tooltips.
> * The adding / sorting order of icons in the superweapon sidebar does not appear to follow any easily discernible rules, at the very least if you constrain the number of columns. The normal sidebar sorts them based on recharge time (from shortest to longest) and by `UIName` in case of a tie. At the very least there needs to be some control over this.
> * There has been at least one report of 'Select target' EVA announcement not playing when activating SW from superweapon sidebar but I was not able to reproduce this.

cameo's order should work fine for now, please test it again

2025-02-22 02:56 UTC, NetsuNegi commented
I added the initialization of EVA, it also should be fixed now.

2025-03-24 15:26 UTC, Speederovsky commented
It seems all issues but #1 from my previous post (anchored tooltips not being anchored properly on the left sidebar if the feature is enabled) have been fixed. Can hear "Select target" EVA report now and can't reproduce any weird glitches involving the tooltips.

The toggle button for hiding the left sidebar moving vertically depending on the number of SWs in it feels quite weird, especially when you close it and see that it is no longer centered/in the original position. I'm not sure how this could be improved though.

2025-05-07 04:48 UTC, CrimRecya approved these changes
The main function is working well.

2025-05-31 15:58 UTC, Speederovsky commented
_Toggle Super Weapon Sidebar_ in hotkeys shouldn't be controlled by the SuperWeaponSidebarKeysEnabled tag. It should just always be available when the exclusive SW sidebar is used, completely separate from the SW launch hotkeys.

2025-06-05 04:49 UTC, CrimRecya approved these changes

2025-06-05 04:55 UTC, merged

2025-09-23 14:45 UTC, Damfoos commented
Sorry for necroposting of sorts, but I don't know where else to ask this. On a scale of "a few tweaks to the code and it'll work" to "fuck no,  easier to build a new engine", how difficult would it be to make players able to customise the contents of SW sidebar in-game? Like this: you right click a SW cameo in the armory tab, it goes into the SW sidebar; you right click a SW cameo in the SW sidebar, it goes back into the armory tab. 

Essentially that'd allow the player to build their own "deck" of SWs in the SW sidebar, to suit their own playstyle. From my experience, a modder might have different idea of what SWs are important enough to put into a separate sidebar than the player does, and being able to customise the set of SWs to suit yourself would go a looooong way