Customize SuperWeapon TabIndex
Phobos-developers/Phobos pull request #1387
Opened 2024-09-19 12:48 UTC by NetsuNegi

- Now you can specific sw will insert to which tab of sidebar.

In `rulesmd.ini`
```ini
[SOMESW]                    ; Super Weapon
TabIndex=1                  ; integer
```

2024-09-20 22:44 UTC, mevitar commented
Is it just me, or does the sidebar icon blinks for ready SWs only when they are on structure and defense tabs?
Does it work for infantry/unit tabs for anyone else, or is there some limitation there?

2024-09-21 01:20 UTC, NetsuNegi commented
> Is it just me, or does the sidebar icon blinks for ready SWs only when they are on structure and defense tabs?
Does it work for infantry/unit tabs for anyone else, or is there some limitation there? 

got it, I'll try to fix it

2024-09-21 01:23 UTC, NetsuNegi commented
> Is it just me, or does the sidebar icon blinks for ready SWs only when they are on structure and defense tabs?
Does it work for infantry/unit tabs for anyone else, or is there some limitation there? 

thank you for your feedback

2024-09-21 03:30 UTC, NetsuNegi commented
> Is it just me, or does the sidebar icon blinks for ready SWs only when they are on structure and defense tabs?
Does it work for infantry/unit tabs for anyone else, or is there some limitation there? 

it should be fixed now, could you test it again?

2024-09-21 11:31 UTC, mevitar commented
Works fine for all 4 sidebar icons now.

2024-09-23 12:58 UTC, MortonPL requested changes
Looks good, but I think that we shouldn't take raw user input in cases where it can be easily validated and fixed.

2024-09-23 12:58 UTC, MortonPL commented on docs/Whats-New.md
> +- Customize superweapon tabindex (by NetsuNegi)
```suggestion
- Assign Super Weapon cameo to any sidebar tab (by NetsuNegi)
```

2024-09-23 12:58 UTC, MortonPL commented on CREDITS.md
> +   - Customize superweapon tabindex
```suggestion
   - Assign Super Weapon cameo to any sidebar tab
```

2024-09-23 12:58 UTC, MortonPL commented on docs/New-or-Enhanced-Logics.md
> +In `rulesmd.ini`
```suggestion
- You can now assign a Super Weapon's cameo to any sidebar tab using `TabIndex`.
  - Valid values are: 0 (buildings tab), 1 (arsenal tab), 2 (infantry tab), 3 (vehicle tab).

In `rulesmd.ini`:
```

2024-09-23 12:58 UTC, MortonPL commented on src/Ext/SWType/Body.cpp
> +	this->TabIndex.Read(exINI, pSection, "TabIndex");
I think that the value should be clamped between 0 and 3, so that the user can't input incorrect indices and crash the game.

2024-09-23 16:39 UTC, Metadorius approved these changes

2024-09-23 16:39 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +TabIndex=1                  ; integer
```suggestion
[SOMESW]    ; Super Weapon
TabIndex=1  ; integer
```

2024-09-23 16:40 UTC, merged