[Bugfix]Fix a bug that infantry get stuck when move too fast
Phobos-developers/Phobos pull request #1388
Opened 2024-09-19 13:07 UTC by NetsuNegi

it is just a bugfix

2024-09-19 13:16 UTC, TaranDahl commented
Mech locomotor also has this bug. Will be great if you can handle it too.
It is at 5B11DD.

2024-09-19 13:17 UTC, NetsuNegi commented
> Mech locomotor also has this bug. Will be great if you can handle it too. It is at 5B11DD.

got it

2024-09-19 13:42 UTC, NetsuNegi commented
> Mech locomotor also has this bug. Will be great if you can handle it too. It is at 5B11DD.

it should be fixed for now.

2024-09-19 22:34 UTC, mevitar commented
Does not glitch anymore whether the units/infantry have a very high speed from the start, or it gets increased and then lowered back.

The actual speed will not be exactly as high as the value indicates, but that's due to how these locomotors work (they force the infantry/unit to pause for a moment when transitioning between cells).

2024-09-20 14:38 UTC, NetsuNegi commented
> Does not glitch anymore whether the units/infantry have a very high speed from the start, or it gets increased and then lowered back.
> 
> The actual speed will not be exactly as high as the value indicates, but that's due to how these locomotors work (they force the infantry/unit to pause for a moment when transitioning between cells).

There is indeed this problem, and it is not clear what methods can be used to optimize it, but at least it is better than before

2024-09-20 15:03 UTC, Metadorius requested changes
Code looks good apart from a few style nitpicks, but it would be cool if you also added a brief explanation in the code comments of what was the issue in the vanilla game and what you did with those hooks to fix it, so in future people will immediately have the idea of what the hooks are for.

2024-09-20 15:03 UTC, Metadorius commented on CREDITS.md
> +   - Fix a bug that some loco (Tunnel,Walk,Mech) get stuck when move too fast
```suggestion
   - Tunnel/Walk/Mech locomotor being stuck when moving too fast bugfix
```

2024-09-20 15:03 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +- Fixed that some loco (Tunnel,Walk,Mech) get stuck when move too fast.
```suggestion
- Fixed some locomotors (Tunnel, Walk, Mech) getting stuck when moving too fast.
```

2024-09-20 15:03 UTC, Metadorius commented on docs/Whats-New.md
> +- Fixed that some loco (Tunnel,Walk,Mech) get stuck when move too fast (by NetsuNegi)
```suggestion
- Fixed some locomotors (Tunnel, Walk, Mech) getting stuck when moving too fast (by NetsuNegi)
```

2024-09-20 15:25 UTC, NetsuNegi commented
> Code looks good apart from a few style nitpicks, but it would be cool if you also added a brief explanation in the code comments of what was the issue in the vanilla game and what you did with those hooks to fix it, so in future people will immediately have the idea of what the hooks are for.

comments has been added

2024-09-20 15:45 UTC, Metadorius approved these changes

2024-09-20 15:45 UTC, Metadorius approved these changes

2024-09-20 15:45 UTC, merged

2024-09-20 21:42 UTC, mevitar commented
> There is indeed this problem, and it is not clear what methods can be used to optimize it, but at least it is better than before
I don't think that's necessarily a problem, i think it might be an intentional design choice there (at least for the walker locomotor).

2024-09-21 01:12 UTC, NetsuNegi commented
> > There is indeed this problem, and it is not clear what methods can be used to optimize it, but at least it is better than before
> 
> I don't think that's necessarily a problem, i think it might be an intentional design choice there (at least for the walker locomotor).

If it is really intentionally designed to avoid displaying defects, then I think a more appropriate approach is to limit current speed of the walk locomotor.

2024-09-21 01:13 UTC, NetsuNegi commented
> > > There is indeed this problem, and it is not clear what methods can be used to optimize it, but at least it is better than before
> > 
> > 
> > I don't think that's necessarily a problem, i think it might be an intentional design choice there (at least for the walker locomotor).
> 
> If it is really intentionally designed to avoid logic defects, then I think a more appropriate approach is to limit current speed of the walk locomotor.

2024-09-21 11:21 UTC, mevitar commented
I mean the pausing before moving to a new cell for walker locomotor might be intentional design choice by WestWood to simulate walker wobbling effect. Not the best way to do it, but it would make sense. I think better not to change that (people can use a different locomotor if they don't want the wobbling).

Locomotors breaking on higher speed is definitely a bug (or result of laziness), though.

2024-09-21 11:28 UTC, NetsuNegi commented
> I mean the pausing before moving to a new cell for walker locomotor might be intentional design choice by WestWood to simulate walker wobbling effect. Not the best way to do it, but it would make sense. I think better not to change that (people can use a different locomotor if they don't want the wobbling).
> 
> Locomotors breaking on higher speed is definitely a bug (or result of laziness), though.

Okay, I understand what you mean