[Simple Fix] Select Friendly Units that have been Cloaked
Phobos-developers/Phobos pull request #1389
Opened 2024-09-21 07:22 UTC by a851903106

Phobos allow the player to observe friendly units that have been cloaked, but they cannot be selected unless a unit with Sensors=yes is present nearby.
![bug](https://github.com/user-attachments/assets/94006472-4daf-41aa-858a-202e85fb866e)

So I made a short fix to select units with Sensors=yes even if they don't exist nearby.
![fix](https://github.com/user-attachments/assets/09d068fc-72cc-483e-878d-7d98ee37328b)

2024-09-23 12:32 UTC, MortonPL requested changes
Looks good. I've run it and it looks like it also fixes a campaign bug with multiple player houses and uncontrollable stealth units.

From modified all01md.map:
![image](https://github.com/user-attachments/assets/c5141211-5762-455c-a49d-850ee597122a)

Remember to add an entry in `docs/Whats-New.md`, `CREDITS.md` and `docs/Fixed-or-Improved-Logics.md` (bugfixes section). Once that's done, this PR can be merged.

2024-09-23 12:32 UTC, MortonPL commented on src/Ext/Techno/Hooks.Cloak.cpp
> +	enum { SkipGameCode = 0x6F4F3A, Continue = 0x6F4F21 };
Remove `Continue = 0x6F4F21` if it's not used.

2024-09-23 13:21 UTC, chaserli commented
Partially already implemented, partially in another PR 

https://github.com/CnCNet/yrpp-spawner/pull/20
https://github.com/CnCNet/yrpp-spawner/blob/main/src/Misc/Observers.Visibility.cpp

2024-09-23 14:24 UTC, MortonPL approved these changes

2024-09-29 22:13 UTC, Metadorius commented
So uhh what are we doing with this one?

2025-03-03 04:14 UTC, closed without merging