use SW deferment on Phobos logic
Phobos-developers/Phobos pull request #1412
Opened 2024-10-25 02:43 UTC by Coronia

Previously several Phobos super weapon launching logic (e.g. `SW.Next` and `LaunchSW`) didn't support `SW.Deferment`. This pull request implements a workaround to enable this. `UseDeferment` tags delay the launch by a certain amount of frames determined by the superweapon's `SW.Deferment` if set to true, while `ExtraDeferment` tags add an extra value to this delay.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]                     ; Warhead
LaunchSW.UseDeferment=false       ; boolean
LaunchSW.ExtraDeferment=0         ; integer

[SOMESW]                        ; Super Weapon
SW.Next.UseDeferment=false      ; boolean
SW.Next.ExtraDeferment=0        ; integer

[SOMEBUILDING]                                        ; BuildingType
SpyEffect.VictimSuperWeapon.UseDeferment=false        ; boolean
SpyEffect.VictimSuperWeapon.ExtraDeferment=0          ; integer
SpyEffect.InfiltratorSuperWeapon.UseDeferment=false   ; boolean
SpyEffect.InfiltratorSuperWeapon.ExtraDeferment=0     ; integer
```

2024-10-27 09:51 UTC, chaserli requested changes

2024-10-27 09:51 UTC, chaserli commented on src/Ext/SWType/FireSuperWeapon.cpp
> +							pSuper->SetReadiness(true);
I think you can remove all in-place sw launches, and do that in your global launchsw state machines

2024-10-27 09:51 UTC, chaserli commented on src/Ext/Scenario/Body.h
> +class SWFireTypeClass
The name is inappropriate, it's something like ares' sw state machines and shouldn't be named like xxTypeClass

2024-10-27 09:51 UTC, chaserli commented on src/Ext/WarheadType/Body.cpp
> +	this->LaunchSW_UseDeferment.Read(exINI, pSection, "LaunchSW.UseDeferment");
Not sure if such an additional xx.UseDeferment is necessary, deferment should have been respected and it was an oversight that I wasn't aware of back then.

2024-10-27 09:51 UTC, chaserli commented on src/Ext/Scenario/Body.h
> +		std::vector<std::unique_ptr<SWFireTypeClass>> DefermentSWs;
do you have any practical reason using a vector of unique_ptr rather than a vector of instances?

2024-10-28 03:35 UTC, Coronia commented on src/Ext/Scenario/Body.h
> +		std::vector<std::unique_ptr<SWFireTypeClass>> DefermentSWs;
It's mostly for the convenience of constructing and destructing. Could change it to an instance if needed

2024-10-28 03:38 UTC, Coronia commented on src/Ext/WarheadType/Body.cpp
> +	this->LaunchSW_UseDeferment.Read(exINI, pSection, "LaunchSW.UseDeferment");
I'm doing it with the assumption that someone already used what it was for their mods, while adjusting it directly might break those stuffs. So this is made into an optional thing.

2024-10-28 03:43 UTC, Coronia commented on src/Ext/SWType/FireSuperWeapon.cpp
> +							pSuper->SetReadiness(true);
I'm not sure if making them all in the vector that being checked every frame is a good idea, might cost extra performance tax and make the SW unwantedly delay 1 frame sometime

2024-10-28 03:55 UTC, NetsuNegi commented
Have you test deferment at SW.Next? I had tried it and it cause desync by unknown reseaon.

2024-10-28 04:06 UTC, Coronia commented
Not really, only tested it in singleplayer so far. I do suspect changing SW timer tends to desync the game, but in that case there might also be similar problems with the original implementation of not-RealLaunch.

I'll be appreciated if someone could do some more multiplayer testing on it.

2024-10-28 08:41 UTC, chaserli commented on src/Ext/Scenario/Body.h
> +		std::vector<std::unique_ptr<SWFireTypeClass>> DefermentSWs;
which is also the reason why you don't need it in a vector. so far you don't have pimpl, inheritance or something else, there's no extra benefit but some minor runtime overhead

2024-10-28 08:41 UTC, chaserli commented on src/Ext/SWType/FireSuperWeapon.cpp
> +							pSuper->SetReadiness(true);
you already checked this vector as well as the ReloadInTransport/AutoDeath ones on a per-frame basis, and they are most of the time empty.
You can investigate whether the updates of these vectors should happen before logics' (in your case bullets' and houses') or after. won't hurt to move the order.

2024-10-29 02:48 UTC, Coronia commented
Addressed the instance and global launch changes suggested above

Also we've done some multiplayer testing on it yesterday, and no desync so far

2024-11-04 06:52 UTC, chaserli commented on src/Ext/WarheadType/Body.cpp
> +	this->LaunchSW_UseDeferment.Read(exINI, pSection, "LaunchSW.UseDeferment");
No I mean have you looked into how deferment works now? I don't think the underlying logic was ever changed since 0.A. Those 4 SWTypes that support SW.Deferment still use the old launch chain. 
In this context xx.UseDeferment as well as your additional parsing of SW.Deferment are unnecessary.
Mind if I ask which swtypes you want to use exactly?

2024-11-04 06:52 UTC, chaserli commented on src/Ext/Scenario/Body.h
> +	int oldleft;
```suggestion
class PendingSW
{
public:
	SuperClass* SW;
	CDTimerClass Deferment;
	CellStruct Cell;
	bool ForReal;
```
It notes which sw to launch later so nothing should be done in ctor. You reset the sw and swap the timer more once.

2024-11-11 07:37 UTC, Coronia commented
It's confirmed that those SWs which supporting Deferment in Ares also work in Phobos. Therefore I'd like to close it for now since I don't want to add extra complexity and performance tax (this logic is checked per frame). But if there's a need to make Deferment support more SWs please let me know.

2024-11-11 07:37 UTC, closed without merging