Distribution click action mode
Phobos-developers/Phobos pull request #1453
Opened 2024-12-15 17:51 UTC by CrimRecya

`[ ]` Distribution Mode Spread / Filter
- Change the click action.
  - When the range is 0, it is the original default behavior of the game. The range can be adjusted to 4, 8 or 16 cells by shortcut keys.
    - The targets within the range will be allocated equally to the selected technos. Only when the behavior to be performed by the current techno is the same as that displayed by the mouse will it be allocated. Otherwise, it will return to the original default behavior of the game (it will not be effective for technos in the air)
  - When the filter is `None`, it is the default behavior of the game. You can adjust the filter mode to:
    - `Auto` - if the behavior to be executed by the current techno is different from the behavior displayed by the mouse, and the behavior to be executed will make the techno move near the target, the behavior will be replaced with area guard.
    - `Type` - on the basis of `Auto`, only targets of the same type (like infantries, vehicles or buildings) will be selected among the targets allocated in the range.
    - `Name` - on the basis of `Type`, only targets of the same name (or with the same `GroupAs`) will be selected among the targets allocated in the range.
- For localization add `TXT_DISTR_SPREAD`, `TXT_DISTR_FILTER`, `TXT_DISTR_SPREAD_DESC` and `TXT_DISTR_FILTER_DESC` into your `.csf` file.

https://github.com/user-attachments/assets/6f343fef-3003-408f-8703-2f2ff22dc072

2024-12-16 06:53 UTC, TaranDahl approved these changes
lgtm

2024-12-16 07:17 UTC, CrimRecya commented
In theory, it should work normally under the condition of multiple people, but I haven't tested it yet. It would be great if it could work as expected.
In addition, as for the display of the current mode, the scheme has not been finalized yet. At present, I want it to be displayed directly at the mouse position, such as the display range of SW, instead of using print message like in video. If anyone has any good ideas, PLEASE comment.

2025-02-10 12:05 UTC, TaranDahl commented
Tested locally. Doing good.

2025-02-10 14:25 UTC, TaranDahl commented
> I am hesitant on how to deal with this feature. It removes a huge amount of microcontrol from the game, essentially automating half of whatever required skill before and now just requires a mouse click.-----------谷歌翻译-----------我对如何处理此功能感到犹豫。它从游戏中删除了大量的微控制，从本质上讲是在此之前所需的任何技能的一半，现在只需单击鼠标即可。

I think all you want is a toggle?

2025-02-10 14:35 UTC, Metadorius commented
I would say that if we will merge it, a toggle is a must, because the whole existence of such a hotkey alters gameplay significantly, removing a huge amount of microcontrol requireemtn.

The bigger question is where do we draw the line on what should be included in mainline Phobos and what not? In other words, what is the scope of the project?

This is an exaggeration, but just to show the point that I am trying to make -- imagine suddenly a pull request appears that is intended specifically to turn YR into a whole different genre of game (say, a visual novel with no RTS stuff at all) and is not usable for purposes of regular RTS players or modders. Should we merge it at all? I don't think we should, it is, as we say, out of scope.

The main question is where do we draw the line between such features that are out of scope and the features that should be merged and are in the scope? And what potential drawbacks are there if we merge it?

2025-02-10 16:02 UTC, TaranDahl commented
> The main question is where do we draw the line between such features that are out of scope and the features that should be merged and are in the scope?

Personally, I came to Phobos because everyone knows Phobos. If I get something done here, then people will know it's done and other people don't need to spend time on what I've already done. I think it is meaningful.
So for me, as long as I think this feature is likely to be used by others, then it is not out of scope.

> And what potential drawbacks are there if we merge it?

Negligible performance impact.
Careless devs can introduce issues that can cause crashes even if features are not enabled.

2025-02-10 18:29 UTC, Metadorius commented
> as for the display of the current mode, the scheme has not been finalized yet. At present, I want it to be displayed directly at the mouse position, such as the display range of SW, instead of using print message like in video. If anyone has any good ideas, PLEASE comment.

I have an idea.

First, the radius can be controlled not via hotkeys, but with a mouse. How that would work? You press a hotkey to activate distribution mode, and when you press right mouse button on the target and drag your mouse without releasing the mouse button - it displays the circle and changes the radius depending on how far you drag the cursor, so you regulate the radius with the mouse drag. Then when you release the mouse - the orders are given to every selected unit. You do that each time and effectively draw circles to give orders.

This is inspired by Call to Arms: Gates of Hell game. There you can spread your infantry among covers this way, click behind covers and drag to spread people better.

2025-02-10 18:37 UTC, CrimRecya commented
> I would say that if we will merge it, a toggle is a must, because the whole existence of such a hotkey alters gameplay significantly, removing a huge amount of microcontrol requireemtn.

Yes, I think we still need a toggle to enable this feature, not just defining buttons. I will add later.

> The bigger question is where do we draw the line on what should be included in mainline Phobos and what not? In other words, what is the scope of the project?

Personally, if someone (whether they are modders or task package authors) needs a certain feature and I happen to be interested in it, I will try to do it. Whether to merge or not is actually related to whether more people will use it. But no matter what, these features will only be pushed if there is a demand.

> This is an exaggeration, but just to show the point that I am trying to make -- imagine suddenly a pull request appears that is intended specifically to turn YR into a whole different genre of game (say, a visual novel with no RTS stuff at all) and is not usable for purposes of regular RTS players or modders. Should we merge it at all? I don't think we should, it is, as we say, out of scope.

If it is assessed that this should not be merged, then I will close it.

> The main question is where do we draw the line between such features that are out of scope and the features that should be merged and are in the scope? And what potential drawbacks are there if we merge it?

As TaranDahl said, for example, if this feature does not have any impact on performance and can be disabled (assuming I have already added the switch), then I think it can be merged.

2025-02-10 18:46 UTC, CrimRecya commented
The opening video is based on the initial design, which is now outdated. I will share another one when I have time.

2025-02-20 15:05 UTC, CrimRecya commented
> > but I'd prefer it to be another optional manifestation of this feature.
> 
> Do you mean toggle between hotkey radius selection and mouse adjustment? I am not sure if the hotkey radius selection is intuitive enough to be left in.
> 
> Compare "a single long enough drag to give and customize the order" against "toggle a hotkey or multiple, give an order, toggle hotkeys again". It is also far more intuitive to adjust the radius with a mouse, just like you do in a 2D or 3D graphics editor when you create a circle or, say, a cylinder, and change the size with a mouse. Hotkey doesn't have immediate visual feedback, you have to read the number and translate it into a circle in your mind, or, alternatively, you'll have a constantly floating circle around, and a toggle to enable/disable the feature altogether. If you implement it like I suggested - there will be much less friction for the user.

I currently have a new solution that uses a mouse wheel to assist. Still testing and waiting for feedback.

2025-02-20 15:10 UTC, Metadorius commented
> I currently have a new solution that uses the mouse wheel to assist. Still testing and waiting for feedback.

Sounds like an interesting option, is that what you mentioned earlier?

2025-02-20 15:11 UTC, DeathFishAtEase commented
> Do you mean toggle between hotkey radius selection and mouse adjustment? I am not sure if the hotkey radius selection is intuitive enough to be left in.

不，我认为它们都应当是可选的，它们的具体效果都非常有趣，它们也同样会有人希望使用，所以只要给足 mod 创作者是否使用这个效果的自由，再确保它们不会拖累 FPS，那么它们就是可以保留的。

---
No, I mean they should all be optional.
Their specific effects are very interesting, and there are also always have people who would want to use them.
So as long as **mod creators are given the freedom to choose** whether to use these effects and ensure that they don't drag down the FPS, then they can be kept.

2025-02-20 15:15 UTC, CrimRecya commented
> Sounds like an interesting option, is that what you mentioned earlier?

Yes, it's based on #1522 .

2025-02-20 15:21 UTC, DeathFishAtEase commented
> This is an exaggeration, but just to show the point that I am trying to make -- imagine suddenly a pull request appears that is intended specifically to turn YR into a whole different genre of game (say, a visual novel with no RTS stuff at all) and is not usable for purposes of regular RTS players or modders. Should we merge it at all? I don't think we should, it is, as we say, out of scope.

Have you heard of *TS: Another World*? It is a YR MOD that is set in the world of TS, retains RTS elements, and **features visual novel-style missions**. We might not need to focus on requirements that may deviate from RTS content, but if someone provides a feature, accepting it with the option to disable it is not an issue.

---
> 这有点夸张，但只是为了说明我想要表达的一点——想象一下突然出现一个拉取请求，它专门用于将 YR 变成一个完全不同类型的游戏（比如，一部根本没有 RTS 内容的视觉小说），并且不适用于普通 RTS 玩家或 Mod 作者。我们应该合并它吗？我认为我们不应该这样做，正如我们所说，这超出了范围。

你听说过《TS:AnotherWorld》吗，它是一个以TS为世界背景、保留RTS内容，任务内容属于视觉小说的YR MOD。我们或许不必要将可能有些偏离 RTS 内容的需求作为重点，但如果有人提供了功能那么在允许关闭的情况下接收它并不是什么问题。

2025-02-20 15:34 UTC, Metadorius commented
Well, after a bit of thinking and input from you all I think that if we gate it behind a toggle - it's fine. The feature is isolated and doesn't make a big impact neither at modders, nor at users, nor at developers if it's off. Of course, it's a maintenance cost, but hopefully there won't be much problems with it.

2025-02-20 15:38 UTC, Metadorius commented
![GIF 20 02 2025 17-23-00](https://github.com/user-attachments/assets/8a3c0c7f-f5ac-42ed-9f15-31612ebb2567)

Another example for the approach I suggested. This GIF is a recording of an RTS game Zero-K, based on Spring RTS engine. It has one of the best in class user interface feature, they make playing the game a delight. You can draw paths or areas with the mouse and it's all very intuitive. I recommend you to give a look and maybe even try it.
Can be downloaded for free on [Steam](https://store.steampowered.com/app/334920/ZeroK) or without it from the [official site](https://zero-k.info/).

2025-02-20 15:40 UTC, Metadorius commented
(If someone is not familiar with Supreme Commander/Total Annihilation style gameplay: the GIF shows designating metal extractors to be built at all spots that are available in the area designated by drag and click.)

2025-02-20 15:43 UTC, DeathFishAtEase commented
Personally, I might prefer to use two separate clicks to determine the center and radius (the second click on a point on the arc) rather than long-pressing and dragging, unless it's for weapons like bows in a first-person perspective that require a special feel :P

2025-03-26 04:12 UTC, Coronia commented
think this is a better user interaction approach than https://github.com/Phobos-developers/Phobos/pull/1452, which is using mouse click to trigger the following command. The other one has the drawbacks of 1) having to select both passengers and transport then uses hotkey, which is kinda against players' habit 2) the hotkey setting visible issue in https://github.com/Phobos-developers/Phobos/issues/1496

However, Autoload shortcut PR has the advantage of calculating whether a passenger should get into a transport more accurately. If we're thinking a way to unify these 2 PRs, I would suggest use Distribution click as a base, while adding some passenger picking logic from Autoload shortcut

2025-03-26 08:50 UTC, Coronia commented
one thing I'm concerning is whether `DefaultDistributionFilterMode` should be allowed to customize by Players, since it requires much learning cost. The filter rule is fairly complicated to Players who don't know about ini, and there's no place to explain it clearly in game, so they might not be able to tell what these modes are exactly doing, which could result in confusion and misclick. Meanwhile, the current interaction is 'click a hotkey and rotate between 4 modes', which is also kinda unintuitive since Players can only know what they're currently selected by the color of ring, which again couldn't be explained to Players well. While `DefaultDistributionSpreadMode` uses the same method, the difference of ring size is at least self-explanatory

IMO `DefaultDistributionFilterMode` should be a [General] thing that's controlled by rules, while `DefaultDistributionSpreadMode` could only use mouse wheel to control its size, no need to add more hotkeys here other than the one to enable distribution mode

2025-03-26 09:02 UTC, CrimRecya commented
> The opening video is based on the initial design, which is now outdated. I will share another one when I have time.

A late video.

https://github.com/user-attachments/assets/e2e3b5f3-f472-43ac-96be-4e42a40df2a6

2025-03-26 09:15 UTC, CrimRecya commented
> think this is a better user interaction approach than #1452, which is using mouse click to trigger the following command. The other one has the drawbacks of 1) having to select both passengers and transport then uses hotkey, which is kinda against players' habit 2) the hotkey setting visible issue in #1496

The visible issue was solved a long time ago.

> However, Autoload shortcut PR has the advantage of calculating whether a passenger should get into a transport more accurately. If we're thinking a way to unify these 2 PRs, I would suggest use Distribution click as a base, while adding some passenger picking logic from Autoload shortcut

I don't plan to do that at the moment, that's a specially designed feature.

> IMO DefaultDistributionFilterMode should be a [General] thing that's controlled by rules, while DefaultDistributionSpreadMode could only use mouse wheel to control its size, no need to add more hotkeys here other than the one to enable distribution mode

I think this is a very simple classification method. Players only need a little time and try using it a few times, and they can clearly understand the difference between them. The display of different colors may seem hasty, but I don't think it's a reason to prevent players from freely choosing.

2025-07-22 16:26 UTC, Metadorius requested changes
I consulted with @ZivDero and we agree that currently the feature is good in the concept but rather clunky to use in details. I haven't had the chance to review the code just yet, so pardon if I repeat something  that is already implemented

1. Different modes and customisations like whether to affect allies seem to be an overcomplication. What I think has to be done and that is more intuitive is replicating the mouse cursor action over all eligible targets in the range.

   I imagine the following algorithm:
   1) get currently shown action on the cursor (like attack, enter, capture) (What_Action/MouseOverObject/MouseOverCell call)
   2) use this to enumerate all eligible targets in the circle (so, enter would enumerate all enterable buildings, capture would enumerate all capturable buildings, repair would enumerate all repairable buildings, attack -- all enemies that are legit for attack like the vanilla cursor, move/guard/attack move -- units get random destinations to unblocked cells in the circle, force attack civilians -- all civilians in the circle, heal allies -- all allies in the circle, etc etc etc)
   3) uniformly randomly and non-repetitively assign each individual target, simulating a mouse click on every unit or cell. Non-repetitively means that unless there are more units than targets -- no target should get 2 or more units assigned to it; if there are -- just repeat the process until there are no unassigned units left.
   
   So, to recap, this essentially means that we use the cursor to pick eligible targets, and then simulate mouse click (without voice) for each separate unit from our selection to a randomly chosen not-yet-clicked target. I've did this in TA branch here: https://github.com/Phobos-developers/Phobos/pull/352/files#diff-9698616732fcbee5d98549d09c43f973aa6e3c3a2bba245f1a2427c9972894f2R492-R549
   
2. The hotkeys and the circle control could be brought in-line with existing implementations:
   - I would still advocate that it would be more useful to have the user specify radius with mouse drag, like on the image I've shown. There are multiple RTS and RTT games that use drag-distribution or drag-positioning (Zero-K, Beyond All Reason, Gates of Hell, IIRC C&C3 also uses drag-select; Total War uses drag for spreading units), so it won't be unnatural.
   - The hotkey could work like `[Z] Waypoint mode`: hold to enter it and then dragging with something selected would produce a circle.
   - That being said, I don't object for optionally (user togglable) using mouse wheel to select the circle radius as alternative option. However, I am not sure on the exact implementation.
   
3. Maybe an extra, but it would be extra cool to show the targets which are going to be affected in the circle by highlighting it with a white-ish color, the same flash as the target flash. It would be highlighted like the target flashing when you press on it, but not flash until you release it. This would immediately tell the player what is considered a target.
   - For "move" or "guard" command showing specific unit positions as faint silhouttes for the units would be cherry on top, but I realise this is a big workload, so it should be left for later. Just something to keep in mind. I know AutoGavy has such implemented for his formations in Tiberium Crisis, maybe he could share the code for that later.

2025-07-23 03:37 UTC, Coronia commented
The affect allies/enemies setting is needed cuz there's indeed a demand that some people would only like to use it for auto loading instead of auto targeting, since the latter one might break existing stuffs.

I can agree that extra options for Spread Mode and Filter Mode can be confusing and unfriendly to players, hence the other toggles are made to disable it. Not sure if directly removing them would be a good idea tho, also the scroll of Spread Mode is fine and intuitive as I illustrated above so this one could be kept at least.

Other settings are mostly worked like what you've proposed already, except the 'selection flash' thing.

2025-07-23 10:09 UTC, Metadorius commented
> since the latter one might break existing stuffs.

like what?

2025-07-23 11:01 UTC, Metadorius commented
> also the scroll of Spread Mode is fine and intuitive as I illustrated above so this one could be kept at least.

Yeah I don't mind it being an option instead of "drag" mode, and I agree it is intuitive too. But I think while both modes are convenient to use, that "press and drag to specify radius" behavior should be the default, because from my observation it is far more common in RTS/RTT games (wouldn't mind to hear any examples of games where scroll is used like this). Also, while niche, some people may play on laptop and click-drag is much easier to execute on a trackpad.

2025-07-23 11:02 UTC, Metadorius commented
> by highlighting it with a white-ish color, the same flash as the target flash

Typo, I meant just highlight before releasing, not flash specifically.

2025-07-23 19:42 UTC, Metadorius commented
Hmm. I've re-read the modes and I am not quite sure if they are too much automation? It seems to remove the microcontrol aspect. One of the skills in the game is able to micro units in the battle so that specific targets are picked. Those modes may detract from this. So if you still think they are needed -- I think the special modes should be gated behind a switch, depending on whether the modder wants to give easy micro possibilities to players.

I've also thought about the modes a bit and I think that it would make sense to rework them a bit.


> * `Auto` - if the behavior to be executed by the current techno is different from the behavior displayed by the mouse, and the behavior to be executed will make the techno move near the target, the behavior will be replaced with area guard. At this time, a blue ring will be displayed.

I think this should not be a part of distribution mode but instead a general fix to mouse clicks. Regardless of the distribution mode, it's not nice for example to select infantry, accidentally also select a tank and order everyone to garrison some neutral structure, only for the tank to destroy the building. Or have an engineer capture the building you attack accidentally.

"Fallback" behavior could be defined globally and per-techno-type, for example, something like `[SOMETECHNO]->GroupMouseClickFallbackBehavior=Default/Move/AreaGuard/AttackMove/AreaGuard/Idle`. Needs further thought though.

The rest of the modes could be called not mode but filter level. Think of the following:
- `None` - just like I described in the previous post, I guess similar to yours.
- `Similar` - additionally use ArmorType when targeting. I am not sure whether "all vehicles" or "all infantry" or "all buildings" is good for this one, because they could have different armor, and are more technical than ArmorType.
- `Same` - same type or GroupAs only, just like you described.

I guess could use green/yellow/red to be in-line with ConditionYellow and ConditionRed, but I am not sure on the colors. Not sure on what could be the best UI for the hotkeys here, but having this as "level" could mean there would be "make filter more specific" and "make filter less specific" hotkeys.

2025-07-24 04:37 UTC, CrimRecya commented
> I guess could use green/yellow/red to be in-line with ConditionYellow and ConditionRed, but I am not sure on the colors. Not sure on what could be the best UI for the hotkeys here, but having this as "level" could mean there would be "make filter more specific" and "make filter less specific" hotkeys.

At present, the filter mode uses a single hotkey cycle switching modes. Replacing with two hotkeys is indeed more straightforward. But I think it may not be very convenient to operate.
There are not many modes available for filtering now, and a single hotkey should be sufficient. In addition, I have received feedback from players that too many hotkeys are not conducive to operation, especially when the keys on the left-hand side of the keyboard are already heavily occupied.
So I don't quite agree with the suggestion of splitting it into two hotkeys.

2025-07-24 04:39 UTC, CrimRecya commented
> Typo, I meant just highlight before releasing, not flash specifically.

Are you referring to making the targets in the area brighter when pressing the 'drag range' hotkey?

2025-07-24 09:53 UTC, Metadorius commented
> There are not many modes available for filtering now, and a single hotkey should be sufficient. In addition, I have received feedback from players that too many hotkeys are not conducive to operation, especially when the keys on the left-hand side of the keyboard are already heavily occupied.
> So I don't quite agree with the suggestion of splitting it into two hotkeys.

Yeah, sounds fair. It was only a thought. I initially thought that maybe having mouse wheel or +/- keys would be intuitive, but one hotkey works too I guess.

> Are you referring to making the targets in the area brighter when pressing the 'drag range' hotkey?

Yes, just to show what targets will be affected.

As for highlighting for move action distribution with silhouettes (the one I mentioned as present in Tiberium Crisis) -- @ZivDero pointed out that there is also a problem of displaying them in the correct facing, so I don't think that's needed for now at all due to complexity.

2025-08-06 13:46 UTC, CrimRecya commented
I haven't thought of any good methods for dragging and flashing for now. I will consider it later.

2025-08-06 13:50 UTC, Metadorius commented
> * `Similar` - additionally use ArmorType when targeting. I am not sure whether "all vehicles" or "all infantry" or "all buildings" is good for this one, because they could have different armor, and are more technical than ArmorType.
> * `Same` - same type or GroupAs only, just like you described.

Randomly recalled one thing: disguise/faking should also be considered when checking this (think Libra clones), otherwise it would be easy to discern copies from the real deal.

2025-08-26 23:45 UTC, Metadorius commented
Same should be done to disguised units I think

2025-08-27 03:17 UTC, CrimRecya commented
> Same should be done to disguised units I think

The mouse behavior on disguised units will be different, so there is no need for special adaptation

2025-08-27 03:28 UTC, CrimRecya commented
TODO:
- More flexible range adjustment
- Drag mouse to adjust the range
- Target highlight within the range

2025-08-27 18:32 UTC, Metadorius commented
> > Same should be done to disguised units I think
> 
> The mouse behavior on disguised units will be different, so there is no need for special adaptation

But won't that mean you could easily check who that is? like imagine a conscript-disguised spy infiltrating the army, you just take a unit that affects friendlies, drag and see that it's not highlighted.

If the highlighting is complicated at the time, maybe we could leave it to another PR? It is an extra clarity for the player, but I think the feature is usable without it.

2025-08-28 04:52 UTC, CrimRecya commented
> But won't that mean you could easily check who that is? like imagine a conscript-disguised spy infiltrating the army, you just take a unit that affects friendlies, drag and see that it's not highlighted.

I was thought about the mirage Tank.
If it's a spy, it won't be considered as a target. I think there's no problem with the action, because it cannot be selected by the box, and moving the mouse over it will result in an attack cursor. And highlight display is another thing.

> If the highlighting is complicated at the time, maybe we could leave it to another PR? It is an extra clarity for the player, but I think the feature is usable without it.

I think it's possible, then I'll leave comments in the code later.

2025-10-18 13:49 UTC, Coronia approved these changes
as per discussed with CrimRecya, it already has most of the feature done, and the requested things can be added without needing to alter the existing stuffs. Better merge this first and do further tweak if needed

2025-10-29 14:06 UTC, merged

2025-10-29 14:30 UTC, Metadorius commented
Why was this merged? This is a T2 request, and no T2 maintainer gave approval or even reviewed the code. My feedback wasn't addressed in full and I haven't expressed any agreement with dismissing it.

2025-10-29 14:50 UTC, DeathFishAtEase commented
Since this PR is labeled as `T2 maintainer review` is sufficient, it is indeed better for another T2 maintainer to review the code first and confirm approval. Especially it was previously in the Request changed state. Especially it was previously in the Request changed state.

2025-10-30 02:17 UTC, Coronia commented
I think I've already written part of my reasons above, but to be clarified I'd like to list it one more time:
- main reason is that I don't think all things need to be done in one PR, but can be gradually implemented pieces by pieces. Otherwise, it'll either take more time to implement, review and test, but also have more risk to become the 'big bad PR' we don't want
- follow that, I've checked the current codes and review records and confirmed that there's no word related to the implementation itself. What @Metadorius suggested was all about adding more features, which @CrimRecya has confirmed that it can be compatible with current design
- Crim also stated the same idea: this batch could be merged first and had more features added in the future (and he has also consulted you for that). And given he might not have time for it, others can help with these features once it's been merged, like I'll try to finish some of the things that's been mentioned above in https://github.com/Phobos-developers/Phobos/pull/1935
- and on top of that, this PR has gone through many test already in both single and multiplayer, so its correctness and stability can be ensured. And since it's a standalone feature that needs enabling and not interfering others, it won't pose any issue to other things ingame either

To sum up, I think it would be better to not let PR stay in the fridge for too long (this one has been almost a year). As long as its tag design is extendible, being test sufficiently and not affecting existing things if not enabled, it could be merged first and maintained further in the future with more than one people's efforts (which is also my opinion towards the New Trajectory PR, if you've read it)

I do apologize for merging it without a T2 review tho and wouldn't do it next time, but please take my word into consideration cuz I think it's the better way for Phobos

2025-10-30 09:38 UTC, ZivDero commented
@Coronia CC @CrimRecya 

You seem to misunderstand how collaborative projects work. If a senior team member (let alone, project lead) tells you that a change *has* to happen, is *necessary*, or a PR is otherwise unfitting, then it *has* to happen. What you do *not* do is go around their back and force whatever *you* think is right into the project. If you think that your counterpart is mistaken, you can try to convince them, but ultimately it is their decision as to what happens and what doesn't happen.

I understand your concerns regarding potentially long feature development times. However, it is the feature author's burden to develop the feature, request reviews and address any concerns in a timely manner. While there are not many T2 maintainers, I don't believe you have exhausted all opportunities to get a review.

That said, what happened is absolutely unacceptable and you've clearly overstepped your boundaries. Everyone pushes features they are interested in, and that is normal, but forcing the issue beyond your permissions without upper management's consent is a breach of trust.

2025-10-30 10:28 UTC, Metadorius commented
Treat the majority of what @ZivDero has written above as my words too.

@CrimRecya @Coronia 

> (which is also my opinion towards the New Trajectory PR, if you've read it)

Talking about new trajectories PR. Seeing the difficulties with acceptance of our feedback, both me and @ZivDero were trying a diplomatic approach in how to convey it as a friendly way of resolving the issue. I stopped responding because I felt bad about the conflict and didn't have the energy at the time to continue swallowing disregard for the sake of smooth resolution of the issue.

We thought that the authority of myself, @Starkku and @ZivDero, as well as other maintainers together, is at least somewhat clear, and that it does not need to be brought to the conversation, but first your responses with borderline disrespectful comments about "losing patience", "wasting time" and now what happened here yesterday (and especially that) suggests that no, I should have been direct and explicit without diplomatic niceties, so let me state it clearly now.

You __do not__ have the right to dismiss the unresolved critical feedback of other maintainers of equal or higher status, or endlessly argue about it without resolution, wasting *their* time and patience. Yes, this is a community project, but we still have an organizational structure, and being a community project doesn't grant you automatic rights to dismiss feedback, *especially* feedback about core architectural issues, like Starkku's feedback about trajectories (especially considering he's *the* most experienced Phobos maintainer), or decide on your own what's best for Phobos and for specific PRs.

2025-10-30 12:12 UTC, TaranDahl commented
我想说，问题的根源在于Phobos的pr审核效率仍然低下得令人发指。他们说 "losing patience" "wasting time" 不是不尊重你，他们只是在陈述事实，因为事实就是你们在轨迹PR上花费了太多的时间。
pr审核效率低下得根本原因在于我们的项目缺少明确的、能在确定的时间内结束的pr审核流程。
当一个新的pr出现的时候，谁来审核？谁来测试？不知道，谁爱来谁来。这个pr可能我感兴趣那我来，下个pr可能Recya感兴趣那Recya来，但如果没人感兴趣怎么办？那你就等吧，一等一个不吱声，冰箱里最早的pr是2021年，如果算上之前因为没有继续维护而被关闭的那还要更早。
既然Phobos是一个社区项目，接受社区提供的pr，那就得有一个确定性的pr处置流程，不能全靠维护者自发地审核。
I want to say that the root of the problem lies in Phobos' PR review efficiency, which is still shockingly low. They say 'losing patience' and 'washing time' is not disrespectful to you, they are just stating the fact that you have spent too much time on trajectory PR.
The fundamental reason for the low efficiency of PR review is that our project lacks a clear PR review process that can be completed within a certain time frame.
Who will review a new PR when it appears? Who will test it? No one knows, who loves who comes. If I am interested in this PR, then I will do it. If Recya is interested in the next PR, then Recya will do it. But what if no one is interested? Then you can go and wait, with no ending time. The earliest PR in the refrigerator was in 2021, and if we include those that were closed before due to lack of continued maintenance, it will be even earlier.
Since Phobos is a community project that accepts PR provided by the community, there must be a deterministic PR disposal process that cannot rely solely on maintainers' spontaneous review.

2025-10-30 12:51 UTC, Metadorius commented
> I want to say that the root of the problem lies in Phobos' PR review efficiency

While I agree it is a problem, this is not what is happening here, nor it was what was happening in the #1582. The review feedback was given, but instead of being addressed it was dismissed multiple times.

> They say 'losing patience' and 'washing time' is not disrespectful to you, they are just stating the fact that you have spent too much time on trajectory PR.

That is not stating the fact. Stating the fact would be "We have spent a lot of time on this PR". What was said instead was disrespectful, when we were actively trying to be diplomatic, the other side didn't care on the same level about a choice of words.

> The fundamental reason for the low efficiency of PR review is that our project lacks a clear PR review process that can be completed within a certain time frame.

No, the fundamental reason is the lack of active T2 maintainers and slow "growth" of new T2 maintainers, which is the cause of slow review process. Yes, it's sad that it's slow, but there's no magic to just get more maintainers or magically transfer more skills and experience to others to be able to handle the project on a higher level, and I am not willing to shoot the project in the foot by accepting code with major architectural issues. We neither lose any money, nor endanger someone's lives, nor have any other life dependency, nor do we even have deadlines to warrant that, but we do have reputation and standards to uphold, which is my responsibility to do, ultimately.

2025-10-30 13:03 UTC, Metadorius commented
And for the record, we *always* had issues with reviewing and housekeeping. My contribution list is so small not because I am doing nothing, but because I spent more time than anyone else reviewing things in the past, to the point of burning out multiple times, because no one ever wanted to actively review and housekeep things, but everyone wanted to write them. Credits where it's due, you guys have been more actively doing that, which is the reason we went from 140 PRs to 70 PRs, which was a huge relief, but alas, now Starkku and ZivDero are busy elsewhere, I am working on completing things related to Ares/Phobos/new spawner update for CnCNet, which means we lack people on T2+ level.

It is a problem that ideally requires a solution, but what has been done is not an acceptable solution to that.

2025-10-30 13:29 UTC, TaranDahl commented
> No, the fundamental reason is the lack of active T2 maintainers and slow "growth" of new T2 maintainers, which is the cause of slow review process. 

我去看了Teams，我们有8位T2维护者。即使现在有4位因为各种原因而无法审查PR，还有另外4位。他们在做什么？
I checked Teams. We have 8 T2 maintainers. Even if 4 of them are unable to review PRs for various reasons at the moment, there are still 4 others. What are they doing?

2025-10-30 13:33 UTC, Metadorius commented
> 我去看了Teams，我们有8位T2维护者。即使现在有4位因为各种原因而无法审查PR，还有另外4位。他们在做什么？ I checked Teams. We have 8 T2 maintainers. Even if 4 of them are unable to review PRs for various reasons at the moment, there are still 4 others. What are they doing?

The teams are not representative of *active* maintainers. For the past years I've been executing the policy of keeping historical roles of people and not removing them from the team out of courtesy for their past work. It's a hobby after all, maybe they'll want to return some day and it would be mentally easier for them to do so.

See active maintainers in the README.md instead.

2025-10-30 13:44 UTC, TaranDahl commented
我们当然应该记住那些曾经做过贡献的人，但我认为你将他们放在T2这个标签里是不合适的，毕竟我们需要这个标签来审核PR。你可以创建一个新的，比如"Honorable Retired"之类的。
Of course, we should remember those who have made contributions. However, I think it's inappropriate for you to put them under the T2 label. After all, we need this label to review PRs. You can create a new one, such as "Honorable Retired" or something like that.

2025-10-30 13:48 UTC, Metadorius commented
Maybe, however, let's not stray away from the core issue.

2025-10-30 13:50 UTC, TaranDahl commented
Yeah. I will discuss that with you privately later.

Forget it. There's nothing more to discuss. 
I was going to draft a plan for the review cycle. Then I realized that we only have 7 people in total reviewing the code😅
Given this number, there's nothing to blame for the current speed.

2025-10-30 14:20 UTC, ZivDero commented
@TaranDahl 
> there are still 4 others. What are they doing?

I dunno? Did you ask them? Yes, in an ideal world reviewers come by themselves. But as you've said, we're very short on manpower. I have TS, Starkku has PP. However, if the authors asked either of us, I'm sure they would've received feedback. Maybe not immediately. Maybe it'd take a few weeks even. But within the lifespan of this PR, even that seems pretty short.

So don't hesitate to ask directly. We're a tightly knit community, and the situation dictates that it's appropriate and even necessary.

2025-10-30 20:37 UTC, Metadorius commented
This PR has to be reopened to facilitate proper process, as we, of course, don't want to stop it from being merged eventually.