[Minor] Update Trajectory Template and Uniform Trajectory Modifications
Phobos-developers/Phobos pull request #1463
Opened 2024-12-26 16:11 UTC by CrimRecya

Update the old template of Trajectory=Sample, add some comments. And make some uniform changes for Trajectories: 1. Avoid inertia effect on trajectories fired by aircrafts; 2. Draw laser trails with the actual moving direction of the projectile.

2024-12-26 20:05 UTC, Metadorius commented on src/Ext/Bullet/Hooks.cpp
> +	{
Isn't this sanity check redundant? If the extension is missing - we got way bigger problems than this.

2024-12-26 20:05 UTC, Metadorius commented on src/Ext/Bullet/Trajectories/SampleTrajectory.h
> +	SampleTrajectory(SampleTrajectoryType const* trajType) : Type { trajType }
I barely touched trajectories code, so take this with a grain of salt: aren't you supposed to explicitly declare which constructor you are "inheriting" from here as well?

2024-12-27 06:33 UTC, CrimRecya commented on src/Ext/Bullet/Hooks.cpp
> +	{
Get it.

2024-12-27 06:42 UTC, CrimRecya commented on src/Ext/Bullet/Trajectories/SampleTrajectory.h
> +	SampleTrajectory(SampleTrajectoryType const* trajType) : Type { trajType }
I don't know much about this question. Maybe you'd better ask Trsdy. I just reset the old Trajectory=Sample (header files are copied from Trajectory=Straight) with the new trajectory template remade by Trsdy, and added my thought in comments.

2024-12-27 14:30 UTC, chaserli requested changes
You also have some other common changes in your trajectory prs. Copy them here so that we can process them together.

2024-12-27 14:30 UTC, chaserli commented on src/Ext/Bullet/Trajectories/SampleTrajectory.h
> +	SampleTrajectory(SampleTrajectoryType const* trajType) : Type { trajType }
PhobosTrajectory is now a pure virtual interface. There's no constructor.

2024-12-27 15:58 UTC, CrimRecya commented
> You also have some other common changes in your trajectory prs. Copy them here so that we can process them together.

I have picked out the most common part. Please check it out.

2024-12-29 11:01 UTC, chaserli approved these changes

2025-01-15 06:59 UTC, Coronia approved these changes
since this isn't a real function, think it could be merged safely

2025-01-15 14:37 UTC, merged