[Simple Fix] Draw visual effects for airburst weapons
Phobos-developers/Phobos pull request #1466
Opened 2024-12-28 09:24 UTC by CrimRecya

- `AirburstWeapon` now supports `IsLaser` (with Ares `LaserThickness`), `IsElectricBolt` (with Phobos `Bolt.Disable1`, `Bolt.Disable2`, `Bolt.Disable3`, `Bolt.Arcs`, without Ares `Bolt.Color1` 、`Bolt.Color2` 、`Bolt.Color3`), `IsRadBeam` (with Ares `Beam.Color` 、`Beam.Duration` 、`Beam.Amplitude` 、`Beam.IsHouseColor`), and `AttachedParticleSystem`.

2025-02-14 10:09 UTC, Coronia requested changes
again I would like some comments about how the position in `SimulatedFiringAnim` is calculated. If someone else reading the codes, they might be confused by the algorithm or magic number in it

2025-02-20 09:09 UTC, Coronia reviewed
the current code only used `SimulatedFiringEffects` for once with `firingEffect` set to false, which means that `SimulatedFiringAnim` and `SimulatedFiringReport` are actually omitted. Is this the intended way? If so, then where should these functions be used?

2025-02-20 09:11 UTC, CrimRecya commented
> the current code only used `SimulatedFiringEffects` for once with `firingEffect` set to false, which means that `SimulatedFiringAnim` and `SimulatedFiringReport` are actually omitted. Is this the intended way? If so, then where should these functions be used?

`Disperse` and `Tracing` trajectory.

2025-03-02 16:21 UTC, Coronia approved these changes
tested with laser, bolt and rad beam, they can all be shown/dealt damage/applied effects properly

2025-03-02 16:52 UTC, merged