[Customized] Avoid weapon fire overflow in the same frame
Phobos-developers/Phobos pull request #1472
Opened 2024-12-28 09:31 UTC by CrimRecya

- Now you can make the weapon declare that the target has been locked at the moment of firing, and all weapons with positive `NoRepeatFire` value will not attack the declared target again during this period of time. Made for seckill and control weapons.

In `rulesmd.ini`:
```ini
[SOMEWEAPON]       ; WeaponType
NoRepeatFire=0     ; integer, game frames
```

2024-12-28 13:45 UTC, CrimRecya commented
If the techno can attach effect to the target at the moment of firing, it can achieve a similar effect. But I am not sure whether it needs to be expanded. It seems that there are not many places suitable for this.

2024-12-28 18:37 UTC, Aephiex commented
> Now you can make the weapon declare that the target has been locked at the moment of firing, and all weapons **with positive NoRepeatFire value** will not attack the declared target again during this period of time. Made for seckill and control weapons.

Maybe change that to only the weapons in a specific group?

2025-01-15 07:50 UTC, Coronia requested changes

2025-01-15 07:50 UTC, Coronia commented on docs/New-or-Enhanced-Logics.md
> +- Now you can make the weapon declare that the target has been locked at the moment of firing, and all weapons with positive `NoRepeatFire` value will not attack the declared target again during this
Rename the tag to something like `PreventTargetDuration` for better clarification
- what it can stop is the targeting process, but not the real damage
- it's supposed to be an integer tag for frame amount, instead of a boolean one

2025-01-15 07:53 UTC, Coronia commented
> > Now you can make the weapon declare that the target has been locked at the moment of firing, and all weapons **with positive NoRepeatFire value** will not attack the declared target again during this period of time. Made for seckill and control weapons.
> 
> Maybe change that to only the weapons in a specific group?

I think we can already use new AEs for that. This avoid fire logic should remain simple as it is imo

2025-01-15 08:32 UTC, CrimRecya commented
#1482 can complete this implement in a more customized way, so I decided to turn this off.

2025-01-15 08:32 UTC, closed without merging