[Customized] Aggressive attack move mission
Phobos-developers/Phobos pull request #1473
Opened 2024-12-28 09:32 UTC by CrimRecya

- `AttackMove.Aggressive` allows your technos to attack the enemy's unarmed buildings more aggressively when in attack move mission (Ctrl+Shift). If a higher threat enemy techno is found in the range during this process, it will attack this enemy techno instead first.

In `rulesmd.ini`:
```ini
[General]
AttackMove.Aggressive=false   ; boolean
```

2024-12-29 13:52 UTC, TaranDahl commented
Tested locally.

2025-01-15 08:18 UTC, Coronia approved these changes

2025-01-16 12:11 UTC, Starkku requested changes
A little bit of feedback about weapon-related sanity checks.

2025-01-16 12:11 UTC, Starkku commented on src/Ext/Techno/Hooks.TargetEvaluation.cpp
> +		return false;
This kind of sanity checking is and unnecessary, `GetWeapon()` never returns `nullptr`. You can simply do something like

```cpp
const auto pPrimaryWeapon = pThis->GetWeapon(0)->WeaponType;

if (!pPrimaryWeapon)
		return false;
```

instead and it will be fine.

2025-03-19 06:23 UTC, Coronia commented
should add an option on building to prevent it being the target of aggressive attack move

also it would be better to split the tag in [General] just like techno, or it would be weird and inconvenient to have both 2 tags default to the same one

2025-04-22 08:27 UTC, merged