[Customized] Fast access vehicle
Phobos-developers/Phobos pull request #1475
Opened 2024-12-28 09:34 UTC by CrimRecya

- Now you can let passengers quickly enter or leave the transport vehicles (useless for buildings) without queuing. Defaults to `[General]` -> `NoQueueUpToEnter` or `NoQueueUpToUnload`.

In `rulesmd.ini`:
```ini
[General]
NoQueueUpToEnter=false    ; boolean
NoQueueUpToUnload=false   ; boolean

[SOMEUNIT]                ; UnitType
NoQueueUpToEnter=         ; boolean
NoQueueUpToUnload=        ; boolean
```

2025-02-01 01:17 UTC, mevitar commented
This happened when i tried to load PoweredBy= units into a NoQueueUpToEnter=yes and NoQueueUpToUnload=yes transport, and then i unpowered them mid load. They stayed unpowered this entire time.

![fastloadbug](https://github.com/user-attachments/assets/4d4f83ac-d451-46ba-9fe4-11ab4d4c3573)

Will still test if it happens for regular load.

2025-02-01 01:32 UTC, mevitar commented
> I'll still recheck if it happens with regular transports.

Yes, it indeed happens with regular transports, and it's not an issue introduced by Phobos.

2025-03-27 04:18 UTC, Coronia requested changes
worked properly in test, the issue listed below are just some minor stuffs

also, maybe we don't have to follow the QueueUpToEnter variable name, but name this feature as `QuickEnter` and `QuickUnload` instead

2025-03-27 04:18 UTC, Coronia commented on src/Ext/Techno/Hooks.Transport.cpp
> +					pThis->CurrentGattlingStage = 0;
guess the gatling part is not needed unless we're making infantry support it
also I'm not sure if more variable reset is needed here, if we can look into how vanilla was handling it then it would be better

2025-03-27 04:18 UTC, Coronia commented on src/Ext/Techno/Hooks.Transport.cpp
> +					if (const auto pMind = pThis->MindControlledBy)
the same 2 things as above

2025-03-27 04:18 UTC, Coronia commented on src/Ext/Techno/Hooks.Transport.cpp
> +		if (pThis->Passengers.NumPassengers <= pThis->NonPassengerCount)
would it be more accurate to just use size for this check? NonPassengerCount's comment mentioned it has interaction with Gunner but I'm not sure what it is

2025-03-27 04:18 UTC, Coronia commented on src/Ext/Techno/Hooks.Transport.cpp
> +					if (const auto pMind = pThis->MindControlledBy)
mind control is already filtered in CanEnterNow it seems?

2025-03-27 04:18 UTC, Coronia commented on docs/New-or-Enhanced-Logics.md
> +- Now you can let passengers quickly enter or leave the transport vehicles (useless for buildings) without queuing. Defaults to `[General]` -> `NoQueueUpToEnter` or `NoQueueUpToUnload`.
technically aircraft could also have passenger, should we support it as well? If not, then it should be mentioned in the doc

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +	if (!pTransport->Owner->IsAlliedWith(pPassenger) || pTransport->IsBeingWarpedOut())
Rewrite from 7375A6.

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +	if (needCalculate && remain < (bySize ? static_cast<int>(pLink->GetTechnoType()->Size) : 1))
The passenger who is asking if they can enter may not necessarily be the link techno.

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +					pThis->CurrentGattlingStage = 0;
Rewrite from 51A2AD.

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +					if (const auto pMind = pThis->MindControlledBy)
Rewrite from 73A6F1.

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +		if (pThis->Passengers.NumPassengers <= pThis->NonPassengerCount)
If your unit is a `Gunner`, it will stop before unloading to this passenger, which is the vanilla logic. See 73D8B7.

2025-03-27 04:43 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Transport.cpp
> +					if (const auto pMind = pThis->MindControlledBy)
That's true, but this is how it was done in vanilla. See 51A2C3 and 73A714.

2025-03-27 04:43 UTC, CrimRecya commented on docs/New-or-Enhanced-Logics.md
> +- Now you can let passengers quickly enter or leave the transport vehicles (useless for buildings) without queuing. Defaults to `[General]` -> `NoQueueUpToEnter` or `NoQueueUpToUnload`.
Passengers on airplanes are completely different from those on vehicles or even buildings.
Their boarding and unloading logic is completely different.

2025-03-27 06:31 UTC, CrimRecya commented
> worked properly in test, the issue listed below are just some minor stuffs
> 
> also, maybe we don't have to follow the QueueUpToEnter variable name, but name this feature as `QuickEnter` and `QuickUnload` instead

Wait a moment, there is currently an issue: when the vehicle to be loaded is surrounded by the transport vehicle within a circle, it cannot be loaded quickly because non moving units will not call `UpdatePosition()`.
Also, regarding the key names, I would like to emphasize that there is no need to wait in line when taking transportation vehicles. Simple key names may not be clear enough, so I would like to hear other people's opinions.

2025-03-29 17:45 UTC, Coronia approved these changes

2025-03-31 05:08 UTC, merged