[Minor] Attach effect when weapon fire
Phobos-developers/Phobos pull request #1482
Opened 2024-12-29 06:35 UTC by CrimRecya

`AttachEffect` will directly act on the target at the instant after firing.
More general expansion for #1472 .

2025-01-15 06:51 UTC, Coronia commented
I would say we should still keep AE for warhead only, especially when we can use ExtraWarheads and such to provide different effects for different technos in one shot. Adding a connection between weapon and AE would make the system overcomplicated, while not gaining much

2025-01-15 06:56 UTC, CrimRecya commented
> I would say we should still keep AE for warhead only, especially when we can use ExtraWarheads and such to provide different effects for different technos in one shot. Adding a connection between weapon and AE would make the system overcomplicated, while not gaining much

The biggest advantage of weapon AE over warhead AE is that it is completed in an instant. It can produce different effects with the order of unit update, and the warhead AE will not take effect until all bullets are updated and detonated. Sometimes, it is too late.

2025-01-15 06:58 UTC, CrimRecya commented
> I would say we should still keep AE for warhead only, especially when we can use ExtraWarheads and such to provide different effects for different technos in one shot. Adding a connection between weapon and AE would make the system overcomplicated, while not gaining much

The biggest advantage of weapon AE over warhead AE is that it is completed in an instant. It can produce different effects with the order of unit update, and the warhead AE will not take effect until all bullets are updated and detonated. Sometimes, it is too late.

2025-01-15 07:08 UTC, Starkku requested changes
It is potentially niche but the code is not as complex as it could be since there's very little bespoke code (parsing is handled by `AEAttachInfoTypeClass` which can directly be passed to the attach/detach functions). Whether or not there's a performance overhead that outweighs potential benefits is hard to quantify, though.

There's one small thing that should be changed at the very least.

2025-01-15 07:08 UTC, Starkku commented on src/Ext/Techno/Hooks.Firing.cpp
> +				AttachEffectClass::Attach(pTargetTechno, pThis->Owner, pThis, pWeapon->Warhead, info);
The source parameter should be just the weapon, not Warhead. It takes `AbstractClass` pointer and does not make assumptions about what type it is, it is there just to track where the AE instance came from.

2025-01-15 07:15 UTC, CrimRecya commented on src/Ext/Techno/Hooks.Firing.cpp
> +				AttachEffectClass::Attach(pTargetTechno, pThis->Owner, pThis, pWeapon->Warhead, info);
In this regard, I found it inappropriate to pass weapons as parameters in previous tests, because the warhead of the current weapon is used to determine whether the weapon can attack (`IgnoreFromSameSource`). If the incoming source here is a weapon, units cannot continue to attack the target.

2025-01-15 07:21 UTC, Starkku commented on src/Ext/Techno/Hooks.Firing.cpp
> +				AttachEffectClass::Attach(pTargetTechno, pThis->Owner, pThis, pWeapon->Warhead, info);
Right, forgot about that. Might be acceptable concession then in order to reduce complexity in the AE checks then, although it could cause some unusual results.

2025-01-15 16:25 UTC, Speederovsky commented
Why make this when you could design something like an InstantWarhead detonation that skips all these checks too and gives us more flexibility to what the instantly applied effects actually are? Not just AE, and you skip having to redo all nuAE tags on WeaponTypes.

2025-01-15 17:12 UTC, CrimRecya commented
> Why make this when you could design something like an InstantWarhead detonation that skips all these checks too and gives us more flexibility to what the instantly applied effects actually are? Not just AE, and you skip having to redo all nuAE tags on WeaponTypes.

Your idea touched me. If killing some units in the process of traversing all units will not cause problems in the iterator due to DTOR or quantity reduction (maybe, not sure), it is worth trying.

2025-01-20 08:39 UTC, CrimRecya commented
After evaluation, `InstantWarhead` is considered to be unhelpful to the content of this pr. The same warhead is required if AE needs to be used to search target by the weapon. That is, `InstantWarhead` should be used as the Boolean value of a projectile with `Inviso=true`, so that the projectile will detonate immediately after it is set in position, instead of waiting for a uniform update time.

2025-01-20 08:43 UTC, Metadorius commented
I didn't quite get why is `InstantWarhead` unsuitable, can you elaborate?

2025-01-20 08:52 UTC, CrimRecya commented
> I didn't quite get why is `InstantWarhead` unsuitable, can you elaborate?

As discussed with Starkku before, if the weapon needs to use AE to target (such as `IgnoreFromSameSource`), the warhead of the weapon must be the same. If it wants to replace the requirement that PR can solve, it should move to the target position immediately after the projectile is generated, and then detonate immediately (to ensure that the `Warhead` is the same). If we use a new logic similar to `ExtraWarhead` to carry a new warhead, we can not achieve the purpose of PR.
In short, it should be possible, but it is different from the goal of PR.

2025-02-13 09:12 UTC, Coronia approved these changes

2025-08-12 04:40 UTC, closed without merging