[Minor] More aircrafts actions enhancement for #1366
Phobos-developers/Phobos pull request #1484
Opened 2024-12-30 07:46 UTC by CrimRecya

1. Fix aircrafts planning waypoint problem - At the end of each task, all units with planning waypoints will generate an mega event to the next planning waypoint and respond after 1 frame. This is really no problem for most units, but for aircrafts, they will always return to the airport after each task. So they will try to return to the airport in the frame before it respond to event. There will be looked like a "shaking", if the `Speed` and `ROT` of the aircraft are fast. To solve this problem, I check the waypoints of aircrafts and let them wait before returning.
2. Fix a vanilla issue - Now aircrafts can fly towards the water surface normally.

2025-01-08 13:15 UTC, Metadorius requested changes
Looking good so far, I'll fix the docs a bit soon.

2025-01-08 13:15 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	if (!reinterpret_cast<bool(__thiscall*)(AircraftClass*)>(0x6385C0)(pThis))
Let's add this to YRpp. Not sure of the name though, do you have any suggestions?

2025-01-08 13:15 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +DEFINE_HOOK(0x4DDD66, FootClass_vt_entry_550_ReplaceHardcode, 0x5) // To avoid that the aircraft cannot fly towards the water surface normally
```suggestion
DEFINE_HOOK(0x4DDD66, FootClass_IsLZClear_ReplaceHardcode, 0x6) // To avoid that the aircraft cannot fly towards the water surface normally
```

2025-01-08 13:15 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	R->AL(MapClass::Instance->GetCellAt(cell)->IsClearToMove(pType->SpeedType, false, false, -1, pType->MovementZone, -1, true));
I think this change alone may change the vanilla behavior. Are `SpeedType::Track` and `MovementZone::Normal` default values?

2025-01-08 13:29 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +DEFINE_HOOK(0x4DDD66, FootClass_vt_entry_550_ReplaceHardcode, 0x5) // To avoid that the aircraft cannot fly towards the water surface normally
Oh, sorry for the mistake.

2025-01-08 13:34 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	if (!reinterpret_cast<bool(__thiscall*)(AircraftClass*)>(0x6385C0)(pThis))
Maybe `TryNextPlanningTokenNode` ?
Sorry, but I can't think of a good name.

2025-01-08 13:43 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	R->AL(MapClass::Instance->GetCellAt(cell)->IsClearToMove(pType->SpeedType, false, false, -1, pType->MovementZone, -1, true));
This is to enable the aircraft to fly directly to above the water surface by clicking. It will definitely change the vanilla behavior.
These two were hard coded, which caused the aircraft to set the destination back to the shore like ordinary ground units.

2025-01-08 14:22 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
> +	if (!reinterpret_cast<bool(__thiscall*)(AircraftClass*)>(0x6385C0)(pThis))
Sounds good. Can you submit a PR to YRpp?

2025-01-08 14:26 UTC, CrimRecya commented on src/Ext/Aircraft/Hooks.cpp
> +	if (!reinterpret_cast<bool(__thiscall*)(AircraftClass*)>(0x6385C0)(pThis))
I just submitted a PR to YRpp.

2025-01-12 09:07 UTC, Metadorius submitted a review, later dismissed
Clarify docs

2025-01-12 09:10 UTC, Metadorius approved these changes

2025-01-12 09:11 UTC, merged