Allow to sort sidebar cameos
Phobos-developers/Phobos pull request #192
Opened 2021-04-24 15:33 UTC by Thrifinesma

[TechnoType]>CameoPriority=
Issue #66

2021-06-14 11:01 UTC, Metadorius requested changes

2021-06-14 11:01 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +    this->CameoPriority.Read(exINI, pSection, "CameoPriority");
Spaces instead of tabs here and everywhere below.
Also perhaps it would be better to have this ins `artmd.ini`?

2021-06-14 11:04 UTC, Thrifinesma commented on src/Ext/TechnoType/Body.cpp
> +    this->CameoPriority.Read(exINI, pSection, "CameoPriority");
All sorting rules are in `rulesmd.ini`, so I don't suggestion the new one in `artmd.ini`

2021-06-19 16:24 UTC, FS-21 commented
For the tests I added CameoPriority=<integer value> to some few artillery units that I already know that in Unholy Alliance game mode (the one you can build everything of any faction) and 1 aircraft, another one that is a transport vehicle "considered aircraft", 2 naval units, 3 defenses of different factions and 2 Super Weapons.

I modified a testing UnitDelivery SW I had for deploy all the factories and structures that unlocks new units/structures.

What I saw after deploying the debug SW:
- In SW/defenses tab Super Weapons can't be ordered.
- In SW/defenses tab Structures Can't be placed before the Super Weapons.
- In SW/defenses tab the buildable Wall of the player's faction is placed before the first structures with "CameoPriority" tag. The wall didn't have any "CameoPriority" tag and you can't move the cameo adding a low value with "CameoPriority", looks hardcoded like Super Weapons.
- In SW/defenses tab **(ignoring all I said above)** The cameos with "CameoPriority" are ordered BEFORE the unordered cameos.
- In SW/defenses tab Structures with the same CameoPriority value are ordered by Tech Level (ordered from lower levels to highers levels).
- In vehicles tab ground vehicles are hardcoded to be placed first, then the aircrafts (and vehicles considered aircrafts) and finally naval units. In these 3 hardcoded groups the "CameoPriority" tag works as expected.

2021-06-26 16:58 UTC, FS-21 commented
Tested the newer build, I noticed:
- In units tab now any icon can be sorted ignoring the original 3 hardcoded groups (Ground units, Aircrafts & Naval).
- The (Player's) Wall (that depends of which House you selected) is still hardcoded to be the first icon after the Super Weapons.

2021-07-19 09:48 UTC, Metadorius requested changes
The code quality is OK, just a bit of changes and it can be merged.

2021-07-19 09:48 UTC, Metadorius commented on src/Misc/Hooks.UI.cpp
> +	// jz short loc_6A8477
```suggestion
	// Restore overridden instructions
```

2021-07-19 09:48 UTC, Metadorius commented on src/Ext/TechnoType/Hooks.cpp
> +*/
```suggestion
```

2021-07-19 09:48 UTC, Metadorius commented on src/Ext/SWType/Hooks.cpp
> +*/
Not sure if there's any point in keeping this file at all.

2021-07-19 09:55 UTC, merged