Shield Refactoring (Fix possible Shield Anim crash)
Phobos-developers/Phobos pull request #213
Opened 2021-05-23 03:59 UTC by Thrifinesma

2021-05-24 09:39 UTC, Metadorius commented on src/Misc/Shield.cpp
> +#define Serialize(Stm) \
Why a define instead of a proper function like what's used in Ext classes?

2021-06-05 21:49 UTC, Metadorius requested changes
The code looks good aside from a bunch of minor issues.

2021-06-05 21:49 UTC, Metadorius commented on src/Enum/ShieldType.cpp
> +void ShieldTypeClass::LoadListSection(CCINIClass* pINI)
This should be implemented in `Enumerable<T>`. Actually I have already fixed the implementation in laser trails branch so I guess I could cherrypick it to develop and merge the changes here.

2021-06-05 21:49 UTC, Metadorius commented on src/Enum/ShieldType.cpp
> +	for (auto& radType : Array)
CnP naming error.

2021-06-05 21:49 UTC, Metadorius commented on src/Ext/Techno/Hooks.Shield.cpp
> +DEFINE_HOOK(71A88D, TemporalClass_AI_Shield, 0)
Missing newlines and it's not clear what's happening without enum'ed addresses and/or comments.

2021-06-05 21:49 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +	this->Shield = ShieldTypeClass::FindOrAllocate("Radiation");
CnP naming error yet again. Not sure if we even need the default stuff. See lasertrails branch.

2021-06-05 21:49 UTC, Metadorius commented on src/ExtraHeaders/ArmorType.h
> +	ArmorType(T value) {
Brace not on a newline.

2021-06-05 21:49 UTC, Metadorius commented on src/ExtraHeaders/ArmorType.h
> +	ArmorType& operator = (T value) {
Ditto.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
> +	if (pFromExt->ShieldData) {
Missing newline here and after that code block, brace not on a newline yet again.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
>  				static_cast<int>(this->Techno->GetTechnoType()->Armor)) > 0)
Either don't split a condition or use braces. Right now it's badly readable. Also missing newline before return.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
> +			{
Not sure why the code block content isn't indented.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
> +	if ( !this->Cloak && !this->Temporal && this->Online && this->HP > 0 )
We don't use spaces around conditions.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
> +	if (!this->Available)
Missing newline here and excessive use if newlines in all the other function code. I won't mention newlines from this comment on.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.cpp
> +			(double)pType->Strength
Not sure at all but maybe there's an operator precedence error here, in any case I'd rather be safe and write multiplication first.

2021-06-05 21:49 UTC, Metadorius commented on src/Misc/Shield.h
> +		{ };
Think the semicolon is not necessary here, also empty code blocks should have spaces in them.

2021-06-05 21:49 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +				Debug::INIParseFailed(pSection, pKey, parser.value(), "Expected a super weapon affected house");
CnP error yet again.

2021-06-24 09:17 UTC, Metadorius commented
On develop branch (needs to be checked here as well):
![image](https://user-images.githubusercontent.com/17500545/123237108-09fbde00-d4e6-11eb-98b1-bbed9a0a533d.png)
![image](https://user-images.githubusercontent.com/17500545/123237132-0e27fb80-d4e6-11eb-9f28-6528652fabb0.png)

2021-06-24 09:20 UTC, Metadorius commented
Shielded infantry gets infected by parasites, which is kinda unintended default behavior (courtesy of @SukaHati)
[video](https://cdn.discordapp.com/attachments/773636942775582720/856858229950251018/Mental_Omega_2021-06-22_19-20-45.mp4)

2021-06-24 09:29 UTC, Metadorius commented
Shielded units with an anim are blocking selection of air units over them (possibly Z sort issue that can be fixed via ini):
[video](https://cdn.discordapp.com/attachments/773636942775582720/856807249099227166/whatisthisbug.mp4)

2021-06-24 12:23 UTC, Metadorius commented on src/Misc/Shield.cpp
>  {
Why is this method static?

2021-06-24 12:26 UTC, Metadorius commented on src/New/Type/ShieldType.cpp
> +		.Success()
Method returns void, is this really needed?

2021-06-24 21:27 UTC, Metadorius approved these changes

2021-06-24 21:30 UTC, Belonit commented on src/New/Type/ShieldType.cpp
> +		.Success()
yes. Success is not needed here

2021-06-24 21:32 UTC, Belonit commented on src/Misc/Shield.cpp
>  {
I had to resort to such a design, since the templates did not solve the const \ not-const type conflict

2021-06-24 22:01 UTC, Metadorius approved these changes

2021-06-24 22:01 UTC, merged