Laser trails
Phobos-developers/Phobos pull request #217
Opened 2021-05-26 19:38 UTC by Metadorius

```ini
[LaserTrailTypes]
0=LTRL

[LTRL]
IsHouseColor=no
Color=255,0,0
Duration=15
Thickness=8
Distance=32
IgnoreVertical=no
IsIntense=no

[SOMEPROJ] ; BulletType
LaserTrail=LTRL
```

2021-07-19 15:45 UTC, Metadorius commented
TODO fix save/load issues

2021-07-27 03:57 UTC, Otamaa reviewed
Here is some that i found out , hope this can help to fix the S/L  issues all together !

2021-07-27 03:57 UTC, Otamaa commented on src/Ext/TechnoType/Body.cpp
> +		Nullable<LaserTrailTypeClass*> trail;
To Fix the S/L (1.a) : change this to ``NullableIdx<LaserTrailTypeClass> trail;`` 
 and save the index(int) instead of the Type pointer , it wont serialize the Type pointer for some reason.

2021-07-27 03:57 UTC, Otamaa commented on src/Ext/TechnoType/Body.h
> +			LaserTrailTypeClass* Type;
To Fix the S/L (1.b) : change this to ``int TypeIdx``

2021-07-27 03:57 UTC, Otamaa commented on src/Ext/TechnoType/Body.h
> +			bool Save(PhobosStreamWriter& stm) const;
To Fix the S/L (2) : Use ``void SaveToStream`` and ``void LoadFromStream`` instead of this , causing crash When trying to Load the save game.

2021-07-27 03:57 UTC, Otamaa commented on src/New/Entity/LaserTrailClass.cpp
> +		.Success();
To Fix the S/L (3) : You miss the ``.Process(this->CurrentColor)`` ,
``.Process(this->IsOnTurret)`` and ``.Process(this->FLH)`` maybe also need to be add ? 
i do add thse three , but CurrentColor one is most likely more important piece.

2021-07-27 03:57 UTC, Otamaa commented on src/Ext/Techno/Body.cpp
> +			pExt->LaserTrails.push_back(
To Fix the S/L (4) : Change this code to ``Find`` laser trail type From ``Index`` that previously stored 
`if (auto const pLaserType = LaserTrailTypeClass::Array[entry.TypeIdx].get())
 {
    pExt->LaserTrails.push_back( std::make_unique<LaserTrailClass>(pLaserType, pThis->Owner, entry.FLH,   entry.IsOnTurret));
}`

2021-07-27 13:26 UTC, secsome commented on src/Ext/Bullet/Hooks.cpp
> +		CoordStruct drawnCoords = CoordStruct
Just wondering, should we just keep our init to use Initialial-lists introduced in C++11 like
```cpp
CoordStruct drawnCoord
{
  Xstuff,
  Ystuff,
  Zstuff,
};
```
I think it's not quite well for us to use
```cpp
T foo = T{};
```

2021-07-27 13:26 UTC, secsome commented on src/Ext/TechnoType/Body.cpp
> +	for (size_t i = 0; i <= this->LaserTrailData.size(); ++i)
In most cases, we took for-loop as a way to iterate for datas. It's not quite well for us to use it on data initalizing, but, `while` might be better in this case.

2021-07-27 15:20 UTC, Thrifinesma requested changes

2021-07-27 15:20 UTC, Thrifinesma commented on src/Ext/Bullet/Body.cpp
> +			owner = pThis->Owner->Owner;
```suggestion
		auto pOwner = owner = pThis->Owner ? pThis->Owner->Owner : nullptr;
```

2021-07-27 15:20 UTC, Thrifinesma commented on src/Ext/Bullet/Body.cpp
> +					std::make_unique<LaserTrailClass>(pLaserType, owner));
```suggestion
					std::make_unique<LaserTrailClass>(pLaserType, pOwner));
```

2021-07-27 15:20 UTC, Thrifinesma commented on src/Misc/Hooks.LaserDraw.cpp
> +	//Debug::Log("cos x = %f; rgb = %d %d %d\n", mult, r, g, b);
```suggestion
```

2021-07-27 16:46 UTC, Metadorius commented on src/Ext/Bullet/Hooks.cpp
> +		CoordStruct drawnCoords = CoordStruct
I guess we can use cpp11 syntax.

2021-07-27 17:33 UTC, merged