DebrisMaximums BugFix
Phobos-developers/Phobos pull request #220
Opened 2021-05-30 13:40 UTC by Otamaa

- `DebrisMaximums` now is parsed and counted properly , spawned debris cannot go beyond Spesific Maximum anymore.

2021-06-01 08:43 UTC, MirceaOfRivia commented
Fantastic work,
`DebrisMaximums=` works fine but has no interactions with 
```
MaxDebris=
MinDebris=
```
meaning that there is a precedent change that nothing will spawn, this will impact any effect that needs at least 1 debri to spawn 
for example in my Brutal Yuri mod, the Kirov relies on a debri to cause the death damage to units under it, so I use 
```
DebrisTypes=ZEP_H,ZEP_H,
DebrisMaximums=1
MaxDebris=2
MinDebris=1
```
this forces the game to always spawn one debri, works only in the Origin version
![ezgif-4-c0ab158d04a0](https://user-images.githubusercontent.com/85160142/120294147-35642200-c2c6-11eb-8c42-cec45969ddd0.gif)

2021-06-21 11:07 UTC, Metadorius requested changes
Changes look good but you reeeeally need to pay more attention to making your code clean and following code style.

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	auto &DTypesMax = type->DebrisMaximums;
Styleguide violations (PascalCase, unneded shortenings, & attached to the name instead of type), also not sure if those are actually needed.

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	GET(TechnoClass*, pTech, ESI);
Should be pThis.

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	auto random = ScenarioClass::Instance->Random.RandomRanged(type->MinDebris, max);
Should name variables after their purpose, not after where they are from.

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +				auto maxallow = DTypesMax.GetItem(current);
Not camelCase.

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +				auto pAtype = DTypes.GetItem(current);
What does `pAtype` even mean?

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +					break;
```suggestion

				if (random < 0)
					break;
```

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	}
```suggestion
			++current;
		}
		while (current < DTypes.Count);
	}
```

2021-06-21 11:07 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +		return 0;
Also this special behavior should be documented.

2021-06-21 11:10 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +//A
//A?

2021-06-24 16:44 UTC, Metadorius approved these changes

2021-06-24 21:06 UTC, merged