Re-Write 0x65B580 to reduce hooks amount
Phobos-developers/Phobos pull request #262
Opened 2021-06-30 18:20 UTC by Otamaa

2021-07-03 08:04 UTC, secsome commented on src/Ext/RadSite/Body.cpp
> +void RadSiteExt::ExtData::Create_Light()
Move it to RadSiteExt::CreateLight instead of under RadSiteExt::ExtData will be better

2021-07-03 08:05 UTC, secsome commented on src/Ext/RadSite/Body.cpp
> +double RadSiteExt::ExtData::GetRadLevelAt(CellStruct const& cell) const
Also the other functions

2021-08-08 14:15 UTC, Metadorius requested changes

2021-08-08 14:15 UTC, Metadorius commented on src/Ext/RadSite/Hooks.cpp
> +	AbstractClass* pTarget = nullptr;//default WWP nullptr
```suggestion
	AbstractClass* pTarget = nullptr; //default WWP nullptr
```

2021-08-08 14:15 UTC, Metadorius commented on src/Ext/RadSite/Body.cpp
> +	LightFactor = LightFactor > 2000.0 ? 2000.0 : LightFactor;
~~PascalCase~~ camelCase

2021-08-08 14:15 UTC, Metadorius commented on src/Ext/RadSite/Body.cpp
> +	Blue = Blue > 2000.0 ? 2000.0 : Blue;
~~PascalCase~~ camelCase

2021-08-16 20:00 UTC, SMxReaver commented
Not sure if this should be here or under Hotfix v0.2.2.1, and I had a hard time trying to understand the underlying issue with this PR or the Hotfix PR due to a lack of description about the fix or the problem at hand. I am under the impression DecloakToFire=yes is not being respected currently, which I can confirm is now respected in this version of the Phobos DLL.
![fixed](https://user-images.githubusercontent.com/77598000/129622565-9e12d346-1c73-46c1-9b14-74184bac3cdb.gif)

2021-08-18 11:23 UTC, merged