Unlimited localVariables
Phobos-developers/Phobos pull request #321
Opened 2021-08-09 06:34 UTC by secsome

In vanilla YR, local variables are limited up to 100, now you can use up to INT_MAX waypoints.

2021-08-11 06:37 UTC, Thrifinesma commented
Unlimited Global Variables when :)

2021-08-15 12:52 UTC, Metadorius requested changes
Overall the code is good but the code for globals and locals is pretty much duplicated. I suggest to remove duplication and merge if there are no any more issues. Also needs docs/readme entries.

2021-08-15 12:52 UTC, Metadorius commented on src/Ext/Scenario/Body.h
> +			GlobalVariables {}
```suggestion
			Waypoints { },
			LocalVariables { },
			GlobalVariables { }
```

2021-08-16 20:50 UTC, SMxReaver commented
I do not know the best way to test Save/Load since I am very unfamiliar with how locals function in-game, but I can confirm the game successfully fired Local Variable triggers that were indexed higher than 100. Attached is my test map, I use Local 103 to reveal the map and Local 90 to display "Boris" in the top left corner.
[variabletestmap.zip](https://github.com/Phobos-developers/Phobos/files/6995297/variabletestmap.zip)

2021-08-21 11:39 UTC, Metadorius approved these changes

2021-08-21 11:39 UTC, merged