Feature/canfire target
Phobos-developers/Phobos pull request #327
Opened 2021-08-11 03:42 UTC by Thrifinesma

### Weapon targeting filter

- You can now specify which house this weapon can fire at.

In `rulesmd.ini`:
```ini
[SOMEWEAPON]        ; WeaponType
CanTargetHouse=all  ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
```

2021-08-11 04:07 UTC, Thrifinesma commented
tag name changed from `CanTargetHouse` to `CanTargetHouses`

2021-08-15 17:06 UTC, Metadorius requested changes

2021-08-15 17:06 UTC, Metadorius commented on src/Ext/WarheadType/Hooks.cpp
> +	enum { CannotFire = 0x6FCB7E};
```suggestion
	enum { CannotFire = 0x6FCB7E };
```

2021-08-15 17:07 UTC, Metadorius approved these changes

2021-08-15 17:07 UTC, merged