Fix death weapon not properly detonates
Phobos-developers/Phobos pull request #330
Opened 2021-08-13 16:45 UTC by Thrifinesma

2021-08-13 19:12 UTC, Lylaktech commented
Tried it on all deathweapons in MO, no issues.

2021-08-13 19:17 UTC, Metadorius requested changes
Good, add doc / credits additionally and we'll merge.

2021-08-13 19:17 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +				for (; amountToSpawn > 0; --amountToSpawn)
```suggestion
				for ( ; amountToSpawn > 0; --amountToSpawn)
```

2021-08-13 19:17 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	pBullet->Fire(true);
Let's rename it to correspond to IDB.

2021-08-13 19:17 UTC, Metadorius commented on src/Misc/Hooks.BugFixes.cpp
> +	pBullet->Target = pThis;
Is this one actually needed? I suggest to check if CreateBullet assigns target or not.

2021-08-15 12:34 UTC, Metadorius approved these changes

2021-08-15 12:34 UTC, merged