Ported `GiftBox` for Phobos
Phobos-developers/Phobos pull request #340
Opened 2021-08-22 17:39 UTC by Otamaa

Original Author : `ChrisLV-CN`
`https://github.com/ChrisLv-CN/PatcherExtension/blob/main/MyExtension/GiftBox.cs`

No detail documentation yet  !
Tags: 
In `rulesmd.ini`:
```ini
[SOMETECHNO]
GiftBox.Types=;List TechnoType 
GiftBox.Nums=;List integer , Amount each Types will be created
GiftBox.Remove=;bool, Remove this Techno after creating Gifbox Types
GiftBox.Destroy=;bool, Destroy this Techno  after creating Gifbox Types
GiftBox.Delay=;integer , Giftbox Delay
GiftBox.RandomDelay=;integer (Min,Max) , Giftbox Random delay 
GiftBox.CellRandomRange=;integer 
GiftBox.EmptyCell=;bool
GiftBox.RandomType=;bool , Create random Types instead of all Types on the list 
```

2021-11-15 23:17 UTC, RexDraco commented
Some wishlists, not important:
Some type of auto scatter
a tag for auto selection of new unit(s) if giftbox was selected

When using "GiftBox.Destroy=" on infantry, they do not appear to actually be killed but rather just remove (Terrorists do not give off explosion). The differences between destroy and remove seems to be whether they follow the walking orders from giftbox or not. For units, it works as intended and in both cases they follow previous orders.

Infantry inside Bioreactors do not appear to keep track of delay.
Infantry cannot seem to convert to structures, did not know if this was by design or not, but they tend to disappear because of it

Infantry, when constructed, seem to walk into the cell of a converted infantry type without care. This is regardless if the infantry type is also converting to a new infantry or not. Having an GI walk to the rally point, convert to Brute, and then a GGI walk to same rally point and never convert will cause GGI to walk right on top of the Brute. Note I do not see a difference even if there's one Brute or ten, just that three GGI causes the cell to be full so he walks to the next.


When using this on SLAV types, they come out of the slave miner as expected and, even when converted to a new infantry, they travel to where the ore the SLAV was walking towards and then stand there. They continue to walk to destination regardless if removed or destroyed, in spite the common pattern from other scenarios with infantry where remove causes them to stop dead in their tracks. If delay is zero, the infantry simply exits the slave miner and then stops, not walking towards ore (probably because slaves do not have a destination set until finally exiting slave miner).

[SLAV]
...
Sight=5 ;!!
...
GiftBox.Types=SLAV
GiftBox.Nums=1
;GiftBox.Remove=yes
GiftBox.Destroy=yes;bool, Destroy this Techno  after creating Gifbox Types
GiftBox.Delay=50;integer , Giftbox Delay

Slaves spawn as usual from slave miner, then stop at Ore not mining due to convert to a non enslaved SLAV. Works as expected.
I do notice that, unlike tests with terrorists earlier, Slaves always go to last order given, even if it was their previous giftbox's order. Newly spawned slaves follows old orders.


Swapping to GiftBox.Remove:

GiftBox.Types=SLAV
GiftBox.Nums=1
GiftBox.Remove=yes
;GiftBox.Destroy=yes;bool, Destroy this Techno  after creating Gifbox Types
GiftBox.Delay=50;integer , Giftbox Delay

I notice no changes. Slaves follow last order given.


I notice that the SLAV has no sight in shroud however in both cases when being removed or "destroyed". Increasing the Delay to 500 fixes this.



Giftbox with jumpjets:

Insant transforms from units that concert into jumpjet work as expect, the rocketeer starts on the ground and flies of barracks
Transforms that have a delay seem to stop infantry from walking towards their location depending on if Destroy or Remove is used. Remove causes them to stop in their tracks.

Rocketeers that convert to GIs work as expected, the GI stands in the air until ordered to move.
Gis that convert to Rocketeers work as expected, the Rocketeer stands on the ground until ordered to move.
GIs deployed before convert does not negatively impact the jumpjets.


Giftbox with attackdogs:

When giving attack dogs a larger range and slower projectile speed, it can be observed that their delay isn't counted any longer. When given the attack dogs the ability to attack vehicles, their delay is also not counted. This applies to remove or destroy.



Giftbox With Units:

Work as expected, they continue to follow the orders given to the previous unit regardless if removed or destroyed.
Destroyed actually causes them to blow up with the explosion animation taking place.


Giftbox with Battlefortresses
They work as expected. However, infantry in original Battlefortress disappear and are lost with new battlefortress. 
-Infantry do not spawn even with the battlefortress being destroyed rather than removed, even with:
RookiePassengerChance= 100
Survivor.VeteranPassengerChance=100
Survivor.ElitePassengerChance=100

Infantry are unable to enter battlefortresses that are spawned this way, regardless if the previous one had infantry inside it or not, regardless if the previous unit was a battlefortress or not.


Giftbox with slave miner
When destroyed or removed, slaves go neutral, even if the SMIN turns into another SMIN



I will test Units more thoroughly next. This was primarily for infantry. Let me know if there's any questions or tests I should do, or if there's anything else I should have in mind.

2021-11-30 04:09 UTC, Metadorius requested changes
I left some requests and suggestions, due to me doing this at 6AM feel free to argue against some of them. Overall the code style has greately improved since last PRs.

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	static const void LoadFromINI(GiftBoxData& nGiftboxData, INI_EX& parser, const char* pSection)
Could be made prettier as a class method.

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	Valueable<bool> RandomType;
What if instead of RandomType we utilized the system me and Morton have invented for LimboDelivery? as in Types, Weights, Chances?

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	{}
```suggestion
	{ }
```

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +
```suggestion
	explicit GiftBoxData(noinit_t) noexcept { }
```

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	{}
```suggestion
	{ }
```

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	{}
```suggestion
	{ }
```

2021-11-30 04:09 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +		Delay{ nGData.DelayMinMax.Get().Y == 0 ? abs(nGData.Delay.Get()) : abs(ScenarioClass::Instance->Random.RandomRanged(nGData.DelayMinMax.Get().X, nGData.DelayMinMax.Get().Y)) }
Split the line, too long.

2021-12-05 13:03 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.cpp
> +	}
```suggestion
	}
```

2021-12-05 13:05 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.cpp
> +					if (nGiftBox.EmptyCell.Get() && (pCell->GetBuilding() || pCell->GetUnit(false) || pCell->GetInfantry(false)))
```suggestion
					if (nGiftBox.EmptyCell.Get() && (pCell->GetBuilding()
							|| pCell->GetUnit(false) || pCell->GetInfantry(false)))
```

2021-12-05 13:17 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.cpp
> +		}
```suggestion
			strcpy_s(this->TechnoID, newID);
```

2021-12-05 13:17 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.cpp
> +			}
```suggestion
				pTechno->UnInit();
			}
```

2021-12-05 13:18 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.cpp
> +	//	GET_STACK(int, Direction, 0x8);
```suggestion
```

2021-12-05 13:18 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	}
```suggestion
		RandomType.Read(parser, pSection, "GiftBox.RandomType");
	}
```

2021-12-05 13:18 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +		//min(X),max(Y)
```suggestion
```

2021-12-05 13:19 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +		DelayMinMax({ 0,0 }),
```suggestion
		DelayMinMax({ 0, 0 }),

```

2021-12-05 13:20 UTC, Metadorius commented on src/New/Entity/GiftBoxClass.h
> +	Valueable<int> Delay;
Why don't use a timer?

2022-07-30 01:55 UTC, ChrisLv-CN commented
`GiftBox` is a duplicate of Kratos, and I've received reports that Kratos' `GiftBox.RandomDelay` doesn't work, probably because of a conflict. Maybe need a new name.

2024-06-22 12:51 UTC, closed without merging