New logic: Automatic Passenger Deletion
Phobos-developers/Phobos pull request #347
Opened 2021-08-24 21:56 UTC by FS-21

New tags applied in a transport for consuming the passengers after some frames.
PassengerDeletion.Countdown=0           ; integer. Game frames multiplied by the unit size
PassengerDeletion.Soylent=no            ; boolean
PassengerDeletion.SoylentFriendlies=no  ; boolean
PassengerDeletion.Report=               ; sound

Can be combined with Ares abductor logic for a better Chrono Prison & optionally this can refund some money like a Grinder.

2021-08-24 22:20 UTC, FS-21 commented
Because if the logic could be used only for the grinding feature I added a new tag:
PassengerDeletion.SizeDependence=yes
By default the Unit's size is used for calculating the unit's countdown for the deletion. If set "No" then only the PassengerDeletion.Countdown value is used. In that case use PassengerDeletion.Countdown=1 for instant passenger deletion.

2021-09-19 15:20 UTC, Metadorius requested changes

2021-09-19 15:20 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +PassengerDeletion.Report=               ; sound
See tag name suggestions.
```suggestion
PassengerDeletion.Rate=                 ; integer, game frames
PassengerDeletion.Rate.SizeMultiply=yes ; boolean, whether to multiply frames amount by size
PassengerDeletion.Soylent=no            ; boolean
PassengerDeletion.SoylentFriendlies=no  ; boolean
PassengerDeletion.ReportSound=          ; sound
```

2021-09-19 15:20 UTC, Metadorius commented on src/Ext/Techno/Body.h
> +		int PassengerDeletion_Countdown;
Not sure why this is not a timer.

2021-09-19 15:20 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		Valueable<int> PassengerDeletion_Countdown;
Maybe `Nullable` will be better here?

2021-09-24 21:02 UTC, Metadorius requested changes
More style issues that I missed from the last time. Also what about other concerns that I have raised during the last review?

2021-09-26 14:04 UTC, FS-21 reviewed
I think that it's done, maybe.

2021-09-26 14:04 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +						}
changed

2021-09-26 14:04 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +				pData->PassengerDeletion_Countdown--;
changed

2021-09-26 14:04 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +		return;
changed

2021-09-26 14:04 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +void TechnoExt::EatPassengers(TechnoClass* pThis)
Solved?

2021-09-26 14:13 UTC, FS-21 commented on src/Ext/TechnoType/Body.cpp
> +	this->PassengerDeletion_Countdown.Read(exINI, pSection, "PassengerDeletion.Rate");
renamed.

2021-09-26 14:17 UTC, FS-21 commented on src/Ext/TechnoType/Body.h
> +		Valueable<int> PassengerDeletion_Countdown;
PassengerDeletion_Rate should have always a value for if-else comparations :-/

2021-09-26 14:19 UTC, FS-21 reviewed
reviewed without mistakes? :-/

2021-09-26 15:49 UTC, Metadorius approved these changes

2021-09-26 15:50 UTC, Metadorius commented
Good to go, resolve conflicts and you can merge this one.

2021-09-26 18:13 UTC, FS-21 commented
Fixed merge conflicts.

2021-09-30 19:24 UTC, merged