Conditional Death
Phobos-developers/Phobos pull request #349
Opened 2021-08-26 15:19 UTC by FS-21

New ways for self-killing objects under certaing cases.
· No Ammo: The object will die if the remaining ammo reaches 0.
· Countdown: The object will die if the countdown (in frames) reaches 0. Optionally the affected object can decrease the health until the countdown ends.

In rulesmd.ini:

[SOMETECHNO]                       ; TechnoType
Death.NoAmmo=no                    ; boolean
Death.Countdown=0                  ; integer
Death.Countdown.DecreaseHealth=no  ; boolean

2021-09-24 21:49 UTC, YRIDZE submitted a review, later dismissed
Code looks good except for some braces and newlines. Please, fix it and add info to Whats-New.md

2021-09-24 21:49 UTC, YRIDZE commented on src/Ext/Techno/Body.cpp
> +		}
```suggestion
		if (pTypeThis->Ammo > 0 && pThis->Ammo <= 0)
			pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
```

2021-09-24 21:49 UTC, YRIDZE commented on src/Ext/Techno/Body.cpp
> +
```suggestion
```

2021-09-24 21:49 UTC, YRIDZE commented on src/Ext/Techno/Body.cpp
> +
```suggestion
```

2021-09-24 21:49 UTC, YRIDZE commented on src/Ext/Techno/Body.cpp
> +			pData->DeathIfCountdown = pTypeData->DeathIfCountdown; // Start countdown
```suggestion
		else
		{
			pData->DeathIfCountdown = pTypeData->DeathIfCountdown; // Start countdown
		}
```

2021-09-24 21:49 UTC, YRIDZE commented on docs/New-or-Enhanced-Logics.md
> +- New ways for self-killing objects under certaing cases.
TechnoTypes can now self-destruct in new ways in certain cases.

2021-11-13 18:43 UTC, CommanderNour commented
Tested, Everything works just fine

2021-11-16 05:09 UTC, FS-21 commented
Thanks for the testing :-)
This PR can be reviewed if necessary & if acepted then merge.

2022-01-03 18:55 UTC, Metadorius requested changes

2022-01-03 18:55 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		break;
This doesn't belong here.

2022-01-03 18:55 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +void TechnoExt::ApplyDeath_If(TechnoClass* pThis)
This function name is really broken, `CheckDeathConditions` would be better.

2022-01-03 18:55 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +Death.Countdown.DecreaseHealth=no  ; boolean
Mismatch between tag names and internal variable names.

2022-01-03 18:55 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +- Countdown: The object will die if the countdown reaches 0. Optionally the affected object can decrease the Health until the countdown ends.
The `decrease health` part looks pretty pointless to me, one can make the same stuff using a weapon that techno is firing on itself.

2022-01-03 18:55 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +- New ways for self-killing objects under certaing cases.
Brambuca meant that this line should be rephrased.

2022-03-01 17:49 UTC, Metadorius approved these changes
Fix conflicts and merge.

2022-03-01 19:05 UTC, merged