Created script action: Un-register Team success
Phobos-developers/Phobos pull request #364
Opened 2021-09-14 17:28 UTC by FS-21

Is just the opposite effect of 49,0

2021-09-24 21:16 UTC, Metadorius requested changes
Changing script action numbers further is a very bad idea, change it to a final or at least semi-final number (111 I guess?)

2021-09-24 21:16 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		break;
We shouldn't merge it like so, make it 111 or the number that you will implement without the need for other changes further.

2021-09-24 21:17 UTC, Metadorius commented
Also no changelog mention.

2021-09-25 17:03 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +		break;
The problem is FA2 that script action numbers should be consecutive. The last one was 73 and the 74 and forward are the ones of PR #296, being the 111 the first free slot for any of the new script actions I'm creating.

2021-09-25 17:09 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +		break;
Ok, I leave the definitive number 111 and made the mention f the action.

2021-10-03 17:42 UTC, closed without merging