WIP TechnoType conversion warhead
Phobos-developers/Phobos pull request #369
Opened 2021-09-18 17:38 UTC by MortonPL

Documentation excerpt below. Tests encouraged. Marked as WIP until Ares interaction issue is settled.

- Warheads can now change TechnoTypes of affected units to other Types in the same category (infantry to infantry, vehicles to vehicles, aircraft to aircraft). This feature has the same limitations as [Ares' Type Conversion](https://ares-developers.github.io/Ares-docs/new/typeconversion.html). ***This feature does not support Ares' new entities.*** This means that i.e. upon converting to a unit with AttachEffect, the effect ***will not*** be present. ***This feature does not support BuildingTypes at the moment.***
  - `Converts` enables the logic.
  - `Converts.From` specifies which TechnoTypes are valid for conversion. This entry can have many types listed, meanging that many types will be converted at once.
  - `Converts.To` specifies which TechnoTypes are the result of converion. This entry should have the same length as `Converts.From`, as every listed type can convert separately.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]
Converts=false			; boolean
Converts.From=			; list of tehnoTypes
Converts.To=			        ; list of TechnoTypes
```

2021-09-18 19:05 UTC, Falaka21 commented
This solves everything for me.I know ,here  is  not the place for making these kind of conversations, but  I think, even this supreme product comes closer to its upper limits. I can't think even what can be made for a 21 years old  2,5D  game engine...Finally ,we might use global upgrade system like C&C Generals(ZH), C&C3 (KW) and RA3(UpR) uses...

2021-11-13 13:45 UTC, CommanderNour commented
Works like a charm finally we can have a proper upgrade system

2022-10-01 19:41 UTC, MortonPL commented
Converting to draft again, as I want to add mass conversion on SW launch. For that I need changes from #760.

2022-10-13 13:25 UTC, chaserli commented on src/Misc/AresData.cpp
> +void __stdcall AresData::CallHandleConvert(TechnoClass* pTechno, TechnoTypeClass* pConvertTo)
Are you sure the return type is not bool?

2022-10-23 16:24 UTC, MortonPL commented on src/Misc/AresData.cpp
> +void __stdcall AresData::CallHandleConvert(TechnoClass* pTechno, TechnoTypeClass* pConvertTo)
Updated definition and handled return value.

2022-10-23 17:03 UTC, chaserli requested changes

2022-10-23 23:05 UTC, MortonPL commented on src/Misc/AresData.cpp
> +	AresData::AresBaseAddress = GetModuleBaseAddress(ARES_DLL_S);
Added.

2022-10-24 00:32 UTC, MortonPL commented on src/Misc/AresData.cpp
> +	0x43650, 0x44130,	// HandleConvert
"[...] more organized like YRpp" might be more difficult, because we're not dealing with absolute addresses and we have to take into account multiple versions. I believe that this system's extensibility and performance outweights the work required to add a new function (increment AresData::AresFunctionCount, add addresses to AresData::AresFunctionOffsets, declare & define functions).

2022-10-31 09:26 UTC, brsajo commented
Latest version of this PR causes crashes when something is converted, both with SW and Warhead versions. Was working on a previous version with the same code but I'm not sure which.

2022-10-31 11:31 UTC, FS-21 commented
Hi,
It would be very useful for the developer if you zip the crash folder (if you didn't  have more crashes its the one with the most recent date, inside the debug folder) and upload it in Google Drive or similar service.

2022-10-31 11:33 UTC, chaserli commented
> Latest version of this PR causes crashes when something is converted, both with SW and Warhead versions. Was working on a previous version with the same code but I'm not sure which.

The last build has a merge conflict with the develop branch because I reverted several commits. I already updated this PR, you can check if the problem still exists

2022-11-01 06:02 UTC, chaserli commented on docs/New-or-Enhanced-Logics.md
> +Convert.AffectedHouses=owner    ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
Shouldn't this be controlled by AffectsAllies/AffectsEnemies/AffectsOwner already?

2023-03-04 14:09 UTC, closed without merging