Implement issue #372
Phobos-developers/Phobos pull request #373
Opened 2021-09-20 13:22 UTC by secsome

Closes #372 

### Default disguise for each InfantryType
- Infantry with `DefaultDisguise` can now has its own default disguise.
  - This tag's priority is higher than Ares' [Sides]>DefaultDisguise

In `rulesmd.ini`:
```ini
[SOMEINFANTRY]                    ; InfantryType
DefaultDisguise=E2                ; InfantryType              
```

2021-09-21 14:35 UTC, Thrifinesma commented
What if this expands to per side like Ares' `Survivor.Side#=` or per country?

2021-09-23 15:28 UTC, secsome commented
> What if this expands to per side like Ares' `Survivor.Side#=` or per country?

I think it should be implemented in another PR, leave it later

2021-09-24 19:50 UTC, Metadorius requested changes
Code quality is good except the addresses part. Fix it - and then it will be mergable.

2021-09-24 19:50 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +DefaultDisguise=E2                ; InfantryType
```suggestion
[SOMEINFANTRY]      ; InfantryType
DefaultDisguise=E2  ; InfantryType              
```

2021-09-24 19:50 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +  - This tag's priority is higher than Ares' [Sides]>DefaultDisguise
```suggestion
### Default disguise for individual InfantryTypes

- Infantry can now have its `DefaultDisguise` overridden per-type.
  - This tag's priority is higher than Ares' per-side `DefaultDisguise`.
```

2021-09-24 19:50 UTC, Metadorius commented on src/Ext/TechnoType/Hooks.cpp
> +			return R->Origin() == 0x522790 ? 0x5227BF : 0x6F4277;
The raw addresses that are used here are non-descriptive. Use anonymous enum to alias them.

2021-09-25 15:33 UTC, Metadorius approved these changes

2021-09-25 15:33 UTC, merged

2025-02-14 18:22 UTC, DmitryVolkov666 commented
[SOMEINFANTRY] 
DefaultDisguise=

![image1](https://github.com/user-attachments/assets/643a79f1-0c79-4287-93ab-d3295979312c)
![image4](https://github.com/user-attachments/assets/5f571966-31ff-4daf-8392-1273256c383b)
![image3](https://github.com/user-attachments/assets/d4c92362-8adb-4ece-997a-bb811b74ce44)
![image2](https://github.com/user-attachments/assets/a53dcad0-876e-4145-a3cb-921118618219)

I (Volkov_T-666), as the owner, am red (My color)
YuriAL sees it as yellow (Own color)
Zazo4ek sees it as purple (Own color)

Although they both (YuriAL, Zazo4ek) should see it with red collor (My)

Moreover, if you try to disguise yourself in multiplayer as a foot soldier who already has a default disguise that doesn't work correctly, the game will crash referring to gamemd.exe and address (not immediately, but after a few tries).

But if we use it from ares:

[SOMESIDE]
DefaultDisguise=

There are no such problems. the owner of the object will be displayed correctly and there are no crashes when trying to disguise

![image5](https://github.com/user-attachments/assets/ae50cd0d-df15-461e-9938-5841a73723eb)

I hope I explained everything clearly. My translation is very bad