Customizable OpenTopped Properties
Phobos-developers/Phobos pull request #374
Opened 2021-09-21 00:21 UTC by Otamaa

close #7 
this also partially solve #225 

### Customizable OpenTopped Properties

- You can now specify settings of `OpenTopped` transport locally

```ini
[SOMETECHNO]			       ; require `TechnoType` with `OpenTopped=yes`
OpenToppedRangeBonus=1			; integer, range bonuses for troops shooting from open topped transport
OpenToppedDamageMultiplier=1.3       ; float , damage bonuses for troops shooting from open topped transport
OpenToppedWarpDistance=8		; integer , temporal range bonuses for troops shooting from open topped transport

2021-09-21 04:38 UTC, secsome commented
I recommend to use Ares style tag naming like the following:
```ini
OpenTopped.RangeBonus
OpenTopped.DamageMultiplier
OpenTopped.WarpDistance
```

2021-09-21 14:31 UTC, Thrifinesma commented on src/Ext/Techno/Hooks.cpp
> +		}
```suggestion
		if (auto pExt = TechnoTypeExt::ExtMap.Find(pTransport->GetTechnoType()))
		{
			R->EAX(pExt->OpenToppedRangeBonus.Get(RulesClass::Instance->OpenToppedRangeBonus));

			return 0x6F72DE;
		}
```

2021-09-21 14:31 UTC, Thrifinesma commented on src/Ext/Techno/Hooks.cpp
> +			}
```suggestion
			if (auto pExt = TechnoTypeExt::ExtMap.Find(pTransport->GetTechnoType()))
			{
				//it is float isnt it YRPP ? , check tomson26 YR-IDB !
				nDamageMult = pExt->OpenToppedDamageMultiplier.Get(nDamageMult);
			}
```

2021-09-21 14:31 UTC, Thrifinesma commented on src/Ext/Techno/Hooks.cpp
> +		auto nDamageMult = static_cast<float>(RulesClass::Instance->OpenToppedDamageMultiplier);
```suggestion
		float nDamageMult = static_cast<float>(RulesClass::Instance->OpenToppedDamageMultiplier);
```

2021-09-24 20:11 UTC, Metadorius requested changes
Code style is good mostly. Fix stuff pointed out in comments and add readme entry for your contribution.

2021-09-24 20:11 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +OpenTopped.WarpDistance=8		; integer , temporal range bonuses for troops shooting from open topped transport
```suggestion
### Customizable OpenTopped properties

- You can now override `OpenTopped` properties per TechnoType.

```ini
[SOMETECHNO]                  ; TechnoType
OpenTopped.RangeBonus=        ; integer
OpenTopped.DamageMultiplier=  ; float
OpenTopped.WarpDistance=      ; integer
```

2021-09-24 20:11 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	return 0x6FE460;
Better use anonymous enums here, it's not instantly obvious what those returns mean.

2021-09-24 20:11 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +	this->OpenToppedWarpDistance.Read(exINI, pSection, "OpenTopped.WarpDistance");
Either remove the dot in tag names or add the underscore to match the writing of the tag.

2021-09-24 20:11 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	//#define Die(x) x + 10
```suggestion
```

2021-09-24 20:11 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	//#undef Die(x)
```suggestion
```

Don't leave commented obsolete code in pull requests.

2021-09-25 10:32 UTC, Metadorius approved these changes

2021-09-25 10:32 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	enum{ ApplyDamageMult = 0x6FE45A , ContinueCheck = 0x6FE460 };
```suggestion
	enum { ApplyDamageMult = 0x6FE45A, ContinueCheck = 0x6FE460 };
	
	GET(TechnoClass* const, pThis, ESI);
```

2021-09-25 10:32 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
>  		{ }
```suggestion
		{ }
```

2021-09-25 10:32 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +			return 0x71A838;
```suggestion
			return 0x71A838;
```

2021-09-25 10:32 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +		return ApplyDamageMult;
```suggestion
		R->EAX(Game::F2I(nDamage * nDamageMult));
		return ApplyDamageMult;
```

2021-09-25 10:32 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +			return 0x6F72DE;
```suggestion
			R->EAX(pExt->OpenTopped_RangeBonus.Get(RulesClass::Instance->OpenToppedRangeBonus));
			return 0x6F72DE;
```

2021-09-25 10:42 UTC, merged