New Attack actions 74-81
Phobos-developers/Phobos pull request #378
Opened 2021-09-24 16:33 UTC by FS-21

Due to the size of the PR 296 I'll split in smaller PRs. and once all the parts get merged then close the PR 296.

Since this Attack function is the base of new attacks I can't reduce it more.

A few brave testers explained that these actions 74-81 does what is intended.

I think that what is needed is a code review & if approved then merge.

2021-09-24 21:04 UTC, YRIDZE requested changes
Please, clean your code from unnecessary comments. I suggest to re-read the braces style guide part.

2021-09-24 21:18 UTC, Metadorius commented
Should also add a changelog mention.

2021-09-24 21:29 UTC, Metadorius requested changes
Should also add a changelog mention.

2021-09-25 16:18 UTC, FS-21 commented on docs/New-or-Enhanced-Logics.md
> +Note: All Aircrafts that attacks other air units will end the script. This behavior is intentional because without it aircrafts had some bugs that wasn't fixable at the time of developing the feature
Any hint for a non-native speaker? :-/
Line 517 "looks" fine...
The table "seems" fine...
Line 536 is fine?
Maybe in 538 is "... Aircrafts that attack other air units ..." &
"it aircrafts had some bugs that weren't fixable"

If those grammar mistakes aren't he ones I mentioned then I have no idea. Any English teacher in the room? :-P

2021-09-25 16:41 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +Note: All Aircrafts that attacks other air units will end the script. This behavior is intentional because without it aircrafts had some bugs that wasn't fixable at the time of developing the feature
We also aren't native speakers :P
`These Actions instruct`
`New Attack action scripts`
`All Aircrafts that attack`
`(74, 75, 78, 79)`
+ the ones you pointed out.

2021-09-25 16:55 UTC, FS-21 commented on docs/New-or-Enhanced-Logics.md
> +Note: All Aircrafts that attacks other air units will end the script. This behavior is intentional because without it aircrafts had some bugs that wasn't fixable at the time of developing the feature
I think I fixed all the mentioned mistakes (I never used before the GH web editor for modifying files).
If I marked something as "Viewed" in this review by mistake is because I'm not used to the tool and maybe I ignored something by ignorance.

2021-09-25 18:10 UTC, FS-21 reviewed
Checked, but I'll see now if there are more needed changes in the code style.

2021-09-26 11:10 UTC, FS-21 reviewed
I checked the code style in src/Ext/Script/Body.cpp
can be rechecked if necessary.

2021-09-26 13:54 UTC, FS-21 reviewed
I think that I made all the changes in that file

2021-09-26 13:54 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +				if ((passengerWeaponType1 && passengerWeaponType1->Projectile->AA) || (passengerWeaponType2 && passengerWeaponType2->Projectile->AA))
Edited

2021-09-26 13:54 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +				if ((passengerWeaponType1 && passengerWeaponType1->Projectile->AG) || (passengerWeaponType2 && passengerWeaponType2->Projectile->AG))
Edited

2021-09-26 13:54 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +			&& (!pLeaderUnit->Owner->IsAlliedWith(pFocus) || (pLeaderUnit->Owner->IsAlliedWith(pFocus) && pFocus->IsMindControlled() && !pLeaderUnit->Owner->IsAlliedWith(pFocus->MindControlledBy))))
Changed as requested

2021-09-26 13:54 UTC, FS-21 commented on src/Ext/Script/Body.cpp
> +						&& (pUnitType->WhatAmI() == AbstractType::AircraftType && abstract_cast<AircraftTypeClass*>(pUnitType)->AirportBound)
changed.

2021-09-30 18:46 UTC, Metadorius approved these changes
I left a few more changes to make changes better.

2021-09-30 18:47 UTC, Metadorius commented
Also fixed a bad merge.

2021-09-30 18:47 UTC, merged