Action Script 113: Conditional skip next action
Phobos-developers/Phobos pull request #419
Opened 2021-10-28 15:25 UTC by FS-21

New Script Action 113,n
"n" is an integer from 0 to 100 and is a success percentage value. If the dice is lower than the "n" value then the next line of the script list will be skipped. Default to 0.

2021-11-16 05:06 UTC, FS-21 commented
This PR can be reviewed & if acepted then merge.

2021-11-17 17:29 UTC, FS-21 commented
Examples for testing it:

```
; Script test 1
[B0000001-G]
Name=test 1
0=113,80 ; 80% of skipping the next action
1=0,5    ; Attack vehicles
2=0,2    ; attack structures
3=6,1    ; just return to the action 113

; Script test 2
[B0000002-G]
Name=test 2
0=113,20 ; 20% of skipping the next action
1=0,5    ; Attack vehicles
2=0,2    ; attack structures
3=6,1    ; just return to the action 113

; Script test 3
[B0000003-G]
Name=test 3
0=113,0 ; 0% of skipping the next action (never skips the next action)
1=0,5    ; Attack vehicles
2=0,2    ; attack structures
3=6,1    ; just return to the action 113

; Script test 4
[B0000004-G]
Name=test 4
0=113,20 ; 100% of skipping the next action (always skips the next action)
1=0,5    ; Attack vehicles
2=0,2    ; attack structures
3=6,1    ; just return to the action 113
```

2021-11-24 09:31 UTC, Metadorius requested changes
Doc, what's new and readme entries are not present.

2021-11-24 09:31 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		Debug::Log("DEBUG: ScripType: [%s] [%s] Jump to NEXT line: %d = %d,%d -> (Reason: No team members alive)\n", pTeam->Type->ID, pTeam->CurrentScript->Type->ID, pTeam->CurrentScript->idxCurrentLine +
Break up the line in a few because it's not convenient to read such long lines.

2021-11-24 09:31 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		Debug::Log("DEBUG: ScripType: [%s] [%s] (line: %d) Next script line skipped successfuly. Next line will be: %d = %d,%d\n", pTeam->Type->ID, pTeam->CurrentScript->Type->ID, pTeam->CurrentScript->idx
Ditto.

2021-11-24 17:04 UTC, FS-21 reviewed
Split some Log lines into multiples lines as requested.

2022-01-04 23:33 UTC, FS-21 commented
> Doc, what's new and readme entries are not present.

All documentation was added weeks ago. It's action 113

2022-01-05 10:23 UTC, Metadorius approved these changes

2022-01-06 22:23 UTC, merged