WIP Make Image work for InfantryTypes and VehicleTypes in artmd.ini
Phobos-developers/Phobos pull request #434
Opened 2021-11-15 00:00 UTC by MortonPL

`Image` tag in artmd.ini previously was available only for BuildingTypes and AnimationTypes. Now it is possible to use it for InfantryTypes ~~and VehicleTypes~~. Usage is the same as with BuildingTypes/AnimationTypes.

```ini
[SOMEINFANTRY]
Image=        ; name of the file that will be used as image, without extension
```

2021-11-15 13:10 UTC, mevitar commented
This will affect vanilla YR since multiple units and infantry have Image= in their art entries (Camel, Clint Eastwood, Battle Fortress...).

2021-11-15 13:55 UTC, MortonPL commented
@mevitar By default this feature will be disabled to ensure that vanilla state of the game remains unchanged.

2021-11-15 16:32 UTC, MortonPL commented
Outside of SHP vehicles, this PR is ready for testing. All features should be reliably working, but the documentation is to be done.

2021-11-21 13:35 UTC, YRIDZE requested changes
Code looks good except for some newlines. Please, fix it.

2021-11-21 13:35 UTC, YRIDZE commented on src/Misc/Hooks.Image.cpp
> +		if (CCINIClass::INI_Art->ReadString(aircraftType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```suggestion
		GET(AircraftTypeClass*, aircraftType, ESI);
		char nameBuffer[0x19];
		
		if (CCINIClass::INI_Art->ReadString(aircraftType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```

2021-11-21 13:35 UTC, YRIDZE commented on src/Misc/Hooks.Image.cpp
> +		if (CCINIClass::INI_Art->ReadString(infantryType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```suggestion
		GET(InfantryTypeClass*, infantryType, ESI);
		char nameBuffer[0x19];
		
		if (CCINIClass::INI_Art->ReadString(infantryType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```

2021-11-21 13:35 UTC, YRIDZE commented on src/Misc/Hooks.Image.cpp
> +		if (CCINIClass::INI_Art->ReadString(unitType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```suggestion
		GET(UnitTypeClass*, unitType, EDI);
		char nameBuffer[0x19];
		
		if (CCINIClass::INI_Art->ReadString(unitType->ImageFile, "Image", 0, nameBuffer, 0x19) != 0)
```

2021-11-21 18:05 UTC, Metadorius approved these changes

2021-11-23 18:20 UTC, merged

2023-08-09 15:26 UTC, zhztheplayer commented
Is this feature still working? I tried with it following the doc but ended up like no image is replaced.

Also no "[Phobos] Replacing image for %s with %s.\n" log was found so I guess the hooks in `Hooks.Image.cpp` were not entered?

2023-08-09 15:33 UTC, zhztheplayer commented
This is what I have done with the files (I just copy & paste the texts from my files to make sure we can see potential typos):

`mymap.yrm`
```
[General]
ArtImageSwap=true

[CAPOC_BOSS]
Image = CAPOC_BOSS
...
```

`artmd.ini`
```
[CAPOC_BOSS]
Image = CMTNK
Voxel = yes
LaserTrail0.Type = GENERATED_LASER_TRAIL_4
PrimaryFireFLH = 570,75,360
Cameo = CMTNKICON
AltCameo = CMTNKUICO
Remapable = yes
```

I am using Ares 3.0 and Phobos 0.3.0.0

2023-08-09 15:40 UTC, zhztheplayer commented
It seems that I've found the reason...

If I put `ArtImageSwap=true` into `rulesmd.ini`, the feature works properly. However it doesn't work if I just put it into `mymap.yrm` without changing `rulesmd.ini`.

Is this something by design? @Metadorius I am feeling like changes to `[General]` section in map file always work for me as well  changing `rulesmd.ini`

2023-08-09 21:12 UTC, mevitar commented
Usually you'll need to add entries to rulesmd.ini in order for maps to use them or modify them properly. For example, Ares SWs added through maps will not work, but they will work if the map modifies existing SWs.
It's probably something similar going on here, and i think it's just a limitation of how maps work, and not a fault of Phobos.

2023-08-09 21:40 UTC, Metadorius commented
I am not sure if by design, maybe @MortonPL  knows.

2023-08-10 01:03 UTC, zhztheplayer commented
Aha, that makes sense. Thank you guys for helping.

2023-08-10 11:02 UTC, MortonPL commented
TechnoTypes art is swapped when their sections are being read and when `ArtImageSwap=true`. The rules reading order (limiting to relevant things) is:
1. [General],
1. TechnoTypes,
1. scenario

So if you don't have `ArtImageSwap=true` in 1., then nothing happens in 2., even if in 3. it is defined. However, if you have TechnoTypes (re)defined in scenario rules, they might be affected, not sure.