AITriggers support upgrades
Phobos-developers/Phobos pull request #436
Opened 2021-11-16 08:26 UTC by Thrifinesma

In vanilla, it is not allowed that use Building Upgrades in AITriggerTypes. This would fix that.

2021-11-21 17:50 UTC, YRIDZE requested changes
Code looks pretty good. Please, fix some codestyle mismatches.

2021-11-21 17:50 UTC, YRIDZE commented on src/Misc/Hooks.BugFixes.cpp
> +						count++;
```suggestion
				for (const auto& pUpgrade : pBld->Upgrades)
				{
					if (pUpgrade == pType)
						count++;
				}
```

2021-11-21 17:50 UTC, YRIDZE commented on src/Misc/Hooks.BugFixes.cpp
> +	return R->Origin() + 0xC;
```suggestion
	R->EAX(count);
	
	return R->Origin() + 0xC;
```

2021-11-21 17:50 UTC, YRIDZE commented on src/Misc/Hooks.BugFixes.cpp
> +	// TODO: support Phobos extended Building Upgrades logic
```suggestion
	
	// TODO: support Phobos extended Building Upgrades logic
```

2021-11-26 13:19 UTC, ayylmaoRotE commented
tested and can confirm working

2021-12-08 22:40 UTC, Metadorius approved these changes
![image](https://user-images.githubusercontent.com/17500545/145302825-d72244e0-c457-43af-99af-d90f0ae7d937.png)

2021-12-09 09:37 UTC, Metadorius approved these changes

2021-12-09 09:38 UTC, merged