CreateUnit improvements
Phobos-developers/Phobos pull request #440
Opened 2021-11-17 10:28 UTC by Starkku

- `CreateUnit.ConsiderPathfinding`, if set, makes game look for eligible cells around the animation's coordinates if the cell at those coordinates is not passable to the created unit, and creates the unit at the first eligible cell found instead.
- Warhead `AnimList/SplashList` animations and animations created through map trigger action `41 Play Anim At` now have owner set correctly if the animation has `CreateUnit` set.

2021-11-17 21:29 UTC, CommanderNour commented
Tested & working correctly

2021-11-21 18:00 UTC, YRIDZE requested changes
Please, check my comments and fix the issues. Add info to "What`s New".

2021-11-22 21:06 UTC, Starkku commented
> Please, check my comments and fix the issues. Add info to "What`s New".

This particular pull request does not warrant a separate entry in "What's New" as the only changes contained are additions to a feature that is being introduced in the version the "What's New" is currently comprised of.

2021-11-23 18:19 UTC, Metadorius approved these changes

2021-11-23 18:19 UTC, Metadorius commented on src/Ext/AnimType/Hooks.AnimCreateUnit.cpp
> +		}
```suggestion
		if (auto unit = pTypeExt->CreateUnit.Get())
			AnimExt::SetAnimOwnerHouseKind(pAnim, pHouse, pHouse, pHouse);

```

2021-11-23 18:19 UTC, Metadorius commented on src/Ext/AnimType/Hooks.AnimCreateUnit.cpp
> +		}
```suggestion
		if (TechnoClass* Target = generic_cast<TechnoClass*>(pThis->Target))
			pVictim = Target->Owner;
```

2021-11-23 18:19 UTC, Metadorius commented on src/Ext/AnimType/Hooks.AnimCreateUnit.cpp
> +		}
```suggestion
		if (auto unit = pTypeExt->CreateUnit.Get())
			AnimExt::SetAnimOwnerHouseKind(pAnim, pInvoker, pVictim, pInvoker);
```

2021-11-23 18:20 UTC, merged