Shield modification warheads & minor fixes/additions
Phobos-developers/Phobos pull request #441
Opened 2021-11-17 21:10 UTC by Starkku

```
[SOMESHIELDTYPE]                    ; ShieldType name
InitialStrength=0                   ; integer

[SOMEWARHEAD]                       ; WarheadType
Shield.Penetrate=false              ; boolean
Shield.Break=false                  ; boolean
Shield.BreakAnim=                   ; animation
Shield.AbsorbPercent=               ; double, percents
Shield.PassPercent=                 ; double, percents
Shield.Respawn.Amount=0.0           ; double, percents or absolute
Shield.Respawn.Rate=-1.0            ; double, ingame minutes
Shield.SelfHealing.Duration=0       ; integer, game frames
Shield.SelfHealing.Amount=0.0       ; double, percents or absolute
Shield.SelfHealing.Rate=-1.0        ; double, ingame minutes
Shield.AffectTypes=                 ; List of ShieldType names
Shield.AttachTypes=                 ; List of ShieldType names
Shield.RemoveTypes=                 ; List of ShieldType names
Shield.ReplaceOnly=false            ; boolean
Shield.InheritStateOnReplace=false  ; boolean
```

- `InitialStrength` can be used to set a different initial strength value from maximum.
- `Shield.Respawn.Rate` & `Shield.Respawn.Amount` override ShieldType `Respawn.Rate` and `Respawn.Amount` for next shield respawn, respectively. Negative rate & zero or lower amount default to ShieldType values. If applied when respawn timer is active, current timer is reset.
- `Shield.SelfHealing.Rate` & `Shield.SelfHealing.Amount` override ShieldType `SelfHealing.Rate` and `SelfHealing.Amount` for duration of `Shield.SelfHealing.Duration` amount of frames. Negative rate & zero or lower amount default to ShieldType values. Current self-healing timer is reset upon applying this effect and once it ends.
- `Shield.AffectsTypes` allows listing which ShieldTypes can be affected by any of the effects listed above. If none are listed, all ShieldTypes are affected.
- `Shield.AttachTypes` & `Shield.RemoveTypes` allows listing ShieldTypes that are attached or removed, respectively from any targets affected by the warhead (positive `Verses` values). Normally only first listed ShieldType in `Shield.AttachTypes` is applied.
  - If `Shield.ReplaceOnly` is set, shields from `Shield.AttachTypes` are only applied to affected targets from which shields were simultaneously removed, matching the order listed in `Shield.RemoveTypes`. If `Shield.AttachTypes` contains less items than `Shield.RemoveTypes`, last item from the former is used for any remaining removed shields.
  - If `Shield.InheritStateOnReplace` is set, shields replaced via `Shield.ReplaceOnly` inherit the current strength (relative to ShieldType `Strength`) of the previous shield and whether or not the shield was currently broken. Self-healing and respawn timers are always reset.

## Note the spelling changes for `PenetratesShield`, `BreaksShield`, `AbsorbPercentShield` and `PassPercentShield`!

In addition, following Phobos bugs were fixed:

- Shields being able to be damaged when under effects of `Temporal` warheads.
- `AbsorbPercentShield` and `PassPercentShield` not being saved properly.

2021-11-18 14:05 UTC, Starkku commented
Misc. additions & fixes.

- Implemented `BreakWeapon` & `Shield.BreakWeapon`, a weapon that is fired on the TechnoType with the shield when the shield breaks.
- Adjusted how `Shield.SelfHealing` & `Shield.Respawn` affect timers and added `ResetTimer` keys to control whether or not timers are reset on application.
- Made `Shield.BreakAnim` apply if Warhead breaks shield through damage.
- Implemented `Shield.HitAnim`.

2021-11-19 19:56 UTC, Starkku commented
Further adjustments to the timer logic.

- Added `Shield.Respawn.Duration` and made it run on timer instead of always applying to next shield respawn.
- Duration of respawn & self-healing warhead effects should now correctly reset on re-applying the effect.

2021-11-21 21:04 UTC, YRIDZE requested changes
Code seems good. I found several problems in "if" statements. Please fix it.

2021-11-21 21:04 UTC, YRIDZE commented on src/New/Entity/ShieldClass.cpp
> +	if (this->Temporal || !this->HP || *args->Damage == 0 || this->Techno->IsIronCurtained() || pWHExt->Shield_Penetrate)
Please, split it up into a few lines.

2021-11-28 17:56 UTC, Starkku commented
- Fixed a potential issue with shield attaching, not sure what kind of problems it may have caused (it replaced the currently used ShieldType even if it couldn't replace shield (new type has Strength <=0 or the unit already had a shield).
- Added an option to allow replacing non-respawning shields via attaching a new one.

2021-12-08 18:07 UTC, Metadorius commented on src/Ext/WarheadType/Body.h
> +			, Shield_SelfHealing_Rate_InMinutes(-1.0)
```suggestion
			, Shield_SelfHealing_Duration(0)
			, Shield_SelfHealing_Amount(0.0)
			, Shield_SelfHealing_Rate(-1)
			, Shield_SelfHealing_Rate_InMinutes(-1.0)
```

2021-12-08 22:25 UTC, Metadorius approved these changes

2021-12-08 22:25 UTC, merged