Attached animation Layer customization.
Phobos-developers/Phobos pull request #444
Opened 2021-11-19 20:44 UTC by Starkku

2021-11-20 23:02 UTC, mevitar commented
AllowLayerDeviation=no or JumpjetAllowLayerDeviation=no causes jumpjets to be untargetable while on the ground. Weapons that can attack both air and ground will be able to target them, but will do damage instead.

2021-11-20 23:37 UTC, mevitar commented
As for updating mods and unmodded YR to adjust for this build, i noticed that the default layering for DrainAnimationType= changed now, as it will be drawn over the Floating Disk (or similar unit) instead of under. It needs Layer.UseObjectLayer= to be manually set to "no" to work as it used to.
Something that might need to be added in the documentation.

Didn't notice other issues so far.

2021-11-21 12:44 UTC, Starkku commented
Fixed jumpjets using wrong layer when on ground problem and changed the behaviour of `Layer.UseObjectLayer`. If it is not set then attached animations use `ground` layer like before. Setting it to `true` or `false` is what makes it follow the object's layer or respect the animation `Layer` setting, respectively so there are no backwards compatibility issues whatsoever now.

2021-11-21 18:14 UTC, YRIDZE requested changes
Code looks good.  Please, fix just one issue.

2021-11-22 17:50 UTC, mevitar commented
Didn't find any issues anymore.

2021-11-23 18:23 UTC, Metadorius approved these changes

2021-11-23 18:23 UTC, Metadorius commented on src/Ext/AnimType/Body.cpp
> +	this->Layer_UseObjectLayer .Read(exINI, pID, "Layer.UseObjectLayer");
```suggestion
	this->Layer_UseObjectLayer.Read(exINI, pID, "Layer.UseObjectLayer");
```

2021-11-23 18:25 UTC, merged

2023-05-12 21:37 UTC, mevitar commented
I can't find AllowLayerDeviation and JumpjetAllowLayerDeviation in the newest doc. Was this feature entirely removed, or is it undocumented?

2023-05-12 22:03 UTC, Starkku commented
> I can't find AllowLayerDeviation and JumpjetAllowLayerDeviation in the newest doc. Was this feature entirely removed, or is it undocumented?

Was removed in favour of fixing the layering properly by default.

2023-05-12 23:19 UTC, mevitar commented
> If the old approach was more desirable in certain cases, must've flown over my head.

I was trying to do it the old way and i jumpjets were covering the AE animation when they were in the top position of the wobble, so i was wondering whether something broke or did i use it incorrectly.

But no worries, since i can use YSortAdjust now i will do it with Layer.UseObjectLayer=yes on the animation (it seems to work fine so far, so that solves my problem).

2023-05-13 00:02 UTC, mevitar commented
Ugh, and right after i wrote that it works fine, i get the jumpjets clipping over the anim again. Worst part is, it doesn't always happen. Sometimes it always stays on top, and sometimes it vanishes when the aircraft is in top position. Same thing happens with YSortAdjust=20 and default value.
I even tried attaching the anim while the unit is on the ground, and then the anim went under the unit once it lifted up, and stayed like that forever.

I think it might have something to do with the position that the unit is in at the moment the animation is attached to it - if it's on top, then the animation will stay always on top, but if it's at the bottom, then it will vanish if the unit cycles to the top. I guess Layer.UseObjectLayer=yes might not be updating the layer properly.

Of course if i set Layer.UseObjectLayer=no and Layer=top then the animation always stays on top of the unit, but i wanted to avoid that because the animation can be attached to ground units.

2023-05-13 13:42 UTC, Starkku commented
>  I guess Layer.UseObjectLayer=yes might not be updating the layer properly.

Correct. It doesn't work correctly in all cases, bit of a design fault. Updating it it do that might be bit of a task but I'll take a look.

2023-05-13 22:52 UTC, mevitar commented
Checked the newest devbuild, and this time I couldn't find any issues with Layer.UseObjectLayer=yes on jumpjets.
(i hope i won't have to come here again in 10 minutes to say i was wrong)