IsSimpleDeployer improvements
Phobos-developers/Phobos pull request #446
Opened 2021-11-20 22:31 UTC by Starkku

- `DeployDir` can be used to set the facing the vehicle needs to turn towards before deploying if it has `DeployingAnim` set. This is works the same as Ares flag of same name other than allowing use of negative numbers to disable the direction-specific deploy and that it only applies to units on ground.
- In addition there are some new options for `DeployingAnim`:
  - `DeployingAnim.KeepUnitVisible` determines if the unit is hidden while the animation is playing.
  - `DeployingAnim.ReverseForUndeploy` controls whether or not the animation is played in reverse for undeploying.
  - `DeployingAnim.UseUnitDrawer` controls whether or not the animation is displayed in the unit's palette and team colours.

In `rulesmd.ini`:
```ini
[SOMEVEHICLE]                          ; VehicleType
DeployDir=0                            ; integer, facing or a negative number to disable.
DeployingAnim.KeepUnitVisible=false    ; boolean
DeployingAnim.ReverseForUndeploy=true  ; boolean
DeployingAnim.UseUnitDrawer=true       ; boolean
```

2021-11-21 20:52 UTC, YRIDZE requested changes
Code looks good. Just please correct a couple of points.

2021-11-21 20:52 UTC, YRIDZE commented on src/Ext/TechnoType/Hooks.cpp
> +			pThis->DeployAnim = nullptr;
```suggestion
		else
		{
			pThis->DeployAnim = nullptr;
		}
```

2021-11-22 19:42 UTC, mevitar commented
DeployingAnim.X= additions and sound changes work fine, didn't notice any issues there.

2021-11-22 19:44 UTC, mevitar commented
As for DeployDir, i'll be a downer here, but did it really have to be changed?
AFAIK it already worked _any_  VehicleType with a DeployingAnim= before build, including type conversion ones (i know, i use it extensively). Furthermore, it used to default to the [General]DeployDir= setting, but now it doesn't read that one and everything faces 0 direction unless i manually change it for each unit. So this change feels more like a downgrade.

2021-11-22 19:48 UTC, Starkku commented
> As for DeployDir, i'll be a downer here, but did it really have to be changed? AFAIK it already worked _any_ VehicleType with a DeployingAnim= before this build, including type conversion ones (i know, i use it extensively). Furthermore, it used to default to the [General]DeployDir= setting, but now it doesn't read that one and everything faces 0 direction unless i manually change it for each unit. So this change feels more like a downgrade.

It worked but it was also *forced* on any unit with DeployingAnim, allowing no direction-agnostic deploy combined with animation. With regular animation settings this isn't particularly useful but with the additions here that's another story. Not defaulting to `[General] -> DeployDir` is a bug, it should default to it and it not being mentioned in documentation is an oversight.

2021-11-22 20:43 UTC, mevitar commented
Fair enough. I thought it was intentional since the doc says that DeployDir is set to 0 (which is an actual ingame direction) by default.

2021-11-22 21:00 UTC, Starkku commented
Implemented code style suggestions and following tweaks:

- Units now automatically start deploy process/DeployingAnim once they are done turning to the correct direction.
- Make TechnoType->DeployDir default to General->DeployDir properly.

Both are also now mentioned in documentation.

2021-11-22 23:40 UTC, mevitar commented
I think that making deploy process start immediately causes a rare bug that i'm not able to reproduce: the deploying vehicle vanishes and gets stuck in undeployed form, unable to move, and without an image (it was a unit-unit conversion).

On the left there is the unit that lost its image and is stuck (you can faintly see the AE animation on it still active, though). On the right there is a bunch of that unit type but they deployed succesfully. No entries from this build were used for this unit, everything is the same as i used before i did the tests.
![nanidafuq](https://user-images.githubusercontent.com/1313344/142950432-4185bfeb-d3ae-4674-860a-94eab05d7e74.png)

Also noticed that the same unit, if initially facing a direction different than the deploying one (specified as being ingame south here), it will vanish for like 1 frame when the deploy animation didn't start yet, making it look as if it blinked for a moment. This doesn't happen if it already faces the correct direction, nor did it happen before (since they had to turn to be facing the correct direction first).

This obviously doesn't happen with DeployingAnim.KeepUnitVisible=yes, but as the said unit is supposed to completely change its form, i can't keep the unit visible or the transformation won't look the way it should.

2021-11-23 18:31 UTC, Metadorius commented
I assume this needs more work? I am marking it as draft then, if I mistakenly assumed it or you fix it - un-draft it then.

2021-11-23 18:57 UTC, Starkku commented
Reverted the automatic deploy after turning to required facing, it might be doable without issues but it'd require more thought and might be best saved for later.

2021-11-23 19:43 UTC, merged