Occupied Buildinng MuzzleFlashX Bug Fix
Phobos-developers/Phobos pull request #465
Opened 2021-12-12 08:52 UTC by Otamaa

close #439

2021-12-27 17:01 UTC, FS-21 commented
I added increased the passengers from 10 to 12 in rulesmd and in artmd I added MuzzleFlash10 and MuzzleFlash11 (with extreme values just for noticing if new annims appears) and tried before and after using this PR binary. in my test looks that this work as planned.

; artmd.ini
[CARUS01]
Normalized=yes
Remapable=no
Foundation=4x4
Height=8
NewTheater=yes
DemandLoad=false
MuzzleFlash0=40,42 ; these are pixel offsets for muzzle flashes from center of base
MuzzleFlash1=-40,64
MuzzleFlash2=-2,-11
MuzzleFlash3=-31,0
MuzzleFlash4=30,64
MuzzleFlash5=-33,35
MuzzleFlash6=-72,46
MuzzleFlash7=0,-51
MuzzleFlash8=-5,79
MuzzleFlash9=-58,47
MuzzleFlash10=65,235 <----- new
MuzzleFlash11=-65,235 <----- new
CanBeHidden=False
OccupyHeight=5
DamageFireOffset0=-15,38
DamageFireOffset1=46,49
AddOccupy1=-4,-4
RemoveOccupy1=-2,1
RemoveOccupy2=-3,0
RemoveOccupy3=-3,-1
RemoveOccupy4=2,-1
RemoveOccupy5=1,-2
RemoveOccupy6=0,-3

![imagen](https://user-images.githubusercontent.com/1371539/147492235-2d2f6dda-78e5-4d8a-a6da-864d6a003850.png)

2021-12-27 17:30 UTC, CommanderNour commented
![eiffle1](https://user-images.githubusercontent.com/78245698/147494391-006cd7b3-8d17-420a-82a3-8a756d8c391b.gif)

2022-01-03 17:05 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	R->EDX(0);
Would be good to have an explanation of what happens here.

2022-01-03 17:14 UTC, Metadorius requested changes
Some minor issues that need to be addressed.

2022-01-03 17:14 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	return !nCount || nCount == 11 ? 0x460388 : 0x460299;
Use anonymous enums for user-readable addresses.

2022-01-03 17:14 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	R->EDX(0);
Or even better, maybe you can make references to those locations with human-readable names and assign values to them?

2022-01-03 17:14 UTC, Metadorius commented on src/Ext/BuildingType/Body.h
> +		DynamicVectorClass<Point2D> PhobosMuzzleFlash;
How about just `MuzzleFlashes` instead?

2022-01-03 17:14 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +namespace Templated
I am not entirely sure this function needs to be here, with that name and that we need it and can't use something that already exists? @secsome
@Thrifinesma

2022-01-03 17:22 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +			std::string nFlag(pBaseFlag + std::to_string(i));
There were implementations of this stuff without usage of std::string, look up LaserTrails for example.

2022-01-04 05:15 UTC, Otamaa commented on src/Utilities/TemplateDef.h
> +namespace Templated
hmm , i can use one from laser trail , but writing them on `LoadFromINI` like that is big chunk of code , maybe better template it for further usage and look cleaner

2022-01-04 08:59 UTC, Metadorius approved these changes

2022-01-04 09:07 UTC, merged