Initial commit
Phobos-developers/Phobos pull request #484
Opened 2021-12-26 21:58 UTC by FS-21

In YR when AI has multiple Factories it clones the built object.

Ares fix the behavior with a new tag:
[GlobalControls]
AllowParallelAIQueues=no

But in the case of aircraft factories they have a bug that only fills all the docks of the primary factory, limiting the AI gameplay.

Now AI can fill all available docks like human players do.

2021-12-27 01:27 UTC, NetsuNegi commented
Nice job!!!!!!!!!!!!!!

2021-12-27 11:43 UTC, Metadorius requested changes

2021-12-27 11:43 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +		return;
Lacks braces. Check styleguide.

2021-12-27 11:43 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +			}
Redundant braces

2021-12-27 11:43 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +		}
Braces again

2021-12-27 11:43 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		return 0;
Code duplication here?

2021-12-27 11:43 UTC, Metadorius commented on src/Phobos.cpp
> +	Phobos::Config::AllowParallelAIQueues = rulesINI->ReadBool("GlobalControls", "AllowParallelAIQueues", Phobos::Config::AllowParallelAIQueues);
Add comment that states that this is an Ares tag.

2021-12-27 15:59 UTC, FS-21 commented on src/Ext/Building/Hooks.cpp
> +		return 0;
I removed pOwner->Type->MultiplayPassive & pOwner->IsNeutral() in the main function for reducing duplicated checks.

2021-12-27 16:03 UTC, FS-21 reviewed
Updated code style due to the review

2022-01-03 17:32 UTC, Metadorius approved these changes

2022-01-03 17:32 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +	}
```suggestion
		return;
```

2022-01-03 17:32 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +		}
```suggestion
			nOccupiedDocks++;
```

2022-03-01 17:51 UTC, Metadorius approved these changes

2022-03-03 11:05 UTC, merged