Shield / new features about shield stole
Phobos-developers/Phobos pull request #487
Opened 2021-12-28 06:05 UTC by Loritas

works when the ShieldDamage > 0

[SOMEWARHEAD]
Shield.Stole=false  ; boolean, whether steal the target's shield HP, default false
Shield.Stolen.Rate=1.0 ; double, if can, the percentage of stolen HP, formula: actual ShieldDamage * rate, minimum = 0, maximum = 10
Shield.StoleType=false ; boolean, whether steal the target's ShieldType for the current unit, works when the unit does not have any shield, defalut false
Shield.StolenType.InitRate=0.0 ; double, if can,  the percentage to initialize the shield strength, minimum = 0, maximum = 1.0

[SOMESHIELDTYPE]
CanBeStolen=true   ; boolean, whether the shield can be stolen HP, default true
CanBeStolenType=true  ; boolean,  whether the ShieldType can be stolen, default true

poor my english

2022-01-03 18:01 UTC, Metadorius requested changes
The PR needs a few improvements. 
1. The assimilation and stealing logic aren't explained, and deducing them from code is a bit hard.
2. The doc entries, changelog and credits entries are missing.
3. Not sure how does stealing interact with already existing shields?
4. Some minor issues on the code style side.

2022-04-21 14:33 UTC, Starkku requested changes
There are some remaining, mostly smaller issues that need to be addressed (including the change Kerbiter has requested earlier still).

2022-04-21 14:33 UTC, Starkku commented on Phobos.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Is there a reason behind this change?

2022-04-21 14:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +CanBeStolenType=true  				 ; boolean
Indentation of the commented bits should be fixed to line up (two spaces from the end of longest line to ;, and rest lining up with that).

2022-04-21 14:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +
Introduction of unnecessary empty lines.

2022-04-21 14:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +
Same as previous comment.

2022-04-21 14:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +Shield.StealTargetType.InitShieldHealthRate=0.0 ; double, percents
Same issue as in previous comment. Also `Shield.StealTargetType.InitShieldHealthRate` is obnoxiously long key name, maybe atleast drop the second `Shield` from it to make it slightly less long if nothing else.

2022-04-21 14:51 UTC, Loritas commented on Phobos.vcxproj
> +    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
Just because vs changed it when I have a problem about compiling project (actually it doesn't change anything)

2022-05-06 17:58 UTC, SMxReaver commented
Shield stealing to restore your own health as well as stealing another object's entire ShieldType both seem to be working correctly. I was able to use:
- non-respawning zero initial health shields were respawned and filled up by shield.steal
- shields can be successfully stolen based on their type, and this works between technotypes (infantry can steal tank shields, buildings can steal aircraft shields, etc.)
- shields not specified to be stolen cannot be stolen
- shields not 

I wonder if the naming for turning on warhead-based stealing could be a bit better. This is just personal opinion, but perhaps Shield.Steal= could perhaps be Shield.Assimilate= to match second tag (Shield.Assimilate.Rate). Or Shield.Assimilate.Rate renamed to be Shield.Steal.Rate=?

2022-09-06 01:11 UTC, closed without merging