Added Timed Jump functions
Phobos-developers/Phobos pull request #488
Opened 2022-01-02 11:46 UTC by FS-21

Action 124,0 : Stop the Timed jumps.

Action 125,x : When the timer reaches 0 the current action ends and jumps to the next Script Action line.

Action 126,x : When the timer reaches 0 the current action ends and restarts again the current Script Action line. Infinite loop timer.

These Actions are measured in game ticks, not seconds so is recommended big values.

2022-01-03 18:03 UTC, Metadorius requested changes
Doc/changelog/credits entries?

2022-01-05 10:25 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +x=125,n           ; integer n=0
What does n=0 mean here? should be a bit more verbose.

2022-01-05 10:25 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +x=126,n           ; integer n=0
Same here.

2022-01-05 22:17 UTC, FS-21 commented on docs/New-or-Enhanced-Logics.md
> +x=125,n           ; integer n=0
TimerStruct what is? ticks/frames/seconds ... ? I don't know if writing "frames" is the right word :-/

2022-01-06 09:00 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +x=125,n           ; integer n=0
Ingame measurment is done in frames usually.

2022-05-05 05:05 UTC, SMxReaver commented
All three scripts appear to be functioning as intended here, everything looks good! 124 successfully kills the jump timer, 125 will jump forward, and 126 jumps backwards and continues the loop.

2022-05-07 16:42 UTC, merged