4 new script action type, aiming for more powerful ai manipulating
Phobos-developers/Phobos pull request #492
Opened 2022-01-07 15:05 UTC by FrozenFog

- Script 572: Change team member group value. Group is actually very handful and currently not quite used. But this script action should be the last to execute as all member cannot match the TeamType designated group, all member instruction will consider discarded, but set / clear variable can still take effect.

- Script 573: Distributed transport loading. This script will instruct all "Passenger" load onto their nearest "Transport" member. "Transport" is determined by their SizeLimit, anyone has the largest SizeLimit will be considered as "Transport", the rest will be "Passengers". 
There're two ways to find the largest SizeLimit: 
1. Consider all member in current team, find the largest SizeLimit.
2. Consider only member which still has enough room for passengers.
This script will loop until there are no valid passengers or transports.

- Script 574,575: Instruct team member to follow friendly/enemy object with certain group value. All member will share a common target to follow. If this object is destroyed or group number changed, the team will find another target until there's no  valid target in the map, then the script will continue.
If all team member is naval, this team can only target naval units.
If all team member is airbound, this team can target anything.
If this team neither naval nor airbound, then this team can only target ground objects.
As group value can be negative, this script cannot add the second argument.
![record2](https://user-images.githubusercontent.com/22377717/148562868-c06837ea-cb12-4d74-8b87-0e36b34257f6.gif)
(Distributed loading onto transport, use only 1 team and 2 line of script action)

2022-01-08 22:47 UTC, Metadorius commented
From a quick glance code style seems to be good, and the code is thoroughly commented which is a plus. Why 572-575 though?

2022-01-09 12:16 UTC, FrozenFog commented
> From a quick glance code style seems to be good, and the code is thoroughly commented which is a plus. Why 572-575 though?

secsome suggested that new script action should avoid conflict with other possible Ares-based extension custom script, 500+ seems a reasonable start, and this 4 action follows secsome's variable manipulating script action.
And I recommend to move all previous script action to post 500 index

2022-01-10 09:32 UTC, Metadorius commented
> > From a quick glance code style seems to be good, and the code is thoroughly commented which is a plus. Why 572-575 though?
> 
> secsome suggested that new script action should avoid conflict with other possible Ares-based extension custom script, 500+ seems a reasonable start, and this 4 action follows secsome's variable manipulating script action. And I recommend to move all previous script action to post 500 index

Then I suggest to separate logically what script actions should be where. For example, say, 500-599 would be variable manipulation script actions, 600-699 - AI param adjustment actions, 700-799 - script flow manipulation actions etc.
Or even better - introduce named actions or action aliases perhaps? I assume most of modders edit the scripts directly, so would be very convenient for them.

2022-01-13 20:24 UTC, Metadorius requested changes
The code quality is quite good, theres a bunch of smaller issues or corrections I outlined.

2022-01-13 20:24 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +- Instruct team member to enter nearest TRANSPORT until there's no valid TRANSPORT or PASSENGERS.
```suggestion
- Instruct team member to enter nearest transport until there's no valid transport or passengers.
```

2022-01-13 20:24 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		}
```suggestion
			return;
```

2022-01-13 20:24 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +	// fuck you westwood - FrozenFog
Don't show this line to CCHyper

2022-01-13 20:24 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		FollowTargetByGroup(pTeam, nArg, false); break;
This doesn't really belong in variable handler function.

2022-01-13 20:24 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +		double Space;
Not sure if this is supposed to be double or not. AFAIK space should be integer?

2022-05-06 19:11 UTC, SMxReaver commented
I was unable to confirm that 572/574/575 interactions were working correctly. These were the steps I used to setup the code:
- create two taskforces, one that will be the "leader" and have it's group changed and one that will be the "follower" and will not have it's group changed
- create two scripts, one for the leader to "do their mission (attack anything)" while the follower uses Gather at Friendly Base followed by 574, follow friendly in group
- team types and triggers were created to force the AI to send off both the Leader team and the Follower team on their scripts

What happened was that the Follower team would always Gather at Friendly Base, and then never move again.
- I tried setting group values on the TaskForce and TeamType for the "Leader" taskforce, when it was set above -1 the leader TF failed to execute script
- debug.log outputs that scripts 572 and 574 don't exist, upon inspecting the GH code I can see it's set to script actions 114 and 116 (there is no mention of a script to follow enemy units in src/Ext/Script/Body.h where the script numeration seems to be located)

I have not tested distributed loading, until a followup is done I'd say this feature is incomplete or non-functional. Attached are my codes I used for testing, and my debug.log to support the output messages mentioned. (is it possible that debug output could show when Group values are updated by these scripts until they are finished?)

[debug.log](https://github.com/Phobos-developers/Phobos/files/8643129/debug.log)
[testcode.txt](https://github.com/Phobos-developers/Phobos/files/8643130/testcode.txt)

2022-05-07 02:59 UTC, FrozenFog commented
> I was unable to confirm that 572/574/575 interactions were working correctly. These were the steps I used to setup the code:
> 
> * create two taskforces, one that will be the "leader" and have it's group changed and one that will be the "follower" and will not have it's group changed
> * create two scripts, one for the leader to "do their mission (attack anything)" while the follower uses Gather at Friendly Base followed by 574, follow friendly in group
> * team types and triggers were created to force the AI to send off both the Leader team and the Follower team on their scripts
> 
> What happened was that the Follower team would always Gather at Friendly Base, and then never move again.
> 
> * I tried setting group values on the TaskForce and TeamType for the "Leader" taskforce, when it was set above -1 the leader TF failed to execute script
> * debug.log outputs that scripts 572 and 574 don't exist, upon inspecting the GH code I can see it's set to script actions 114 and 116 (there is no mention of a script to follow enemy units in src/Ext/Script/Body.h where the script numeration seems to be located)
> 
> I have not tested distributed loading, until a followup is done I'd say this feature is incomplete or non-functional. Attached are my codes I used for testing, and my debug.log to support the output messages mentioned. (is it possible that debug output could show when Group values are updated by these scripts until they are finished?)
> 
> [debug.log](https://github.com/Phobos-developers/Phobos/files/8643129/debug.log) [testcode.txt](https://github.com/Phobos-developers/Phobos/files/8643130/testcode.txt)

There are some major changes that currently not included in the doc, I will update that later. "575" is not Follow Enemy now and all ids have changed

2022-05-14 09:27 UTC, FrozenFog commented
Some brief info:
TeamTypes and Units are all have group value of their own, which means they may not be equal.
In skirmish：
- All units produced by AI have the same group value -1 and cannot be changed by Taskforce's group value or Team's group value, it can only be changed with script action 114.
- If a TeamType has a group value not equal to -1, the team member will be produced but never be recruited correctly, unless there're already valid units (has same group value with this TeamType) in the battlefield.
- TeamType with `Recruiter=yes` will ignore the group restriction, but also will make the group role control invalid.

How to utilize group with skirmish AI:
1. Produce some unit with group value of -1, upon recruited, change their group into designated value
2. Use another TeamType with designated group value to recruit these unit. This can achieve an AI unit role control system (Group 4 focus on defense, group 5 focus on offense, group 6 focus on follow and repair, group 99 is a recruiter team when AI's base is crowded with group 5 and will rally all they have to throw at player's base. With `Recruiter=no`, these member will never be recruited by other team with different group value, unless they change their group).

In singleplayer map:
- Do whatever you want

Skirmish test case:
- Team A (focus on production and assign to group 4 as pool unit)
  - Group = -1, Max = 5
  - Taskforce: 6 MTNK
  - Script: converge (optional) and change group to 4
  - `Autocreate=yes`, `AreTeamMembersRecruitable=yes`, other set to `no`
- Team B (produce, only do repair job, and only follow unit that is in combat)
  - Group = -1, Max = 3
  - Taskforce: 4 ENGINEER, 4 IFV
  - Script: distributed load, change group to 3, converge (optional), and loop follow group 5
  - `Autocreate=yes`, other set to `no`
- Team C (rally pool unit and send them to battlefield)
  - Group = 4, Max = 5
  - Taskforce: 6 MTNK
  - Script: change to group 5 and attack
  - All set to `no`
- Team D (if there're too many of units, flush them into enemy's base)
  - Group = 4, Max = 1
  - Taskforce: 1 MTNK
  - Script: rally all group 4, change to 5 and attack
  - `Autocreate=yes`, other set to `no`
  - Only enable when MTNK count >= 20 (AI Trigger)
- Use AI Trigger to control these team. This combination can apply to other style of attack

2022-06-12 17:55 UTC, FS-21 commented
Regarding:
In `aimd.ini`:
```ini
[SOMESCRIPTTYPE]
x=115,n           ; n is a mask value. Eg: n=65546 means type 1, 10 seconds (1 << 16 + 10)
```

In my opinnion, the worst idea for ScriptType Actions is merging multiple arguments into one argument because you have to create the value manually because a Map Edutor wouldn't support that kind of operation :-/
Just for curiosity how is "type 27, 38 seconds"? For understanding my concern don't use a calculator.

2022-06-13 01:40 UTC, FrozenFog commented
> Regarding: In `aimd.ini`:
> 
> ```ini
> [SOMESCRIPTTYPE]
> x=115,n           ; n is a mask value. Eg: n=65546 means type 1, 10 seconds (1 << 16 + 10)
> ```
> 
> In my opinnion, the worst idea for ScriptType Actions is merging multiple arguments into one argument because you have to create the value manually because a Map Edutor wouldn't support that kind of operation :-/ Just for curiosity how is "type 27, 38 seconds"? For understanding my concern don't use a calculator.

This can be solved with new editor that support alternative parameter read-write option, otherwise all script action can only take 1 parameter.

2022-06-13 05:50 UTC, FS-21 commented
I understand what you mean but be realistic, after (more than) 22 years do you expect a Map Editor capable to do that?
All existing (secsome mentioned 2 or 3 time ago) map editor attempts are so immature that doesn't exist a stable release and isn't  expected in a near future...

2022-06-13 08:18 UTC, Metadorius commented
FS-21 is right, we won't target the features of new map editors that don't exist in public space and are usable.

2022-06-13 09:24 UTC, FS-21 commented
Not necessary 3 actions, it can be 2 but depends of how are designed each action you developed.

For example if the timer part (those 10 seconds of the example I mentioned) is shared between 2 or more actions it can be made as an extra support Action that setup the main action when is executed (and if the timer value remains or get cleared after 1 use depends to you), if the "Type" thing is something exclusive for the main Action you developed then make it as the argument of that action. If the "Type" argument is shared with more actions like what happened with the timer then is up to you to decide if create a new a Action for setting the main action or be the argument of the Action.

In my case I have some parameters that are shared in some Attack & Move actions so I setup the "scenerio" before the main action is executed.

All this is only a recommendation for making it a bit more easy to use your new actions.

2022-06-13 09:56 UTC, FrozenFog commented
This function is relatively simple, it won't need to involve other parameters

2023-02-27 12:59 UTC, closed without merging