Added PassengerDeletion.Anim
Phobos-developers/Phobos pull request #499
Opened 2022-01-12 16:44 UTC by FS-21

Added PassengerDeletion.Anim tag. 
Is an optional animation when the passenger is erased.

2022-01-13 20:13 UTC, Metadorius requested changes

2022-01-13 20:13 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +PassengerDeletion.Rate=0                 ; integer, game frames
```suggestion
PassengerDeletion.Rate=0                ; integer, game frames
```

2022-01-13 20:13 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +							}
Better check if the value was set with `isset`.

2022-01-14 15:43 UTC, FS-21 commented
Applied suggested review changes.

2022-01-29 22:45 UTC, Starkku approved these changes
Feature seems to work as expected and code looks fine. Approving & merging.

2022-01-29 22:46 UTC, merged