Allow `EnemyUIName` to be used for other TechnoTypes
Phobos-developers/Phobos pull request #506
Opened 2022-01-15 10:15 UTC by Otamaa

close #503
`EnemyUIName`  not applied if  `Disguised` , `Civilian/MultiplayPassive Owned` , `Observer` !

```INI
Rules
[UNIT/INFANTRY/AIRCRAFT TYPE]
EnemyUIName= (csf string)
```

2022-01-17 07:10 UTC, CommanderNour commented
![SCRN 20220117-084111-00473](https://user-images.githubusercontent.com/78245698/149723470-147b9eb3-2e45-4e0a-8ce6-f4a126eefee6.png)

Works

2022-01-29 21:57 UTC, Starkku requested changes
Code looks okay, just some minor code style tweaks required.

2022-01-29 21:57 UTC, Starkku commented on src/Ext/TechnoType/Body.h
> +			, EnemyUIName{ }
Move space from between the curly braces to before.

2022-01-29 21:57 UTC, Starkku commented on src/Ext/TechnoType/Hooks.cpp
> +	enum {SetUIName = 0x4AE678 };
Add space before `SetUIName`.

2022-01-29 21:57 UTC, Starkku commented on src/Ext/TechnoType/Hooks.cpp
> +			if (auto pEnemyUIName = pTechnoTypeExt->EnemyUIName.Get().Text)
Add empty line between the variable declaration and if clause.

2022-01-30 11:04 UTC, Starkku approved these changes
Approving changes & merging.

2022-01-30 11:04 UTC, merged