Self-fire weapons on warping in / out
Phobos-developers/Phobos pull request #515
Opened 2022-01-23 16:00 UTC by Starkku

It is now possible to add weapons that are fired on a teleporting TechnoType when it warps in or out. They are at the same time as the appropriate animations (`WarpIn` / `WarpOut`) are displayed.
  - `WarpInMinRangeWeapon` is used instead of `WarpInWeapon` if the distance traveled (in leptons) was less than `ChronoRangeMinimum`. This works regardless of if `ChronoTrigger` is set or not. If `WarpInMinRangeWeapon` is not set, it defaults to `WarpInWeapon`.

In `rulesmd.ini`:
```ini
[SOMETECHNO]           ; TechnoType
WarpInWeapon=          ; WeaponType
WarpInMinRangeWeapon=  ; WeaponType
WarpOutWeapon=         ; WeaponType
```

2022-01-30 01:31 UTC, mevitar commented
Everything appears to be working as intended, noticed no issues so far.
None of these triggers when an object is transferred through a Chronosphere-like SW, but i suppose that was the intention here.

2022-02-14 06:36 UTC, Thrifinesma requested changes

2022-02-14 06:36 UTC, Thrifinesma commented on src/Ext/TechnoType/Hooks.Teleport.cpp
> +	TechnoExt::ExtData* pTechnoExt = TechnoExt::ExtMap.Find(pLocomotor->LinkedTo);
```suggestion
	auto pTechnoExt = TechnoExt::ExtMap.Find(pLocomotor->LinkedTo);
```

2022-02-19 21:37 UTC, Metadorius approved these changes

2022-02-19 21:38 UTC, merged