Grinder improvements / additions
Phobos-developers/Phobos pull request #518
Opened 2022-01-29 21:15 UTC by Starkku

You can now customize which types of objects a building with `Grinding` set can grind as well as the grinding sound.
- `Grinding.AllowedTypes` can be used to define InfantryTypes and VehicleTypes that can be grinded by the building. Listing any will disable grinding for all types except those listed.
- `Grinding.DisallowedTypes` can be used to exclude InfantryTypes or VehicleTypes from being able to enter the grinder building.
- `Grinding.Sound` is a sound played by when object is grinded by the building. If not set, defaults to `[AudioVisual]`->`EnterGrinderSound`.

In `rulesmd.ini`:
```ini
[SOMEBUILDING]             ; BuildingType
Grinding.AllowedTypes=     ; List of InfantryTypes / VehicleTypes
Grinding.DisallowedTypes=  ; List of InfantryTypes / VehicleTypes
Grinding.Sound=            ; Sound
```

In addition following minor improvements / bugfixes are included:
- Fixed interaction of `UnitAbsorb` & `InfantryAbsorb` with `Grinding` buildings. The keys will now make the building only accept appropriate types of objects.
- Fixed missing 'no enter' cursor for VehicleTypes being unable to enter a `Grinding` building.
- Fixed Engineers being able to enter `Grinding` buildings even when they shouldn't (such as ally building at full HP).

Should work as expected with the AI script action 'Enter grinder' and the Ares bugfix for Ivan & Grinder interaction.

2022-01-30 08:15 UTC, brsajo commented
In my testing:

- `Grinding.AllowAllies=true` works as expected.
- `Grinding.AllowedTypes=INIT` doesn't seem to have any effect on what types are allowed to enter.
- `Grinding.DisallowedTypes=LTNK` doesn't seem to have any effect on what types are allowed to enter.
- `Grinding.Sound=CloningVatsCreate` works as expected.
- `UnitAbsorb` & `InfantryAbsorb` fixes confirmed working as expected.
- 'no enter' cursor for VehicleTypes fix confirmed working as expected.
- Engineers entering grinders fix confirmed working as expected.
Haven't tested the 'Enter grinder' AI script.

2022-02-07 11:12 UTC, CommanderNour commented
Tested every tag works as intended even the Allow & Disallow Types, Good job man
& sorry for not providing any screen shots

2022-02-11 03:59 UTC, SMxReaver commented
![grindweapon](https://user-images.githubusercontent.com/77598000/153534899-64e3ddad-c4a2-40ca-8f1c-32df84c8a4e5.gif)

So far, testing: 
Grinding.AllowAllies=false stops you from entering an allies' grinder but not your own, would we need a hypothetical Grinding.AllowOwner for this functionality?
Grinding.AllowTypes, Grinding.DisallowTypes, Grinding.Weapon, Grinding.Sound all working as intended

UnitAbsorb and InfantryAbsorb fixes seem to be working correctly too. Have not tested Engineer or script actions at this moment.

2022-02-16 13:39 UTC, Starkku commented
Fixed `Grinding.Weapon` generating INI parsing errors and added `Grinding.AllowOwner`.

2022-02-19 21:22 UTC, Metadorius requested changes

2022-02-19 21:22 UTC, Metadorius commented on Phobos.vcxproj
> +	<ClCompile Include="src\Ext\Techno\Hooks.Grinding.cpp" />
```suggestion
    <ClCompile Include="src\Ext\Techno\Hooks.Grinding.cpp" />
```

2022-02-19 21:22 UTC, Metadorius commented on src/Ext/Techno/Hooks.Grinding.cpp
> +	enum { Return_Static = 0x43C31A, Return_Negative = 0x43CB68, Return_Roger = 0x43CCF2 };
Let's keep it strictly `PascalCase`, not `Some_Mixed_Case`.

2022-02-19 21:28 UTC, Starkku commented on src/Ext/Techno/Hooks.Grinding.cpp
> +	enum { Return_Static = 0x43C31A, Return_Negative = 0x43CB68, Return_Roger = 0x43CCF2 };
Pascal sliced into bits.

2022-02-19 21:34 UTC, Metadorius commented on src/Ext/Techno/Hooks.Grinding.cpp
> +	enum { Return_Static = 0x43C31A, Return_Negative = 0x43CB68, Return_Roger = 0x43CCF2 };
Too delicious.

2022-02-19 21:44 UTC, merged