Fixes, tweaks and optimizations of Attack and Move actions
Phobos-developers/Phobos pull request #521
Opened 2022-02-03 12:37 UTC by FS-21

- Fixed 2 rare cases that made the team units unable to execute the script action at some point.
- Now the wait timer when the action didn't find a valid object won't be shared  with the GuardAreaTimer timer.
- Removed pTeam->Focus will store (again) the selected target.
- Some tweaks.

2022-02-11 04:59 UTC, ayylmaoRotE commented
Hoverattack (helicopters) are actually following their scripts and not being interrupted by attackers or when attacking. Nice work

2022-02-14 06:34 UTC, Thrifinesma requested changes

2022-02-14 06:34 UTC, Thrifinesma commented on src/Ext/Script/Body.cpp
> +		}
```suggestion
		if (pTeamData->CloseEnough > 0)
			pTeamData->CloseEnough = -1;
```

2022-02-14 06:34 UTC, Thrifinesma commented on src/Ext/Script/Body.cpp
> +						}
```suggestion
						if (pUnit->Target != pFocus)
							pUnit->SetTarget(pFocus);
```

2022-02-14 06:34 UTC, Thrifinesma commented on src/Ext/Script/Body.cpp
>  		}
```suggestion
			pTeamData->CloseEnough = -1;
```

2022-02-19 21:15 UTC, Metadorius approved these changes

2022-02-20 10:13 UTC, merged