Customization of the storage resource
Phobos-developers/Phobos pull request #524
Opened 2022-02-07 11:29 UTC by FS-21

[General] > Storage.TiberiumIndex=-1
This new tag set which type of Tiberium (from [Tiberiums] list) is used for storage, making it more easy to respect/calculate money limitations.

It needs Ares Storage logic activation for working.

2022-02-11 03:22 UTC, SMxReaver commented
![oretest](https://user-images.githubusercontent.com/77598000/153532816-8ecbdb55-13c5-40d7-913a-fcb835db0844.gif)

Tested this feature out, pretty neat. Essentially it converts all other resource types into the specified resource by the tag. In this test, you see a Chrono Miner with Gems deposit the resource as stored ore into the refinery, mine ore offscreen, return to deposit and it is stored ore as well. This persists through save games, the feature works on multiple refineries and if one is destroyed the others remain working as intended.

2022-02-14 06:32 UTC, Thrifinesma requested changes

2022-02-14 06:32 UTC, Thrifinesma commented on src/Ext/Building/Body.cpp
> +			if (pExt)
```suggestion
		if (auto pBuildingType = pThis->Type)
		{
			if (auto const pExt = BuildingTypeExt::ExtMap.Find(pBuildingType))
```

2022-02-17 14:27 UTC, FS-21 commented
Applied the last requested change from the review.

2022-02-19 21:14 UTC, Metadorius approved these changes

2022-02-19 21:14 UTC, merged