Minor Save fix
Phobos-developers/Phobos pull request #529
Opened 2022-02-18 12:04 UTC by secsome

This PR has been already tested by hundreds of MO336 players which is known as `Extra Save Fix` in it, it provides fixes like:
Map lighting get corrupted after load the save
BuildOfAlly is reset after load the save

It also include a new trigger action called AdjustLighting which is more detailed. Which means you can choose to only update CellDrawers, Objects, and CustomPalettes. That has been tested already too, by many mappers like Sandman, Esther and so on.

2022-02-18 12:09 UTC, secsome commented
This dll conflicts with the savefix dll in mo336, do not test them together.

2022-04-09 18:54 UTC, Metadorius requested changes
Lacks docs, changelog, credits.

2022-04-09 18:54 UTC, Metadorius commented on src/Ext/TAction/Hooks.cpp
> +	ScenarioExt::Global()->CurrentTint_Hashes = ScenarioClass::Instance->NormalLighting.Tint;
Not sure what I am even looking at.

2022-08-04 03:16 UTC, chaserli commented on src/Ext/TAction/Hooks.cpp
> +	ScenarioExt::Global()->CurrentTint_Hashes = ScenarioClass::Instance->NormalLighting.Tint;
May I ask what's the status of this PR currently? Is it equivalent to savefixmo.dll in mo336?

2022-08-04 04:39 UTC, secsome commented on src/Ext/TAction/Hooks.cpp
> +	ScenarioExt::Global()->CurrentTint_Hashes = ScenarioClass::Instance->NormalLighting.Tint;
> May I ask what's the status of this PR currently? Is it equivalent to savefixmo.dll in mo336?

Mo336's fix is a bugged fix version, this is the complete version of it

2022-08-12 09:18 UTC, Metadorius commented
@secsome add the damn docs and let's merge before 0.3 comes out ffs
@chaserli may help with testing for example?

2022-08-12 12:15 UTC, chaserli commented
> @secsome add the damn docs and let's merge before 0.3 comes out ffs @chaserli may help with testing for example?
After the branch gets updated. I don't quite understand the code here.

2022-09-05 01:55 UTC, chaserli commented
Which part is responsible for BuildOffAlly S/L fix? I don't quite get it

2022-09-05 02:29 UTC, secsome commented
> Which part is responsible for BuildOffAlly S/L fix? I don't quite get it Is it the serialization of `SessionClass::Instance->Config`?

yes, `.Process(SessionClass::Instance->Config)` does the fix, as YR didn't do  serialization on `SessionClass`, I decided to simply serialize it in `ScenarioClass`

2022-09-05 07:06 UTC, chaserli commented
![AED040XDG} 3DCLKP(@UGM6](https://user-images.githubusercontent.com/9932846/188385191-d3e5ebb5-2016-4620-9aae-eea75f7549d6.png)
I didn't S/L, just after time-freeze it becomes like this

2022-09-08 18:17 UTC, chaserli reviewed
I updated your branch with upstream a few days ago and refactored a few stuff for my better comprehension, can you check if that still conforms to what you would have meant?

2022-09-08 18:17 UTC, chaserli commented on src/Ext/TAction/Body.cpp
> +	if (pThis->Value & 0b001) // Update Tiles
Can you add the docs related to this TAction? and how to give `TActionClass::Value` in a map editor?

2022-09-08 18:17 UTC, chaserli commented on src/Ext/Scenario/Body.cpp
> +					pBld->LightSource->Activate();
I get the whole picture of what you have done here, but I can't find the possible cause of some light posts failing to update light sources as I showed in the conversation before.

2022-09-13 13:05 UTC, secsome commented
![screenshot](https://user-images.githubusercontent.com/41946354/189908276-2b58f04e-6749-4eb2-9fbd-ec3027faef76.png)
I cannot reproduce the issue you mentioned here.

This feature should have a tag to switch it on, I will add a tag later.

2022-09-13 13:06 UTC, secsome commented on src/Ext/Scenario/Body.cpp
> +					pBld->LightSource->Activate();
I cannot reproduce it even I've did more than 10 tries. I'm not sure if it has some problem here.

2022-09-13 13:07 UTC, secsome commented on src/Ext/TAction/Body.cpp
> +	if (pThis->Value & 0b001) // Update Tiles
Well, in map editor we just write a number, 1 stands for `Tiles`, 2 stands for `Units & Buildings`, 3 stands for `Tiles &  Units and Buildings`, ... and so on. The document should be implemented later.

2022-09-13 13:50 UTC, Metadorius commented
Err why exactly is the switch needed?

2022-09-13 14:04 UTC, chaserli commented
> Err why exactly is the switch needed?

I think he may refer to the issue I reported above, although I think it's actually not quite needed too

2022-09-14 10:53 UTC, secsome commented
There are some existing maps set the lighting without the fix, if you don't give an option  to disable the lighting fix, the existing maps will looks bad. So this is just a forward compatibility.

2022-09-14 19:56 UTC, Metadorius commented
so what's the actual state😵 
![image](https://user-images.githubusercontent.com/17500545/190249903-7ca84d4b-7136-4c38-b91c-060078cdbee1.png)

2022-10-02 09:57 UTC, chaserli commented on src/Ext/Rules/Body.cpp
> +	this->AdjustLightingFix.Read(exINI, "Map", "AdjustLightingFix");
I prefer `[Basic]` or even `[Lighting]` for the sake of clarity

2022-12-12 03:35 UTC, secsome commented
What needs to be tested:
1. Reveal All Command
2. `BuildOfAlly`
3. TAction 507 `AdjustLighting`
4. `[Basic]>AdjustLightingFix`

2022-12-12 11:18 UTC, chaserli requested changes
It seems we won't be able to make it for v0.3, but at least we can add that BuildOffAlly part into v0.3.

2022-12-12 11:18 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +- Fixed the bug that `GameModeOptions` are not being saved. For example, `BuildOffAlly` will be corrupted when loading the game.
```suggestion
- Fixed the bug that `GameModeOptions` are not being saved. For example, `BuildOffAlly` will no longer be corrupted when loading the game.
```
Is that the correct logic?

2022-12-12 11:18 UTC, chaserli commented on src/Commands/RevealAll.h
> +#pragma once
You broke the convention set by yourself 0efa15c23f91eb51abc658585a325dc0f6c25e14

2023-01-13 10:04 UTC, chaserli commented on src/Ext/Scenario/Body.cpp
> +	AdjustLightingFix = pINI->ReadBool("Basic", "AdjustLightingFix", AdjustLightingFix);
Are you sure that your parsing is successful in this `ScenarioClass_LoadFromINI` hook? `pINI` seems to be released somehow. Should we move it a bit earlier? such as
```cpp
DEFINE_HOOK(0x68AD2F, ScenarioClass_LoadFromINI, 0x5)
{
	GET(ScenarioClass*, pItem, ESI);
	GET(CCINIClass*, pINI, EDI);
	ScenarioExt::LoadFromINIFile(pItem, pINI);
	return 0;
}
```

2024-06-22 12:53 UTC, closed without merging