Documentation Improvements
Phobos-developers/Phobos pull request #547
Opened 2022-03-10 16:02 UTC by MortonPL

- Minor spelling and word changes
- Made lists in "What's New" collapsible
- Sort subsections and entries alphabetically

List of "interesting" feature entries that are lacking media:

- In Fixed & Improved
  - Attached animation position customization
  - Customizable & new grinder properties
  - Customizable projectile gravity
  - Kill spawns on low power
  - IsSimpleDeployer vehicle deploy animation / direction customization
  - Toggle-able ElectricBolt visuals
- In New & Enhanced
  - Automatic Passenger Deletion
  - Firing offsets for specific Burst shots
  - Kill Unit Automatically
  - Break Mind Control on impact
  - Chance-based extra damage or Warhead detonation / 'critical hits'
  - Remove disguise on impact

2022-03-10 16:13 UTC, Metadorius requested changes

2022-03-10 16:13 UTC, Metadorius commented on docs/Whats-New.md
> +Phobos fixes:c
:c

2022-03-10 16:15 UTC, MortonPL commented on docs/Whats-New.md
> +Phobos fixes:c
:>

2022-04-10 15:27 UTC, Metadorius approved these changes

2022-04-10 15:28 UTC, merged