Building Placement Preview
Phobos-developers/Phobos pull request #548
Opened 2022-03-10 18:02 UTC by Otamaa

- the code not that pretty , feel free to tweak it , sorry 
- No documentation included atm 
```ini
[AUDIOVISUAL]
ShowBuildingPlacementPreview =  ;bool , globally setting
BuildingPlacementGrid.Transculency = ;int , default to 0 , {0=0% , 1=25%  , 2=50% , 3=75%}

[BUILDINGTYPE]
PlacementPreview.Show=  ;bool , default to [AudioVisual]->ShowBuildingPlacementPreview
PlacementPreview.Shape=  ;SHPFile , default to Building->Image 
PlacementPreview.ShapeFrame = ;int , default to  0
PlacementPreview.Offset=  ;int int , default to {0 , -15}
PlacementPreview.Remap=   ; bool , default to true 
PlacementPreview.Palette=  ; .PAL file , default to nullptr , if remap , this option not used 
PlacementPreview.TransculentLevel = ;int , default to 0 ,{0=0% , 1=25%  , 2=50% , 3=75%}
```
![image](https://user-images.githubusercontent.com/9769329/157726214-e28a9268-3798-46bb-aba2-acfc07d59d44.png)

2022-03-11 18:34 UTC, CommanderNour commented
Every tag works except 
**PlacementPreview.Remap=false**
![SCRN 20220311-202529-00441](https://user-images.githubusercontent.com/78245698/157929170-2ebdbf16-e807-48bb-89c0-7e5c7a4c1b1d.png)
for some reason it shows wrong palette if used
**PlacementPreview.Shape=NAREFN**
![SCRN 20220311-202857-00562](https://user-images.githubusercontent.com/78245698/157930298-a18257da-436a-43d5-8e2a-5619d0b3e5f0.png)
it should show me a soviet refinery instead of the allied one right ?!
I tried it on different buildings but it didn't work as intended
also is it possible to show the building BibShape with the building itself

2022-03-11 23:00 UTC, Otamaa commented
> Every tag works except **PlacementPreview.Remap=false** ![SCRN 20220311-202529-00441](https://user-images.githubusercontent.com/78245698/157929170-2ebdbf16-e807-48bb-89c0-7e5c7a4c1b1d.png) for some reason it shows wrong palette if used **PlacementPreview.Shape=NAREFN** ![SCRN 20220311-202857-00562](https://user-images.githubusercontent.com/78245698/157930298-a18257da-436a-43d5-8e2a-5619d0b3e5f0.png) it should show me a soviet refinery instead of the allied one right ?! I tried it on different buildings but it didn't work as intended also is it possible to show the building BibShape with the building itself

it is better to use `PlacementPreview.Shape=` option 
including Bib , it mean i need to handle separate drawing function and calculation for that , i dont want to do that 
too much code for a simple feature !

2022-03-12 02:21 UTC, secsome requested changes

2022-03-12 02:21 UTC, secsome commented on src/Ext/BuildingType/Hooks.cpp
> +	ObjectClass* pObject = Make_Global<ObjectClass*>(0x88098C);
`DisplayClass::Instance->CurrentBuilding`

2022-03-12 02:21 UTC, secsome commented on src/Ext/BuildingType/Hooks.cpp
> +				auto const nFlag_ = Math::clamp(pTypeExt->PlacementPreview_Transculency.Get(), 0, 3);
I noticed that this code block is duplicated, maybe wrap it as a function would be a wise decision.

2022-03-12 02:21 UTC, secsome commented on src/Ext/BuildingType/Hooks.cpp
> +	auto const nFlag_ = Math::clamp(RulesExt::Global()->PlacementGrid_Transculency.Get(), 0, 3);
What I've mentioned above

2022-03-12 04:30 UTC, CommanderNour commented
The remap works
![SCRN 20220312-055359-00662](https://user-images.githubusercontent.com/78245698/158002772-f9dd84db-f388-43f3-91f2-7888957c2156.png)
For the preview shape image I really don't know 
here I used **PlacementPreview.Shape=NARADR**
![SCRN 20220312-061050-00391](https://user-images.githubusercontent.com/78245698/158003254-a20645c9-599a-4330-adb8-f9a7d714edda.png)
didn't work as shown in the image above
and here I used **PlacementPreview.Shape=EAREFN**
![SCRN 20220312-061035-00680](https://user-images.githubusercontent.com/78245698/158003297-ff746a15-efd2-4294-95e5-6299ba4e168f.png)
works but displays a wrong theatre image it should pick the  second filename character A for snow ,D for desert and G for everything etc....
right ?!
I think you should wait for someone else to test this tag so you can make sure it works fine
also there is a bug with the allied barracks a 3x2 building
![SCRN 20220312-055511-00582](https://user-images.githubusercontent.com/78245698/158003573-3f6a4824-0568-4898-97d9-19f90cadea97.png)
if I went to look elsewhere in the map and get back to it the bug disappears as shown with one of the barracks
also why it shows in the Construction yard it doesn't related to the barrack

2022-03-26 13:21 UTC, CommanderNour commented
Works as intended

2022-04-03 17:04 UTC, Starkku requested changes
Code for most part looks okay, only some small things to point out.

As for the actual feature, I think using the `BuildUp` shape's last regular frame as the default if `PlacementPreview.Shape` is undefined, instead of simply the building's basic shape is the most sensible default option from modder's standpoint, as it would require the least amount of additional code to allow the feature to be used.

2022-04-03 17:04 UTC, Starkku commented on src/Ext/BuildingType/Hooks.cpp
> +				DSurface::Temp()->DrawSHP(
I don't think there's any need to lay out the params on their own lines here. This type of approach is useful in locations that are modified often, but here it at the best provides tiny bit of extra clarity at expense of taking a lot of vertical space.

2022-04-03 17:05 UTC, Starkku commented on src/Ext/BuildingType/Hooks.cpp
> +					 1000, 0, nullptr, 0, 0, 0
I don't think there's any need to lay out the params on their own lines here. This type of approach is useful in locations that are modified often, but here it at the best provides tiny bit of extra clarity at expense of taking a lot of vertical space.

2022-04-03 17:05 UTC, Starkku commented on src/Ext/BuildingType/Hooks.cpp
> +					 1000, 0, nullptr, 0, 0, 0
I don't think there's any need to lay out the params on their own lines here. This type of approach is useful in locations that are modified often, but here it at the best provides tiny bit of extra clarity at expense of taking a lot of vertical space.

2022-04-03 17:18 UTC, Otamaa commented
> Code for most part looks okay, only some small things to point out.
> 
> As for the actual feature, I think using the `BuildUp` shape's last regular frame as the default if `PlacementPreview.Shape` is undefined, instead of simply the building's basic shape is the most sensible default option from modder's standpoint, as it would require the least amount of additional code to allow the feature to be used nicely with existing assets.

hmm , yeah 
i just dont wat to bother to figuering out which frames i need to use from build up 
easier to test with building image

2022-04-03 17:27 UTC, Metadorius commented
I believe trsdy on discord has already made a change to accomodate that.
```cpp
DEFINE_HOOK(0x6D528A, TacticalClass_DrawPlacement_PlacementPreview, 0x6)
///......
auto const pImage = pType->LoadBuildup(); //pTypeExt->PlacementPreview_Shape.Get(pType->GetImage());
if (!pImage)
    return 0x0;
auto const nFrame = (int)((pImage->Frames)/2-1); //Math::clamp(pTypeExt->PlacementPreview_ShapeFrame.Get(), 0, (int)pImage->Frames);
```

2022-04-04 07:28 UTC, Otamaa commented
> I believe trsdy on discord has already made a change to accomodate that.
> 
> ```c++
> DEFINE_HOOK(0x6D528A, TacticalClass_DrawPlacement_PlacementPreview, 0x6)
> ///......
> auto const pImage = pType->LoadBuildup(); //pTypeExt->PlacementPreview_Shape.Get(pType->GetImage());
> if (!pImage)
>     return 0x0;
> auto const nFrame = (int)((pImage->Frames)/2-1); //Math::clamp(pTypeExt->PlacementPreview_ShapeFrame.Get(), 0, (int)pImage->Frames);
> ```

yeah , done 
you can check latest code i push

2022-04-04 09:10 UTC, Metadorius commented
Another improvement from trsdy, support for building upgrades:
```cpp
const bool isUpgrade = pType->PowersUpBuilding[0] || (!pTypeExt->PowersUp_Buildings.empty());
auto const pImage = isUpgrade ? pType->GetImage() : pType->LoadBuildup();
if (!pImage) return 0x0;
const int nFrame = isUpgrade ? 0 : (int)((pImage->Frames)/2-1);
```

2022-04-04 09:55 UTC, Metadorius commented
Another thing that should be in - it should be disable-able via a flag in RA2MD, because this is a UI feature that not all players may necessarily like. See how I made it for smart selection filtering.

2022-04-04 12:19 UTC, Otamaa commented
> Another improvement from trsdy, support for building upgrades:
> 
> ```c++
> const bool isUpgrade = pType->PowersUpBuilding[0] || (!pTypeExt->PowersUp_Buildings.empty());
> auto const pImage = isUpgrade ? pType->GetImage() : pType->LoadBuildup();
> if (!pImage) return 0x0;
> const int nFrame = isUpgrade ? 0 : (int)((pImage->Frames)/2-1);
> ```

i mean , what is the point now 
my first implementation is open enough you can change the shape image manually if the thing not supported and or user dont like it 
Now you want add another check for upgrades ? 
yeah , single boolean wont be too much but , why ,..

2022-04-04 12:25 UTC, Metadorius commented
Because things working automagically where possible is a good thing for the end user of Phobos. This was already implemented by someone so why not add it if it's good enough? A few lines of code like this saves a lot of people's time, because with this they can just add a toggle to show the preview and be done with it instead of having to look up how to fix the wrong image.

This is not meant as a criticism in any way.

2022-04-04 12:27 UTC, Otamaa commented
> Another thing that should be in - it should be disable-able via a flag in RA2MD, because this is a UI feature that not all players may necessarily like. See how I made it for smart selection filtering.

new catagory ? or should i put it in inside `Sidebar` ?

2022-04-04 12:29 UTC, Metadorius commented
I am pretty sure Sidebar is a category in UIMD.ini, not in RA2MD.ini which is a user settings file.

2022-04-04 13:22 UTC, chaserli commented
This is Trsdy from discord. I noticed that you've changed the type of `BuildingTypeExt::ExtData::PlacementPreview_ShapeFrame ` from `Valuable<int>` to `Nullable<int>`. As far as I've tested, it always get 0 when `this->PlacementPreview_ShapeFrame.Read(exINI, pSection, "PlacementPreview.ShapeFrame")` is executed

2022-04-04 13:41 UTC, chaserli commented
> > Another improvement from trsdy, support for building upgrades:
> > ```c++
> > const bool isUpgrade = pType->PowersUpBuilding[0] || (!pTypeExt->PowersUp_Buildings.empty());
> > auto const pImage = isUpgrade ? pType->GetImage() : pType->LoadBuildup();
> > if (!pImage) return 0x0;
> > const int nFrame = isUpgrade ? 0 : (int)((pImage->Frames)/2-1);
> > ```
> 
> i mean , what is the point now my first implementation is open enough you can change the shape image manually if the thing not supported and or user dont like it Now you want add another check for upgrades ? yeah , single boolean wont be too much but , why ,..

The reason why I suggest such change is that I want to use the last frame of buildup or the first frame of powersup-workinganim to be the preview frame, and this seems pretty natural to a modder's logic. If I want to do so with your previous versions, I'll have to know the frame number of every buildup anim a prior. 

Maybe the case when buildup anim is absent should also be taken into consideration in this case.

2022-04-21 16:27 UTC, Starkku approved these changes
Rebased and fixed some issues like custom paletted buildings being displayed in unit*.pal with the remap option on, and some code style tweaks. Added documentation by @SMxReaver from his PR #591.

On the upgrade support, they work fine by default if you omit `Buildup` which usually is omitted for upgrades anyway.

The only real remaining issue there could be to fix is remappable previews tinting under superweapon or map trigger tint lighting

![image](https://user-images.githubusercontent.com/1392346/164506863-05822f41-860d-4fe4-b757-a8652cfc721f.png)

However I believe that fixing this and maintaining the ability to keep the image remapped to house's color scheme would be somewhat complex and require more research so it could be left as it is for now.

Not seeing any real issues left to fix so approving for merge.

2022-04-25 06:52 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +				{ Selected = pType->GetImage(); }
```suggestion
				{
					Selected = pType->GetImage();
				}

```

2022-04-25 06:52 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +}
```suggestion
```

2022-04-25 06:58 UTC, merged