Mastermind Overload characteristic deharcoded
Phobos-developers/Phobos pull request #549
Opened 2022-03-10 19:29 UTC by Otamaa

```ini
[MASTERMIND]
Overload.Count=           ;default to `[CombatDamage]->OverloadCount`
Overload.Damage=          ;default to `[CombatDamage]->OverloadDamage`
Overload.Frames=          ;default to `[CombatDamage]->OverloadFrames`
Overload.DeathSound=      ;default to `[AudioVisul]->MasterMindOverloadDeathSound`
Overload.ParticleSys=     ;default to `[CombatDamage]->DefaultSparkSystem`
MindControll.DrawLink=    ;bool , default to true (wheter this techno with capture manager draw their link to the victim)
```

2022-03-11 22:53 UTC, Otamaa commented
> **Overload.Count=5,7,9,11** **Overload.Damage=0,25,50,1000** **Overload.Frames=30,60,60,600** **Overload.DeathSound=NukeSiren** **Overload.ParticleSys=SmallGreySSys** **MindControll.DrawLink=false**
> 
> If my codes here are correct the only tags that worked for me is **Overload.Count** & **MindControll.DrawLink** the reset didn't work but they don't fall back to the old numbers meaning this ![SCRN 20220311-200637-00632](https://user-images.githubusercontent.com/78245698/157925243-7be81d9a-1f5d-4cc1-b21f-c05fdc8870ce.png) The Master Mind is at full HP

it seems the parser is broken , they not parsing the values , should be fixed now !

2022-03-12 05:33 UTC, CommanderNour commented
the **Overload.DeathSound** should play when the Master Mind dies right ? it plays when it reach any of the Overload Counts

beside that every thing works as intended

2022-03-12 05:48 UTC, Otamaa commented
> the **Overload.DeathSound** should play when the Master Mind dies right ? it plays when it reach any of the Overload Counts
>

It is not apparently ,but i why WW name this like that , omg  :kekw:

2022-05-05 06:15 UTC, SMxReaver commented
Using YR 1.001, I've added the following tags to the Lasher Tank for this test. I've found the following based on the newest available Nightly.

Overload.Count does not appear to be working correctly. When set to 'Overload.Count=5,7,11,55' , the game will start inflicting damage on the 8th captured object. In Vanilla YR, an 'OverloadCount=5,7,11,55' would start inflicting damage on the 6th captured object. 

Overload.Damage seems to be working correctly even with the issues described in Overload.Count. _Observed behavior: if you set the first value to above 0 (Overload.Damage=1,50,100,500 for example), the unit will immediately take damage upon construction without any captured victims._

Overload.Frames seems to be working correctly even with the issues described in Overload.Count.

Overload.DeathSound= is also working. Is it possible that a tag rename to 'Overload.VoiceFeedback' to indicate this is played when the unit is taking damage? The current game uses VoiceFeedback for units that hit yellow health and I think it may indicate it's functionality clearer.

Overload.ParticleSys and Overload.ParticleSysCount both seem to be working. Overload.ParticleSys= confirmed to work on Spark, Smoke and does not work with Gas, Fire, did not test Railgun, but I have my doubts.

MindControll.DrawLink= is also working. It has a typo in the tag name, maybe it is supposed to be MindControl.DrawLink= without the second L in MindControl?

2025-04-15 16:08 UTC, CrimRecya commented on src/Ext/CaptureManager/Hooks.cpp
> +					nCurIdx = i + 1; //select the index !
This is different from the original logic, as it is possible to obtain an index value equal to size when the maximum value is exceeded, and may out of bounds.

2025-04-15 16:08 UTC, CrimRecya commented on src/Ext/CaptureManager/Hooks.cpp
> +				return iter.empty() ? 0 : iter[nInput > (int)iter.size() ? (int)iter.size() : nInput];
[size()] should be out of bounds.

2025-04-15 16:08 UTC, CrimRecya commented on src/Ext/CaptureManager/Hooks.cpp
> +					double const nBase = (nCurIdx != 1) ? 0.015 : 0.029999999;
I think it's 0.03, just a small thing.

2025-04-17 16:06 UTC, CrimRecya requested changes

2025-04-17 16:06 UTC, CrimRecya commented on src/Ext/CaptureManager/Hooks.cpp
> +	GET_STACK(int, nNodeCount, STACK_OFFSET(0x30, 0x1C));
GET_STACK(int, nNodeCount, STACK_OFFSET(0x30, -0x1C));

2025-04-19 14:06 UTC, Coronia commented
The crash is fixed, and the logic works well in testing

2025-04-19 14:08 UTC, CrimRecya approved these changes

2025-04-20 11:52 UTC, Coronia commented
Profiler showed that the draw link hook cost a lot when the game REALLY had a lot of mind control links, but since it's taking over the vanilla link drawing process it should be acceptable, and numerous links is a laggy thing even in vanilla anyway. It won't contribute to lag visibly when there're not that many links, which is the case for most of the games

Though, it would be appreciated if it can be further optimized in the future

2025-04-20 11:53 UTC, merged