Various Building properties Deharcoded
Phobos-developers/Phobos pull request #550
Opened 2022-03-10 20:41 UTC by Otamaa

```ini
[BUILDINGTYPE]
-Deharcoded occupy and bunker bonus  , Default to `[CombatDamage]`
OccupyDamageMultiplier=       ;float  
OccupyROFMultiplier=   	  ;float
BunkerDamageMultiplier=   	;float
BunkerROFMultMultiplier=    ;float

-Bunker Wall Sound , Default to  `[AdioVisual]`
BunkerWallsUpSound=			;Foc
BunkerWallsDownSound=		;Foc

-Completely disable damaged sound 
DisableDamagedSound=  ;bool

-PackupSound
PackupSoundPlayGlobal=  ;bool 
```

Q : Why range bonus not included ? 
A : Ares hooked around that area , so i dont bother

2022-03-11 18:52 UTC, CommanderNour commented
**PackupSoundPlayGlobal** & **Power.DegradeWithHealth** doesn't work

didn't test **DisableDamagedSound**

but the rest works as intended

2022-03-12 00:24 UTC, Otamaa commented
> **PackupSoundPlayGlobal**

Fixed !

2022-03-12 07:33 UTC, CommanderNour commented
**Power.DegradeWithHealth** works fine
**DisableDamagedSound** works fine
every tag works fine except the **PackupSoundPlayGlobal** I don't understand it
does the **PackupSoundPlayGlobal** mean the PackupSound will play globally ?
if that is the case then no it doesn't work

2022-05-25 10:56 UTC, Starkku requested changes
Still needs documentation and credits. There's also a couple of things in the code I have commented upon, one style thing and another regarding functionality.

2022-05-25 10:58 UTC, Starkku commented on src/Ext/BuildingType/Hooks.cpp
> +}
If by 'play globally' you mean play independently of the current viewport position, should use `VocClass::PlayGlobal` instead of `VocClass::PlayIndexAtPos`. I am aware that the last argument for the latter is called `is_global` in at least some versions of the IDB Phobos devs are using. I however believe it does not do what is required here, if anything at all.

2022-06-04 07:41 UTC, brsajo commented
When I use this build it breaks `BunkerWallsDownSound` (Both the tag in [General] and the new local one don't work): `BunkerWallsUpSound` is used instead.

`OccupyDamageMultiplier`, `OccupyROFMultiplier`, `BunkerDamageMultiplier` and `BunkerROFMultMultiplier`, all work.
BunkerWallsUpSound set on a building also works.

Putting `PackupSoundPlayGlobal=yes` on YAREFN didn't play `DeploySound=SlaveMinerUndeploy` when the slave miner undeploys off-screen, assuming that's what the tag is meant to do.

`Power.DegradeWithHealth` works fine.

2024-07-07 10:03 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +}
The hook seemed to be removed whatsoever, so resolving this convo for now.

2024-07-07 10:12 UTC, Metadorius requested changes

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Body.cpp
> +void BuildingTypeExt::PlayBunkerSound(BuildingClass const* pThis, bool bUp)
We don't use hungarian notation for stuff apart from pointers.

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Body.cpp
> +	auto nSound = bUp ? RulesClass::Instance->BunkerWallsUpSound : RulesClass::Instance->BunkerWallsDownSound;
Same here. Won't comment on the further occurances

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Body.h
> +			, Grinding_Weapon{}
Unrelated stylistic changes, should be removed

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Body.h
> +			, Power_DegradeWithHealth{ true }
```suggestion
			, Power_DegradeWithHealth { true }
```

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum { ApplyDamageBonus = 0x6FE405, Nothing = 0x0 };
```

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum { ApplyDamageBonus = 0x6FE435, Nothing = 0x0 };
```

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum { ApplyRofMod = 0x6FD1AB, SkipRofMod = 0x6FD1B1, Nothing = 0x0 };
```

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum { ApplyRofMod = 0x6FD1EF, SkipRofMod = 0x6FD1F1, Nothing = 0x0 };
```

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum
	{
		BunkerWallUpSound = 0x45933D,
		BunkerWallUpSound_Handled_ret = 0x459374,

		BunkerWallDownSound_01 = 0x4595D9,
		BunkerWallDownSound_01_Handled_ret = 0x459612,

		BunkerWallDownSound_02 = 0x459494,
		BunkerWallDownSound_02_Handled_ret = 0x4594CD
	};
```

Also if you're defining hook addresses in the enum - maybe it could be good to have the enum defined outside of the hook and reused in hook definition macro? assuming that is possible at all

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
```suggestion
	enum
	{
		BuildingClass_TakeDamage_DamageSound = 0x4426DB,
		BuildingClass_TakeDamage_DamageSound_Handled_ret = 0x44270B,

		TechnoClass_TakeDamage_Building_DamageSound_01 = 0x702777,
		TechnoClass_TakeDamage_Building_DamageSound_01_Handled_ret = 0x7027AE,

		TechnoClass_TakeDamage_Building_DamageSound_02 = 0x70272E,
		TechnoClass_TakeDamage_Building_DamageSound_02_Handled_ret = 0x702765,

		Nothing = 0x0
	};
```

Same here.

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
Also the enum names could be less verbose tbh. Maybe name the enum, bring it outside and shorten the names?

2024-07-07 10:12 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +	};
Unnecessary

2024-07-07 10:14 UTC, Metadorius commented
Missing docs, needs stylistic changes, also apparently something is broken. @Otamaa if you're willing to fixup the stuff - please do, or maybe ask someone of the contributors to help, otherwise please close the PR as stale if there's no intention from anyone to finish the PR.

2025-06-05 14:47 UTC, Coronia approved these changes

2025-06-05 14:52 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +
should be in fixed/improved

2025-06-05 14:52 UTC, Metadorius commented on docs/Whats-New.md
> +- [Power plant damage factor](New-or-Enhanced-Logics.md#power-plant-damage-factor) (by Otamaa and Ollerus)
good change

2025-06-05 14:57 UTC, Metadorius approved these changes
LGTM otherwise

2025-06-05 14:57 UTC, Metadorius commented on src/Ext/BuildingType/Body.cpp
> +		pTypeExt->BunkerWallsDownSound.Get(RulesClass::Instance->BunkerWallsDownSound);
```suggestion
	auto const nSound = buildUp
		? pTypeExt->BunkerWallsUpSound.Get(RulesClass::Instance->BunkerWallsUpSound)
		: pTypeExt->BunkerWallsDownSound.Get(RulesClass::Instance->BunkerWallsDownSound);
```

2025-06-05 15:56 UTC, merged