Fix mind control indicator animations not reappearing on uncloak
Phobos-developers/Phobos pull request #556
Opened 2022-03-16 16:16 UTC by Starkku

Game deletes mind control animations when cloaking objects, but doesn't restore them on uncloak. This fixes that, and should function with any types of mind control animation (regular, Dominator and Ares PermaControl warheads).

2022-03-16 16:27 UTC, Metadorius requested changes
I wonder if line trails can be fixed this way too.

2022-03-16 16:27 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +					offset = 104 * pBuilding->Type->Height;
Magic numbers?

2022-03-16 17:10 UTC, Metadorius approved these changes

2022-04-09 22:57 UTC, AlliedG commented
Tested MindControl=yes MindControl.Permanent=yes and Dominator and worked as described.

![normal-mind-control_NexsUM3l](https://user-images.githubusercontent.com/84816840/162594231-8a40f17e-185a-43f3-a703-d9dc7d1c30ea.gif)

MindControl=yes

![mindcontrolpermanent_FLYDkpIL](https://user-images.githubusercontent.com/84816840/162594232-64045ea5-fea8-4581-89a6-246bc74fce85.gif)

MindControl.Permanent=yes

2022-04-10 16:59 UTC, merged