Include first version of Experience Warhead
Phobos-developers/Phobos pull request #57
Opened 2021-02-07 21:07 UTC by MortonPL

Note: including MortonUtils in a separate file still causes build to fail for magical reasons

2021-02-20 11:07 UTC, Metadorius requested changes
Looks good, left a bit of feedback in the code comments.

2021-02-20 11:07 UTC, Metadorius commented on Utilities/MortonUtils.h
> +class MortonUtils
Class would be an overkill. I introduced `GeneralUtilities.h/.cpp` file where the function could go until it's categorized.

2021-02-20 11:07 UTC, Metadorius commented on src/Utilities/MortonUtils.cpp
> +#include "MortonUtils.h"
Code duplication.

2021-02-20 11:07 UTC, Metadorius commented on src/Ext/WarheadType/Hooks.cpp
> +	auto const pTarget = abstract_cast<TechnoClass*>(pThis->Target);
@Belonit told me `abstract_cast` is the reason why it wouldn't compile.

2021-03-02 12:56 UTC, Otamaa commented
Move "AddNoNegative" function to somewhere out "GeneralUtils" to "Hook.cpp" for example , this will fix the compiler problems

2021-03-03 23:01 UTC, MortonPL commented
Since the fork is automatically rechecked, I've got some things to explain here:

- cellspread support is here, but still requires additional testing to search and destroy possible bugs.
- that <abstract_cast>(TechnoClass*) is to stay - build errors are no more and normal cast causes fatals,
- as of now warhead doesn't work with GenericWarhead SW,
- in other cases everything's fine

2021-03-18 20:02 UTC, SMxReaver commented
This is a repost of the comments made in #phobos-project to keep feedback easily found:
- Experience has been working well so far, the only noticed issue I have currently is that the effect ignores Trainable=no and will promote even civilian structures.
- In addition, infantry firing inside an opentopped transport will promote as expected when Experience.FirerGetsExp=yes. When inside a garrisoned structure however, the building itself receives the experience and the firer receives none.

2021-08-21 13:31 UTC, Metadorius commented
For reference, the suggested tags for this are:
```INI
Transact.Source.Experience.Flat=0
Transact.Source.Experience.Percent=0
Transact.Source.Experience.Percent.CalcFromTarget=false

Transact.Target.Experience.Flat=0
Transact.Target.Experience.Percent=0
Transact.Target.Experience.Percent.CalcFromSource=false

Transact.SpreadAmongAffectedTargets=true
```
The way it works is that you calculate the availability of specified value changes for target and source in form of 0-1 coeffitient (or, say, percentage from 0% to 100%), and then take the lowest coeffitient and use it for transfer. If there's no transfer (only source or only targets are affected) then you just apply that one coeffitient.

`SpreadAmongAffectedTargets` is for switching the CellSpread mode: if it's true - then the transact values are spread amongst all targets affected by this warhead (so 20 exp. flat source/target transfer divided among 4 units would transfer as 5 to each, 20 total from source), if false - then full transfer would be applied to each affected target (same situation would result in 20 to each of 4 units, 80 from source).

This is to lay out the foundation for Transact warhead expansion.

2022-03-16 22:57 UTC, MortonPL commented
After a long-needed rework, the now Transact Warhead should be ready for preliminary testing.

2022-03-17 05:33 UTC, ayylmaoRotE commented
Tested 4 times all resulted in an IE.
7C0A74F6 - rookie source & rookie aircraft target
783C1AF1 - veteran source & rookie unit target
78811AF1 - veteran source & unit target
Uploaded dumps to discord.

Used default settings with Transact=true
Tried changing some of the exp tags but no luck, still get IEs.
All attempts were with rookie and veteran units alike.

2022-03-18 03:37 UTC, ayylmaoRotE commented
541F1BB2 on CellSpread

[ExperienceWH]
Verses=10%,10%,10%,10%,10%,10%,10%,10%,10%,10%,10%
CellSpread=5
Transact=true                                          ; boolean
Transact.SpreadAmongTargets=false                       ; boolean
Transact.Experience.Source.Flat=0                       ; integer
Transact.Experience.Source.Percent=0.0                  ; float, percents or absolute (-1.0 - 1.0)
Transact.Experience.Source.Percent.CalcFromTarget=false ; boolean
Transact.Experience.Target.Flat=0                       ; integer
Transact.Experience.Target.Percent=2.0                  ; float, percents or absolute (-1.0 - 1.0)
Transact.Experience.Target.Percent.CalcFromSource=false ; boolean

2022-03-18 05:32 UTC, ayylmaoRotE commented
Same IE happens when you smash too many EXPs into a single unit too quickly:
e.g. 
[PilotWH]
Verses=0%,0%,0%,10%,10%,10%,0%,0%,0%,0%,0%
Versus.t2mediump=0%
Transact=true                                          ; boolean
Transact.SpreadAmongTargets=false                       ; boolean
Transact.Experience.Source.Flat=0                       ; integer
Transact.Experience.Source.Percent=0.0                  ; float, percents or absolute (-1.0 - 1.0)
Transact.Experience.Source.Percent.CalcFromTarget=false ; boolean
Transact.Experience.Target.Flat=0                       ; integer
Transact.Experience.Target.Percent=10.0                  ; float, percents or absolute (-1.0 - 1.0)
Transact.Experience.Target.Percent.CalcFromSource=false ; boolean

even with Percent=2.0, though I can't reproduce every time, especially if you do it 1 by 1 initially. See vids below:

https://user-images.githubusercontent.com/69301373/158943007-f646fd80-938f-4911-905c-c63efd6d8d0d.mp4


https://user-images.githubusercontent.com/69301373/158943014-c6f61e9e-2bb0-4c05-8af3-04dfbd2996b5.mp4


https://user-images.githubusercontent.com/69301373/158943016-d46b0de5-cd2d-45d3-8a63-176e3891fa3c.mp4


https://user-images.githubusercontent.com/69301373/158943025-5303baba-46ce-4cdd-9868-1b0bdb5063af.mp4

:

2022-03-25 06:31 UTC, ayylmaoRotE commented
Some more findings (bugs):
1. The Transact.Experience aspect of the warhead will ignore verses/versus and whether the target is Trainable=yes or not 
e.g. if the WH has CellSpread=6 and Verses=0%,0%,0%,10%,10%,10%,0%,0%,0%,0%,0%, everything will be affected, infantry and buildings too.

> CellSpread=<1 or no CellSpread:
> - Flat: Works on source and target
> - Percent: Works on source and target
> 
> CellSpread=1>:
> - Flat: Works on source and target
> - Percent: Works on source and target
> - Only works on weapons, if triggered via SW (GenericWarhead) it will crash

3. If an infantry has IsDesolator=yes (AreaFire potentially affects this too), this breaks CellSpread on the Exp WH, e.g.:

> CellSpread=<1 or no CellSpread:
> - Flat: Does not work at all
> - Percent: Does not work at all
> 
> CellSpread=1>:
> - Flat: The correct value will be given to the source only, e.g. 500
> - Percent: The source will instantly gain the maximum experience possible regardless of the value used
> - CellSpread value is actually ignored, it won't affect any nearby targets

4. Trainable=no is ignored, e.g. MCVs, Engineers, buildings etc will also gain veterancy

2022-05-06 21:40 UTC, mevitar commented
> EDIT: some further tests, if the unit does not die mid EXP transfer, no crashes, but the Weapon I use kills the unit (not via Suicide but via Anim=), I think this is why the crash happens, maybe store the unit info like anim2unit directions is stored?

I can confirm the on-death crashes (although in my case i tried it with Death.NoAmmo=yes, so the units always die during the transfer, even though i used an Inviso=yes projectile).

> 4. Trainable=no is ignored, e.g. MCVs, Engineers, buildings etc will also gain veterancy

I would ask for it to be kept that way, because with it and Ares' conversion-on-promotion, modders can make units that don't gain experience, but still morph into a different one when affected by an SW or attacked by something. If someone wants exclude specific units from gaining experience, there's Versus.X for that.
But preferably, it might be best if whether Trainable=no units are affected was a separate tag.

2022-05-06 22:24 UTC, mevitar commented
> 3\. If an infantry has IsDesolator=yes (AreaFire potentially affects this too), this breaks CellSpread on the Exp WH, e.g.:

It's not AreaFire=yes, that one works fine. CellSpread also appears to works fine for me (tried with CellSpread=3).
Did you perhaps try it on a test infantry? I made that mistake and it didn't work at first because incorrect sequence forced it to use primary on deploy. Once i put the weapon on a proper YuriClone-like infantry, it worked fine (except for the fact that verses were still completely ignored and everything in the area got the experience...).

2022-09-20 16:34 UTC, MortonPL commented
Reopening after a long break. All reported crashes and issues (ignoring verses and Trainable) should be addressed, updated documentation is in PR description.

2022-10-29 23:25 UTC, Metadorius reviewed
From a quick glance (can't do a full review at the time, sorry) I've found two things that bother me.

2023-03-04 14:09 UTC, closed without merging