Shield animation & pip customizations
Phobos-developers/Phobos pull request #588
Opened 2022-04-10 21:53 UTC by Starkku

Added damage-state specific shield idle animations.

In `rulesmd.ini`: (Only new keys shown)
```ini
IdleAnim.ConditionYellow=            ; animation
IdleAnim.ConditionRed=               ; animation
IdleAnimDamaged=                     ; animation
IdleAnimDamaged.ConditionYellow=     ; animation
IdleAnimDamaged.ConditionRed=        ; animation
```
An excerpt from adjusted documentation for shield idle animations:
- `IdleAnim`, if set, will be played while the shield is intact. This animation is automatically set to loop indefinitely.
  - `IdleAnim.ConditionYellow` and `IdleAnim.ConditionRed` can be used to set different animations for when shield health is at or below the percentage defined in `[AudioVisual]`->`ConditionYellow`/`ConditionRed`, respectively. If not set, `IdleAnim` is used.
  - `IdleAnimDamaged`, `IdleAnimDamaged.ConditionYellow` and `IdleAnimDamaged.ConditionRed` are used in an identical manner, but only when health of the object the shield is attached to is at or below `[AudioVisual]`->`ConditionYellow`. If none are set, then regular `IdleAnim` or variants are used.

There are also additional customizations for shield pips:

In `rulesmd.ini`: (Only new keys shown)
```ini
[AudioVisual]
Pips.Shield.Background=PIPBRD.SHP  ; filename - including the .shp/.pcx extension
Pips.Shield.Building.Empty=0       ; int, frame of pips.shp (zero-based) for empty building pip

[SOMESHIELDTYPE]                   ; ShieldType name
Pips=                              ; int, frames of pips.shp (zero-based) for Green, Yellow, Red
Pips.Building=                     ; int, frames of pips.shp (zero-based) for Green, Yellow, Red
Pips.Background=                   ; filename - including the .shp/.pcx extension
Pips.Building.Empty=               ; int, frame of pips.shp (zero-based) for empty building pip
```
An excerpt from adjusted documentation for shield pips:
- A TechnoType with a shield will show its shield Strength. An empty shield strength bar will be left after destroyed if it is respawnable. Several customizations are available for the shield strength pips.
  - By default, buildings use the 6th frame of `pips.shp` to display the shield strength while others use the 17th frame.
  - `Pips.Shield` can be used to specify which pip frame should be used as shield strength. If only 1 digit is set, then it will always display that frame, or if 3 digits are set, it will use those if shield's current strength is at or below `ConditionYellow` and `ConditionRed`, respectively. `Pips.Shield.Building` is used for BuildingTypes.
  - `Pips.Shield.Background` can be used to set the background or 'frame' for non-building pips, which defaults to `pipbrd.shp`. 4th frame is used to display an infantry's shield strength and the 3th frame for other units, or 2nd and 1st respectively if not enough frames are available.
  - `Pips.Shield.Building.Empty` can be used to set the frame of `pips.shp` displayed for empty building strength pips, defaults to 1st frame of `pips.shp`.
  - The above customizations are also available on per ShieldType basis, e.g `[ShieldType]`->`Pips` instead of `[AudioVisual]`->`Pips.Shield` and so on. ShieldType settings take precedence over the global ones, but will fall back to them if not set.
  - `BracketDelta` can be used as additional vertical offset (negative shifts it up) for shield strength bar. Much like `PixelSelectionBracketDelta`, it is not applied on buildings.

Additionally fixed an issue that caused crashes with shield idle animations under certain circumstances. This should hopefully fix the crashes some people were having with shield animations and cloaked units.

2022-04-17 12:58 UTC, ayylmaoRotE commented
[SHIELD]
Pips=n is bugged, documentation states that all condition stages should respect a single entry, it does not. It starts off as the default value in AudioVisual then at 50% it returns the 6th pip regardless of value entered
Pips=n,n,n works as described
BracketDelta= works as described

if n exceeds the number of frames available it returns nothing, which is good i suppose if you simply want to hide the shield

2022-04-17 14:35 UTC, Starkku commented
Fixes the issue with `Pips`. Both `[AudioVisual]`->`Pips_Shield(_Building)` and `[ShieldType]`->`Pips(_Building)` will now fall back to the first defined value if second or third one is not defined. If first value of  `[ShieldType]`->`Pips(_Building)` is not defined it falls back to `[AudioVisual]`->`Pips_Shield(_Building)` as a whole.

2022-04-27 00:11 UTC, mevitar commented
Are IdleAnimDamaged.X= animations supposed to always take priority over IdleAnim.X= ones? The latter will never be used if the unit's health is below green, even when shields are fully restored.

In fact, they won't switch once both health and shields are back to full either, and shields will be stuck at the IdleAnimDamaged= animation. The only way to get IdleAnim= back again is to let the shield regenerate while the unit's regular health is green. Anything but that and it won't activate.

2022-04-27 22:22 UTC, mevitar commented
```
Strength=250
AbsorbOverDamage=no
SelfHealing.Rate=.0165
SelfHealing=5
Respawn.Rate=.033
Respawn=10
IdleAnim=WARPOUT
IdleAnim.ConditionYellow=NUKEBALL
IdleAnim.ConditionRed=PDFXCLD
IdleAnim.OfflineAction=None
IdleAnim.TemporalAction=None
IdleAnimDamaged=WARPIN
IdleAnimDamaged.ConditionYellow=NUKEANIM
IdleAnimDamaged.ConditionRed=PDFXLOC
```

![shieldbug](https://user-images.githubusercontent.com/1313344/165640693-49b7954e-f4b4-4e04-af6f-e80b880288c8.gif)
Still happens in the newest build.

2022-04-28 15:20 UTC, Starkku commented
Okay that GIF clarified it to me, there was a missing check so it should work now that I amended it.

2022-04-29 20:30 UTC, mevitar commented
I guess a gif is worth a thousand words after all. :D
Woks fine in the newest build.

2022-05-05 16:34 UTC, Metadorius requested changes
Good to go after addressing the comments.

2022-05-05 16:34 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> -  - `Bouncer=yes` animations are not supported at the moment.
I guess that needs to be mentioned in the changelog.

2022-05-05 16:34 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +  - `IdleAnimDamaged`, `IdleAnimDamaged.ConditionYellow` and `IdleAnimDamaged.ConditionRed` are used in an identical manner, but only when health of the object the shield is attached to is at or belo
Maybe if `ConditionRed` ones are not set but `ConditionYellow` are then it would be better to fall back to `ConditionYellow`, not the regular one?
![image](https://user-images.githubusercontent.com/17500545/166968692-287d8f32-22f7-4e4f-9469-f33302557bb6.png)

2022-05-05 16:34 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +  - `IdleAnimDamaged`, `IdleAnimDamaged.ConditionYellow` and `IdleAnimDamaged.ConditionRed` are used in an identical manner, but only when health of the object the shield is attached to is at or belo
Alternative idea, not sure which would be better to use this though because the first one feels more natural: 
![image](https://user-images.githubusercontent.com/17500545/166969276-d72af477-d04f-450a-8f11-b01a99016215.png)

2022-05-05 16:34 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +, Respawn_Rate_Warhead { -1 }
Not sure of a reason for this change?

2022-05-05 16:37 UTC, Starkku commented on src/New/Entity/ShieldClass.cpp
> +, Respawn_Rate_Warhead { -1 }
Visual studio auto-formatting based on the current .editorconfig settings.

2022-05-05 16:38 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +, Respawn_Rate_Warhead { -1 }
> Visual studio auto-formatting based on the current .editorconfig settings.
hm, not sure if that can be configured to behave other way, either way that is undesirable.

2022-05-05 16:56 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +  - `IdleAnimDamaged`, `IdleAnimDamaged.ConditionYellow` and `IdleAnimDamaged.ConditionRed` are used in an identical manner, but only when health of the object the shield is attached to is at or belo
The first diagram looks like a sensible approach, I can probably make it follow that.

2022-05-05 16:58 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> -  - `Bouncer=yes` animations are not supported at the moment.
It doesn't actually work per se, it just doesn't instantly crash the game. That and the fact that `IsMeteor=true` animations *do* crash the game makes me think either the parsing check should be brought back (it is just going to be more complicated due to the multiple animations parsed) or there needs to be a warning in the docs.

2022-05-07 19:51 UTC, Starkku commented
Addressed the issues.

2022-05-08 14:27 UTC, Metadorius approved these changes

2022-05-08 14:27 UTC, Metadorius commented on src/Utilities/TemplateDef.h
> +	}
```suggestion
	// read the common flag, with the trailing dot being stripped
	char flagName[0x40];
	auto const pSingleFormat = pSingleFlag ? pSingleFlag : pBaseFlag;
	auto res = _snprintf_s(flagName, _TRUNCATE, pSingleFormat, "");

	if (res > 0 && flagName[res - 1] == '.')
		flagName[res - 1] = '\0';
```

2022-05-08 14:28 UTC, merged