HP and SHP Value Show
Phobos-developers/Phobos pull request #589
Opened 2022-04-12 05:26 UTC by ststl-s

Can use Text or SHP show health point and shield point

2022-04-12 09:55 UTC, Metadorius reviewed
Welcome to the Phobos project! We gathered some feedback from the discussion that probably should be applied to the pull request:
- There should be a key in `RA2MD.ini` (user configuration) to disable digital number display, like `[Phobos]>ShowDigitalHealth=yes/no`. (Additionally I think it would be good to have it toggleable via a modifier key but that's up to you if you are able or want to implement that.)
- Because masses of such numbers would lead to visual clutter - there should be an ability for modder to enable/disable the display per different TechnoType. In my opinion instead of hardcoding the parameters for every technotype and also additional default parameters you should implement a `DigitalIndicatorTypeClass` that you would be able to assign as a default one and assign to each TechnoType in art.ini somewhere, something like this:
  ```ini
  [DigitalDisplayTypes]
  0=DEFDISPL
  1=BOSSDISPL
  
  [DEFDISPL]
  ; all the parameters that you've written here, same for BOSSDISPL
  
  [AudioVisual]
  DefaultHPDisplay=DEFDISPL ; Nullable, empty by default
  
  [BOSSUNITIMAGE]
  HPDisplay=BOSSDISPL
  ```
- There should be an ability to align the text and anchor it to different sides/corners/center I guess.

In addition, the Chinese documentation should be in a translation file. @Thrifinesma @Chasheenburg can help you with that. Please use deepl.com to translate it to English. Check other documentation entries to see how it should be written.

Feel free to ask us on Discord if you need any further elaborations, we also have many Chinese users/developers who can help you.

2022-04-12 10:04 UTC, ststl-s commented
I saw the discussion on discord, they maybe didn't read the New-or-Enhanced-Logics.md carefully, digital show has 
local definition, most of functions has local definition except Buildings/Units.ShowHPOffset.WithoutShield.

2022-04-12 10:05 UTC, Metadorius commented
My point is that there's so much new tags that it would be better as it's own type class.

2022-04-12 10:07 UTC, ststl-s commented
> My point is that there's so much new tags that it would be better as it's own type class.

Ok, I get it, I will improve it later.

2022-04-12 11:30 UTC, MortonPL requested changes
- I agree with @Metadorius that this whole feature should be its own Entity & Type - right now the code is stretched, repeated  across several files (buildings, units, shields) and has effectively tripled ini flags.
- Consider using ColorStruct instead of Vector3D<int>, as it is made for handling RGB colors. Note that I haven't applied this everywhere in the review (i.e. struct fields would be R, G, B and not X, Y, Z).
- Please try to keep the style more consistent, especially in if blocks.
- To keep the alphabetical order in the documentation, this feature should be under Technos, after Promoted Spawns
- The documentation needs to be redone - there is little explanation what specific flags do and the comments in the code block are not aligned properly.
- Missing What's New and Credits entries.

2022-04-12 11:30 UTC, MortonPL commented on src/Ext/Techno/Body.cpp
> +			strcpy_s(FilenameSHP, RulesExt::Global()->Buildings_HPNumberSHP.data());
Nullable<T>::Get(T default) could simplify this code.
```suggestion
		char FilenameSHP[0x20];
		strcpy_s(FilenameSHP, pTypeExt->HP_ShowSHP.Get(RulesExt::Global()->Buildings_HPNumberSHP).data());
```

2022-04-12 11:30 UTC, MortonPL commented on src/Ext/Techno/Body.cpp
> +		else NumberPAL = pTypeExt->SHP_HealthPAL = FileSystem::LoadPALFile(FilenamePAL, DSurface::Composite);
Same as before, Get() would improve readability.
```suggestion
		char FilenamePAL[0x20];
		strcpy_s(FilenamePAL, pTypeExt->HP_ShowPAL.Get(RulesExt::Global()->Buildings_HPNumberPAL).data());
		if (strcmp(FilenamePAL, "") == 0)
		    NumberPAL = pTypeExt->SHP_HealthPAL = FileSystem::PALETTE_PAL;
		else
		    NumberPAL = pTypeExt->SHP_HealthPAL = FileSystem::LoadPALFile(FilenamePAL, DSurface::Composite);
```

2022-04-12 11:30 UTC, MortonPL commented on src/Ext/Techno/Body.h
> +	static void DrawFootClassTextValue(TechnoClass* pThis, TechnoTypeExt::ExtData* pTypeExt, Point2D vPos);
Why do you use pLocation here and vPos there?

2022-04-12 11:30 UTC, MortonPL commented on src/Ext/TechnoType/Body.h
> +		Nullable<Vector2D<int>> HP_ShowOffset;
```suggestion
		Nullable<ColorStruct> HP_ShowColorHigh;
		Nullable<ColorStruct> HP_ShowColorMid;
		Nullable<ColorStruct> HP_ShowColorLow;
		Nullable<ColorStruct> HP_ShowOffset;
```

2022-04-12 11:30 UTC, MortonPL commented on src/New/Type/ShieldTypeClass.cpp
> +	this->ShieldValue_ShowInterval.Read(exINI, pSection, "ShieldValue_ShowInterval");
```suggestion
	this->ShieldValue_ShowBackground.Read(exINI, pSection, "ShieldValue.ShowBackground");
	this->ShieldValue_UseSHPShow.Read(exINI, pSection, "ShieldValue.UseSHPShow");
	this->ShieldValue_ShowSHP.Read(pINI, pSection, "ShieldValue.ShowSHP");
	this->ShieldValue_ShowPAL.Read(pINI, pSection, "ShieldValue.ShowPAL");
	this->ShieldValue_ShowInterval.Read(exINI, pSection, "ShieldValue.ShowInterval");
```

2022-04-12 11:30 UTC, MortonPL commented on src/New/Type/ShieldTypeClass.h
> +	Nullable<Vector3D<int>> ShieldValue_ShowColorLow;
```suggestion
	Nullable<ColorStruct> ShieldValue_ShowColorHigh;
	Nullable<ColorStruct> ShieldValue_ShowColorMid;
	Nullable<ColorStruct> ShieldValue_ShowColorLow;
```

2022-04-12 11:30 UTC, MortonPL commented on src/New/Type/ShieldTypeClass.h
> +	PhobosFixedString<32U> ShieldValue_ShowPAL;
```suggestion
	Nullable<PhobosFixedString<32U>> ShieldValue_ShowSHP;
	Nullable<PhobosFixedString<32U>> ShieldValue_ShowPAL;
```

2022-04-12 11:44 UTC, ststl-s commented
Thanks. I will improve these code.

2022-04-12 18:54 UTC, ststl-s commented
Reconstructed

2022-04-13 01:07 UTC, NetsuNegi commented
I found that HP value did not perform well on spies, so I hope to add a percentage to show HP.

2022-04-13 01:36 UTC, ststl-s commented
> I found that HP value did not perform well on spies, so I hope to add a percentage to show HP.

I don't have time recently. I may do it in the future.

2022-04-14 13:10 UTC, ststl-s commented
> I noticed that Buildings.ShieldNumberInterval= doesn't seem to work? The shield value Interval doesn't changed.

The first version had some bug, some entries of shield used '_' instead of '.'
You can use the current version
Here are entries use '_'  instead of '.' in the first version
this->ShieldValue_ShowBackground.Read(exINI, pSection, "ShieldValue_ShowBackground");
this->ShieldValue_UseSHPShow.Read(exINI, pSection, "ShieldValue_UseSHPShow");
this->ShieldValue_ShowSHP.Read(pINI, pSection, "ShieldValue_ShowSHP");
this->ShieldValue_ShowPAL.Read(pINI, pSection, "ShieldValue_ShowPAL");
this->ShieldValue_ShowInterval.Read(exINI, pSection, "ShieldValue_ShowInterval");

2022-04-21 15:00 UTC, Starkku requested changes
There are some code style, documentation issues and one or two other things that should be addressed.

2022-04-21 15:00 UTC, Starkku commented on src/New/Entity/ShieldClass.cpp
> +	ConvertClass* PALFile = pDisplayType->PALFile;
There probably isn't need for empty line between each assignment statement here.

2022-04-22 15:20 UTC, ststl-s commented
> There are some code style, documentation issues and one or two other things that should be addressed.

Update completed

2022-04-22 18:22 UTC, Metadorius commented
What about the following:
> There should be an ability to align the text and anchor it to different sides/corners/center I guess.
Did you look into this?
IMO at least the anchoring of the text to the left/right/center of HP bar should be customizable. And perhaps it would be good to be able to customize the position (say, maybe someone wants it to display to the right of HP bar), but that can be left for later.

2022-04-23 11:08 UTC, ststl-s commented
> What about the following:
> 
> > There should be an ability to align the text and anchor it to different sides/corners/center I guess.
> > Did you look into this?
> > IMO at least the anchoring of the text to the left/right/center of HP bar should be customizable. And perhaps it would be good to be able to customize the position (say, maybe someone wants it to display to the right of HP bar), but that can be left for later.

I forgot about it.

2022-04-23 12:41 UTC, ststl-s commented
> What about the following:
> 
> > There should be an ability to align the text and anchor it to different sides/corners/center I guess.
> > Did you look into this?
> > IMO at least the anchoring of the text to the left/right/center of HP bar should be customizable. And perhaps it would be good to be able to customize the position (say, maybe someone wants it to display to the right of HP bar), but that can be left for later.

Update completed

2022-04-25 08:55 UTC, 8abs commented
How could a non-developer use this new logic? I completely have no idea about any code or cpp language, but I really want to add it into my DIY mode. Any chance you can give out the updated .dll and .pdb files like how they publish each version of phobos?（My email: m17891972749@163.com, I can sponsor you via Alipay or WeChat in a considerable price）
中文：蚌埠住了，一点C++(大一学的编程早忘了）都不懂怎么办，两眼一抹黑，能不能有偿求助开发者帮我合并一个解压到游戏根目录后就能直接改ini生效的压缩包（应该是dll和pdb文件？），QQ: 2358410144，价格你出。

2022-04-25 08:58 UTC, Metadorius commented
@8abs
We don't sell anything here. In fact, you don't need to compile anything yourself, just scroll through the pull request to find [this comment](https://github.com/Phobos-developers/Phobos/pull/589#issuecomment-1096144853) where you can download the most recent build with this particular feature.

2022-04-26 13:58 UTC, 8abs commented
Thank you very much for informing me that "Nightly Build" is what I need. I'm less than a noob on programming and this website's UI and basic functions. I only come here to download your masterpieces to enhance my DIY map. This function really would make my map wonderful. Thank you all for your contribution. (BTW, I will never make any profit with my map. Even I give out money as bonus for my own group of friend to play and compete to the last survivor with this map. This bring us a lot of joy. My comment about giving you money above is only for gratefulness. After all even Github support people sponsoring the contributor. Hope you can understand it.

2022-04-26 21:01 UTC, NotAGeek25 commented
How about customized font position by using coordinate and offer an option whether display maximum HP. Obviously the maximum HP part makes the text too long. (500/500 seems too long compared with a direct 500)

2022-04-27 03:20 UTC, ststl-s commented
> Is there going to be a "HugeBar" part for boss unit?

No.

2022-04-27 03:21 UTC, ststl-s commented
> How about customized font position by using coordinate and offer an option whether display maximum HP. Obviously the maximum HP part makes the text too long. (500/500 seems too long compared with a direct 500)

It may be updated in a week. Including percentage display and hide strength.

2022-05-07 15:14 UTC, ststl-s commented
All code has been completed and will not be updated unless errors are found during testing.

2022-05-09 14:55 UTC, Metadorius commented
![image](https://user-images.githubusercontent.com/17500545/167437374-69851732-97d7-433a-909f-f0ba35f79274.png)
I am not sure if default values are valid/suitable. This is with those values overriden:
```ini
[DigitalDisplayTypes]
0=DEFHPDISPLAY

[DEFHPDISPLAY]
UseSHP=yes
SHP.Interval=4,0
SHP.Interval.Building=4,2```
Offest seems to be gone somewhere and building HP are drawn whereever.

2022-05-09 15:08 UTC, ststl-s commented
> 
I use my SHP file, and these offsets are just right, like my illustration.

2022-05-09 15:12 UTC, Metadorius commented
That's not the point. The point is that it doesn't work as expected by default. The only difference between my and your SHP is that I have a smaller SHP size.

2022-05-09 15:20 UTC, ststl-s commented
> That's not the point. The point is that it doesn't work as expected by default (without specification of any parameters). The only difference between my and your SHP is that I have a smaller SHP size. By not working as expected I meant that the building text is drawn in other direction and default offset on a unit is too big. Maybe also alignment needs to be adjusted.

Wait a minute, the building display doesn't look normal. let me have a look.

2022-05-09 15:21 UTC, ststl-s commented
How to deal with the display of units? The size of SHP canvas is different.

2022-05-09 15:26 UTC, Metadorius commented
Not a full review, but a bit of the feedback. We'll give more feedback later when I get it working on my setup.
1. You missed `Offest`s in the docs.
2. I think you should remove separate building and non-building intervals and leave only one interval. We already have an ability to specify different display types, so this is redundant.

2022-05-09 15:33 UTC, Metadorius commented
> How to deal with the display of units? The size of SHP canvas is different.

Different between what?
Ideally the drawing needs to be done relative to health bar.

2022-05-09 15:43 UTC, ststl-s commented
![image](https://user-images.githubusercontent.com/103478314/167446461-e44bbe7d-6337-4dfc-9409-ed6b43a988c0.png)
Modified like this?
I don't know why the direction of your building display would be abnormal. Maybe you can use negative intervals.

2022-05-09 15:59 UTC, ststl-s commented
![image](https://user-images.githubusercontent.com/103478314/167449698-4c57a106-ef54-4149-920d-860516606cbc.png)
The default interval is a negative number, and the description in the docs is incorrect.

2022-05-09 16:03 UTC, Metadorius commented
> ![image](https://user-images.githubusercontent.com/103478314/167446461-e44bbe7d-6337-4dfc-9409-ed6b43a988c0.png) 

That looks good.

>Modified like this? I don't know why the direction of your building display would be abnormal. Maybe you can use negative intervals.

This will lead to building HP being reversed. This is not a normal behavior and should be looked into.
Overall I think you need to get HP border coordinates and draw text relative to them. Also anchoring will help customize that.

This is the ideal way of dealing with this. This way every mod author will be able to customize how he wants to display the numbers. 
![image](https://user-images.githubusercontent.com/17500545/167450606-c9cc50c4-47ed-4fcd-9c5a-f796ba251d34.png)

2022-05-09 16:10 UTC, Metadorius commented
Perhaps this will help you. Not Sure if ChrisLv works with it differently.
https://github.com/ChrisLv-CN/YRDynamicPatcher-Kratos/blob/7c2d2ce088f3bb40be67fd43f31935acb987219f/DynamicPatcher/ExtensionHooks/TechnoExt.cs#L783

2022-05-09 16:31 UTC, ststl-s commented
Now I will modify the default value of the building to supplement the description of the document. Then finish anchoring the HP boundary and finally decide whether to discard `SHP.Interval.Building`.

2022-05-09 16:31 UTC, Metadorius commented
> I'll write one in this way, and then see which one is more popular.

There's no need to see which is more popular, if you can set both anchor and alignment point every modder will be able to do both as you wrote it initially and as in my example, just select a different anchor point.

For example your current behavior will be:
```ini
Anchor=Top
Alignment=Center
```

What I want to implement:
![image](https://user-images.githubusercontent.com/17500545/167455357-2778b455-b1d8-4aae-b960-412813d3dd99.png)
```ini
Anchor=TopRight
Alignment=Right
```

What I shown in the previous comment:
```
Anchor=Right
Alignment=Left
```

2022-05-09 16:34 UTC, ststl-s commented
> > I'll write one in this way, and then see which one is more popular.
> 
> There's no need to see which is more popular, if you can set both anchor and alignment point every modder will be able to do both as you wrote it initially and as in my example, just select a different anchor point.
> 
> For example your current behavior will be:
> 
> ```ini
> Anchor=Top
> Alignment=Center
> ```
> 
> What I would personally like to see in mods: ![image](https://user-images.githubusercontent.com/17500545/167455357-2778b455-b1d8-4aae-b960-412813d3dd99.png)
> 
> ```ini
> Anchor=TopRight
> Alignment=Right
> ```
> 
> What I shown in the previous comment:
> 
> ```ini
> Anchor=Right
> Alignment=Left
> ```

Indeed. I'll modify it in this way.

2022-05-09 17:11 UTC, Metadorius commented
[number.shp.zip](https://github.com/Phobos-developers/Phobos/files/8653805/number.shp.zip)
Just for the record this is my SHP. I used 4px wide interval so the outline doesn't add too much.

2022-05-10 00:40 UTC, 8abs commented
Please don't forget to default leave some space for possible shield pip.

2022-05-13 17:57 UTC, ststl-s commented
Update complete

2022-05-13 18:09 UTC, Metadorius commented
Awesome!
Will test and review it soon, though I am not sure why you picked only `Left/Right/TopLeft/TopRight`, there's also Top, Center, BottomLeft, Bottom, BottomRight. Also I suggest to separate `Alignment` and `Anchor` types out of your code to somewhere in utilities. Those are very useful types and I am sure @MortonPL will find a use for them, for example.

2022-05-13 18:09 UTC, Metadorius commented
And yeah, for the new build to compile, you have to resolve the merge conflicts, unfortunately.

2022-05-13 18:21 UTC, ststl-s commented
> Awesome! Will test and review it soon, though I am not sure why you picked only `Left/Right/TopLeft/TopRight`, there's also Top, Center, BottomLeft, Bottom, BottomRight. Also I suggest to separate `Alignment` and `Anchor` types out of your code to somewhere in utilities. Those are very useful types and I am sure @MortonPL will find a use for them, for example.

Update it tomorrow, now is 2:00PM here. Bottom is image of unit, so I didn't use it, but still add it because someone may need to display it under the healthbar. Center... will overlap with healthbar, `TopCenter` I think can use `Align=Center`.

2022-05-13 18:25 UTC, Metadorius commented
Take your time, there's no rush. I just thought that it's not hard to add all 9 anchor positions once you added some of them, but that will make the anchoring code future-proof and further contributors may reuse it as well.

2022-05-13 18:34 UTC, ststl-s commented
> Take your time, there's no rush. I just thought that it's not hard to add all 9 anchor positions once you added some of them, but that will make the anchoring code future-proof and further contributors may reuse it as well.

Yes, but the digital display should not use all, offset is enough to adjust. The current position is absolute, without considering the size of custom pips.

2022-05-14 18:01 UTC, ststl-s commented
Two helpers:
`TechnoExt::GetScreenLocation`
`TechnoExt::GetHealthBarPostion`
`ShieldClass::DrawShieldBar` changed to use `GetHealthBarPostion`

2022-05-16 17:32 UTC, Metadorius commented
I am testing it now.
1. I am ot sure if the anchoring is working fully correct still. The letters appear higher and a pixel or two to the right of the expected position. I didn't set any offset.
![image](https://user-images.githubusercontent.com/17500545/168647873-29e02678-c731-42e7-96f4-60889575f10d.png)

```ini
[DigitalDisplayTypes]
0=DEFHPDISPLAY
1=DEFHPDISPLAY2

[DEFHPDISPLAY]
UseSHP=yes
SHP.Interval=4,0
SHP.Interval.Building=4,2
Align=Right
Anchor=TopRight

[DEFHPDISPLAY2]
UseSHP=yes
SHP.Interval=4,0
SHP.Interval.Building=4,2
Align=Right
Anchor=TopRight
HideStrength=true
```

2. There's a bug when the health drops to 0 it is green and not red.
![image](https://user-images.githubusercontent.com/17500545/168647814-9bb703ac-fafc-4af4-8f2e-dcd214646ec6.png)

2022-05-16 20:50 UTC, Metadorius commented
What I suspect is that you used hardcoded number size which is different from mine, hence why it's offset is wrong. I think in order for this to work as expected you need to dynamically get the SHP size and offset by that amount.

2022-05-17 03:48 UTC, ststl-s commented
> There's a bug when the health drops to 0 it is green and not red.

That maybe bug of `TechnoClass::IsRedHP`.

2022-05-17 04:35 UTC, ststl-s commented
> What I suspect is that you used hardcoded number size which is different from mine, hence why it's offset is wrong. I think in order for this to work as expected you need to dynamically get the SHP size and offset by that amount.

Now use `SHPFile->Height`, check `pThis->Health==0` and fix the bug of shieldpoint display color always same to healthpoint.

2022-05-17 04:41 UTC, ststl-s commented
use your `number.shp`

![image](https://user-images.githubusercontent.com/103478314/168730488-5afa91d2-ba46-429d-97d0-fe00409d788c.png)

2022-05-22 14:04 UTC, Metadorius commented
I'll push some changes soon. There are quite a few areas to improve and it would be better if I fix the major ones of them and you will see what I meant.

2022-05-23 02:53 UTC, ststl-s commented
> I'll push some changes soon. There are quite a few areas to improve and it would be better if I fix the major ones of them and you will see what I meant.

ok.

2022-06-16 17:45 UTC, Metadorius requested changes
Sorry, I was in process of improving the code but currently busy with real life stuff so didn't finish it, so I'll briefly go through major issues. 
I've started doing a prototype of a generic anchor class that is useful for other purposes too here, please use it as a starter: https://gist.github.com/Metadorius/c69fc4a79412a7ed2b705090362ce33f

Please see my review for details, there are lots of them. Also you really should do another pass at code style and documentation style, the code is inconsistent with the existing code.

2022-06-16 17:45 UTC, Metadorius commented on src/New/Type/DigitalDisplayTypeClass.h
> +	Valueable<ColorStruct> Text_ColorLow;
Pretty sure this doesn't account for all different infotypes. Also look at `Damageable` template, it may be useful for you.

2022-06-16 17:45 UTC, Metadorius commented on src/New/Type/DigitalDisplayTypeClass.h
> +	void DigitalDisplaySHP(TechnoClass* pThis, Point2D Pos, int ValueA, int ValueB);
1. Non-static functions can't have args named `pThis`. `pThis` is only useful when you need to fake a non-static function of a class that's being extended, hence the name `pThis`.
2. I feel there are some issues with how and where the functions are written. Like why do you need location if you already have TechnoClass?

What changes I propose:
- `RunDigitalDisplay` should be moved to TechnoExt and renamed into `DrawDigitalDisplays` or probably `ProcessDigitalDisplays`, with `pLocation` removed;
- The code for selecting the values based on DigitalDisplay's `InfoType` should be in a separate function that would return two values of the type you need;
- `DigitalDisplay` should be renamed into `Display` and have it's `pLocation` arg removed (pretty sure you can get that info from the techno itself), also moved to TechnoExt probably because it relates more to techno itself (DigitalDisplay would be a `pDisplay` then);
- Add a `Draw` function which would dispatch between two of those functions, takes position, current value, maximum value (NOT TechnoClass! they should not know of TechnoClass) and draws the display there;
- Remaining two `...Text` and `...SHP` methods should be renamed to `DrawText` and `DrawShape` with the same arg as Draw and made private.

2022-06-16 17:45 UTC, Metadorius commented on src/New/Type/ShieldTypeClass.h
> +
```suggestion

```

2022-06-16 17:45 UTC, Metadorius commented on src/PhobosHelper/Helper.cpp
> +}
Not clear what it does.

2022-06-16 17:45 UTC, Metadorius commented on src/Utilities/Enum.h
> +MAKE_ENUM_FLAGS(HealthBarAnchors);
This is only for bitflags enums, should not used on regular enumerations.

2022-06-16 18:00 UTC, Metadorius commented
Forgot to add.
1. I still can't get DigitalDisplay to consistently align to right side of the HP bar at correct position. without having to do some weird offset tweaks.
2. Since you added multiple info display types I think you should use the selection border (that is hidden by default but otherwise there AFAIK) as a canvas for anchoring I think. It would make no sense to display passengers on top for example. The same treatment should be done with buildings. It's quite a challenge because in case of buildings you would need to be able to attach it to corners/center of the hexagon that is the projection of a selection border on the screen.

2022-06-16 18:04 UTC, Metadorius commented
> ![image](https://user-images.githubusercontent.com/103478314/167449698-4c57a106-ef54-4149-920d-860516606cbc.png) The default interval is a negative number, and the description in the docs is incorrect.

On the other thought yeah, you were right because screen cords start from top left and we offset from bottom left, so it makes sense to have one of the offset coords negative, my bad.

2022-06-17 07:46 UTC, ststl-s commented
> Forgot to add.
> 
> 1. I still can't get DigitalDisplay to consistently align to right side of the HP bar at correct position. without having to do some weird offset tweaks.
> 2. Since you added multiple info display types I think you should use the selection border (that is hidden by default but otherwise there AFAIK) as a canvas for anchoring I think. It would make no sense to display passengers on top for example. The same treatment should be done with buildings. It's quite a challenge because in case of buildings you would need to be able to attach it to corners/center of the hexagon that is the projection of a selection border on the screen.

Ok, I'll start fix these after a while.

2022-07-06 20:35 UTC, ststl-s commented
I think `Shape.Interval.Building` can provide a better default value, and don't needs to create a new type, convenient for modders to modify.

Shape canvas should as bigger as number, or will difficult to adjustment.

2022-07-06 20:41 UTC, Metadorius commented
> I think `Shape.Interval.Building` can provide a better default value, and don't needs to create a new type, convenient for modders to modify.

It's the inconsistency that is bothering me. Why have only one separate building-only key? Why not make other keys working the same way if you're adding a separate key here? Besides, vehicle and infantry canvas are different too and may have different sizings, but we don't provide a separate key for them.

> Shape canvas should as bigger as number, or will difficult to adjustment.

What do you mean exactly?

2022-07-06 20:45 UTC, ststl-s commented
> What do you mean exactly?

If the canvas is too large, it is difficult to adjust, because many position adjustments are made through the height of the SHP file.

Maybe I should let someone else write the docs. My English level is too poor.

2022-07-06 20:58 UTC, ststl-s commented
Check whether there are other places that need to be modified, and if you insist `Shape.Interval.Building` is.... useless, I will delete this entry, I am inexperienced in this field.

Now I need to go to bed because 5:00AM here.... if there are other problems, I will correct them tomorrow.

2022-07-08 13:38 UTC, Metadorius submitted a review, later dismissed
You didn't address a good part of my comments. Please, go over ALL of the comments and address them one by one. If you don't understand what I mean then ask to clarify.

2022-07-08 13:38 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		ValueableVector<DigitalDisplayTypeClass*> Aircrafts_DefaultDigitalDisplayTypes;
This isn't addressed still.

2022-07-08 18:07 UTC, ststl-s commented
Docs and new problems will fix tomorrow.

2022-07-09 16:53 UTC, ststl-s commented
How to write doc when the default value is different in different cases? For example, `InfoType=Shield`, `Offset.ShieldDelta` default to `0,-10`, others `0,0`.

2022-07-09 19:16 UTC, Metadorius commented
> How to write doc when the default value is different in different cases? For example, `InfoType=Shield`, `Offset.ShieldDelta` default to `0,-10`, others `0,0`.

You can write that outside of the code block.

2022-07-26 06:13 UTC, brsajo commented
IMO the documentation should be put in `User Interface` -> `Battle screen UI/UX`, not `New / Enhanced Logics` -> `New types / ingame entities`.

It also needs some introduction to the feature, for example: 

> - You can now configure various types of numerical counters to be displayed over TechnoTypes to represent its attributes such as strength or shield strength.

2022-07-26 14:19 UTC, ststl-s commented
> IMO the documentation should be put in `User Interface` -> `Battle screen UI/UX`, not `New / Enhanced Logics` -> `New types / ingame entities`.
> 
> It also needs some introduction to the feature, for example:
> 
> > * You can now configure various types of numerical counters to be displayed over TechnoTypes to represent its attributes such as strength or shield strength.

It has been moved. Your example of introduction is used and slightly modified.

2022-07-27 08:41 UTC, ststl-s commented
> Alignment seems to be broken for text displays. ![noshape](https://user-images.githubusercontent.com/86821333/181061824-8328b0f9-76f9-42d1-9311-60a5ce267bc6.png) ![withshape](https://user-images.githubusercontent.com/86821333/181061833-bd721580-9dd3-4195-ba51-0ebe77f073f2.png)
> 
> Also, what exactly does `Border` do? What would you use it for that you can't do with `Anchor.Horizontal` and `Anchor.Vertical`?
> 
> On the topic of Anchors, shouldn't a display with `Align=Center` be centered on the unit if `Anchor.Horizontal` is set to `=Center`? Currently to have the display in the center, you must have `Anchor.Horizontal=Left` and `Align=Center` offsets the text far enough to the right to be in the middle. This makes little sense as soon as you try using `Align=Center` with other anchors because instead of being centered on the anchor, it is drawn way off to the right.

Text right alignment fixed.
Border is a automatic position fix, like this. 
![image](https://user-images.githubusercontent.com/103478314/181202560-2fce9629-2bd7-4850-b68f-bb0eb9b2a467.png)

![image](https://user-images.githubusercontent.com/103478314/181202188-d9211957-b0cd-4723-aa7f-eb46a27aecf0.png)

2022-07-27 12:42 UTC, brsajo commented
> Border is a automatic position fix, like this. 
![image](https://user-images.githubusercontent.com/103478314/181202560-2fce9629-2bd7-4850-b68f-bb0eb9b2a467.png)
> 
> ![image](https://user-images.githubusercontent.com/103478314/181202188-d9211957-b0cd-4723-aa7f-eb46a27aecf0.png)

What are the anchor points relative to? I was under the impression that they were in relation to the HP bar, and if that is the case then I would expect the code to get the result you have shown in [test2] to look like this:
![test2](https://user-images.githubusercontent.com/86821333/181216104-f0aa7a23-36b9-421b-b956-189fcd212638.png)

Or are anchors actually relating to the border? If that is true then users would need a diagram or at least a better explanation for where the anchor points are in relation to a unit and a structure. It could look something like this:
![AnchorPointsExample](https://user-images.githubusercontent.com/86821333/181248999-5d5fc04e-8152-4bcb-9f07-3fd9b5e4e8af.png)

2022-07-27 16:36 UTC, ststl-s commented
Anchor just position to the select bracket. `Border=top` decide it is upper of healthbar and `Border=left` is left side of rectangle. Border is a reference for positioning when anchor is vertex. `Anchor.Horizontal=left Anchor.Vertical=bottom` just set position to left top vertex, `Border=top` set upper of healthbar, `Border=left` set left side. 
![image](https://user-images.githubusercontent.com/103478314/181298289-1d79dca3-8118-4a00-8eb1-a378ff138e51.png)
 
For example, if you want to draw numbers on the right side of health bar
```ini
[test1]
Offset=0,-5
Percentage=yes
Border=right
Anchor.Horizontal=right
Anchor.Vertical=top
```
![image](https://user-images.githubusercontent.com/103478314/181301560-7cab1e01-63b3-40bf-810e-dd877e96b5f5.png)

Want to draw numbers on upper of health bar
```ini
[test1]
Percentage=yes
Align=right
Border=top
Anchor.Horizontal=right
Anchor.Vertical=top
```
![image](https://user-images.githubusercontent.com/103478314/181301263-e175ea24-8980-4a2b-a77a-cf7341d8e2a3.png)

2022-07-27 16:42 UTC, ststl-s commented
And `Border=left` and `Border=right` has a automatic adjustment to avoid numbers are drawn on techno.

![image](https://user-images.githubusercontent.com/103478314/181302629-a2b06a41-e097-4167-a9de-b9de39401669.png)

2022-08-05 16:22 UTC, brsajo commented
Sorry for the image spam, I've tested every combination of the following tags:
`Align` `Anchor.Horizontal` `Anchor.Vertical` `Border`

In all of these examples, the infantry on the left and the vehicle on the right use the following:

```
InfoType=health        
Offset=0,9
Percentage=no
HideMaxValue=yes
Shape=number.shp
Shape.Interval=5,0
```

The vehicle in the middle doesn't use a SHP so it only uses these:
```
InfoType=Health
Percentage=no         
HideMaxValue=yes      
```

![BorderTop](https://user-images.githubusercontent.com/86821333/183108510-a3323d51-175a-44ee-93dd-1f844c496b8e.png)
![BorderLeft](https://user-images.githubusercontent.com/86821333/183108559-3bb6f01b-8eca-495c-8ac6-f762d12923f9.png)
![BorderRight](https://user-images.githubusercontent.com/86821333/183108614-806bc730-96d1-44fc-a400-32adf474c548.png)
![BorderBottom](https://user-images.githubusercontent.com/86821333/183108688-74c02640-96e1-42a4-a8fb-e7cc21ec7b0c.png)

Please inspect these carefully, since there are inconsistencies and I agree with Kerbiter that there doesn't seem to be much point in having a `Border` tag when you should be able to achieve those positions with just the `Anchor.` tags. If needed I can show what I'd expect as an end user.

2022-08-05 16:43 UTC, Metadorius commented
Yeah we discussed in Discord that Border tag is currently pointless.
Judging from your definition `Border=top` = `Anchor.Horizontal=Center` + `Anchor.Vertical=Top`.

2022-08-06 06:19 UTC, ststl-s commented
> Sorry for the image spam, I've tested every combination of the following tags: `Align` `Anchor.Horizontal` `Anchor.Vertical` `Border`
> 
> In all of these examples, the infantry on the left and the vehicle on the right use the following:
> 
> ```
> InfoType=health        
> Offset=0,9
> Percentage=no
> HideMaxValue=yes
> Shape=number.shp
> Shape.Interval=5,0
> ```
> 
> The vehicle in the middle doesn't use a SHP so it only uses these:
> 
> ```
> InfoType=Health
> Percentage=no         
> HideMaxValue=yes      
> ```
> 
> ![BorderTop](https://user-images.githubusercontent.com/86821333/183108510-a3323d51-175a-44ee-93dd-1f844c496b8e.png) ![BorderLeft](https://user-images.githubusercontent.com/86821333/183108559-3bb6f01b-8eca-495c-8ac6-f762d12923f9.png) ![BorderRight](https://user-images.githubusercontent.com/86821333/183108614-806bc730-96d1-44fc-a400-32adf474c548.png) ![BorderBottom](https://user-images.githubusercontent.com/86821333/183108688-74c02640-96e1-42a4-a8fb-e7cc21ec7b0c.png)
> 
> Please inspect these carefully, since there are inconsistencies and I agree with Kerbiter that there doesn't seem to be much point in having a `Border` tag when you should be able to achieve those positions with just the `Anchor.` tags. If needed I can show what I'd expect as an end user.

ok... It seems that `Border` is really pointless. Just `Offset` and `Anchor` are enough.

2022-08-06 07:31 UTC, ststl-s commented
There was a problem with the alignment, I use `&` instead of `|`....

2022-08-06 18:09 UTC, brsajo commented
That fixed it; text alignment and related tags now work as expected. 😄
![SHPs](https://user-images.githubusercontent.com/86821333/183260019-9e3b213e-a985-4e46-a5f8-1774c0d96a65.png)
![Text](https://user-images.githubusercontent.com/86821333/183260022-a73a0507-4cc8-443c-b00b-0b1a7db587c2.png)

Haven't done much testing with buildings yet, will do that next.
There are a couple of minor things I've noticed that could potentially be improved:

- Displays can be seen regardless of who owns the unit/building. Often it is undesirable for info on enemy owned technos to be available to a player, so it would be best if there was a tag you could put on each DigitalDisplayType to choose who can see it, e.g. (owner/self|allies/ally|observers|enemies/enemy|all)
- Very minor issue, digital display on buildings are affected by magbeam laser distortion
![MagBeam](https://user-images.githubusercontent.com/86821333/183260773-babaf5c0-13da-402c-b75c-aac76d651619.png)

2022-08-07 16:37 UTC, brsajo commented
Text display on buildings is all working fine, although it would be nice if displays could be drawn over the pips. 
You can see below how the building pips overlap ontop of the display:
![Overlap](https://user-images.githubusercontent.com/86821333/183298631-0c5f6f29-7816-49b1-ba75-461100304a2a.png)

For SHPs there are a couple of issues. 
1. Align seems to be a bit off to the left. 
If I understand correctly, the blue display in the image should be centered on the white line.
![align=center on shp](https://user-images.githubusercontent.com/86821333/183298617-cccdd5dd-c81b-4d86-a273-3cfe18cf5c25.png)
2. Setting Align=center causes crash if Shape.Interval has a vertical number higher or lower than 0. 
If not fixable then it needs a warning in the docs since shps default to Shape.Interval=8,-4.

2022-08-08 14:55 UTC, ststl-s commented
Magbeam can also affect healthbar, I don't know how to fix this.

2022-08-12 05:25 UTC, brsajo commented
`CanSee` and `CanSee.Observer` are working correctly. Remember to put them in the docs.

Also why have `Offset.ShieldDelta=`? 
In my testing, it appears to do nothing unless the techno has a shield, making it useless for DisplayTypes other than Shield, and unless there's something I haven't considered something, its purpose is fulfilled by  `Offset`.

2022-08-12 06:30 UTC, ststl-s commented
> `CanSee` and `CanSee.Observer` are working correctly. Remember to put them in the docs.
> 
> Also why have `Offset.ShieldDelta=`? In my testing, it appears to do nothing unless the techno has a shield, making it useless for DisplayTypes other than Shield, and unless there's something I haven't considered something, its purpose is fulfilled by `Offset`.

Supplement: 
```ini
Offset.ShieldDelta=                    ; integer - horizontal, vertical, offset when shield exist, final offset = Offset + Offset.ShieldDelta
```

If I want to display health value above the healthbar, it will be overlapped by shieldbar if this techno has shield, `Offset.Shield` can adjust automatically.

2022-09-04 13:16 UTC, Kanegawa-TK commented
This maybe a problem? I use the textbox and produce many TechnoType,When I select them and make the screen full down, some number show up on the selection box which under the screen.
![(YYWXK_AY(UR){`XF{W1D2G](https://user-images.githubusercontent.com/107867636/188315461-43559849-6bbd-4851-86c9-6c6f2f1c4f29.png)

2022-09-04 13:21 UTC, chaserli commented on src/New/Type/DigitalDisplayTypeClass.cpp
> +	DSurface::Temp->DrawTextA(text, &rect, &posDraw, color, 0, ePrintType);
You need to do `rect.Height-=32` before that, check flyingstrings and placementpreview for example

2022-09-04 14:01 UTC, Kanegawa-TK commented on src/New/Type/DigitalDisplayTypeClass.cpp
> +	DSurface::Temp->DrawTextA(text, &rect, &posDraw, color, 0, ePrintType);
Ohho, thank you very much

2022-10-14 11:09 UTC, MortonPL commented on docs/User-Interface.md
> +
Rewrote this section to match style, fix errors and make it clear to readers. I also propose to rename `Shape.Interval` to `Shape.Spacing`, a more fitting word (this of course will need to be changed in code too, but I won't make suggestions everywhere).

I believe that there should additionally be images showing anchor position (especially `Anchor.Building`, as referring to buildings as hexagons might be initially confusing).

```suggestion
### Digital display

![image](_static/images/DigitalDisplay1.png)

![image](_static/images/DigitalDisplay2.png)

- You can now configure various types of numerical counters to be displayed over Techno to represent its attributes, such as health points or shield points.
  - `Anchor.Horizontal` and `Anchor.Vertical` set the anchor point of display relative to unit center. For buildings, `Anchor.Building` is used instead.
    - `Offset` and `Offset.ShieldDelta` (the latter applied when a shield is active) can be used to further modify the position.
  - By default, values are displayed in `current/maximum format` (i.e. 20/40). `HideMaxValue=yes` will make counter show only the current value (i.e. 20). `Percentage=yes` changes the format to `percent%` (i.e. 50%).
  - `CanSee` and `CanSee` observer can limit visibility to specific players.
  - The digits can be either a custom shape or a text drawn using the game font. This depends on wheter `Shape` is set.
    - `Text.Color`, `Text.Color.ConditionYellow` and `Text.Color.ConditionRed` allow to customize font color. `Text.Background=yes` will additionally draw a black rectangle background.
    - When using shapes, a custom palette can be specified with `Palette`. `Shape.Spacing` controls pixel spacing between characters.
    - Frames 0-9 will be used as digits when the owner's health bar is green, 10-19 when yellow, 20-29 when red. For `/` and `%` characters, frame numbers are 30-31, 32-33, 34-35, respectively.
  - Default `Align` for texts is `right` for BuildingTypes, `center` for others.
  - Default `Align` for shapes is `left` for BuildingTypes, `center` for others.

In `rulesmd.ini`:

```ini
[DigitalDisplayTypes]
0=SOMEDIGITALDISPLAYTYPE

[AudioVisual]
Buildings.DefaultDigitalDisplayTypes=  	; list of DigitalDisplayTypes
Infantry.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes
Vehicles.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes
Aircraft.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes

[SOMEDIGITALDISPLAYTYPE]				; DigitalDisplayType
; Generic
InfoType=Health                        	; displayed value enumeration (health|shield|ammo|mindcontrol|spawns|passengers|tiberium|experience|occupants|gattlingstage)
Offset=0,0                             	; integer - horizontal, vertical
Offset.ShieldDelta=0,0                  ; integer - horizontal, vertical, added to Offset when a techno is shielded, defaults to 0,-10 when InfoType=shield
Align=None                             	; Text alignment enumeration, - left|right|center/centre|none
Anchor.Horizontal=Left                 	; Horizontal position enumeration (left|center/centre|right)
Anchor.Vertical=top                    	; Vertical position enumeration (top|center/centre|bottom)
Anchor.Building=lefttop                	; Hexagon vertex enumeration (top|lefttop|leftbottom|bottom|rightbottom|righttop)
Percentage=no                          	; boolean
HideMaxValue=no                        	; boolean
CanSee=owner                           	; Affected house enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
CanSee.Observer=true                   	; boolean
; Text
Text.Color=0,255,0                     	; integer - Red,Green,Blue
Text.Color.ConditionYellow=255,255,0   	; integer - Red,Green,Blue
Text.Color.ConditionRed=255,0,0        	; integer - Red,Green,Blue
Text.Background=no                     	; boolean
; Shape
Shape=                                 	; filename with .shp extension, if not present, game-drawn text will be used instead
Palette=palette.pal                    	; filename with .pal extension
Shape.Spacing=8,0                     	; integer - horizontal and vertical spacing between digits, can be negative, defaults to 8,-4 for buildings

[SOMETECHNOTYPE]
DigitalDisplay.Disable=no              	; boolean
DigitalDisplayTypes=                   	; list of DigitalDisplayTypes
```

In `RA2MD.ini`:

```ini
DigitalDisplay.Enable=false		; boolean
```

```

2022-10-14 16:41 UTC, brsajo requested changes

2022-10-14 16:41 UTC, brsajo commented on docs/User-Interface.md
> +
Some minor changes based on Morton's suggestion:
```suggestion
### Digital display

![image](_static/images/DigitalDisplay1.png)

![image](_static/images/DigitalDisplay2.png)

- You can now configure various types of numerical counters to be displayed over Techno to represent its attributes, such as health points or shield points.
 - `Anchor.Horizontal` and `Anchor.Vertical` set the anchor point from which the display is drawn (depending on `Align`) relative to unit's center/selection box. For buildings, `Anchor.Building` is used instead.
    - `Offset` and `Offset.ShieldDelta` (the latter applied when a shield is active) can be used to further modify the position.
  - By default, values are displayed in `current/maximum` format (i.e. 20/40). `HideMaxValue=yes` will make the counter show only the current value (i.e. 20). `Percentage=yes` changes the format to `percent%` (i.e. 50%).
  - `CanSee` and `CanSee.Observer` can limit visibility to specific players.
  - The digits can be either a custom shape (.shp) or text drawn using the game font. This depends on whether `Shape` is set.
    - `Text.Color`, `Text.Color.ConditionYellow` and `Text.Color.ConditionRed` allow customization of the font color. `Text.Background=yes` will additionally draw a black rectangle background.
    - When using shapes, a custom palette can be specified with `Palette`. `Shape.Spacing` controls pixel buffer between characters.
    - Frames 0-9 will be used as digits when the owner's health bar is green, 10-19 when yellow, 20-29 when red. For `/` and `%` characters, frame numbers are 30-31, 32-33, 34-35, respectively.
  - Default `Align` for texts is `right` for BuildingTypes, `center` for others.
  - Default `Align` for shapes is `left` for BuildingTypes, `center` for others.

In `rulesmd.ini`:

```ini
[DigitalDisplayTypes]
0=SOMEDIGITALDISPLAYTYPE

[AudioVisual]
Buildings.DefaultDigitalDisplayTypes=  	; list of DigitalDisplayTypes
Infantry.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes
Vehicles.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes
Aircraft.DefaultDigitalDisplayTypes=   	; list of DigitalDisplayTypes

[SOMEDIGITALDISPLAYTYPE]				; DigitalDisplayType
; Generic
InfoType=Health                        	; Displayed value enumeration (health|shield|ammo|mindcontrol|spawns|passengers|tiberium|experience|occupants|gattlingstage)
Offset=0,0                             	; integer - horizontal, vertical
Offset.ShieldDelta=0,0                  ; integer - horizontal, vertical, added to Offset when a techno is shielded, defaults to 0,-10 when InfoType=shield
Align=None                             	; Text alignment enumeration, - left|right|center/centre|none
Anchor.Horizontal=Left                 	; Horizontal position enumeration (left|center/centre|right)
Anchor.Vertical=top                    	; Vertical position enumeration (top|center/centre|bottom)
Anchor.Building=lefttop                	; Hexagon vertex enumeration (top|lefttop|leftbottom|bottom|rightbottom|righttop)
Percentage=no                          	; boolean
HideMaxValue=no                        	; boolean
CanSee=owner                           	; Affected house enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
CanSee.Observer=true                   	; boolean
; Text
Text.Color=0,255,0                     	; integer - Red,Green,Blue
Text.Color.ConditionYellow=255,255,0   	; integer - Red,Green,Blue
Text.Color.ConditionRed=255,0,0        	; integer - Red,Green,Blue
Text.Background=no                     	; boolean
; Shape
Shape=                                 	; filename with .shp extension, if not present, game-drawn text will be used instead
Palette=palette.pal                    	; filename with .pal extension
Shape.Spacing=8,0                     	; integer - horizontal and vertical spacing between digits, can be negative, defaults to 8,-4 for buildings

[SOMETECHNOTYPE]
DigitalDisplay.Disable=no              	; boolean
DigitalDisplayTypes=                   	; list of DigitalDisplayTypes
# (<--Remove) ```

In `Ra2MD.ini`:

```ini
[Phobos]
DigitalDisplay.Enable=false  ; boolean
# (<--Remove) ```

```

2022-10-15 10:52 UTC, Metadorius commented on docs/User-Interface.md
> +
> `Shape.Interval` to `Shape.Spacing`, a more fitting word (this of course will need to be changed in code too, but I won't make suggestions everywhere).

Unless the logic is changed not really, it's currently working like an interval between characters, so if the character is 4 pixel wide - you're going to set something like 5 px interval so that the display has 1 px of space between characters.

2022-10-15 11:37 UTC, Metadorius commented on docs/User-Interface.md
> +Align=None                             ; TextAlign Enumeration, - left|right|center/centre|none
`none` (or `<none>`) is not actually a part of enumeration and should not be listed as a value. It's just indicating that there's no value set.

2023-01-15 14:21 UTC, Starkku requested changes
Besides the merge conflicts, I did not notice anything that'd immediately pop out as requiring changes other than some nitpicks about documentation and one ambiguously named key.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +[SOMEDIGITALDISPLAYTYPE]				; DigitalDisplayType
Aligment of `; DigitalDisplayType` / the comment should match the ones below it.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +Offset.ShieldDelta=0,0                  ; integer - horizontal, vertical, added to Offset when a techno is shielded, defaults to 0,-10 when InfoType=shield
The description about shielded technos (so everything after `vertical` is redundant since it is mentioned in the comprehensive feature documentation above the code block.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +Shape.Interval=8,0                     	; integer - horizontal and vertical spacing between digits, can be negative, defaults to 8,-4 for buildings
Again, detailed descriptions should be left to the feature descriptions above code block.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +
Unnecessary empty line between INI name and code block.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +
Unnecessary empty line between INI name and code block.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +# (<--Remove) ```
What is the purpose of this line? `# (<--Remove) `

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +CanSee.Observer=true                   	; boolean
`CanSee` should be renamed to something that makes it more obvious it takes the house enumeration as a value. For an example, `VisibleToHouses.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +HideMaxValue=no                        	; boolean
Use `true / false` for boolean values in documentation instead of `yes / no`.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +Text.Background=no                     	; boolean
Use `true / false` for boolean values in documentation instead of `yes / no`.

2023-01-15 14:21 UTC, Starkku commented on docs/User-Interface.md
> +DigitalDisplay.Disable=no              	; boolean
Use `true / false` for boolean values in documentation instead of `yes / no`.

2023-06-21 17:14 UTC, Starkku approved these changes
Took liberty of merging develop to it and fixing a couple of code style issues, looks good to me now.

2023-07-11 13:49 UTC, Metadorius approved these changes

2023-07-11 13:49 UTC, merged