FlyingStrings / TransactMoney.Display / Grinding.DisplayRefund / Display damage hotkey command
Phobos-developers/Phobos pull request #590
Opened 2022-04-12 12:23 UTC by Starkku

FlyingStrings implementation based on the original [Ares implementation](https://github.com/Ares-Developers/Ares/blob/596cb2103f9f1677ae2cb06084a4a0fbbf27c503/src/Misc/FlyingStrings.h) by AlexB & Joshy, modified by otamaa and Starkku.

`Grinding.DisplayRefund` can be set to display the amount of credits acquired upon grinding on the building. Multiple refunded objects within a short period of time have their refund amounts coalesced into single display.
  - `Grinding.DisplayRefund.Houses` determines which houses can see the credits display.
  - `Grinding.DisplayRefund.Offset` is additional pixel offset for the center of the credits display, by default (0,0) at building's center.

In `rulesmd.ini`:
```ini
[SOMEBUILDING]                     ; BuildingType
Grinding.DisplayRefund=false       ; boolean
Grinding.DisplayRefund.Houses=All  ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
Grinding.DisplayRefund.Offset=0,0  ; X,Y, pixels relative to default
```
![image](https://user-images.githubusercontent.com/1392346/164781302-55bb527c-d8d6-47b8-a078-6140cc6b402e.png)

`TransactMoney.Display` can be set to display the amount of credits given or deducted. The number is displayed in green if given, red if deducted and will move upwards after appearing.
  - `TransactMoney.Display.AtFirer` if set, makes the credits display appear on firer instead of target. If set and firer is not known, it will display at target regardless.
  - `TransactMoney.Display.Houses` determines which houses can see the credits display.
  - `TransactMoney.Display.Offset` is additional pixel offset for the center of the credits display, by default (0,0) at target's/firer's center.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]                        ; Warhead
TransactMoney.Display=false          ; boolean
TransactMoney.Display.AtFirer=false  ; boolean
TransactMoney.Display.Houses=All     ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
TransactMoney.Display.Offset=0,0     ; X,Y, pixels relative to default
```
![image](https://user-images.githubusercontent.com/1392346/162961593-bd3ca7ed-517f-434c-9073-7e88ae9bbe56.png)

There's a new hotkey to show exact numbers of damage dealt on units & buildings. The numbers are shown in red (blue against shields) for damage, and for healing damage in green (cyan against shields). They are shown on the affected units and will move upwards after appearing. Available only if `DebugKeysEnabled` under `[GlobalControls]` is set to true in `rulesmd.ini`.

![image](https://user-images.githubusercontent.com/1392346/162967565-1dad97bf-e886-432d-9362-904ea23e919e.png)![image](https://user-images.githubusercontent.com/1392346/162967695-a81f14fa-5dec-4742-9836-7ca6aad82f2d.png)

2022-04-18 01:05 UTC, ayylmaoRotE commented
Works as described. Tried on death, deploy and normal weapons. Some  comments:

1. Would be good if additional display options were possible:

`TransactMoney.DisplayFor=owner` ;owner,team,enemies,all (def=all)
`TransactMoney.DisplaySelf=yes` ;bool, display at position of techno firing this weapon? (def=no)
`TransactMoney.DisplayOffset=0,0` ;int, x,y (def=0,0)

3. Needs smoothing out, e.g. it looks as if it jumps or lags a few pixels in the first second of its life:
![transactgiffy](https://user-images.githubusercontent.com/69301373/163739269-9179c88e-db0d-4267-9d47-3a6b78357b6b.gif)

2022-04-18 17:44 UTC, Starkku commented
1. Sensible suggestions for additional features I can take a look at implementing.
2. This behaviour is consistent with Ares' flying strings (`ProduceCashDisplay/BountyDisplay`) which also do not move upwards for the first 5 frames of their lifetime.

2022-05-02 22:37 UTC, mevitar commented
All tags appear to be working fine, at least in offline games. I did find, however, that WW math sucks (how much is 40% out of 1000$? 399! :D ).

2022-05-05 16:01 UTC, Metadorius requested changes
Other than a few small issues I see no problems here.

2022-05-07 19:06 UTC, Starkku commented
Fixed the remaining issues. Merging.

2022-05-07 19:06 UTC, merged