Units can fire superweapons
Phobos-developers/Phobos pull request #592
Opened 2022-04-13 05:47 UTC by chaserli

### Fire superweapons by units

- Superweapons can be launched when a unit is firing using its primary/secondary or any certain gattling stage weapon.
    - `FireSuperWeapons.RealLaunch` controls whether the owner of the technotype must own the listed superweapon or launch them out of nowhere
    - `FireSuperWeapons.UseWeapon ` indicate the weapon index used for launching superweapon. 0 for primary, 1 for secondary. Gattling weapons are supported as well, but the exact number should be find out by user (I don't know how this is calculated yet). Death weapon is not supported.
    - `FireSuperWeapons.TargetSelf` indicate whether the superweapon should be launched at the firer itself or the target cell

In `rulesmd.ini`

```ini

[TechnoType]                               ; Infantry, Unit, Aircraft, and eventually Building
FireSuperWeapons=                          ; list of SuperWeaponTypes
FireSuperWeapons.RealLaunch = bool         ; Default to no
FireSuperWeapons.UseWeapon = int           ; Default to -1
FireSuperWeapons.TargetSelf =bool          ; Default to no
```

I need revision and help on that DEFINE_HOOK part

2022-04-13 08:52 UTC, ststl-s commented
AbstractType TechnoClass::Target
if (pThis->Target->WhatAmI() == AbstractType::Cell)
		abstract_cast<CellClass*>(pThis->Target);
	else
		abstract_cast<ObjectClass*>(pThis->Target);

2022-04-13 08:52 UTC, ststl-s commented
AbstractClass* TechnoClass::Target;
if (pThis->Target->WhatAmI() == AbstractType::Cell)
abstract_cast<CellClass*>(pThis->Target);
else
abstract_cast<ObjectClass*>(pThis->Target);

2022-04-15 13:51 UTC, secsome commented
It's better to use Anim or WHs to implement the SW firing, instead of using Technos.

2022-04-15 16:10 UTC, chaserli commented
> It's better to use Anim or WHs to implement the SW firing, instead of using Technos.

I'm looking into anims right now. I'll refactor this when I have a clue

2022-04-19 06:23 UTC, Thrifinesma requested changes

2022-04-19 06:23 UTC, Thrifinesma commented on src/Ext/WarheadType/Body.h
> +		NullableVector<SuperWeaponTypeClass*> SpawnSuperWeapons;
I guess this is a wrong usage for NullableVector, I'd suggest to change it to ValueableVector

2022-04-19 06:23 UTC, Thrifinesma commented on src/Ext/WarheadType/Detonate.cpp
> +			for (const auto pSWType : this->SpawnSuperWeapons.GetElements()) {
After changing it to ValueableVector, here only needs
```suggestion
		for (const auto pSWType : this->SpawnSuperWeapons)
		{
```

2022-04-19 06:23 UTC, Thrifinesma commented on src/Ext/WarheadType/Detonate.cpp
> +				else if (pSuper = GameCreate<SuperClass>(pSWType, pHouse)) {
Quite courageous method. Game will accumulate more and more `SuperClass` while running this feature. Change it to some other implementation please

2022-04-19 08:51 UTC, chaserli commented on src/Ext/WarheadType/Detonate.cpp
> +				else if (pSuper = GameCreate<SuperClass>(pSWType, pHouse)) {
Deleted the `GameCreate` part and made the code more concise. However, if the owner already has the superweapon in charge, this will enforce its reset as well, but this would not be a problem for modders.

2022-04-21 14:46 UTC, Starkku requested changes
Lacks documentation, and there's one very small style error but besides that looks fine.

2022-04-21 14:46 UTC, Starkku commented on src/Ext/WarheadType/Detonate.cpp
> +
Remove one of the two empty lines.

2022-04-21 16:33 UTC, Starkku requested changes
Couple of more style issues with the documentation.

Also missing contribution mention from `CREDITS.MD` and mention of the feature in `docs\Whats-New.md` still.

2022-04-21 16:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +    - In either case, the superweapon is launched without any constraint. For example, `SW.Designators` and `SW.Inhibitors` are ignored. The user should not abuse such behavior.
- Remove the empty line between the first level list item and the first child item.
- Fix the list indentation. The second level list items should be prefixed with only two whitespaces, add more two for every sublevel after that.

2022-04-21 16:33 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +SpawnSuperWeapons.RealLaunch= no          ; bool
- Remove the space between `SpawnSuperWeapons.RealLaunch=` and `no`.
- Fix indentation of the comments/variable descriptions. Two whitespaces between the end of longest line in section and ; character, and rest to line up with that.

2022-04-21 16:54 UTC, chaserli commented
I need testing and feedback on this feature from the community first.

2022-05-10 00:58 UTC, DmitryVolkov666 commented
So. Everything works great. Found a problem with a weather storm. He simply, when launching the next weapon, disappeared at the launch of the previous weapon and moved to the next blow. 

There was also a problem with the chronosphere for conventional weapons. see this too. I think it will amuse you
She simply created a starting point and that's it. and you could teleport something with the cursor, but in fact, nothing happened.
Yes, it is understand that not a single modder will use it because of the "complexity" of the chronosphere.
It would be nice to ban the teleportation superweapon. And in the future add separate "keys" to control the chronosphere

for example through one weapon
1 hit - generates the starting point of teleportation
2 - teleports already from 1 point to the one hit by the projectile 2 times. then the counter resets to zero and everything starts all over again.

but 2 weapons (as for me) is better. like how...

Primary = starting point
PipScale=Ammo
Ammo=1
PipWrap=1
EmptyReload=6000
reload=6000
NoAmmoWeapon=1
ReloadAmount=1
Secondary = endpoint (no ammo used)

CONDITIONALLY.

The tank shoot underneath him - creating a starting point for teleporting the object/objects through the primary weapon

Secondary = shooting already in the area you need. and teleport the object/objects to the endpoint

Yet again. This is only a wish regarding the chronosphere for the future. Since I understand that she will have her own problems (do not forget to watch this)

But in general, everything works fine if you do not abuse any complex superweapons. e.g. airstrikes, paradrop, genetic mutator, nuclear strikes, iron curtains, force shields work more excellently.

and most importantly - the superweapon respects the owner of the object.

moreover, if a super weapon is paid, it takes money

if the weapon can de-energize the base (for example, a force shield), then it works as expected. 
phew. looks like that's all

2022-05-10 08:28 UTC, MortonPL commented
"She simply created a starting point and that's it. and you could teleport something with the cursor, but in fact, nothing happened."

That happens because Chronosphere SW is actually two Super Weapons, one for source and one for destination: http://ares-developers.github.io/Ares-docs/new/superweapons/types/chronosphere.html

2022-05-10 08:44 UTC, DmitryVolkov666 commented
> "She simply created a starting point and that's it. and you could teleport something with the cursor, but in fact, nothing happened."
> 
> That happens because Chronosphere SW is actually two Super Weapons, one for source and one for destination: http://ares-developers.github.io/Ares-docs/new/superweapons/types/chronosphere.html


I know. just described the problem

2022-05-11 04:39 UTC, chaserli commented
Close due to un-updated nightly build

2022-05-11 04:39 UTC, closed without merging