Unit auto-death enhancement: allow peaceful removal from the game
Phobos-developers/Phobos pull request #595
Opened 2022-04-15 10:01 UTC by chaserli

### Kill Unit Automatically

- Objects can be destroyed automatically under certaing cases:
  - No Ammo: The object will die if the remaining ammo reaches 0.
  - Countdown: The object will die if the countdown reaches 0.
  - **Peaceful: If `NoAmmo` or `Countdown` is set, the object will be directly removed from the game peacefully, without triggering deathweapon or "Unit lost" EVA.**

In `rulesmd.ini`:
```ini
[SOMETECHNO]                       ; TechnoType
Death.NoAmmo=no                    ; boolean
Death.Countdown=0                  ; integer
Death.Peaceful=no                  ; boolean, default to no
```

2022-04-17 13:09 UTC, ayylmaoRotE commented
Death.NoAmmo=yes works as expected
Death.Peaceful=yes works as expected

All 2 or 3 combos work together

Nice additions!

2022-04-17 14:44 UTC, Starkku requested changes
Looks fine other than for a couple of small code style issues.

2022-04-17 14:44 UTC, Starkku commented on src/Ext/Techno/Body.cpp
>  			pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
- Braces on their own lines instead of immediately after or before statements.
- With `if-else`, if `if` has braces then you should put them on `else` even if it only has a single line to keep things consistent.

2022-04-17 14:44 UTC, Starkku commented on src/Ext/Techno/Body.cpp
>  				pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
- Braces on their own lines instead of immediately after or before statements.
- With if-else, if if has braces then you should put them on else even if it only has a single line to keep things consistent.

2022-04-25 07:21 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
>  			pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
```suggestion
			if (peacefulDeath)
			{
				pThis->Limbo();
				pThis->UnInit();
			}
			else
			{
				pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
			}
```

2022-04-25 07:21 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +
```suggestion
```

2022-04-25 07:21 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		Valueable<bool> Death_Peaceful;
```suggestion
		Valueable<bool> Death_Peaceful;

```

2022-04-25 07:21 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +			, Death_Peaceful {false}
```suggestion
			, Death_Peaceful { false }
```

2022-04-25 07:21 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +Death.Peaceful=no                  ; boolean, default to no
```suggestion
Death.Peaceful=no                  ; boolean, whether to not trigger DeathWeapon and EVA
```

2022-04-25 07:22 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
>  				pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
```suggestion
				if (peacefulDeath)
				{
					pThis->Limbo();
					pThis->UnInit();
				}
				else
				{
					pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
				}
```

2022-04-25 07:26 UTC, merged