Respond issue #621: AI's MCV auto-deploy
Phobos-developers/Phobos pull request #623
Opened 2022-05-04 04:48 UTC by chaserli

Attempt to fix #621

Make AI's MCV automatically deploy itself when its mission turns to hunt.

2022-05-04 08:52 UTC, chaserli commented
![ttt4](https://user-images.githubusercontent.com/9932846/166650306-1d4028dc-bf20-4326-870d-88bf3688771b.gif)
If this is what he wanted

2022-05-04 12:27 UTC, DeathFishAtEase commented
Jumpjet still has some problems finding open areas. If Chrono MCV can't deploy at the beginning, it will still stand as silly as before, even if the obstacles have been cleared
![Non still picture](https://user-images.githubusercontent.com/89088785/166680928-f4235c9c-11f0-46bf-980b-e2dbe3dca91f.gif)

2022-05-04 13:16 UTC, chaserli commented
> Jumpjet still has some problems finding open areas. If Chrono MCV can't deploy at the beginning, it will still stand as silly as before, even if the obstacles have been cleared ![Non still picture](https://user-images.githubusercontent.com/89088785/166680928-f4235c9c-11f0-46bf-980b-e2dbe3dca91f.gif)

What was the mission state of your hovering mcv? Hunt or Unload?

你能把地形放大一点吗，或者把地图和设置给我一下，我不知道咋复现这个

2022-05-04 13:20 UTC, DeathFishAtEase commented
This map is provided by YR CNCNET Client and its file name is 8_malaboo_bay.map

2022-05-05 14:19 UTC, chaserli commented
There are more bugs introduced. I never expected this to be that difficult. will work on it later

2022-05-08 06:03 UTC, chaserli commented
@DeathFishAtEase it should looks better this time

2022-07-02 03:16 UTC, chaserli commented
This one is also tested by @DeathFishAtEase 
Needs review from @Starkku since I was working inside his hook

2022-09-19 05:52 UTC, Belonit commented
@chaserli It seems this PR is broken. I think you should create a new one instead.

2022-09-19 06:07 UTC, Belonit requested changes

2022-09-19 06:07 UTC, Belonit commented on src/Misc/Hooks.BugFixes.cpp
> +
If you do not plan to make new commits in this PR. You can take this suggestion to fix linter issues:
```suggestion

```

2022-09-19 06:07 UTC, Belonit commented on src/Misc/Hooks.BugFixes.cpp
> +	//Force guard mission to mcv when hunt
I'd rather add a space here
```suggestion
	// Force guard mission to mcv when hunt
```

2022-09-19 10:34 UTC, closed without merging