TileSet 255 and above bridge repair fix
Phobos-developers/Phobos pull request #63
Opened 2021-02-20 08:27 UTC by E1Elite

To do: To include .cpp in vcxproj file. If needed .inj file entries for hooks.

2021-02-20 11:02 UTC, Metadorius requested changes
We don't use inj file in Phobos, so you only need to include it in vcxproj and then everyone can try the nightly DLL build. I've left a couple of comments in code.

2021-02-20 11:02 UTC, Metadorius commented on src/Misc/tileset255_bridgerepairfix.cpp
> +DEFINE_HOOK(545BBA, tileset255_01, 5)
1. My recommendation on how to write hook names is `[ClassName]_[MethodName]_[HookName]` or `[FunctionName]_[HookName]`.
2. Hook size is only used when you use `return 0;` so it's better to set size to `0` if you don't use it.

2021-02-20 12:35 UTC, E1Elite commented
Updated, check if its fine now.

2021-02-20 13:46 UTC, Metadorius commented
Still not included in `.vcxproj`, can't push a fix to that because your PR doesn't allow edits by maintainers.

2021-02-20 15:24 UTC, E1Elite commented
Allow edits by maintainers is enabled from the beginning, I unchecked and checked the option again now. Latest clone or download doesn't compile straightaway for some reason, gives include errors. I compiled and tested with 2021-01-25 build, so I am avoiding change to .vcxprj file from latest commit.

Having .inj file has advantages for the modders, they can disable some hooks if they have trouble or don't want a specific change wothout going for a build from the source.

2021-02-20 15:33 UTC, Metadorius commented
Strange, I can't push to the branch anyways.

Latest `develop` compiles fine already. Perhaps you could rebase, start a new branch and reset `develop` to `upstream/develop` ? Something like `feature/bridge-repair-fix`.

Oh and also I highly suggest hopping in on Discord to stay in touch.

2021-02-20 16:50 UTC, E1Elite commented
May be problem could be me being on VS2019. Problem in compiling starts from 2021-02-12 commit onwards giving errors on selection.cpp and tacticalclass.h.

If you want to, go ahead and add the one line inclusion of the .cpp outside this PR.

2021-02-20 17:01 UTC, Metadorius commented
What's the problem? I can compile just fine, are you sure YRpp submodule has the correct branch checked out?

2021-02-21 02:05 UTC, E1Elite commented
Updated vcxprj. Problem was with YRpp branch, was using master. It would be better if YRpp URL in readme leads to correct branch.

2021-03-05 05:37 UTC, E1Elite commented
Updated with better fix.

2021-03-05 08:27 UTC, merged