Death condition refactor: added sync slave-owner death check
Phobos-developers/Phobos pull request #630
Opened 2022-05-08 08:50 UTC by chaserli

### Kill Unit Automatically

- Objects can be destroyed automatically under certaing cases:
  - `NoAmmo`: The object will die if the remaining ammo reaches 0.
  - `Countdown`: The object will die if the countdown reaches 0.
  **- `WithSlaveOwner`: `Slaved=yes` infantry will die simultaneously with its slave owner.**
  - `Peaceful`: In all above cases, the object will be directly removed from the game peacefully, without triggering deathweapon or "Unit lost" EVA for example.
  
In `rulesmd.ini`:
```ini
[SOMETECHNO]                       ; TechnoType
Death.NoAmmo=no                    ; boolean
Death.Countdown=0                  ; integer
Death.WithSlaveOwner=no            ; boolean
Death.Peaceful=no                  ; boolean
```

2022-05-10 17:34 UTC, IgortheBylarge commented
Tested all new parameters: `Death.NoAmmo`, `Death.Countdown`, `Death.WithSlaveOwner`and `Death.Peaceful`. All of them are working stable, without any issues.

2022-06-03 18:06 UTC, FS-21 requested changes
Small changes needed.

2022-06-03 18:06 UTC, FS-21 commented on src/Ext/TechnoType/Body.cpp
> +	this->Death_WithMaster.Read(exINI, pSection, "Death.WithSlaveOwner");
Class fields that can be set via INI tags should be named exactly like ini tags with dots replaced with underscores.

2022-06-27 14:39 UTC, chaserli commented
@Metadorius Please mark this thread as Needs Testing plz
@IgortheBylarge Are you available to test it again?

2022-07-09 13:13 UTC, Metadorius requested changes
Code is mostly good apart from a few issues.

2022-07-09 13:13 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		Valueable<HowToSuicide> Death;
1. Could be Nullable instead of having to add a new enum value but not sure if that would be useful much, up to you.
2. `Death` is not a very descriptive name. I propose to name all the death tags with `AutoDeath` prefix and give the following names (or something like this):
```
AutoDeath.Behavior   <- this one
AutoDeath.OnAmmoDepletion
AutoDeath.AfterDelay
```

2022-07-09 13:13 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
>  				}
Pretty sure this could use a timer, see shield code if you're upt to improving this piece of code.

2022-07-09 13:13 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		ValueableIdx<VocClass> SellSound;
If it's a building-exclusive thing why is it in `TechnoType`? BTW could also be `NullableIdx`.

2022-07-09 13:13 UTC, Metadorius commented on src/Utilities/Enum.h
> +};
1. Could also add `Neutral` option.
2. Not sure on the name, it sounds broken a bit.

2022-07-09 13:13 UTC, Metadorius commented on src/Utilities/Enum.h
> +enum class HowToSuicide
Same deal with the name.

2022-07-09 13:13 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +			, SellSound{ -1 }
```suggestion
			, SellSound { -1 }
```

2022-07-09 13:32 UTC, chaserli commented on src/Ext/BuildingType/Body.h
> +		ValueableIdx<VoxClass> EVA_Sold;
I'm a little bit confused with the use of `ValueableIdx` and `NullableIdx`, Actually, I initialized this value in `Ext\TechnoType\Body.cpp`'s section `void BuildingTypeExt::ExtData::Initialize();` same as the SellSound stuff. I would like to know if this is correct

2022-07-09 13:33 UTC, chaserli commented on src/Ext/TechnoType/Body.h
> +		ValueableIdx<VocClass> SellSound;
1. Because vehicles can be sold on repair bays, if someone uses this eventually
2. same question mentioned above

2022-07-09 13:45 UTC, Metadorius commented on src/Ext/BuildingType/Body.h
> +		ValueableIdx<VoxClass> EVA_Sold;
I don't think that's correct. Usually we don't duplicate the value like this if it's not set, I am pretty sure EVA sell sound already exists initialized somewhere. I guess you would need to change it to nullable and use get with a default value.

2022-07-09 13:46 UTC, chaserli commented on src/Utilities/Enum.h
> +};
1. I thought about this at the beginning, but it doesn't sound quite reasonable imo
2. A long enum name? like `SlaveOwnershipChangeType`?

2022-07-09 14:07 UTC, chaserli commented on src/Ext/BuildingType/Body.h
> +		ValueableIdx<VoxClass> EVA_Sold;
1.I was taking https://github.com/Phobos-developers/Antares/blob/7241a5ff20f4dbf7153cc77e16edca5c9db473d4/src/Ext/SWType/Body.cpp#L78
as a reference from ares. They initialized `EVA_InsufficientFunds` etc in the `::ExtData::Initialize` section too, which are also  initialized as -1 in the header file

2. I don't know if EVA_Sold is initialized or not, but in 0x449CC1 and 0x44AB22 (addresses where I hooked), the vanilla game seems to simply do `VoxClass::Play("EVA_StructureSold")`. What I intended to do instead was to get the vox index when initailizing, and use `VoxClass::PlayIndex(BuidlingTypeExt->EVA_Sold_idx)`.

2022-07-10 06:41 UTC, chaserli commented
New issue identified: if the object enters a transport, it will not get deleted.

2022-07-10 09:46 UTC, chaserli commented on src/Ext/Techno/Body.cpp
>  				}
changed to make the opentopped units coherent with other transports

2022-07-10 09:55 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +}
I am pretty sure with how you still don't use `NullableIdx` and don't fallback to the default value that this would break all vanilla sell sounds.

2022-07-10 09:56 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +			true,// ignoreDefenses = false to let passengers escape, why?
```suggestion
			true,  // ignoreDefenses = false to let passengers escape, why?
```

2022-07-10 10:13 UTC, chaserli commented on src/Ext/BuildingType/Hooks.cpp
> +}
I'll have to hook inside the if statement in this case, I'm not sure how to do so

2022-07-10 10:18 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +}
Um I don't think you need to, you just need to know what's the default index of the EVA sold sound, aka the one that is set globally, change type of `EVA_Sold` to `NullableIdx<VoxClass>` and then
```cpp
VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(/* default value here */));
```

2022-07-10 10:20 UTC, chaserli commented on src/Ext/BuildingType/Hooks.cpp
> +}
So like 
```cpp
VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(VoxClass::FindIndex((const char*)0x819030)));
```?

2022-07-10 10:55 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +}
You can also just check `.isset()` and `return 0` if the nullable is not set.
YRpp name seems to be incorrect. Offset 0x41A seems to be `IsOwnedByPlayer`.

2022-07-10 12:05 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(VoxClass::FindIndex((const char*)0x882630))); //EVA_UnitSold
This is what I meant, very dirty

2022-07-10 12:08 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(VoxClass::FindIndex((const char*)0x882630))); //EVA_UnitSold
`return 0` isn't an option?

2022-07-10 12:24 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(VoxClass::FindIndex((const char*)0x882630))); //EVA_UnitSold
Elsewhere, yes, but here…it seems too narrow to do so

2022-07-12 16:40 UTC, Metadorius requested changes
Good apart from a few minor nitpicks.

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +
```suggestion
```

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +			true,// ignoreDefenses = false to let passengers escape, why?
Missed this :P

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +		pThis->RegisterKill(pThis->Owner);
Forgot KillPassengers call here. May impact some edge cases like capturing enemy infantry and then killing them.

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	enum { SkipVoxPlay = 0x449CEA };
Should keep enum as the first line.

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	enum { SkipVoxPlay = 0x44AB3B };
Same here

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	enum { PlayVocLocally = 0x44A856 };
Ditto

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	enum { EVA_UnitSold = 0x822630, SkipVoxVocPlay = 0x4D9FB5 };
Ditto

2022-07-12 16:40 UTC, Metadorius commented on src/Ext/Techno/Hooks.cpp
> +	VoxClass::PlayIndex(pTypeExt->EVA_Sold.Get(VoxClass::FindIndex((const char*)EVA_UnitSold)));
Also strings like this should be in YRpp but I guess can be done in another PR, there are many of such cases in Phobos.

2022-07-13 07:27 UTC, Metadorius approved these changes

2022-07-13 07:27 UTC, merged

2022-08-12 07:38 UTC, chaserli commented on src/Ext/Techno/Body.cpp
> +		pThis->ReceiveDamage(&pThis->Health, 0, RulesClass::Instance()->C4Warhead, nullptr, true, false, pThis->Owner);
Just a reminder : when `ignoreDefenses=yes`, Ares' `TechnoExt::SpawnSurvivors` will not eject survivors/passengers/hijacker