Launch superweapons using warhead
Phobos-developers/Phobos pull request #632
Opened 2022-05-11 07:07 UTC by chaserli

Reopened the PR for nightly builds for testers

### Launch superweapons on impact

- Superweapons can be launched when a standard warhead is detonated. This means that animation weapons from _Ares_ are **not** supported. Nevertheless, animation warheads may works in certain circumstances. Due to the nature of some superweapon types, not all superweapons are suitable for launch. The user should not abuse this feature.
  - `LaunchSW` specifies the superweapons to launch when the warhead is detonated.
  - `LaunchSW.RealLaunch` controls whether the owner who fired the warhead must own all listed superweapons and sufficient fund to support `Money.Amout`. Otherwise they will be launched out of nowhere.
  - `LaunchSW.IgnoreInhibitors` ignores `SW.Inhibitors` of the superweapon, otherwise only non-inhibited superweapons are launched.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]                 ; Warhead
LaunchSW=                     ; list of superweapons
LaunchSW.RealLaunch=no        ; bool
LaunchSW.IgnoreInhibitors=no  ; bool

2022-05-25 10:50 UTC, 8abs commented
This PR is super useful. Hoping it could be merged into phobos build version.

2022-05-31 15:08 UTC, Metadorius requested changes
Looks good except few code style issues, good to merge after fixing.

2022-05-31 15:08 UTC, Metadorius commented on docs/locale/zh_CN/LC_MESSAGES/New-or-Enhanced-Logics.po
> +
Would need updates after the doc fixes.

2022-05-31 15:08 UTC, Metadorius commented on src/Ext/SWType/Body.cpp
> +	this->SW_AnyInhibitor.Read(exINI, pSection, "SW.AnyInhibitor");
If you're parsing the tags in the end, then you should declare and serialize also in the end, so the order is the same, just for the readability sake.

2022-05-31 15:08 UTC, Metadorius commented on src/Ext/SWType/Body.cpp
> +		.Process(this->SW_AnyInhibitor)
See next comment.

2022-05-31 15:08 UTC, Metadorius commented on src/Ext/SWType/Body.h
> +			, SW_AnyInhibitor{ false }
See prev. comment.

2022-05-31 15:08 UTC, Metadorius commented on src/Ext/SWType/FireSuperWeapon.cpp
> +						{ return IsInhibitorEligible(pSWType, pOwner, Coords, pTechno);}
Not sure if this (one-line and wrong indentation) is OK.

2022-05-31 17:10 UTC, chaserli commented
My local branch falls behind develop, I don't know how to resolve these conflicts

2022-05-31 17:12 UTC, Metadorius approved these changes

2022-05-31 17:13 UTC, Metadorius commented
![image](https://user-images.githubusercontent.com/17500545/171233778-dc519ef5-e640-4d7f-b6b5-d16b739ddbcf.png)

2022-05-31 18:07 UTC, Metadorius commented
Fixed

2022-05-31 23:24 UTC, merged