Reimplemented animation damage / weapon /w improvements
Phobos-developers/Phobos pull request #635
Opened 2022-05-11 18:27 UTC by Starkku

This reimplements animation `Weapon` and `Damage.Delay` from Ares and adds ability to customize whether or not the Damage is dealt by the owner or invoker of the animation (does not affect which House is used to deal damage if `Warhead` is used, but does affect experience gain). `Weapon` is also automatically allocated and does not require explicit listing on `[WeaponTypes]`.

---------------------------

### Animation weapon and damage settings

- `Weapon` can be set to a WeaponType, to create a projectile and immediately detonate it instead of simply dealing``Damage` by `Warhead`. This allows weapon effects to be applied.
- `Damage.Delay` determines delay between two applications of `Damage`. Requires `Damage` to be set to 1.0 or above. Value of 0 disables the delay. Keep in mind that this is measured in animation frames, not game frames. Depending on `Rate`, animation may or may not advance animation frames on every game frame.
- `Damage.DealtByOwner`, if set to true, makes any `Damage` dealt to be considered as coming from the animation's owner. Owner in this case is the firer of the weapon if it is Warhead `AnimList/SplashList` animation, the destroyed vehicle if it is `DestroyAnim` animation or the object the animation is attached to. Does not affect which house the `Damage` dealt by `Warhead` is dealt by.

*`Weapon` and `Damage.Delay`, beyond the other additions, should function similarly to the equivalent features introduced by Ares and take precedence over them if Phobos is used together with Ares.*

In `artmd.ini`:
```ini
[SOMEANIM]                 ; AnimationType
Weapon=                    ; WeaponType
Damage.Delay=0             ; integer, animation frames
Damage.DealtByOwner=false  ; boolean
```

2022-05-13 21:11 UTC, Starkku commented
Misc. fixes

- Damage.Delay now starts the count from correct animation frame
- Total damage dealt by animation no longer has one extra point of damage
- Fixed a damage check that was incorrectly disallowing > 0 but < 1 damage

2022-05-13 22:48 UTC, Starkku commented
Fixed an issue with looping animations and Damage.Delay where it would 'reset' the damage delay counter when a new loop started. It now works independently from animation frame state (and thus works better with loops) and matches how it works in Ares.

2022-05-17 12:48 UTC, Starkku commented
Added `Damage.ApplyOnce` which allows for animation damage to be only dealt once per animation loop on a specific animation frame.

2022-05-17 23:03 UTC, ayylmaoRotE commented
Tested using a basic cannon weapon with AnimList as:

```ini
[DAMAGEDELAY]
Translucent=yes
Image=MININUKE
Damage=500
LoopCount=10
Damage.Delay=1
Damage.DealtByOwner=yes
Damage.ApplyOnce=yes
Weapon=NukePayload
```

With variations such as `Damage.ApplyOnce=no`, different `Damage.Delay` values and by removing `Weapon` tag and only using `Warhead` and `Damage`.

Confirming all working as described.

Observations:
1. If firer dies while animation is looping in damage, nothing happens, e.g. no crash 👍 
2. Firer gains veterancy as expected
3. TransactMoney part 1: Using only `Damage` and `Warhead` + `Damage.DealtByOwner=yes` will have the money displayed from the firer and the owner will receive the corresponding $, but `Damage.DealtByOwner=no` will have the money animation displayed at the detonation point. Will still give the owner $$ though
4. TransactMoney part 2: Using the same method but applying it via a `Weapon` with `Damage.DealtByOwner=yes` will have the same effect as it did in part 1. But `Damage.DealtByOwner=no` will not display any cash nor give any funds.
5. AttachEffects part 1: Will grant units veterancy via this method if enemies are killed but will also damage their firer while weapons/warheads triggering the same effect will not damage the firer. AffectsOwner=no fixes this, so I think the issue is actually that weapons _should_ damage firers by default but they do not. (e.g. triggered via AnimList)
6. AttachEffects part 2: Works the same as point 4 when combined with TransactMoney.
7. Works with effects such as Cluster and EMP but only on `Weapon` use, not `Warhead`. As expected
8. AttachEffects part3: Applying AE makes the targeted unit the owner, pretty neat, all other attributes are as described above.
9. Negative values did not work with damage neither in `Damage` values or `Verses`. TransactMoney negatives works.

Suggestions:
1. Probably Ares territory but is it possible to make it so if AE is applied to enemies, the animation owner is still the firer? If so maybe via a tag? Refer to point 8

2022-05-18 12:31 UTC, Starkku commented
> Suggestions:
> Probably Ares territory but is it possible to make it so if AE is applied to enemies, the animation owner is still the firer? If so maybe via a tag? Refer to point 8

Not doable under current circumstances.

2022-05-25 12:35 UTC, Starkku commented
Deprecated `DetachedFromOwner` weapon key in favour of adding `AllowDamageOnSelf` on warheads that can be applied for same effect (allow dealing damage and damage-adjacent effects on the object considered warhead's source/firer) in wider scenarios and does not have weird interactions with AirburstWeapon.

2022-05-31 11:33 UTC, Starkku commented
- Changed `Damage.DealtByOwner` to `Damage.DealtByInvoker`. This is to prevent confusion over the meaning of term 'owner' which often refers to a house.
- `Trailer` and `TrailerAnim` now have `Owner` and `Invoker` set appropriately based on the object they are attached to.

2022-06-01 16:12 UTC, FS-21 commented
I tested these tags in a trailer animation and works as expected.

Weapon= works as expected
Damage.Delay= starts the damage from the selected animation frame as expected
Damage.DealtByInvoker=true works! Now units that use trailer anims for damaging other objects now can promote. Set as false is the vanilla behavior.
Damage.ApplyOnce=false/true works as expected

One of the final tests I did for my own project is and works as planned in **Trailers**.
```
; Weapon's Projectile
[WavesFakeProjectile]
Image=invisible_pixel
Trailer=TWSMOKEYWAVES     ; <---- **tested here**

[TWSMOKEYWAVES]
Warhead=TWSonicWarhead
Damage=10
Report=TWSonicWave
Flat=yes
Normalized=yes
Translucent=yes
Translucency=75
AltPalette=yes
ZAdjust=-150

Start=0
LoopStart=0
LoopEnd=19
LoopCount=1

**Damage.Delay=4** ; Starts applying damage at TWSMOKEYWAVES's frame 5
**Damage.DealtByInvoker=yes** ; Now the unit can promote when kills enemies
**Damage.ApplyOnce=no** ; Each TWSMOKEYWAVES's frame does 10 of damage
```

2022-06-03 17:25 UTC, FS-21 requested changes
Nested ternary operators are always bad, only one level of ternary operators should be used.

2022-06-03 17:25 UTC, FS-21 commented on src/Ext/AnimType/Hooks.cpp
> +		pInvoker = pExt->Invoker ? pExt->Invoker : pThis->OwnerObject ? abstract_cast<TechnoClass*>(pThis->OwnerObject) : nullptr;
Avoid nested ternary operators.

2022-06-03 17:25 UTC, FS-21 commented on src/Ext/AnimType/Hooks.cpp
> +		auto pWarhead = pThis->Type->Warhead ? pThis->Type->Warhead :
Avoid nested ternary operators.

2022-06-03 17:25 UTC, FS-21 commented on src/Ext/AnimType/Hooks.cpp
> +		auto pOwner = pInvoker ? pInvoker->Owner : pThis->Owner ? pThis->Owner :
Avoid nested ternary operators.

2022-07-01 21:54 UTC, Metadorius requested changes
Can be merged after addressing the comments. (Assuming MaxLenarc's feedback is sufficient.)

2022-07-01 21:54 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +- `Damage.ApplyOnce`, if set to true, makes `Damage` be dealt only once per animation loop instead of on every frame or intervals defined by `Damage.Delay`. The frame on which it is dealt is determin
Confusing naming, probably should be amended to `Damage.ApplyOncePerLoop`.

2022-07-01 21:54 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
>  }
Doesn't seem to be mentioned in docs?

2022-07-02 06:48 UTC, Starkku commented on src/Ext/Aircraft/Hooks.cpp
>  }
[But it is](https://github.com/Phobos-developers/Phobos/pull/635/files#diff-b650a8bcca29a01d5a69be07a793712810b9d1d400547d36d22e70677249c416R68)

2022-07-02 10:42 UTC, merged

2022-07-02 10:43 UTC, Metadorius commented on src/Ext/Aircraft/Hooks.cpp
>  }
I'm blind lol, that's why you don't review when it's 1AM kids