Extend parallel AI queues
Phobos-developers/Phobos pull request #638
Opened 2022-05-14 00:56 UTC by NetsuNegi

In the vanilla game, you could make the AI construct multiple factories by using cloned BuildingTypes whit TechLevel=-1 and AIBuildThis=yes.
Ares can alter the vanilla game behaviour so that this cloning issue no longer occurs when the AI owns more than one of any factory. But we still can't set it for some type of factory.

Now we can set it on specified types of factories do not occurs cloning issue and others will not be affected.

To prevent conflict with Ares, this only work when AllowParallelAIQueues=yes.

code example:
in rulesmd.ini
[GlobalControls]
ExtendParallelAIQueues=yes,yes,yes,yes,yes (list of boolean, corresponding to InfantryTypes, Vehicle without Naval, Vehicle with Naval, Aircraft, Building)

I don't know why the original branches can't be merged, so I created this new pull request.

2022-05-14 08:34 UTC, Metadorius commented
> I don't know why the original branches can't be merged, so I created this new pull request.

They can't be merged because that's how Git works. You made a branch, we updated the `develop` branch, that introduced conflicts with your branch. In order to resolve them you need to merge `develop` into your branch or rebase the branch onto new `develop`. In fact you can do that via GitHub, it makes a button for you to resolve conflicts.

2022-06-04 13:02 UTC, FS-21 requested changes

2022-06-04 13:02 UTC, FS-21 commented on src/Ext/Building/Hooks.cpp
> +	HouseClass* pOwner = pBuilding->Owner;
I would leave GET()'s alone.

```suggestion
	GET(BuildingClass*, pBuilding, ESI);
	
	HouseClass* pOwner = pBuilding->Owner;
```

2022-06-04 13:51 UTC, NetsuNegi commented
Some modifications have been made to the code style

2022-07-09 12:51 UTC, Metadorius requested changes

2022-07-09 12:51 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +		if (!currFactory)
Missing newline after switch statement.

2022-07-09 12:51 UTC, Metadorius commented on src/Ext/House/Body.h
> +			, Factory_NavyType {nullptr }
```suggestion
			, Factory_NavyType { nullptr }
```

2022-07-09 12:51 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> + -To prevent conflict with Ares, this only work when AllowParallelAIQueues=yes.
The description is, quite honestly, hard to understand, it needs to be clarified. Does it depend on the Ares tag? Or does it function like the Ares tag but set on individual types?

2022-07-09 12:51 UTC, Metadorius commented on src/Phobos.cpp
> +bool Phobos::Config::ExtendParallelAIQueues[5] = { true, true, true, true, true };
In my opinion, better introduce either 5 separate tags, or a bitflag enum.

2022-07-09 13:16 UTC, NetsuNegi commented on src/Phobos.cpp
> +bool Phobos::Config::ExtendParallelAIQueues[5] = { true, true, true, true, true };
I will do it soon.

2022-07-09 13:20 UTC, Metadorius commented on src/Phobos.cpp
> +bool Phobos::Config::ExtendParallelAIQueues[5] = { true, true, true, true, true };
Find `AffectedHouses` enumeration across the project to learn how bitflag enums are done.

2022-07-09 13:33 UTC, NetsuNegi commented on docs/New-or-Enhanced-Logics.md
> + -To prevent conflict with Ares, this only work when AllowParallelAIQueues=yes.
That's not rely on Ares. But if you use Ares, it will only work when AllowParallelAIQueues=yes.

2022-07-17 21:03 UTC, Metadorius requested changes

2022-07-17 21:03 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +```
I propose to rename the tags `ForbidParallelAIQueues.*` and invert them as a consequence. This way it would be logical to the end user that they don't work with `AllowParallelAIQueues=no`, because if all the queues are not allowed to be parallel, you can't "forbid" what's already forbidden, and `not forbidden` does not equate to `allowed`.

2022-07-18 01:12 UTC, NetsuNegi commented on docs/New-or-Enhanced-Logics.md
> +```
OK, now I did that.

2022-07-18 08:40 UTC, Metadorius approved these changes

2022-07-18 08:40 UTC, merged

2022-07-30 10:23 UTC, chaserli commented on src/Phobos.cpp
> +	Phobos::Config::ForbidParallelAIQueues_Infantry = rulesINI->ReadBool("GlobalControls", "ForbidParallelAIQueues.Infantry", Phobos::Config::AllowParallelAIQueues);
Why here but not within `RulesExt`?

2022-07-30 11:26 UTC, Metadorius commented on src/Phobos.cpp
> +	Phobos::Config::ForbidParallelAIQueues_Infantry = rulesINI->ReadBool("GlobalControls", "ForbidParallelAIQueues.Infantry", Phobos::Config::AllowParallelAIQueues);
Actually I would want to know that too, somehow missed this one as I don't add too much to RulesExt myself.

2022-07-30 14:43 UTC, chaserli commented on src/Phobos.cpp
> +	Phobos::Config::ForbidParallelAIQueues_Infantry = rulesINI->ReadBool("GlobalControls", "ForbidParallelAIQueues.Infantry", Phobos::Config::AllowParallelAIQueues);
As I traced back to [the moment](https://github.com/Phobos-developers/Phobos/commit/77701da621318cb208c1efe768303ba746fc6b1a) when the hook was created there was no `RulesExt` yet. So I assume later on `RulesExt` was created aiming to replace this one as it provides better parsing utilities (namely `Valueable/Nullable` ones). 
I understand why ares' tag should be here, as for new tags I don't see the difference of putting them inside `RulesExt`

2022-07-30 17:06 UTC, Metadorius commented on src/Phobos.cpp
> +	Phobos::Config::ForbidParallelAIQueues_Infantry = rulesINI->ReadBool("GlobalControls", "ForbidParallelAIQueues.Infantry", Phobos::Config::AllowParallelAIQueues);
I see, feel free to refactor that and PR against the release branch if you want.