Enable and custom select box
Phobos-developers/Phobos pull request #640
Opened 2022-05-16 13:33 UTC by NetsuNegi

#600 
Now you can use and custom a select box for infantry, vehicle and aircraft. Not support on buildings.

in rulesmd.ini
[AudioVisual]
UseSelectBrd=no (boolean)
SelectBrd.SHP.Infantry=select.shp (filename, includingthe .shp extension)
SelectBrd.PAL.Infantry=palette.pal (filename, includingthe .pal extension)
SelectBrd.Frame.Infantry=0,0,0 (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset.Infantry=0,0 (X, Y, positive value is right and down)
SelectBrd.SHP.Unit=select.shp (filename, includingthe .shp extension)
SelectBrd.PAL.Unit=palette.pal (filename, includingthe .pal extension)
SelectBrd.Frame.Unit=3,3,3 (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset.Unit=0,0 (X, Y, positive value is right and down)
SelectBrd.DefaultTranslucentLevel=0
SelectBrd.DefaultShowEnemy=true

Remember not for buildings!!!
[SOMETECHNO]
UseCustomSelectBrd= (boolean, override the UseSelectBrd)
SelectBrd.SHP= (filename, includingthe .shp extension)
SelectBrd.PAL= (filename, includingthe .pal extension)
SelectBrd.Frame= (frame, green hp, yellow hp, red hp)
SelectBrd.DrawOffset= (X, Y, positive value is right and down)
SelectBrd.TranslucentLevel=
SelectBrd.ShowEnemy=

You can also set it in ra2md.ini
[Phobos]
EnableSelectBrd=false (boolean)

2022-06-04 13:08 UTC, FS-21 commented
Just for curiosity, why is called "UseSelectBrd" instead of "UseSelectBox" since the feature is called SelectBox ? :-/

2022-06-04 13:21 UTC, NetsuNegi commented
> Just for curiosity, why is called "UseSelectBrd" instead of "UseSelectBox" since the feature is called SelectBox ? :-/

For some reason I forgot that XD, I had rename this logic. Thanks for reminding.

2022-06-12 13:56 UTC, FS-21 reviewed
I have nothing new since the last feedback I gave until more code is modified.

2022-07-01 21:21 UTC, Metadorius commented
What's the status of this PR? @FS-21 said >since the last feedback but I can't see any feedback other than the `UseSelectBox` one?

2022-07-01 21:23 UTC, FS-21 commented
> What's the status of this PR? @FS-21 said >since the last feedback but I can't see any feedback other than the `UseSelectBox` one?

Because I don't find anything to blame the author of the PR.
Unless someone find some code improvement to me was ok (the code style)

2022-07-01 21:46 UTC, Metadorius requested changes
Missing docs, changelog, credits entries completely. Also please see the review comments.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		ConvertClass* SHP_SelectBoxPAL_UNIT;
1. Use `Valueable<SHPStruct*>`
2. `CustomPalette` exists, see usage across the project.
3. Naming is strange, also no CAPS LOCK allowed. Should be equal to the tag name.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		PhobosFixedString<32U> SelectBox_PAL_Infantry;
No need for that after rework. Also we use `Shape` instead of `SHP` and `Palette` instead of `PAL`.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		Valueable<bool> SelectBox_DefaultShowEnemy;
1. Maybe `ShowOnEnemy`? Also I don't think there's a need in `Default` prefix in those two.
2. I think only being able to toggle enemy visibility is unflexible. Perhaps it would be better to use `AffectedHouse` enum and add a bool determining if observer can see the select boxes? 
```ini
SelectBox.CanSee=Owner  ; list of AffectedHouses
SelectBox.CanObserverSee=no
```

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +			, SelectBox_DrawOffset_Infantry { {0,0} }
Inconsistent space usage.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +			, SelectBox_DrawOffset_Unit { {0,0} }
Inconsistent space usage.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		Nullable<bool> SelectBox_ShowEnemy;
1. Same feedback as with global tags.
2. `UseCustomSelectBox` is unneeded, just make it override the global values one by one if specified.

2022-07-01 21:46 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +			, SelectBox_ShowEnemy {}
Inconsistent space usage around brackets.

2022-07-08 13:33 UTC, NetsuNegi commented
> Have you finished with the changes or not yet? I see some of my comments were unaddressed.

Yes, thoes are finished.

2022-07-08 13:35 UTC, Metadorius commented
> > Have you finished with the changes or not yet? I see some of my comments were unaddressed.
> 
> Yes, thoes are finished.

Well, you didn't address quite a bit of my comments. Fix the issues and then I'll review again.

2022-07-08 13:39 UTC, Metadorius requested changes
Please, go over ALL of the comments and address them one by one. If you don't understand what I mean then ask to clarify.

2022-07-09 14:04 UTC, NetsuNegi commented on src/Ext/TechnoType/Body.h
> +		Nullable<bool> SelectBox_ShowEnemy;
I cannot understand what is note 1 mean.

2022-07-20 07:48 UTC, ststl-s commented
> Please, go over ALL of the comments and address them one by one. If you don't understand what I mean then ask to clarify.

Has been supplemented.

2022-07-31 06:57 UTC, chaserli reviewed
There's a lot of replicating code. A total refactor of the major function is needed imo. Make sure you actually understand what you want to do.

2022-07-31 06:57 UTC, chaserli commented on src/Ext/Techno/Body.cpp
> +	if (iLength == 8)
you already have your `isInfantry`, why checking this `iLength` out of nowhere? It's not a health bar anyway.

There's a lot of similar code replication in this function

2022-07-31 06:57 UTC, chaserli commented on src/Ext/Techno/Hooks.Shield.cpp
> +	if (Phobos::Config::EnableSelectBox)
Quite messy, a LOT of code duplication. You checked `pThis`'s RTTI 3 times, also, the `iLength` is completely useless for your function.

2022-07-31 06:57 UTC, chaserli commented on src/Ext/TechnoType/Body.h
> +			, SelectBox_Frame { { -1, -1, -1 } }
What's the point of using `Nullable` here?

2022-07-31 08:29 UTC, brsajo commented
The phrase "Enable and custom select box" bothers me. Is it supposed to be "Enable customisable select box" or "Enable a custom select box"?

2022-07-31 08:30 UTC, NetsuNegi commented
> The phrase "Enable and custom select box" bothers me. Is it supposed to be "Enable customisable select box" or "Enable a custom select box"?

You need enable it first, then you can custom the selectbox if you want.

2022-07-31 08:34 UTC, brsajo commented
Okay so then to be grammatically correct it should be called "Enable and customize select boxes"

2022-07-31 08:35 UTC, NetsuNegi commented
> Okay so then to be grammatically correct it should be called "Enable and customize select boxes"

OK, thank you.

2022-08-01 09:20 UTC, chaserli commented on src/Ext/Techno/Hooks.Shield.cpp
> +	}
You don't get it, I mean something more concise, like
```cpp
if(Phobos::Config::EnableSelectBox && RulesExt::Global()->UseSelectBox)
    TechnoExt::DrawSelectBox(pThis, pLocation, pBound, isInfantry);
```
and fetch your typeExt inside

2022-08-02 03:55 UTC, chaserli requested changes

2022-08-02 03:55 UTC, chaserli commented on src/Ext/Techno/Body.cpp
> +
Still quite bulky, I didn't look into the detail yet but as an example 
```cpp
void TechnoExt::DrawSelectBox(TechnoClass* pThis, Point2D* pLocation, RectangleStruct* pBound, bool isInfantry)
{
	const auto pTypeExt = TechnoTypeExt::ExtMap.Find(pThis->GetTechnoType());

	SHPStruct* pShape = pTypeExt->SelectBox_Shape.Get(isInfantry ? RulesExt::Global()->SelectBox_Shape_Infantry : RulesExt::Global()->SelectBox_Shape_Unit);
	if (!pShape)
		return;

	const auto canHouse = pTypeExt->SelectBox_CanSee.Get(RulesExt::Global()->SelectBox_CanSee);
	bool canSee = false;
	if (HouseClass::IsPlayerObserver())
	{
		canSee = pTypeExt->SelectBox_CanObserverSee.Get(RulesExt::Global()->SelectBox_CanObserverSee);	 
	}
	else
	{
		if (canHouse & AffectedHouse::Owner)
			canSee |= pThis->Owner->ControlledByPlayer();
		if (canHouse & AffectedHouse::Allies)
			canSee |= pThis->Owner->IsAlliedWith(HouseClass::Player);
		if (canHouse & AffectedHouse::Enemies)
			canSee |= !pThis->Owner->IsAlliedWith(HouseClass::Player);
	}
	if (!canSee)
		return;

	ConvertClass* pPalette = pTypeExt->SelectBox_Palette.GetConvert();
	if (!pPalette)
		pPalette = isInfantry ?
		RulesExt::Global()->SelectBox_Palette_Infantry.GetOrDefaultConvert(FileSystem::PALETTE_PAL) :
		RulesExt::Global()->SelectBox_Palette_Unit.GetOrDefaultConvert(FileSystem::PALETTE_PAL);

	Vector3D<int> selectboxFrame = pTypeExt->SelectBox_Frame.Get();
	if (selectboxFrame.X == -1)
		selectboxFrame = isInfantry ? RulesExt::Global()->SelectBox_Frame_Infantry.Get() : RulesExt::Global()->SelectBox_Frame_Unit.Get();
	int frame = pThis->IsGreenHP() ? selectboxFrame.X : pThis->IsYellowHP() ? selectboxFrame.Y : selectboxFrame.Z;
	
	Point2D vOffset = pTypeExt->SelectBox_DrawOffset.Get(isInfantry ?
		RulesExt::Global()->SelectBox_DrawOffset_Infantry.Get() :
		RulesExt::Global()->SelectBox_DrawOffset_Unit.Get());

	Point2D vPos = { pLocation->X + isInfantry ? 1 : 2 + vOffset.X,
					pLocation->Y + 1 + pThis->GetTechnoType()->PixelSelectionBracketDelta + vOffset.Y };

	auto const nFlag =
		BlitterFlags::Centered |
		BlitterFlags::Nonzero |
		BlitterFlags::MultiPass |
		EnumFunctions::GetTranslucentLevel(pTypeExt->SelectBox_TranslucentLevel.Get(RulesExt::Global()->SelectBox_TranslucentLevel.Get()));

	DSurface::Temp->DrawSHP(pPalette, pShape, frame, &vPos, pBound, nFlag, 0, 0, ZGradient::Ground, 1000, 0, 0, 0, 0, 0);
}
```

2022-08-02 03:55 UTC, chaserli commented on src/Ext/Techno/Hooks.Shield.cpp
> +	}
same
```cpp
	if (pThis->IsSelected && Phobos::Config::EnableSelectBox && RulesExt::Global()->UseSelectBox)
		TechnoExt::DrawSelectBox(pThis, pLocation, pBound, isInfantry);
```

2023-01-18 01:38 UTC, NetsuNegi commented
Every time I want to submit something else, I will be contaminated by it.GitHub is too complex to use for me

2023-01-18 01:39 UTC, closed without merging