Force Team's OnlyTargetHouseEnemy value for all House teams
Phobos-developers/Phobos pull request #643
Opened 2022-05-20 16:37 UTC by FS-21

- Modify `OnlyTargetHouseEnemy` behaviour for all the House teams.
- Only Affects the new Attack / Move actions.
- The default -1 value disables this global behaviour.

2022-05-22 10:07 UTC, Metadorius requested changes

2022-05-22 10:07 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +	}
Does not conform to code style

2022-05-22 10:07 UTC, Metadorius commented on src/Ext/Script/Body.cpp
> +			}
Does not conform to code style

2022-05-22 10:07 UTC, Metadorius commented on src/Ext/House/Body.cpp
> +	}
Does not conform to code style

2022-05-22 10:08 UTC, Metadorius requested changes, later dismissed

2022-05-22 10:08 UTC, Metadorius commented on src/Ext/House/Body.cpp
> +	*/
https://docs.microsoft.com/en-us/cpp/cpp/enumerations-cpp

2022-06-11 16:54 UTC, Otamaa commented on src/Ext/Script/Body.cpp
> +	if (!pTeam)
why check for `!pTeam` , then you try  to acces `pTeam->sStepComplete ` ?  , doesnt make any sense ,..

2024-08-29 12:22 UTC, FS-21 commented
If I'm not wrong, not much to do here and the feature is very small & used in my own mod during these years.

2025-11-25 09:06 UTC, TaranDahl approved these changes

2025-11-25 09:06 UTC, TaranDahl commented on docs/AI-Scripting-and-Mapping.md
> +### `14004` Force Global OnlyTargetHouseEnemy value in Teams
It should be clearly stated in the title that this feature is only for the newly added script actions of Phobos.

2025-12-16 13:41 UTC, merged