Disguise logic improvements & reimplemented insignia drawing
Phobos-developers/Phobos pull request #653
Opened 2022-05-26 13:00 UTC by Starkku

### Disguise logic additions (disguise-based movement speed, ally disguise blinking)

- `ShowAllyDisguiseBlinking`, if set to true, will allow players to see blinking disguises on disguised ally units. Additionally observer players can see blinking disguises of all players.
- `UseDisguiseMovementSpeed`, if set, makes disguised unit adjust its movement speed to match that of the disguise, if applicable. Note that this applies even when the disguise is revealed, as long as it has not been removed.

In `rulesmd.ini`:
```ini
[General]
ShowAllyDisguiseBlinking=false   ; boolean

[SOMETECHNO]                     ; TechnoType
UseDisguiseMovementSpeed=false   ; boolean
```

Additionally, there are following changes / fixes to the logic:
- Fixed disguised infantry no using custom palette for drawing the disguise.
- Disguised infantry now show appropriate insignia when disguise is visible based on the disguise type and house.

And insignia customization is reimplemented on Phobos' side now to facilitate drawing correct insignia for disguised infantry.

### Customizable veterancy insignias

- You can now customize veterancy insignia of TechnoTypes.
  - `Insignia.Rookie|Veteran|Elite` can be used to set a custom insignia file for each veterancy stage. Like the original / default file, `pips.shp`, they are drawn using `palette.pal` as palette.
  - `InsigniaFrame.Rookie|Veteran|Elite` can be used to set (zero-based) frame index of the insignia to display for each veterancy stage. Using -1 uses the default setting. Default settings are -1 (none) for rookie, 14 for veteran and 15 for elite.
  - `Insignia.ShowEnemy` controls whether or not the insignia is shown to enemy players. Defaults to `[General]` -> `EnemyInsignia`, which in turn defaults to true.

```ini
[General]
EnemyInsignia=true        ; boolean

[SOMETECHNO]              ; TechnoType
Insignia.Rookie=          ; filename - excluding the .shp extension
Insignia.Veteran=         ; filename - excluding the .shp extension
Insignia.Elite=           ; filename - excluding the .shp extension
InsigniaFrame.Rookie=-1   ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrame.Veteran=-1  ; int, frame of insignia shp (zero-based) or -1 for default
InsigniaFrame.Elite=-1    ; int, frame of insignia shp (zero-based) or -1 for default
Insignia.ShowEnemy=       ; boolean
```

*Insignia customization should function similarly to the equivalent feature introduced by Ares and takes precedence over it if Phobos is used together with Ares.*

2022-06-03 15:59 UTC, Otamaa commented on src/Ext/Techno/Body.cpp
> +		if (auto const pType = static_cast<TechnoTypeClass*>(pThis->Disguise))
Check the pointer `AbstractType` before cansting it using `static_cast` !

2022-06-03 16:00 UTC, Otamaa commented on src/Ext/Techno/Body.cpp
> +	bool isVisibleToPlayer = pOwner->IsAlliedWith(HouseClass::Player)
`pOwner` May contains `nullptr` check it before using it !

2022-06-03 16:02 UTC, Otamaa commented on src/Ext/Techno/Hooks.Disguise.cpp
> +	auto const pType = pThis->IsDisguised() ? static_cast<TechnoTypeClass*>(pThis->Disguise) : nullptr;
Check the pointer `AbstractType` before cansting it using `static_cast` !

2022-06-03 16:03 UTC, Otamaa commented on src/Ext/Techno/Hooks.cpp
> +			if (auto const pType = static_cast<TechnoTypeClass*>(pThis->Disguise))
Check the pointer `AbstractType` before cansting it using `static_cast` !

2022-06-12 13:44 UTC, FS-21 requested changes
Small tweak suggestion.
Everything else looks well coded.

2022-06-12 13:44 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +
Isn't better 1 unique block of 3 variable declarations instead of 2 blocks of 1 and 2 lines?

2022-06-12 13:47 UTC, FS-21 requested changes

2022-06-12 13:47 UTC, FS-21 commented on src/Ext/TechnoType/Body.cpp
> +		pType->AbsID == AbstractType::InfantryType || pType->AbsID == AbstractType::UnitType)
Isn't better 1 argument per line instead of 2?

2022-10-11 21:48 UTC, Metadorius commented
how about instead of `ShowAllyDisguiseBlinking` we use AffectedHouses?

2022-10-11 22:35 UTC, Starkku commented
> how about instead of `ShowAllyDisguiseBlinking` we use AffectedHouses?

Was originally going to, but then I realized it'd allow weird shit like hiding the blinking from the owner, making the disguised units permanently appear as whatever they are disguised as with no obvious tell.

I could still change it to use that, just in this particular case the customization offered by that is not particularly useful or appropriate.

2022-12-19 13:41 UTC, Starkku commented
Changed `ShowAllyDisguiseBlinking` to `DisguiseBlinkingVisibility` which uses `AffectedHouse`.

2023-02-06 08:00 UTC, chaserli commented
Regarding the insignia drawing one, I don't know if Ares is going to add anything new in future versions or not, but it would be better to have a specific insignia for IFV in repair mode

2023-04-13 16:13 UTC, Starkku commented
Implemented weapon-mode specific insignia for `Gunner=true`.

Considering this feature as finished now so merging to develop.

2023-04-13 16:13 UTC, merged

2023-04-17 14:06 UTC, chaserli reviewed
IT DIDN'T EVEN WORK (the ifv one)

2023-04-18 11:26 UTC, chaserli reviewed
If a spy has a customized insignia it keeps blinking if the disguise type doesn't have the same one

2023-04-18 11:26 UTC, chaserli commented on src/Ext/Techno/Body.cpp
> +	if (pThis->IsDisguised() && !pThis->IsClearlyVisibleTo(HouseClass::CurrentPlayer))
Should add a not controlled by current player check here to prevent annoying insignia blinking which never happened previously