IronCurtain Can Set Kill Infantry and Organic=yes or Not
Phobos-developers/Phobos pull request #674
Opened 2022-06-17 06:23 UTC by ststl-s

In `rulesmd.ini`
```ini
[CombatDamage]
IronCurtainKillOrganic=  ;boolean, whether IronCurtain Kill Infantry or Techno with Organic=yes, default yes

[SOMETECHNO]
CanBeIronCurtain=        ;boolean, whether this Techno will not be killed by ironcurtain if it is Infantry or Organic=yes, default no
```

2022-07-22 21:39 UTC, MaxLenarc commented
No issues here with this Pull Request. IronCurtainToOrganic works as intended with all 3 options. IronCurtain.Affect works as intended as well with all 3 options. Having a unit with the IronCurtain.Affect tag as the IronCurtainToOrganic causes no issues. Have fun with your invincible engineers!

2022-08-18 02:54 UTC, DmitryVolkov666 commented
So far no bugs have been found. yes, and they hardly will
Single request. Add please [General] > IronCurtain.InfDeathAnim=

2022-08-18 04:58 UTC, ststl-s commented
> So far no bugs have been found. yes, and they hardly will Single request. Add please [General] > IronCurtain.InfDeathAnim=

Now can set warhead to decide InfDeathAnim.

2022-08-18 08:46 UTC, DmitryVolkov666 commented
> > So far no bugs have been found. yes, and they hardly will Single request. Add please [General] > IronCurtain.InfDeathAnim=
> 
> Now can set warhead to decide InfDeathAnim.


Already understood. and another problem

[CombatDamage]
IronCurtainToOrganic=kill

Infantry receives maximum damage but does not die. and the second time - dies

Also if you install
IronCurtainToOrganic=noaffect - then infantry will still get IC

2022-08-18 08:59 UTC, ststl-s commented
> Already understood. and another problem
> 
> [CombatDamage] IronCurtainToOrganic=kill
> 
> Infantry receives maximum damage but does not die. and the second time - dies
> 
> Also if you install IronCurtainToOrganic=noaffect - then infantry will still get IC

I don't have this problem... use lastest `dll` test it again?
There are some changes of entries.
```ini
[CombatDamage]
IronCurtain.ToOrganic=kill  ; IronCurtain affects Enumeration (kill|noaffect|affect), IronCurtain to Infantry and Techno with Organic=yes
IronCurtain.KillWarhead=    ; IronCurtain use this warhead kill technos, default to [CombatDamage]->C4Warhead

[SOMETECHNO]
IronCurtain.Affect=         ; IronCurtain affects Enumeration (kill|noaffect|affect)
IronCurtain.KillWarhead=    ; IronCurtain use this warhead kill technos of this type, default to [CombatDamage]->IronCurtain.KillWarhead
```

2022-08-18 09:33 UTC, chaserli reviewed
Just some personal opinions regarding the game and iron curtain: I don't think this is the right way to extend iron curtain.

Iron Curtain is a symbolic feature of Red Alert, aiming to provide invulnerability to units. It can also be used to kill infantries and organics since it explicitly used C4Warhead against them, which can also be achieved using other conventional methods, for example culling. 

Granting infantries and organics with equal invulnerability like buildings and units is already sufficient. The whole warhead part is a total confusion with other generic warheads, especially when your warhead `ignoreDefense=true`.

2022-08-18 09:33 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_HOOK(0x457C90, BuildingClass_IronCuratin, 0x6)
IronCurtain as a symbol of RA2 aims to provide invulnerability, units and buildings are granted by default. I don't understand why messing up with buildings and units.

2022-08-18 09:33 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +				pTypeExt->IronCuratin_KillWarhead.Get(RulesExt::Global()->IronCurtain_KillWarhead.Get(RulesClass::Instance->C4Warhead)),
Subsequent to what I said above, I don't think this is the right way to extend IronCurtain: Vanilla IronCurtain assures instant kill of infantries since it uses C4Warhead. You provided an option of granting invulnerability like units and buildings, that's good, but what you did beyond that is to degenerate IronCurtain to a generic warhead, so why users do not warheads directly since Ares already provided IronCurtain options?

2022-08-18 09:38 UTC, ststl-s commented on src/Ext/Techno/Hooks.cpp
> +				pTypeExt->IronCuratin_KillWarhead.Get(RulesExt::Global()->IronCurtain_KillWarhead.Get(RulesClass::Instance->C4Warhead)),
This is the warhead used in the ironcurtain killing. When `IgnoreDefense=true`, the warhead can only determine the death effect. Versus is useless. Ares ironcurtain warhead does not affect WW's hard coded kill settings, and `c4warhead` is still used for killing.

2022-08-18 09:41 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +				pTypeExt->IronCuratin_KillWarhead.Get(RulesExt::Global()->IronCurtain_KillWarhead.Get(RulesClass::Instance->C4Warhead)),
From players' standpoint, why would they use iron curtain to deliver damage, given the fact that warheads and weapons are more than sufficient?

2022-08-18 09:41 UTC, ststl-s commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_HOOK(0x457C90, BuildingClass_IronCuratin, 0x6)
This may indeed be unnecessary, depending on whether there is a need.

2022-08-18 09:43 UTC, ststl-s commented on src/Ext/Techno/Hooks.cpp
> +				pTypeExt->IronCuratin_KillWarhead.Get(RulesExt::Global()->IronCurtain_KillWarhead.Get(RulesClass::Instance->C4Warhead)),
This is to set the death animation of infantry, which was proposed by DmitryVolkov666 above.

2022-08-18 09:49 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_HOOK(0x457C90, BuildingClass_IronCuratin, 0x6)
The same point as what I said below: I don't mean warhead is useless, but only limited to the situation as you stated here, which is limited to infantries. Buildings and units are unnecessary IMO

2022-08-18 09:51 UTC, ststl-s commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_HOOK(0x457C90, BuildingClass_IronCuratin, 0x6)
That's right. This warhead is useless for other technos. Need to be removed.

2022-08-18 10:52 UTC, DmitryVolkov666 commented on src/Ext/Techno/Hooks.cpp
> +				pTypeExt->IronCuratin_KillWarhead.Get(RulesExt::Global()->IronCurtain_KillWarhead.Get(RulesClass::Instance->C4Warhead)),
> > Already understood. and another problem
> > [CombatDamage] IronCurtainToOrganic=kill
> > Infantry receives maximum damage but does not die. and the second time - dies
> > Also if you install IronCurtainToOrganic=noaffect - then infantry will still get IC
> 
> I don't have this problem... use latest `dll` test it again? There are some changes of entries.
> 
> ```ini
> [CombatDamage]
> IronCurtain.ToOrganic=kill  ; IronCurtain affects Enumeration (kill|noaffect|affect), IronCurtain to Infantry and Techno with Organic=yes
> IronCurtain.KillWarhead=    ; IronCurtain use this warhead kill technos, default to [CombatDamage]->C4Warhead
> 
> [SOMETECHNO]
> IronCurtain.Affect=         ; IronCurtain affects Enumeration (kill|noaffect|affect)
> IronCurtain.KillWarhead=    ; IronCurtain use this warhead kill technos of this type, default to [CombatDamage]->IronCurtain.KillWarhead
> ```

seems to work

2022-09-04 13:13 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_HOOK(0x457C90, BuildingClass_IronCuratin, 0x6)
I still don't think this is right. I suggest removing everything related to buildings and units, only keeping infantries and organics. I still don't think IronCurtain is supposed to be used to deliver damage to buildings or units, this doesn't make sense to me. If users want to make that happen they have many stable ways of doing that already.

2022-09-05 08:21 UTC, chaserli requested changes

2022-09-05 08:21 UTC, chaserli commented on src/Utilities/Enum.h
> +enum class IronCurtainAffects : char
```suggestion
enum class IronCurtainAffects : unsigned char
```
Perhaps, for consistency?

2022-09-05 08:21 UTC, chaserli commented on src/Ext/TechnoType/Body.cpp
> +		.Process(this->IronCurtain_KeptOnDeploy)
```suggestion
```
Processed twice

2022-09-05 08:21 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +[SOMETECHNO]
```suggestion
[SOMETINFANTRY]
```

2022-09-05 08:21 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.Affect=         ; IronCurtain affects Enumeration (kill|noaffect|affect)
```suggestion
IronCurtain.Effect=         ; IronCurtain affects Enumeration (kill | invulnerable | ignore)
```
The name looks wrong to me

2022-09-05 08:21 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.ToOrganic=kill  ; IronCurtain affects Enumeration (kill|noaffect|affect), IronCurtain to Infantry and Techno with Organic=yes
```suggestion
IronCurtain.ToOrganic=kill  ; IronCurtain affects Enumeration (kill| invulnerable | ignore), IronCurtain to Infantry and Techno with Organic=yes
```

2022-09-05 08:21 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	case IronCurtainAffects::Kill:
Since kill is the default behavior, I would suggest putting it as the `default` branch of this `switch` case.

2022-09-05 08:21 UTC, chaserli commented on src/Utilities/TemplateDef.h
> +			if (_strcmpi(str, "kill") == 0)
If using `kill` as default, maybe this part is relocated to the `else` section. In case the user tapped wrong names, just add an `INIParseFailed` warning. Just my opinion.

2022-09-06 08:49 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.ToOrganic=kill  ; IronCurtain effect Enumeration (kill | invulnerable | ignore), IronCurtain to Infantry and Techno with Organic=yes
Polish the doc a bit. The names still sound strange, but I have no better idea either, like `IronCurtain.OnOrganics.Effect=kill, IronCurtain.OnOrganics.Warhead`. Need suggestions from others for that

2022-09-06 08:49 UTC, chaserli commented on src/Ext/Rules/Body.cpp
> +	const char* sectionCombatDamage = "CombatDamage";
I'm not very familiar with compilers but it seems that since the `/GF` option is enabled, there's only one `"CombatDamage"` in the string pool? So I'm not sure if this helps.

2022-09-06 08:49 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	TechnoTypeClass* pType = pThis->GetTechnoType();
Is it already `EAX` at this point?

2022-09-06 08:49 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	GET(FootClass*, pThis, ECX);
Is it already `ESI` as well at this point?  Also encapsulate your return addresses into an anonymous enum class.

2022-09-06 11:55 UTC, ststl-s commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.ToOrganic=kill  ; IronCurtain effect Enumeration (kill | invulnerable | ignore), IronCurtain to Infantry and Techno with Organic=yes
How about `IronCurtain.Effect.Organics`?

2022-09-07 13:12 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.ToOrganic=kill  ; IronCurtain effect Enumeration (kill | invulnerable | ignore), IronCurtain to Infantry and Techno with Organic=yes
> How about `IronCurtain.Effect.Organics`?

and `IronCurtain.Warhead.Organics`? In this case I would prefer `IronCurtain.EffectOnOrganics` and `IronCurtain.KillOrganicsWarhead`

2022-09-21 06:52 UTC, chaserli requested changes
Looks good imo, except for the naming, "CombatDamage" and YRpp part, I'm not sure if any improvement is needed

2022-09-21 06:52 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.Effect=                ; IronCurtain effect Enumeration (kill | invulnerable | ignore)
```suggestion
IronCurtain.Effect=                ; IronCurtain effect Enumeration (kill | invulnerable | ignore), default to [CombatDamage]-> IronCurtain.EffectOnOrganics
```

2022-10-02 18:41 UTC, chaserli requested changes
I think it's OK, maybe we need to update YRpp first?

2022-10-02 18:41 UTC, chaserli commented on src/Ext/Rules/Body.cpp
> +	const char* sectionCombatDamage = reinterpret_cast<const char*>(0x839E8C);
Keep the way it was, we'll deal with the strings later perhaps

2022-10-02 18:41 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	GET_STACK(HouseClass*, pSource, STACK_OFFS(0x10, -0x8));
```suggestion
	GET_STACK(HouseClass*, pSource, STACK_OFFSET(0x10, 0x8));
```
`STACK_OFFS` is deprecated

2022-10-02 18:41 UTC, chaserli commented on docs/Whats-New.md
> +- IronCurtain can set as `kill/Affect/NoAffect` to all Techno (by ststl)
update your enum name

2022-10-17 16:35 UTC, chaserli approved these changes
Needs update

2022-10-22 09:55 UTC, chaserli requested changes
A few words adjustment, I don't know how to deal with the YRpp part

2022-10-22 09:55 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.KillOrganicsWarhead=   ; IronCurtain use this warhead kill technos, default to [CombatDamage]->C4Warhead
```suggestion
IronCurtain.KillOrganicsWarhead=   ; IronCurtain uses this warhead to kill organics, default to [CombatDamage]->C4Warhead
```

2022-10-22 09:55 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +		Invunlnerable = 0x4DEB38,
No need for multiple lines here

2022-10-22 09:55 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +	}
can remove parentheses

2022-10-22 09:55 UTC, chaserli commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.KillWarhead=           ; IronCurtain use this warhead kill technos of this type, default to [CombatDamage]->IronCurtain.KillWarhead
```suggestion
IronCurtain.KillWarhead=           ; IronCurtain uses this warhead to kill this organic, default to [CombatDamage]->IronCurtain.KillWarhead
```

2022-10-22 13:08 UTC, chaserli requested changes

2022-10-22 13:08 UTC, chaserli commented on src/Ext/Techno/Hooks.cpp
> +DEFINE_JUMP(VTABLE, 0x7EB1AC, 0x4DEAE0); // Redirect InfantryClass::IronCurtain to FootClass::IronCurtain
I don't know if adding your modification of YRpp is consistent with the existing style, but I got another way of doing the same thing. 
Please rebase your YRpp with upstream, test it first and fix the lint error for me

2022-10-23 10:16 UTC, ststl-s commented
> A few words adjustment, I don't know how to deal with the YRpp part BTW next time plz name your branch properly

Can operate as before.

2022-10-24 15:24 UTC, chaserli approved these changes

2022-12-28 06:25 UTC, merged