PCX load screen of campaign
Phobos-developers/Phobos pull request #695
Opened 2022-07-07 13:34 UTC by ststl-s

In `missionmd.ini`, `LS800BkgdName` also can set as a pcx file.

2022-07-09 12:15 UTC, secsome requested changes
Fix it and do some test on it.

2022-07-09 12:15 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +	std::string fileName = ScenarioClass::Instance->LS800BkgdName;
No need to construct a std::string object here.

2022-07-09 12:15 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +	if (fileName.length() < 4U)
`strlen`
Also, it shouldn't arise a fatal error here. It's better to just return 0 here.

2022-07-09 12:15 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +		BSurface* pcx = PCX::Instance->GetSurface(fileName.c_str());
`if(auto pPCX = PCX::Instance->GetSurface(lpFileName))`

2022-07-09 12:15 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +			//pSurface->CopyFrom(&surfBounds, &destClip, pcx, &pcxBounds, &pcxBounds, true, true);
Delete unused code here

2022-07-09 12:15 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +			RectangleStruct surfBounds = { 0, 0, pSurface->Width, pSurface->Height };
Remove this unused var here.

2022-07-09 18:42 UTC, ststl-s commented
![image](https://user-images.githubusercontent.com/103478314/178118809-5507e51c-ee76-454a-8911-3c4c62221214.png)

2022-07-09 18:45 UTC, ststl-s commented
```ini
[SOV01UMD.MAP]
Briefing=Brief:Sov01md
UIName=Name:Sov01md
LSLoadMessage=LoadMsg:Sov01md
LSLoadBriefing=LoadBrief:Sov01md
LS640BriefLocX=20
LS640BriefLocY=20
LS800BriefLocX=20
LS800BriefLocY=20
LS640BkgdName=test2.pcx;LS640S01.SHP
LS800BkgdName=test2.pcx;LS800S01.SHP
LS800BkgdPal=LS800S01.PAL
```

2022-07-09 18:46 UTC, ststl-s commented
[test2.zip](https://github.com/Phobos-developers/Phobos/files/9077705/test2.zip)

2022-07-09 19:31 UTC, Belonit commented
Question. This feature work with cncnet5.dll if the game resolution is greater than 800x600 ?

2022-07-10 05:28 UTC, ststl-s commented
> Question: does this feature work with `cncnet5.dll` if the game resolution is greater than 800x600?

1600x900
![$V3}N_VZ`VEYTF210BHPU H](https://user-images.githubusercontent.com/103478314/178132519-ec61583a-155a-4127-a32a-bf877db8af30.png)

PCX size larger than resolution will cause FatalError, `pSurface->CopyFrom` will not....

2022-07-10 05:30 UTC, secsome requested changes

2022-07-10 05:30 UTC, secsome commented on src/Misc/Hooks.PCX.cpp
> +		if (auto pPCX = PCX::Instance->GetSurface(filename))
`auto const` here and others looks fine now

2022-07-10 05:31 UTC, secsome commented
Do more tests and this PR can be merged.

2022-07-10 06:43 UTC, Metadorius commented
> > Question: does this feature work with `cncnet5.dll` if the game resolution is greater than 800x600?
> 
> 1600x900
> ![$V3}N_VZ`VEYTF210BHPU H](https://user-images.githubusercontent.com/103478314/178132519-ec61583a-155a-4127-a32a-bf877db8af30.png)
> 
> PCX size larger than resolution will cause FatalError, `pSurface->CopyFrom` will not....

So does your patch crash if the size is bigger than resolution? Ideal behavior would be allowing it to be centered and cropped.

2022-07-10 09:14 UTC, ststl-s commented
> > > Question: does this feature work with `cncnet5.dll` if the game resolution is greater than 800x600?
> > 
> > 
> > 1600x900
> > ![$V3}N_VZ`VEYTF210BHPU H](https://user-images.githubusercontent.com/103478314/178132519-ec61583a-155a-4127-a32a-bf877db8af30.png)
> > PCX size larger than resolution will cause FatalError, `pSurface->CopyFrom` will not....
> 
> So does your patch crash if the size is bigger than resolution? Ideal behavior would be allowing it to be centered and cropped.

Now it will not. PCX will show part of it when it is larger than the resolution, and it is centered.

2022-07-10 09:15 UTC, ststl-s commented
> > > Question: does this feature work with `cncnet5.dll` if the game resolution is greater than 800x600?
> > 
> > 
> > 1600x900
> > ![$V3}N_VZ`VEYTF210BHPU H](https://user-images.githubusercontent.com/103478314/178132519-ec61583a-155a-4127-a32a-bf877db8af30.png)
> > PCX size larger than resolution will cause FatalError, `pSurface->CopyFrom` will not....
> 
> So does your patch crash if the size is bigger than resolution? Ideal behavior would be allowing it to be centered and cropped.

Now it will not. PCX will show part of it when it is larger than the resolution, and it is centered.

2022-07-10 09:45 UTC, Metadorius approved these changes

2022-07-10 09:46 UTC, merged