IronCurtain status inheritance upon DeploysInto/UndeploysInto
Phobos-developers/Phobos pull request #698
Opened 2022-07-10 15:35 UTC by chaserli

### IronCurtain status inheritance on DeploysInto/UndeploysInto

- When an iron-curtained vehicle is deployed into a building and vice versa, the iron-curtain effect will be removed. This behavior now can be customized. The iron-curtain effect can be preserved.

![preserve-ic](https://user-images.githubusercontent.com/9932846/178151626-a1e8f4f1-3901-4820-9043-fd2a55c8dfe5.gif)

In `rulesmd.ini`:
```ini
[CombatDamage]
IronCurtain.SyncDeploysInto=no  ; boolean

[SOMETECHNO]                    ; BuildingType or VehicleType
IronCurtain.SyncDeploysInto=    ; boolean, default to [CombatDamage]->IronCurtain.SyncDeploysInto

```

2022-07-10 15:54 UTC, Metadorius requested changes

2022-07-10 15:54 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		Valueable<bool> IronCurtain_SyncDeploysInto;
Not fond of the tag name, doesn't read like English. How about something like `IronCurtain.SyncOnDeploy` with true as a default value since this is more of a bugfix?

2022-07-10 15:54 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +- When an iron-curtained vehicle is deployed into a building and vice versa, the iron-curtain effect will be removed. This behavior now can be customized. The iron-curtain effect can be preserved.
```suggestion
- Iron Curtain status is now preserved when converting between TechnoTypes.
  - This behavior can be customized on per-TechnoType and global basis.
```

2022-07-10 15:54 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +![image](_static/images/preserve-ic.gif)
Should move it before the description.

2022-07-10 15:54 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +### IronCurtain status inheritance on DeploysInto/UndeploysInto
```suggestion
### Preserve Iron Curtain status on type conversion 
```

2022-07-10 15:56 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +		Valueable<bool> IronCurtain_SyncDeploysInto;
Same for the override tag.

2022-07-10 16:18 UTC, chaserli commented on src/Ext/Rules/Body.h
> +		Valueable<bool> IronCurtain_SyncDeploysInto;
Perhaps it might be fine to leave it as false, just like those jumpjet turn to target stuff? It changed the vanilla gameplay, although not as much as that jumpjet stuff.

2022-07-12 16:00 UTC, Metadorius approved these changes

2022-07-12 16:00 UTC, Metadorius commented on docs/Fixed-or-Improved-Logics.md
> +IronCurtain.KeptOnDeploy=no  ; boolean
```suggestion
IronCurtain.KeptOnDeploy=yes ; boolean
```

2022-07-12 16:00 UTC, merged