Custom Theater
Phobos-developers/Phobos pull request #704
Opened 2022-07-17 08:51 UTC by Belonit

# Custom Theaters

In **Map**:
```ini
[Map]
Theater=SomeTheaterName        ; Default TEMPERATE
CustomTheater=SomeTheaterName  ; [Map]->Theater
```
- Tag `CustomTheater` is the same as `Theater`, but it has a higher priority. It's needed for more convenient work with **FA2** and **CNCMaps Renderer**, since these tools do not yet support **Custom Theaters**

In **\<SomeTheaterName\>.Theater.ini**:
```ini
[THEATER]                     ; default values ​​for vanilla theaters are different, see table below
TerrainControl=TEMPERATMD.INI ; filename - including the .ini extension or <self>
IsArctic=no                   ; boolean

PaletteISO=ISOTEM.PAL         ; filename - including the .pal extension
PaletteOverlay=TEMPERAT.PAL   ; filename - including the .pal extension
PaletteUnit=UNITTEM.PAL       ; filename - including the .pal extension

Extension=TEM                 ; String of 3 characters
Letter=T                      ; String of 1 characters

RadarBrightness=100%          ; floating point value, percents

[SpecificMixes]               ; list of Mix filename - including the .mix extension
1=TEMPERAT.MIX                ; default values ​​applied if the section is not found
2=TEM.MIX
3=ISOTEMMD.MIX
4=ISOTEMP.MIX
5=
...
```
- The special value `<self>` of the `TerrainControl` tag is equivalent to `TerrainControl=<SomeTheaterName>.Theater.ini`
- The `IsArctic=yes` tag means that this is an arctic theater and should work the same as SNOW. This applies to the <a href=https://modenc.renegadeprojects.com/AlternateArcticArt>AlternateArcticArt</a> tag and also to the features of light generation in the Random Map Generator, maybe something else...

# Bonus
- Tags `ShorePieces`, `WaterSet`, `CliffSet`, `WaterCliffs`, `WaterBridge`, `BridgeSet`, `WoodBridgeSet` have been hardcoded to `-1` for the **Lunar** theatre, this is no longer the case

# Default Values for Vanilla Theaters
|                 | *TEMPERATE*    | *SNOW*         | *URBAN*        | *DESERT*       | *NEWURBAN*     | *LUNAR*     |
:---------------- | :------------- | :------------- | :------------- | :------------- | :------------- | :---------- |
*TerrainControl*  |`TEMPERATMD.INI`|`SNOWMD.INI    `|`URBANMD.INI   `|`DESERTMD.INI  `|`URBANNMD.INI  `|`LUNARMD.INI`|
*IsArctic*        |`no            `|`yes           `|`no            `|`no            `|`no            `|`no         `|
*PaletteISO*      |`ISOTEM.PAL    `|`ISOSNO.PAL    `|`ISOURB.PAL    `|`ISODES.PAL    `|`ISOUBN.PAL    `|`ISOLUN.PAL `|
*PaletteOverlay*  |`TEMPERAT.PAL  `|`SNOW.PAL      `|`URBAN.PAL     `|`DESERT.PAL    `|`URBANN.PAL    `|`LUNAR.PAL  `|
*PaletteUnit*     |`UNITTEM.PAL   `|`UNITSNO.PAL   `|`UNITURB.PAL   `|`UNITDES.PAL   `|`UNITUBN.PAL   `|`UNITLUN.PAL`|
*Extension*       |`TEM           `|`SNO           `|`URB           `|`DES           `|`UBN           `|`LUN        `|
*Letter*          |`T             `|`A             `|`U             `|`D             `|`N             `|`L          `|
*RadarBrightness* |`100%          `|`80%           `|`100%          `|`100%          `|`100%          `|`100%       `|
*SpecificMixes*   |<pre>TEMPERAT.MIX<br/>TEM.MIX<br/>ISOTEMMD.MIX<br/>ISOTEMP.MIX</pre>|<pre>SNOWMD.MIX<br/>SNOW.MIX<br/>SNO.MIX<br/>ISOSNOMD.MIX<br/>ISOSNOW.MIX</pre>|<pre>URBAN.MIX<br/>URB.MIX<br/>ISOURBMD.MIX<br/>ISOURB.MIX</pre>|<pre>DESERT.MIX<br/>DES.MIX<br/>ISODESMD.MIX<br/>ISODES.MIX</pre>|<pre>URBANN.MIX<br/>UBN.MIX<br/>ISOUBNMD.MIX<br/>ISOUBN.MIX</pre>|<pre>LUNAR.MIX<br/>LUN.MIX<br/>ISOLUNMD.MIX<br/>ISOLUN.MIX</pre>

2022-07-17 09:02 UTC, Belonit commented
Before the merge, I should add documentation and get feedback from the community

2022-07-17 17:00 UTC, McPwny commented
would it be difficult to add a tag under the [theater] section that loads a supplementary ini with maps of the theatertype in a way similar to how the ares feature [#include] (https://ares-developers.github.io/Ares-docs/new/misc/include.html) works? incase mods want to use a specific theaters to emulate, for example, alternate timelines or outer space, without injecting ini code into each individual map.

2022-07-18 07:22 UTC, Belonit commented
@McPwny I have added an `AutoInclude` tag for this

2022-07-18 15:29 UTC, McPwny commented
> 

terrific work

2023-05-13 14:59 UTC, FS-21 commented
Hi!
I don't how should I explain it but in general works as planned. Since my mod has a terrain that replaced the  desert from YR game I made changes for testing it:

In Map:
```
[Map]
Theater=DESERT     ; I respected the one used before this test
CustomTheater=TSTemperate     ; this works
```

In INI file called "TSTemperate.Theater.ini":
```
[Theater]
TerrainControl=TSTEMPERATE.INI   ; this works, I just renamed my INI file I was using for the new terrain.
ExtendedRules=<none>      ; Not tested because I don't know how it works.

IsArctic=no     ; Not tested. What it does if "yes"?

PaletteISO=ISOTST.PAL     ; this works. Is the renamed palette I was using until now.
PaletteOverlay=DESERT.PAL   ; Not sure... this tag affects objects from [OverlayTypes] ??? then it doesn't work. I changed it with bad palettes like "DIALOGN.PAL" but I saw no changes.
PaletteUnit=UNITTEM.PAL   ; this tag works!

Extension=TST   ; this tag works!
Letter=Z   ; this tag works!

RadarBrightness=100%   ; this tag works! and not only that, I found that my mini-map terrain looks much better with value "200%" :-D

[SpecificMixes]       ; this tag works! I tried multiple files in this list and that doesn't respect the standard game names.
1=TEST_EXPANDMD08.MIX
2=TEST_EXPANDMD09.MIX
3=TEST_EXPANDMD99.MIX  
```

2023-05-21 07:36 UTC, Belonit commented
@FS-21 Thanks for the feedback. As for the `IsArctic` and `ExtendedRules` tags, it seems you missed this paragraph in the thread header

> - `ExtendedRules` Allows you to specify an ini file to force rules to be included in all maps of this theater
> - The special value `<self>` of the `TerrainControl` and `ExtendedRules` tags is equivalent to `<SomeTheaterName>.Theater.ini`
> - The `IsArctic=yes` tag means that this is an arctic theater and should work the same as SNOW. This applies to the <a href=https://modenc.renegadeprojects.com/AlternateArcticArt>AlternateArcticArt</a> tag and also to the features of light generation in the Random Map Generator, maybe something else...

2023-08-15 10:32 UTC, Metadorius requested changes
What I would do:
1) remove `TerrainControl` tag altogether and just always assume it's the same ini file for theater customisations (I just don't see a point in having something else);
2) use THEATERNAMEMD.INI as the theater INI (with MD suffix configurable in rules I guess? or might introduce Phobos.ini for such stuff);
3) make everything autoconfigurable by name (except vanilla theaters which would use the values that were hardcoded) with an option to override, for example if you name a theater CoolTheater, it will look for COOLTHEATER.INI, and the theater suffix and 1-letter that form all the automatic names will be `COO` and `C` unless specified, which in turn will be used by palettes, mixes (autoconfigured too similar to vanilla theaters) unless specified otherwise.

This way we get effortless defaults and flexible configuration at the same time. Oh and should add docs, changelog and credits entries.

Not an exhaustive review yet, just looking at the API.

2023-08-15 10:54 UTC, Starkku commented
>     1. remove `TerrainControl` tag altogether and just always assume it's the same ini file for theater customisations (I just don't 

Allowing custom INI name would allow using same configuration INI for multiple theaters, particularly useful if someone intends to use the feature for 'reskins' of existing theaters.

2023-08-15 10:57 UTC, Metadorius commented
> > 1. remove `TerrainControl` tag altogether and just always assume it's the same ini file for theater customisations (I just don't 
> 
> Allowing custom INI name would allow using same configuration INI for multiple theaters, particularly useful if someone intends to use the feature for 'reskins' of existing theaters.

In my opinion it's better to do this via $include (remember the toggle between whether to write the stuff on top of current file or below that I suggested? this is it)

2023-08-15 10:59 UTC, Metadorius commented
Although I do admit that I am not fully knowledgeable on the topic so if there are some specific issues with that approach - would be good to hear them.

2024-06-22 12:54 UTC, closed without merging

2024-06-23 19:23 UTC, Belonit commented
Closed due to lack of activity.
May be reopened again in the future

2025-03-10 06:59 UTC, FS-21 commented
Hi!

Are there possibilities to recover this cool feature?

2025-07-04 18:37 UTC, ZivDero commented
The user API seems very foreign.

I'd recommend doing smth like what CCHyper did in VInifera.
https://vinifera.readthedocs.io/en/latest/New-Features-and-Enhancements.html#theaters

That is, make a `theaters(md).ini`
In there, define all the theaters, in a way that's similar to the vanilla game's array
e.g.
```ini
[TEMPERATE]
Root=TEMPERAT
IsoRoot=ISOTEMP
Suffix=TEM
MMSuffix=MMT
ImageLetter=T
IsArctic=false
IsIceGrowthEnabled=false
IsVeinGrowthEnabled=true
IsAllowedInRMG=true
IsGenerateVeinholesInRMG=true
LowRadarBrightness=1.0
HighRadarBrightness=1.6
```

(adjusted for anything else YR may need)

And then dump whatever the custom theater stuff is and just supply the new theater as if it were a vanilla one.