Refactoring PlacementPreview logic
Phobos-developers/Phobos pull request #710
Opened 2022-07-23 01:06 UTC by Belonit

- General code refactoring
- Added ability to load theater-specific shapes - #642 
- Translucent tags now should be set to 0\25\50\70 instead of 0\1\2\3
- Renamed tags and fixed documentation errors:
  -  In AudioVisual
     - `BuildingPlacementPreview.DefaultTranslucentLeve` ---> `PlacementPreview.Building.Translucent`
     - `BuildingPlacementGrid.TranslucentLevel` -------------> `PlacementPreview.Grid.Translucent`
  -  In BuildingType
     - `PlacementPreview.Show` ---------------------------------> `PlacementPreview`
     - `PlacementPreview.TranslucentLevel` -------------------> `PlacementPreview.Translucent`
  -  In ra2md.ini
     - `[Phobos]->ShowBuildingPlacementPreview` -------------> `[Phobos]->PlacementPreview.Building`

[Old](https://phobos.readthedocs.io/en/latest/User-Interface.html#placement-preview) Documentation vs [New](url)

2022-07-23 13:12 UTC, Cpj636 commented
There is my testing feedback:
All three tags in [AudioVisual] work fine.
Theater-specific shapes can be specified by PlacementPreview.Shape.
Theater-specific palettes can be specified by PlacementPreview.Palette.
All the rest tags work as expected.

2022-07-24 13:27 UTC, Belonit commented
The `PlacementPreview.Shape` tag does not currently support save\load. Need to fix

2022-07-25 14:37 UTC, Metadorius requested changes
In general I am not a fan of period overusage in tags. Also not sure if the code blocks you made are really needed, could just put a comment explaining what is being done next instead of adding indentation.

2022-07-25 14:37 UTC, Metadorius commented on docs/User-Interface.md
> +PlacementPreview.Grid.Translucent=0        ; integer, 0 25 50 75
I would call that `PlacementGrid.Translucency=0`.
```ini
PlacementGrid=yes
PlacementGrid.Translucency=0
PlacementGrid.WithPreview=yes
PlacementGrid.Translucency.WithPreview=0`

2022-07-25 14:37 UTC, Metadorius commented on docs/User-Interface.md
> +PlacementPreview.Translucent=              ; integer, defaults to [AudioVisual]->PlacementBuilding.Translucent
Not sure, is there really a need for this tag override? I don't see usecases for this, it only introduces inconsistencies.

2022-07-25 14:37 UTC, Metadorius commented on docs/User-Interface.md
>  ```
````suggestion
```{note}
The `PlacementPreview.Palette` option is not used if `PlacementPreview.Remap=yes`. This may change in future.
```
````

2022-07-25 14:37 UTC, Metadorius commented on src/Ext/BuildingType/Body.cpp
> +			}
This looks like it should not be here but rather in `TemplateDef.h` or wherever else.

2022-07-25 14:37 UTC, Metadorius commented on src/Phobos.cpp
> +		Phobos::Config::PlacementPreview_Enabled = pINI_RULESMD->ReadBool("AudioVisual", "PlacementPreview.Building", false);
We have RulesExt for this. Does not belong here.

2022-07-25 14:37 UTC, Metadorius commented on src/Phobos.cpp
> +			CCINIClass::INI_RA2MD->ReadBool("Phobos", "PlacementPreview.Building", Phobos::Config::PlacementPreview_Enabled);
`ShowPlacementPreview` should work fine as a variable name too.

2022-07-25 14:37 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +			if(pTypeExt->PlacementPreview_Remap.Get())
```suggestion
			if (pTypeExt->PlacementPreview_Remap.Get())
```

2022-07-25 14:37 UTC, Metadorius commented on src/Ext/BuildingType/Hooks.cpp
> +			);
1. Why not implement `TranslucencyLevel` as a type that could be converted to blitter flags instead? 
2. Default-to-global behavior could be done with a method.

2022-07-25 14:37 UTC, Metadorius commented on src/Utilities/EnumFunctions.cpp
>  }
Should be moved to the `Read` specialization for the suggested `TranslucencyLevel` type.

2022-07-25 14:37 UTC, Metadorius commented on src/Utilities/GeneralUtils.cpp
> +		pSuffix[2] = pExtension[2];
```suggestion

		pSuffix[0] = pExtension[0];
		pSuffix[1] = pExtension[1];
		pSuffix[2] = pExtension[2];

```
Also can't this be done via a function call? Also IMO should emit a warning if the amount of `~` symbols doesn't equate to 3, which is a developer error.

2022-07-25 14:58 UTC, Metadorius commented on docs/User-Interface.md
> +PlacementPreview.Building.Translucent=75   ; integer, 0 25 50 75
I disagree, `PlacementPreview` is a preview of how building would look. for grid I recommend to name it `PlacementGrid`, it doesn't have anything to do with previewing the building itself, it only displays a grid.

2022-07-25 15:00 UTC, Belonit commented on docs/User-Interface.md
> +PlacementPreview.Building=   ; boolean, defaults to rulesmd.ini->[AudioVisual]->PlacementPreview.Building
If in the future someone needs to implement PlacementPreview for grid or some other entity, this can cause problems

2022-07-25 15:01 UTC, Belonit commented on src/Phobos.cpp
> +			CCINIClass::INI_RA2MD->ReadBool("Phobos", "PlacementPreview.Building", Phobos::Config::PlacementPreview_Enabled);
As above, I'm all for better semantics

2022-07-25 15:02 UTC, Metadorius commented on docs/User-Interface.md
> +PlacementPreview.Building=   ; boolean, defaults to rulesmd.ini->[AudioVisual]->PlacementPreview.Building
There is literally nothing that can be placed down other than buildings, and as I said PlacementPreview has no relation to placement grid, it's two separate things.

2022-07-25 19:23 UTC, Belonit commented on src/Ext/BuildingType/Body.cpp
> +			}
```cpp
// we cannot load same SHP file twice it may produce artifact , prevent it !
    if (_strcmpi(pValue, pSection) || _strcmpi(pValue, pArtSection))
```
This part applies only to this tag, and should not apply to others.

2022-07-25 19:36 UTC, Belonit commented on docs/User-Interface.md
> +PlacementPreview.Translucent=              ; integer, defaults to [AudioVisual]->PlacementBuilding.Translucent
@Metadorius I don't understand what specific tag you are talking about? `PlacementPreview.Offset` ?

2022-07-25 19:38 UTC, Metadorius commented on docs/User-Interface.md
> +PlacementPreview.Translucent=              ; integer, defaults to [AudioVisual]->PlacementBuilding.Translucent
Hm it should've highlighted only the `PlacementPreview.Translucent`. Why would anyone want to do different transparency for only some of the placement previews?

2022-07-25 19:42 UTC, Belonit commented on src/Phobos.cpp
> +		Phobos::Config::PlacementPreview_Enabled = pINI_RULESMD->ReadBool("AudioVisual", "PlacementPreview.Building", false);
This tag is used as the default value for RA2MD.ini. We should read it first

2022-07-25 19:47 UTC, Belonit commented on docs/User-Interface.md
> +PlacementPreview.Translucent=              ; integer, defaults to [AudioVisual]->PlacementBuilding.Translucent
I'm guessing it might be useful for water-only buildings. In any case, we must keep this tag if you want to maintain pre-release compatibility.

2022-07-25 20:47 UTC, Metadorius commented on src/Phobos.cpp
> +		Phobos::Config::PlacementPreview_Enabled = pINI_RULESMD->ReadBool("AudioVisual", "PlacementPreview.Building", false);
It makes no sense to use it as a default value in RA2MD.ini, those are controlled by the client. It should be a serializable tag that globally disables or enables the logic, and takes precedence over RA2MD.ini value.

2022-07-25 21:19 UTC, Belonit commented on src/Phobos.cpp
> +		Phobos::Config::PlacementPreview_Enabled = pINI_RULESMD->ReadBool("AudioVisual", "PlacementPreview.Building", false);
What should happen if the tag is not defined? This feature originally had false as the default value in ra2md.ini, which made it pretty pointless.

2022-07-25 21:22 UTC, Metadorius commented on src/Phobos.cpp
> +		Phobos::Config::PlacementPreview_Enabled = pINI_RULESMD->ReadBool("AudioVisual", "PlacementPreview.Building", false);
`true` of course. Yeah `false` by default is stupid. This should be an opt-out switch.

2022-08-01 14:19 UTC, Belonit commented on src/Utilities/GeneralUtils.cpp
> +		pSuffix[2] = pExtension[2];
I'm not sure if this is really needed here

2022-08-03 15:21 UTC, Belonit commented
Reopen after accidental closure

2022-08-04 09:57 UTC, Metadorius requested changes
Code's good, need a bit of doc changes, also missing a credits and changelog mentions of your refactor, also please PR to supplementaries repo.

2022-08-04 09:57 UTC, Metadorius commented on docs/Whats-New.md
> +- [Placement Preview](User-Interface.md#placement-preview) logic has been reimplemented, `BuildingPlacementPreview.DefaultTranslucentLeve`, `BuildingPlacementGrid.TranslucentLevel`, `PlacementPreview
1. I think this is more of a refactor than a reimplementation. You didn't change the tag functions right? Might as well list what the changed names are.
2. Please also supply update script entries [here](https://github.com/Phobos-developers/PhobosSupplementaries/blob/develop/MigrationUtility/Scripts/UpdatePhobosTags.sed).
3. Typo in `DefaultTranslucentLeve`.

2022-08-04 09:57 UTC, Metadorius commented on docs/User-Interface.md
> +- The building placement grid *(place.shp)* translucency setting can be adjusted via `PlacementGrid.Translucency`.
```suggestion
- The building placement grid (`place.shp`) translucency setting can be adjusted via `PlacementGrid.Translucency`.
```

Also I would make this a separate section because it's not that related to this feature.

2022-08-04 09:57 UTC, Metadorius commented on docs/User-Interface.md
> +- If using the building's appropriate `Buildup` is not desired, customizations allow for you to choose the exact SHP and frame you'd prefer to show as preview through `PlacementPreview.Shape`, `Place
```suggestion
- If using the building's appropriate `Buildup` is not desired, customizations allow for you to choose the exact SHP and frame you'd prefer to show as preview through `PlacementPreview.Shape`, `PlacementPreview.ShapeFrame` and `PlacementPreview.Palette`.
```

2022-08-05 03:48 UTC, Belonit commented on docs/Whats-New.md
> +- [Placement Preview](User-Interface.md#placement-preview) logic has been reimplemented, `BuildingPlacementPreview.DefaultTranslucentLeve`, `BuildingPlacementGrid.TranslucentLevel`, `PlacementPreview
There is also a problem in the old implementation. The `PlacementPreview.TranslucentLevel` tag is named so in the documentation, but it doesn't work. The `PlacementPreview.Translucent` tag is used instead.

2022-08-12 09:11 UTC, Metadorius requested changes
Still missing credits, update scripts.

2022-08-12 09:11 UTC, Metadorius commented on docs/Whats-New.md
> +- [Placement Preview](User-Interface.md#placement-preview) logic has been reimplemented, `BuildingPlacementPreview.DefaultTranslucentLeve`, `BuildingPlacementGrid.TranslucentLevel`, `PlacementPreview
It wasn't really reimplemented. The tag namess were adjusted. Also you still didn't address 2 and 3. Maybe then don't write the exact tags?

2022-08-12 09:11 UTC, Metadorius commented on docs/User-Interface.md
>  ```
````suggestion

```{note}
The `PlacementPreview.Palette` option is not used when `PlacementPreview.Remap=yes` is set to yes. This may change in future.
```
````

2022-08-16 12:21 UTC, Belonit commented on docs/Whats-New.md
> +- [Placement Preview](User-Interface.md#placement-preview) logic has been reimplemented, `BuildingPlacementPreview.DefaultTranslucentLeve`, `BuildingPlacementGrid.TranslucentLevel`, `PlacementPreview
This PR is broken. I can't add commits to it

2022-09-09 18:07 UTC, chaserli commented on src/Ext/BuildingType/Hooks.cpp
> +				if (pImage = pType->LoadBuildup())
I recently discovered that when `LoadBuildUp` is called normally `ClearBuildUp` is called right after. Like 0x442CC4. Otherwise according to 0x4659D8 I'm afraid that `CCFileClass` or `SHPStruct` call only their CTOR, not DTOR.

2022-09-09 18:10 UTC, Belonit commented on src/Ext/BuildingType/Hooks.cpp
> +				if (pImage = pType->LoadBuildup())
Good remark. I will check it

2022-09-09 18:22 UTC, Belonit commented on src/Ext/BuildingType/Hooks.cpp
> +				if (pImage = pType->LoadBuildup())
![image](https://user-images.githubusercontent.com/54427022/189418344-976a8fe4-ada6-4bfb-b018-b6a76f325c09.png)
I don't think this is a problem. Because if the Buildup is already loaded, then it will not be re-created.

2022-09-10 10:42 UTC, closed without merging