Refactor  ForbidParallelAIQueue and SWTypeExt
Phobos-developers/Phobos pull request #721
Opened 2022-08-03 12:54 UTC by chaserli

I accidentally deleted #720, sorry
1. Fix the wrong hook size and stack offset for future usage
2. Minor refactored limbo delivery part to improve the readability of #379 
3. **Moved all ForbidParalleAIlQueue related settings to `RulesExt`** #638 :

I noticed that `[GlobalControls]->AllowParallelAIQueues` is serialized in Ares, so I think these ones should be serialized as well? Need someone to elaborate on this one

2022-08-04 10:05 UTC, Metadorius requested changes
IIRC no one fixed the inverted tags yet so may as well fix them? https://discord.com/channels/338055131666972683/773636942775582720/1004370122837872760

2022-08-04 10:05 UTC, Metadorius commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK(0x6CDE40, SuperClass_Launch_finale, 0x3)
```suggestion
DEFINE_HOOK(0x6CDE40, SuperClass_Place_Finale, 0x3)
```

2022-08-04 10:37 UTC, chaserli commented on src/Ext/Building/Hooks.cpp
>  	HouseExt::ExtMap.Find(pHouse)->Factory_AircraftType = nullptr;
Actually I didn't look into the detail yet, I cannot understand most of them for the moment, especially when these ones were already set to `nullptr` in ares. I don't see why these hooks are necessary

2022-08-10 14:24 UTC, chaserli commented on src/Ext/Building/Hooks.cpp
>  				pData->Factory_VehicleType = nullptr;
![@0(_(8(N}@FT4%7QQO%8VHE](https://user-images.githubusercontent.com/9932846/183925811-9cd2d63d-004b-438e-a630-822fce73486d.png)
I saw that Ares 0.A Announced invalidation of these pointers, should I do the same?
@NetsuNegi

2022-08-10 14:58 UTC, NetsuNegi commented on src/Ext/Building/Hooks.cpp
>  				pData->Factory_VehicleType = nullptr;
I think it maybe better if do that.

2022-08-12 08:48 UTC, Metadorius requested changes

2022-08-12 08:48 UTC, Metadorius commented on src/Ext/BuildingType/Body.cpp
> +	this->PowerPlantEnhancer_Powered.Read(exINI, pSection, "PowerPlantEnhancer_Powered");
Wrong tag name.

2022-08-12 08:48 UTC, Metadorius commented on src/Ext/WarheadType/Detonate.cpp
> +					canFire = canFire && (this->LaunchSW_IgnoreDesignators || SWTypeExt::HasDesignator(pSWExt, pHouse, cell));
```suggestion
					bool canFire = this->LaunchSW_IgnoreInhibitors || !SWTypeExt::HasInhibitor(pSWExt, pHouse, cell)
						&& (this->LaunchSW_IgnoreDesignators || SWTypeExt::HasDesignator(pSWExt, pHouse, cell));
```

2022-08-12 08:48 UTC, Metadorius commented on src/Ext/SWType/FireSuperWeapon.cpp
> +	}
```suggestion
		return true;
```

2022-08-12 08:55 UTC, Metadorius requested changes

2022-08-12 08:55 UTC, Metadorius commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK(0x6CDE40, SuperClass_Launch_Finale, 0x3)
```suggestion
DEFINE_HOOK(0x6CDE40, SuperClass_Place_FireExt, 0x3)
```

2022-08-12 08:55 UTC, Metadorius commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK(0x6CDE40, SuperClass_Launch_Finale, 0x3)
It is called `Place` in original code.

2022-08-12 08:55 UTC, Metadorius commented on src/Ext/Techno/Body.h
> +		virtual void InvalidatePointer(void* ptr, bool bRemoved) override{ }
```suggestion
		virtual void InvalidatePointer(void* ptr, bool bRemoved) override { }
```

2022-08-12 08:55 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +std::unordered_map<void*, ShieldClass*> ShieldClass::AnimsAndShields { };
How does this play with save/load? Also I would probably name this `ShieldAnimTracker`.

2022-08-12 08:55 UTC, Metadorius commented
@mevitar could you check if cloaking etc. plays nice with those changes to shields?

2022-08-28 05:33 UTC, chaserli commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
Another question here: should such a tracker be serialized somewhere?

2022-08-29 16:11 UTC, Starkku commented on src/Ext/Building/Hooks.cpp
>  		pExt->TypeExtData = BuildingTypeExt::ExtMap.Find(pType);
It might not be currently necessary. Feel free to remove or comment out for time being.

2022-08-29 16:55 UTC, Metadorius commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
I think you construct the tracker automatically when deserializing because you add each anim/shield pair to the map, no?

2022-09-03 13:49 UTC, chaserli commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
Yeah I assume so. Anyway, how can I verify if this method works as expected?

2022-09-03 16:48 UTC, Metadorius commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
Attach a debugger, save the game with one shield, place a breakpoint at constructor where it adds it to the map, load the game, observe for the hits.

2022-09-04 08:36 UTC, chaserli commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
Well it appears that the anims are removed from the map when reloading within the same session, thus even the anims are still attached to shielded objects, there's nothing in the map

2022-09-04 08:41 UTC, chaserli commented on src/New/Entity/ShieldClass.h
> +	static std::unordered_map<void*, ShieldClass*> ShieldAnimTracker;
In this case, I would like to use a brutal for loop temporarily and see how much that affects performance

2022-09-04 10:48 UTC, chaserli commented
This looks huge, should I detach the shield part to review/merge the rest first?

2022-09-14 19:49 UTC, Metadorius approved these changes

2022-09-14 19:50 UTC, merged