New condition when some TechnoTypes exist/nonexist of automatic self-destruction logic
Phobos-developers/Phobos pull request #726
Opened 2022-08-10 15:17 UTC by ststl-s

```ini
AutoDeath.Nonexist=                       ; list of TechnoType names
AutoDeath.Nonexist.House=owner  ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
AutoDeath.Exist=                              ; list of TechnoType names
AutoDeath.Exist.House=owner         ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
```

2022-09-18 14:10 UTC, Starkku requested changes
Idea is good but the code needs some changes. Maybe others could chime in on their suggestions for the INI key names, I put forward my two cents on the matter in a comment as well since I don't think the current ones are descriptive enough.

In an ideal world, having a switch for the 'TechnoType exists' condition that makes it require *all* of the listed TechnoTypes to be present for the condition to be fulfilled would be nice but I believe under the current system where it can check for Technos under more than one House, this would be complicated to implement and could behave oddly so I think omitting it would probably be fine.

2022-09-18 14:10 UTC, Starkku commented on docs/Whats-New.md
> +- New condition when some technotypes exist/nonexist of automatic self-destruction logic (by FlyStar)
*New condition for killing objects automatically when TechnoType(s) exist/don't exist*

2022-09-18 14:10 UTC, Starkku commented on src/Ext/Techno/Body.cpp
> +				KillSelf(pThis, howToDie);
I think this code could be simplified quite a lot. The lambda expression is essentially repeated for exist/does not exist conditions, when it could probably be reused by passing the TechnoType vector and AffectedHouses flags as params. Unless I am missing something that would crucially affect performance by doing it that way.

2022-09-19 04:51 UTC, ststl-s commented
> Idea is good but the code needs some changes. Maybe others could chime in on their suggestions for the INI key names, I put forward my two cents on the matter in a comment as well since I don't think the current ones are descriptive enough.
> 
> In an ideal world, having a switch for the 'TechnoType exists' condition that makes it require _all_ of the listed TechnoTypes to be present for the condition to be fulfilled would be nice but I believe under the current system where it can check for Technos under more than one House, this would be complicated to implement and could behave oddly so I think omitting it would probably be fine.

About the House setting temporarily reserved, is this dangerous? I haven't experimented a lot, just confirmed that it works.

2022-09-30 18:01 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +AutoDeath.TechnoExist.Houses=owner      ; Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
Also missing the `s` here at end of Techno**s** too.

2022-10-29 21:44 UTC, Starkku approved these changes

2022-10-29 22:08 UTC, merged

2022-10-30 09:09 UTC, chaserli commented
I didn't manage to give my review on this in time.
Basically you give too many new arguments on this specific feature, which makes the code looks _extrêmement lourde_, 
in this case I would rather suggest you guys wrap those into a new entity, like the AttachEffectType or PrismForwarding in Ares,
and see if it can work like an AttachEffect.

Same suggestion for other similar tags like the interceptor one