Refactor Harvester counter to improve performance
Phobos-developers/Phobos pull request #728
Opened 2022-08-17 16:27 UTC by chaserli

Detached from #723 ,  restore #628 , closes #603 

* Consider non-selected guarding state as harvesting miner (can subject to change). Returning chronominers will stop blinking the counter.

* Deprecated `TechnoTypeExt::ExtData::IsCountedAsHarvester` and merged the entire logic into `Harverster.Counted` in order to improve performance. Minor refactored related harvester-counter code.

2022-08-28 05:54 UTC, chaserli commented on src/Ext/House/Body.cpp
> +	for (auto pType : TechnoTypeExt::HarvesterTypes)
I got a problem here: When I tested with MO everything's fine, but when I test 
with my vanilla YR it gets an error here: either this `std::vector` or `pType` is some nonsense or `nullptr`

2022-09-03 16:11 UTC, Metadorius approved these changes

2022-09-03 16:11 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +		default:break;
```suggestion
		default: break;
```

2022-09-03 16:11 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +[[deprecated("Use Harvester_Counted directly.")]]
Why leave it in at all?

2022-09-03 16:11 UTC, Metadorius commented on src/Ext/TechnoType/Body.cpp
> +			if(!list.Contains(pItem))
```suggestion
			if (!list.Contains(pItem))
```

2022-09-03 16:13 UTC, Metadorius requested changes
Forgot to say, add yourself to authors of the features you fixed and if it was in a stable build - append the fix to the changelog.

2022-09-04 14:06 UTC, chaserli commented on src/Ext/TechnoType/Body.cpp
> +[[deprecated("Use Harvester_Counted directly.")]]
Removed. Ready to go with #721

2022-09-04 14:39 UTC, merged