Customizable Tooltip background
Phobos-developers/Phobos pull request #737
Opened 2022-08-30 17:21 UTC by secsome

In `rulesmd.ini`:
```ini
[SOMESIDE]
ToolTip.Background.Color=0,0,0      ; integer - R,G,B, defaults to [AudioVisual]->ToolTip.Background.Color
ToolTip.Background.Opacity=100      ; integer, ranged in [0, 100], defaults to [AudioVisual]->ToolTip.Background.Opacity
ToolTip.Background.BlurSize=0.0     ; float, defaults to [AudioVisual]->ToolTip.Background.BlurSize
```

Ready for test.

2022-08-30 17:29 UTC, Metadorius commented on src/Ext/Side/Body.h
> +		Valueable<int> ToolTip_Background_Transparency;
See PlacementPreview refactor PR, maybe you could fix the minor issues I pointed out (Belonit is locked out of that PR) and use the transparency level from there.

2022-08-30 17:35 UTC, secsome commented on src/Ext/Side/Body.h
> +		Valueable<int> ToolTip_Background_Transparency;
> See PlacementPreview refactor PR, maybe you could fix the minor issues I pointed out (Belonit is locked out of that PR) and use the transparency level from there.

The transparency here could be any specific integer ranged from 0 to 100, not just specific numbers.

2022-08-30 17:37 UTC, Metadorius commented on src/Ext/Side/Body.h
> +		Valueable<int> ToolTip_Background_Transparency;
Right, I think it could be good to have it as a new type?

2022-08-30 17:38 UTC, Starkku commented on src/Ext/Side/Body.h
> +		Valueable<int> ToolTip_Background_Transparency;
If it is fully opaque by default (value of 100) then call it Opacity, not Transparency. This also helps to distinguish it from the existing transparency controls for SHP drawing which is constrained to specific values.

2022-08-30 17:38 UTC, Metadorius commented
I'd suggest to add the same tag to AudioVisual for default values. Also not sure if the second dot is needed but that's not critical.

2022-08-30 17:38 UTC, secsome commented on src/Ext/Side/Body.h
> +		Valueable<int> ToolTip_Background_Transparency;
> If it is fully opaque by default (value of 100) then call it Opacity, not Transparency. This also helps to distinguish it from the existing transparency controls for SHP drawing which is constrained to specific values.

I see

2022-08-30 17:46 UTC, secsome commented
> I'd suggest to add the same tags to AudioVisual for default values. Also not sure if the second dot is needed but that's not critical.

We won't have too many sides so I doubt if it's necessary to add an extra tag

2022-08-30 17:54 UTC, Metadorius commented
Confirmed to be working by Speeder.

2022-08-30 17:55 UTC, Metadorius commented on src/Ext/Side/Body.h
> +			, ToolTip_Background_Color { {0,0,0} }
```suggestion
			, ToolTip_Background_Color { { 0, 0, 0 } }
```

2022-09-01 03:18 UTC, secsome commented
Ready  to merge.

2022-09-01 15:25 UTC, Speederovsky commented
Opacity and custom background colors work. Blur also works now, but even when set at 1 it can noticeably decrease performance depending on your setup, and the bigger the extended tooltip, the stronger it gets. The issue with altered harvester count & power delta text colors appears to be fixed as well.

2022-09-03 15:42 UTC, Metadorius requested changes
Well the blur is impressive, but considering it tanks performance a lot I would say that if you want to keep that at least add an RA2MD switch so that the users are able to toggle it off and don't lose performance over a tooltip, lol. Also add a warning that it is resource intensive.

2022-09-03 15:42 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +			, ToolTip_Background_Color { {0, 0, 0} }
```suggestion
			, ToolTip_Background_Color { { 0, 0, 0 } }
```

2022-09-03 15:42 UTC, Metadorius commented on src/Ext/Rules/Body.h
> +			, ToolTip_Background_BlurSize { 0.f }
```suggestion
			, ToolTip_Background_BlurSize { 0.0f }
```

2022-09-14 19:51 UTC, Metadorius commented
![image](https://user-images.githubusercontent.com/17500545/190249078-cfe8c532-971f-4487-9d41-870b15b4a621.png)
No @secsome, you still didn't implement a switch.

2022-09-15 03:10 UTC, secsome commented
> ![image](https://user-images.githubusercontent.com/17500545/190249078-cfe8c532-971f-4487-9d41-870b15b4a621.png) No @secsome, you still didn't implement a switch.

Just set `BlurSize=0.0`, also the default value, will disable the blur effect.

2022-09-15 07:46 UTC, secsome commented
`[RA2MD]>[Phobos]>ToolTipBlur` implemented

2022-09-15 08:38 UTC, Metadorius approved these changes
Fix the stuff I pointed out and then it could be merged.

2022-09-15 08:38 UTC, Metadorius commented on docs/User-Interface.md
> +ToolTip.Background.BlurSize=0.0     ; float, defaults to [AudioVisual]->ToolTip.Background.BlurSize
Defaults should be explicitly listed too.

2022-09-15 08:38 UTC, Metadorius commented on docs/User-Interface.md
> +The blur effect is resource intensive. Please make sure if you want to enable this effect. Leave it to 0.0 to disable this effect.
```suggestion
The blur effect is resource intensive. Please make sure you really want to enable this effect, otherwise leave it to 0.0 so it stays disabled.
```

2022-09-15 08:38 UTC, Metadorius commented on docs/User-Interface.md
> +ToolTipBlur=false ; boolean, whether the blur effect of tooltips will be enabled.
```suggestion
ToolTipBlur=false  ; boolean, whether the blur effect of tooltips will be enabled.
```

2022-09-15 08:38 UTC, Metadorius commented on docs/User-Interface.md
> +- Also, the background color and opacity of tooltips can be customized by player's side.
```suggestion
- The background color and opacity of tooltips can now be customized globally or per side.
```

2022-09-15 08:38 UTC, Metadorius commented on CREDITS.md
> +  - Custom tooltip background
```suggestion
  - Customizable tooltip background
```

2022-09-15 08:38 UTC, Metadorius commented on src/Ext/Rules/Body.cpp
> +
```suggestion
```

2022-09-16 13:05 UTC, merged