Fixed unit playing crashing voice when crashing after being attacked by locomotor warhead
Phobos-developers/Phobos pull request #758
Opened 2022-09-20 15:31 UTC by NetsuNegi

This is a vanilla bug, when a unit begin to crashing after attacked by locomotor warhead, it will play crashing voice and crashing sound. Now it has been fixed, won't play that again.

2022-09-30 18:27 UTC, Starkku requested changes
Code looks fine, some minor nitpicks that should be addressed though.

2022-09-30 18:27 UTC, Starkku commented on CREDITS.md
> +   - Fixed unit will play crash voice when crashing after attacked by locomotor warhead
Needs spelling fixes. F.ex

`Fixed unit playing crashing voice when crashing after being attacked by locomotor warhead`

2022-09-30 18:27 UTC, Starkku commented on docs/Fixed-or-Improved-Logics.md
> +- Fixed unit will play crash voice when crashing after attacked by locomotor warhead.
Same as previous comment.

2022-09-30 18:27 UTC, Starkku commented on src/Misc/Hooks.BugFixes.cpp
> +DEFINE_HOOK(0x4DACF3, FootClass_CrashingVoice, 0x6)
Change hook name to `FootClass_AI_CrashingVoice` to match the convention used elsewhere in Phobos codebase (`ClassName_FunctionName_Application/Purpose`).

2022-10-01 01:09 UTC, NetsuNegi commented
> Code looks fine, some minor nitpicks that should be addressed though.

Finished

2022-10-11 19:44 UTC, Metadorius approved these changes
Looks good to me, update and make sure all checks pass and then it can be merged.

2022-10-12 06:28 UTC, chaserli requested changes
I don't know, I actually don't even consider it a bug

2023-01-18 01:39 UTC, closed without merging