Custom SpyEffects
Phobos-developers/Phobos pull request #759
Opened 2022-09-21 22:30 UTC by MortonPL

### Spy Effects

- Additional espionage bonuses can be toggled with `SpyEffects.Custom`.
  - `SpyEffects.VictimSuperWeapon` instantly launches a Super Weapon for the owner of the infiltrated building at building's coordinates.
  - `SpyEffects.InfiltratorSuperWeapon` behaves the same as above, with the Super Weapon's owner being the owner of the spying unit.

In `rulesmd.ini`:
```ini
[SOMEBUILDING]                     ; BuildingType
SpyEffects.Custom=false            ; boolean
SpyEffects.VictimSuperWeapon=      ; SuperWeaponType
SpyEffects.InfiltratorSuperWeapon= ; SuperWeaponType
```

```{warning}
The following Super Weapon types are supported:
`Type=LightningStorm`                     NO
`Type=MultiMissile`                       NO
`Type=PsychicDominator`                   NO
`Type=ChronoSphere`                       NO
`Type=ChronoWarp`                         NO
`Type=IronCurtain` and `Type=ForceShield` YES
`Type=GeneticConverter`                   YES
`Type=ParaDrop` and `Type=AmerParaDrop`   NO
`Type=SpyPlane`                           NO
`Type=PsychicReveal`                      YES
`Type=SonarPulse` (Ares)                  YES
`Type=GenericWarhead` (Ares)              YES
`Type=UnitDelivery` (Ares)                YES
`Type=Firestorm` (Ares)                   YES
`Type=HunterSeeker` (Ares)                YES
`Type=DropPod` (Ares)                     YES
`Type=EMPulse` (Ares)                     YES
`Type=Battery` (Ares)                     YES
```

2022-09-30 18:22 UTC, Starkku requested changes
Code looks okay to me. There's couple of small changes that should probably be done though.

2022-09-30 18:22 UTC, Starkku commented on src/Ext/Building/Hooks.cpp
> +	GET_STACK(HouseClass*, pInfiltratorHouse, STACK_OFFS(0x14, 0x4));
Reminder to fix the deprecated `STACK_OFFS` macro when rebasing/merging `develop` before merging PR.

E.g `STACK_OFFS(0x14, 0x4)` -> `STACK_OFFSET(0x14, -0x4)`.

2022-09-30 18:22 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +`Type=Battery` (Ares)                     YES
Gonna have to rethink how to format this, line breaks are not currently preserved making it very hard to read.

![image](https://user-images.githubusercontent.com/1392346/193332864-1a3cc6a1-9890-4102-af3d-a9e44d7b4f4d.png)

2022-09-30 18:22 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +`Type=Battery` (Ares)                     YES
Ditto.

2022-10-01 18:22 UTC, MortonPL commented on docs/New-or-Enhanced-Logics.md
> +`Type=Battery` (Ares)                     YES
Would something like this be enough?
![image](https://user-images.githubusercontent.com/23420063/193422966-8a933f8e-5869-442b-8e90-c6e316e2a708.png)

2022-10-01 19:30 UTC, MortonPL commented on docs/New-or-Enhanced-Logics.md
> +`Type=Battery` (Ares)                     YES
Update: the newest #760 commit makes all SW types supported, making this warning unnecessary. Removed.

2022-10-09 22:32 UTC, Metadorius commented on src/Ext/Building/Hooks.cpp
> +	R->EAX<int>(0x77777777);
What's that `0x77777777`?

2022-10-09 22:52 UTC, MortonPL commented on src/Ext/Building/Hooks.cpp
> +	R->EAX<int>(0x77777777);
See the comments for hooks.

Ares has a hook at `0x4571E0` (the beginning of BuildingClass::Infiltrate) and completely overwrites the function. Our logic has to be executed at the end (`0x4575A2`). The hook there assumes that registers have the exact content they had in the beginning (when Ares hook started, executed, and jumped) in order to work when Ares logic is used.

However, this will fail if Ares is *not* involved, because by the time we reach our hook, the registers will be different and we'll be reading garbage. That's why there is a second hook at `0x45759D`, which is only executed when Ares doesn't jump over this function. There, we execute our custom logic and then use EAX (which isn't used later, so it's safe to write to it) to "mark" that we're done with `0x77777777`. This way, when we reach the other hook, we check for this *very specific* value to prevent spy effects from happening twice.

The value itself doesn't matter, it just needs to be unique enough to not be accidentally produced by the game there.

2022-10-11 16:32 UTC, Metadorius approved these changes
Is there really a point in having a toggle? Otherwise LGTM.

2022-10-11 17:36 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +SpyEffects.Custom=false            ; boolean
Disregard that, didn't know that's inherited from Ares...

2022-10-11 17:39 UTC, merged

2022-11-05 10:11 UTC, chaserli reviewed
ehhhhhh

2022-11-05 10:11 UTC, chaserli commented on src/Ext/Building/Body.cpp
> +			pSuper->Launch(CellClass::Coord2Cell(pBuilding->Location), pVictimHouse->IsControlledByHuman());
Did you even test this? How could it work? Did you only test with charged SW?
I assume you were not launching for real, since otherwise normal click fire would suffice. So the SWs you wanted to fire were most likely virtually charged and not manually launchable.