Super Weapons launching Super Weapons
Phobos-developers/Phobos pull request #760
Opened 2022-09-21 22:32 UTC by MortonPL

### Next

Super Weapons can now launch other Super Weapons at the same target. Launched types can be additionally randomized using the same rules as with LimboDelivery.

In `rulesmd.ini`:
```ini
[SOMESW]                        ; Super Weapon
SW.Next=                        ; List of Super Weapons
LimboDelivery.RollChances=      ; List of percentages.
LimboDelivery.RandomWeightsN=   ; List of integers.
```

2022-09-30 08:49 UTC, chaserli requested changes
Speaking of the discussion of SW handled by Ares/Phobos, I think maybe you can add a check to see if it's handled by Ares or not at 0x6CC390, since it will be executed after Ares' hook. And if Ares didn't handle it, you do `SWTypeExt::FireSuperWeaponExt(pSuper, *pCell)` at 0x6CC390, otherwise at 0x6CDE40. Will this work?

2022-09-30 08:49 UTC, chaserli commented on src/Ext/SWType/Body.cpp
> +	this->SW_Next_IgnoreInhibitors.Read(exINI, pSection, "SW.Next.IgnoreInhibitors");
I don't see under which circumstances  should these be ignored

2022-09-30 08:49 UTC, chaserli commented on src/Ext/WarheadType/Detonate.cpp
> +						if (this->LaunchSW_RealLaunch)
I'm not quite sure, is it safe?

2022-09-30 08:49 UTC, chaserli commented on src/Ext/SWType/FireSuperWeapon.cpp
> +void Launch(HouseClass* pHouse, SWTypeExt::ExtData* pLauncherTypeExt, SuperWeaponTypeClass* pLaunchedType, const CellStruct& cell)
The name confused me for a second at first glimpse

2022-09-30 08:49 UTC, chaserli commented on src/Ext/SWType/FireSuperWeapon.cpp
>  			LimboCreate(abstract_cast<BuildingTypeClass*>(this->LimboDelivery_Types[i]), pHouse, id);
I don't think casting is needed here since you already changed the vector type

2022-10-01 18:39 UTC, MortonPL commented on src/Ext/WarheadType/Detonate.cpp
> +						if (this->LaunchSW_RealLaunch)
`SuperClass::Reset()` only resets timer / charge and, according to the decompile, "animation", though I haven't observed anything about the latter.
If the user doesn't want a "real" launch, the charge imo should not be reset.

2022-10-01 18:41 UTC, MortonPL commented on src/Ext/SWType/Body.cpp
> +	this->SW_Next_IgnoreInhibitors.Read(exINI, pSection, "SW.Next.IgnoreInhibitors");
Warhead `LaunchSW` also has `IgnoreInhibitors`. That, and we already allow the user to ignore designators, so inhibitors shouldn't be an exception.

2022-10-01 18:43 UTC, MortonPL commented on src/Ext/SWType/FireSuperWeapon.cpp
>  			LimboCreate(abstract_cast<BuildingTypeClass*>(this->LimboDelivery_Types[i]), pHouse, id);
True, this will be corrected.

2022-10-01 18:48 UTC, MortonPL commented on src/Ext/SWType/FireSuperWeapon.cpp
> +void Launch(HouseClass* pHouse, SWTypeExt::ExtData* pLauncherTypeExt, SuperWeaponTypeClass* pLaunchedType, const CellStruct& cell)
Why? Both Ares and Phobos use "launch" and "fire" interchangeably when describing SW usage (i.e. already existing `LaunchSW`).

2022-10-02 07:16 UTC, chaserli commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK_AGAIN(0x6CC390, SuperClass_Place_FireExt, 0x6)
```suggestion
bool SWLaunchHandledByAres=true;
DEFINE_HOOK(0x6CC390, SuperClass_Place_FireExt, 0x6)
{
    GET(SuperClass* const, pSuper, ECX);
	GET_STACK(CellStruct const* const, pCell, 0x4);
	SWLaunchHandledByAres=false;
	SWTypeExt::FireSuperWeaponExt(pSuper, *pCell);
	return 0;
}

DEFINE_HOOK(0x6CDE40, SuperClass_Place_FireExt, 0x4)
{
	GET(SuperClass* const, pSuper, ECX);
	GET_STACK(CellStruct const* const, pCell, 0x4);
	// GET_STACK(bool const, isPlayer, 0x8);
	if(!SWLaunchHandledByAres)
	    SWTypeExt::FireSuperWeaponExt(pSuper, *pCell);
	return 0;
}
```
I was thinking about this, otherwise you'll fire your ext twice, no?

2022-10-02 16:37 UTC, MortonPL commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK_AGAIN(0x6CC390, SuperClass_Place_FireExt, 0x6)
SW is fired once (tested with all types), there is no need for an additional check. 
As for hook size, there's not much choice, as it's followed by a byte of padding and a jump table.

2022-10-10 05:55 UTC, chaserli requested changes

2022-10-10 05:55 UTC, chaserli commented on src/Ext/SWType/Body.cpp
> +	this->SW_Next_IgnoreInhibitors.Read(exINI, pSection, "SW.Next.IgnoreInhibitors");
Well in that case it would be better to set both default value to flase imo

2022-10-10 05:55 UTC, chaserli commented on src/Ext/SWType/Body.h
> +		ValueableVector<SuperWeaponTypeClass*> SW_Next;
I changed my `LaunchSW` to `ValueableIdxVector<SuperWeaponTypeClass>` since Ares used this one too for BuildingType's SuperWeapons, and I don't quite understand why Phobos still use DVC for that one.

It's up to you, I don't think it makes too much difference other than avoiding a search through all SWTypes

2022-10-10 05:55 UTC, chaserli commented on src/Ext/SWType/Hooks.cpp
> +DEFINE_HOOK_AGAIN(0x6CC390, SuperClass_Place_FireExt, 0x6)
If it doesn't pose any problem then it should be fine, perhaps

2022-10-10 05:55 UTC, chaserli commented on src/Ext/SWType/FireSuperWeapon.cpp
> +void Launch(HouseClass* pHouse, SWTypeExt::ExtData* pLauncherTypeExt, SuperWeaponTypeClass* pLaunchedType, const CellStruct& cell)
I mean, exactly because of that it made me believe this `Launch` function was a routine from vanilla code.

2022-10-10 05:55 UTC, chaserli commented on src/Ext/SWType/Body.h
> +		ValueableVector<ValueableVector<int>> SW_Next_RandomWeightsData;
`std::vector<ValueableVector<`?

2022-10-11 16:30 UTC, merged