Override Target Under EMP Attack Behavior
Phobos-developers/Phobos pull request #769
Opened 2022-10-03 04:51 UTC by FS-21

Overrides a part of the vanilla YR logic for allowing units to use a different weapon if the target is under EMP effect.

In `rulesmd.ini`:

[SOMETECHNO]             ; TechnoType
ForceWeapon.UnderEMP=-1  ; integer. 0 for primary weapon, 1 for secondary weapon, -1 to disable

2022-10-03 04:54 UTC, FS-21 commented
![forceweapon_emp](https://user-images.githubusercontent.com/1371539/193504052-a1eafecf-483d-44bd-a5ae-890620047c95.gif)

2022-10-14 12:39 UTC, MortonPL reviewed
Looks okay to me, nothing major. Out of curiosity - would this work on `Gunner` units and weapon indices past 1?

2022-10-14 12:39 UTC, MortonPL commented on docs/Whats-New.md
> +- Override target under EMP attack behavior (By FS-21)
Should be moved from 0.3 to 0.3.1.

2022-10-16 14:57 UTC, FS-21 commented on src/Ext/Techno/Hooks.Firing.cpp
> +							((pTarget->WhatAmI() == AbstractType::Unit || pTarget->WhatAmI() == AbstractType::Aircraft) && pTargetType->Organic)))))
I never tried because that wasn't the scope of the feature sorry.

2024-05-19 13:04 UTC, Coronia commented
I'm not sure if we should also force weapon for targets that immune to EMP here. Maybe split that to another standalone weapon filter?

2024-08-29 21:19 UTC, FS-21 commented
> I'm not sure if we should also force weapon for targets that immune to EMP here. Maybe split that to another standalone weapon filter?

I agree, I just refactorized the code a bit (is a small feature but is more readable now) and I feel the EMP immunity (and the other opposite conditions) can be a standalone case.

2024-09-18 00:19 UTC, mevitar commented
Is it really needed when AttachEffect.RequiredTypes= exists? Just put an AE on the EMPed target.

Still, i tested it, seems to be working fine. Didn't notice any conflicts with other targeting override mechanisms (like the mentioned AttachEffect.RequiredTypes= ), and they can even go in hand with them (like using NoAmmo= normally to make the unit switch to secondary when runs out of ammo, but it will still switch to secondary against the EMPed target even on full ammo if ForceWeapon.UnderEMP=1 is present).

2024-10-16 13:26 UTC, Coronia requested changes

2024-10-16 13:26 UTC, Coronia commented on docs/New-or-Enhanced-Logics.md
> +
should just move the document to the same place of other ForceWeapon tags

2025-03-10 04:09 UTC, TaranDahl approved these changes
lgtm

2025-03-10 04:54 UTC, CrimRecya approved these changes
Simple and great.

2025-03-11 08:22 UTC, merged