Display the money harvesters/slaves gathered when docking
Phobos-developers/Phobos pull request #775
Opened 2022-10-16 10:34 UTC by chaserli

https://user-images.githubusercontent.com/9932846/196030600-117775f1-e3a1-43c3-a416-2fdd0f074e25.mp4

2022-10-17 18:40 UTC, MortonPL requested changes
I'd suggest to rename tags (`DisplayIncome` maybe?), because they support more than refunds, which may be confusing.

2022-10-18 06:35 UTC, chaserli commented
Known issue atm: If storage logic is enabled nothing is popped up on the screen yet the money counter still increases.

2022-10-18 06:38 UTC, chaserli commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +
This code is just commented out to tell the people that we actually know where the issue is. It doesn't actually run.

2022-10-24 13:27 UTC, chaserli commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +
I don't want to fix it anymore, however it might be useful to point out where the problem was in case someone gets interested in fixing it later

2022-10-29 21:59 UTC, Starkku requested changes
Some minor suggestions, a question about including unrelated code but otherwise looks good to me.

2022-10-29 21:59 UTC, Starkku commented on docs/User-Interface.md
> +- `DisplayIncome` can be set to display the amount of credits acquired when a building is grinding /receiving ore dump / getting sold , or when a collector is collecting a money crate.
`grinding /receiving ore dump` -> `grinding / receiving ore dump`

2022-10-29 21:59 UTC, Starkku commented on docs/Fixed-or-Improved-Logics.md
> -  - `Grinding.DisplayRefund` can be set to display the amount of credits acquired upon grinding on the building. Multiple refunded objects within a short period of time have their refund amounts coal
Could potentially link here to the section in UI for customizing the income display but it isn't particularly pertinent.

2022-10-29 21:59 UTC, Starkku commented on src/Ext/Building/Body.cpp
> +void BuildingExt::ExtData::DisplayMoneyString()
Call this `DisplayAccumulatedIncomeString` or `DisplayIncomeString` instead to make the connection between it and `AccumulatedIncome` more apparent.

2022-10-29 21:59 UTC, Starkku commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +#ifndef USE_UNFINISHED_CORRECT_FIX_FOR_JUMPJETUNIT_TURN
Why is any of the stuff in this file included in this, completely unrelated PR?

2022-10-30 05:59 UTC, chaserli commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +#ifndef USE_UNFINISHED_CORRECT_FIX_FOR_JUMPJETUNIT_TURN
I understand the irrelevancy, but I no longer want to fix this issue again and hoping someone does it in the future, as I finally figured out that jumpjet units stuck at FACING fireerror, which makes them unable to fire or turn.
I might clean my disk shortly and don't want to keep unpushed code on my disk.

2022-12-30 16:21 UTC, Starkku requested changes
Some stuff that could probably be addressed still.

2022-12-30 16:21 UTC, Starkku commented on src/Ext/Building/Hooks.cpp
> +}
There are enough of the hooks related to this that they could probably be placed in a separate file.

2022-12-30 16:21 UTC, Starkku commented on docs/User-Interface.md
> +### Visual indication of income from a building
Considering this concerns more than buildings, this title isn't particularly accurate.

2023-01-29 13:45 UTC, chaserli commented
Removed the money string upon money crate collection since it's really unnecessary and confusing

2023-02-05 18:09 UTC, MortonPL approved these changes

2023-02-13 12:30 UTC, merged