Allowed usage of `AlternateFLH%d` for vehicles in opentopped transport
Phobos-developers/Phobos pull request #783
Opened 2022-10-27 04:13 UTC by chaserli

Units will use `AlternateFLH%d` as the FLH in opentopped transport.
Need testing of whether :
1. All original FLHs are correct (units not in opentopped transport)
2. AlternateFLHs are respected 
3. Any exception or restriction exist

2022-10-29 22:13 UTC, Starkku requested changes
Some minor suggestions regarding spelling and a thought about the way this is implemented.

By the looks of this, this is just a simple vtable function call swap and doesn't interfere with #784 at all, and would in fact work in tandem with it (regardless of which one gets merged first) but that would probably have to be tested anyways in the future.

2022-10-29 22:13 UTC, Starkku commented on CREDITS.md
> +   - `AlternateFLH` of vehicles in opentopped transport.
Capitalize `OpenTopped` since it refers to INI key.

2022-10-29 22:13 UTC, Starkku commented on docs/Fixed-or-Improved-Logics.md
> +- Allowed usage of `AlternateFLH%d` of vehicles in opentopped transport.
Capitalize `OpenTopped` since it refers to INI key.

2022-10-29 22:13 UTC, Starkku commented on docs/Whats-New.md
> +- Allowed usage of `AlternateFLH%d` of vehicles in opentopped transport. (by Trsdy)
Capitalize `OpenTopped` since it refers to INI key.

2022-10-29 22:13 UTC, Starkku commented on src/Ext/Techno/Hooks.Firing.cpp
> +DEFINE_JUMP(VTABLE, 0x7F5D20, 0x523250); // Redirect UnitClass::GetFLH to InfantryClass::GetFLH (used to be TechnoClass::GetFLH)
This could potentially backfire if anyone adds bespoke logic to InfantryClass regarding this in the future. A pretty big if so I guess it is fine for time being, alternate way would've been to do it like the health-related checks in `Techno\Hooks.Shield.cpp` with the wrappers, in which you'd do something similar to `InfantryClass::GetFLH()`.

2022-10-30 06:08 UTC, chaserli commented on src/Ext/Techno/Hooks.Firing.cpp
> +DEFINE_JUMP(VTABLE, 0x7F5D20, 0x523250); // Redirect UnitClass::GetFLH to InfantryClass::GetFLH (used to be TechnoClass::GetFLH)
In case that happens in the future, we can revert this and do as you put it.
As for that AlternateFLH%d>5 PR, it was in `TechnoClass::GetFLH` anyway so it doesn't actually interfere with this one imo

2022-12-23 16:13 UTC, closed without merging