JumpjetTurnToTarget: The correct fix, and OmniFire.TurnToTarget
Phobos-developers/Phobos pull request #799
Opened 2022-11-15 14:00 UTC by chaserli

This is finally the **correct** fix for the jumpjet facing bug, but I think maybe this is not necessary for most of people

Can consider merging this after v0.4 release

besides, according to @Metadorius 's suggestion
### Make units try turning to target when firing with `OmniFire=yes`
Recommended for jumpjets
In `rulesmd.ini`:
```ini
[SOMEUNIT]                ; UnitType
OmniFire.TurnToTarget=no  ; boolean
```

2022-12-30 16:27 UTC, Starkku requested changes
The code looks mostly okay I think, haven't tested if it does what it is supposed to though. Couple of nitpicks I noticed and mentioned.

2022-12-30 16:27 UTC, Starkku commented on src/Ext/WeaponType/Body.h
> +		Valueable<bool> OmniFireTurnToTarget;
Underscore where the . is in INI name.

2022-12-30 16:27 UTC, Starkku commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +DEFINE_HOOK(0x736EE9, UnitClass_UpdateFiring_Ferr_OK_OmniFire_Facing, 0x6)
Try to avoid underscore spam in hook names and generally just stick to `Classname_Functionname_Purpose/Scope` where possible.

2023-02-04 17:51 UTC, Metadorius approved these changes
Only some minor stuff to fix, LGTM otherwise.

2023-02-04 17:51 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +OmniFire=yes
Do you think including vanilla tags should be done? I am not sure of that

2023-02-04 17:51 UTC, Metadorius commented on docs/Whats-New.md
> +- `[JumpjetControls]->TurnToTarget` and `JumpjetTurnToTarget` are obsolete. Jumpjet units who fire `OmniFire=no` weapons **always** turn to targets as other units do.
may add a migration script line to comment that out

2023-02-04 17:51 UTC, Metadorius commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +		pThis->SecondaryFacing.SetDesired(tgtDir);
```suggestion

	if (pType->Turret && !pType->HasTurret) // 0x736F92
	{
		pThis->SecondaryFacing.SetDesired(tgtDir);
	}
```

2023-02-04 17:51 UTC, Metadorius commented on src/Ext/Unit/Hooks.Jumpjet.cpp
> +			if (jjLoco->State != JumpjetLocomotionClass::State::Cruising)
```suggestion
		if (auto jjLoco = locomotion_cast<JumpjetLocomotionClass*>(pThis->Locomotor))
		{
			//wrong destination check and wrong Is_Moving usage for jumpjets, should have used Is_Moving_Now
			if (jjLoco->State != JumpjetLocomotionClass::State::Cruising)
```

2023-02-04 17:52 UTC, Metadorius commented
Also I assume it does work correctly with all cases of turreted/unturreted jumpjets, right?

2023-02-05 04:48 UTC, chaserli commented on docs/New-or-Enhanced-Logics.md
> +OmniFire=yes
It means that it only works if `OmniFire=yes`

2023-02-05 04:48 UTC, chaserli commented on docs/Whats-New.md
> +- `[JumpjetControls]->TurnToTarget` and `JumpjetTurnToTarget` are obsolete. Jumpjet units who fire `OmniFire=no` weapons **always** turn to targets as other units do.
ctrl-f JumpjetTurnToTarget, delete, done

2023-02-05 04:52 UTC, chaserli commented
> Also I assume it does work correctly with all cases of turreted/unturreted jumpjets, right?

Turreted jumpjets won't turn the primary facing as they shouldn't do it anyway, since ground units don't.

2023-02-05 06:22 UTC, chaserli commented
Also the entire FACING FireError code is rewritten, since no one test individually and I haven't observed any anormalies myself we'll have to test it in future versions.

2023-02-05 06:23 UTC, merged