Crates generate fix
Phobos-developers/Phobos pull request #809
Opened 2022-12-03 12:05 UTC by Super-StarX

Fixed the bug that the crates has a higher chance of creating at the edge of the map.

2022-12-05 03:54 UTC, chaserli requested changes
Monte-Carlo? Mind explaining why this gives better probability distribution?

2022-12-05 03:54 UTC, chaserli commented on src/Misc/Hooks.BugFixes.cpp
> +	auto result = Matrix3D::MatrixMultiply(TacticalClass::Instance->IsoTransformMatrix, Location);
you could have done the math manually here, this matrix seems to be 128/30*[1,2;-1,2]

2022-12-05 03:54 UTC, chaserli commented on src/Misc/Hooks.BugFixes.cpp
> +		auto SpeedType = pCell->LandType == LandType::Water ? SpeedType::Float : SpeedType::Track;
can we have a new tag for land-only crate spawn?

2022-12-05 07:15 UTC, Super-StarX commented
> game considers the map as a horizontal rectangle parallel to the screen, but the map is inclined at 45°. So, the map will put some crates in the place without a cell (not in map), and then put them into the map through NearByLocation, which results in more crates generated at the edge of the map. This is obviously unreasonable.

2022-12-05 11:01 UTC, Belonit commented on src/Misc/Hooks.BugFixes.cpp
> +		auto SpeedType = pCell->LandType == LandType::Water ? SpeedType::Float : SpeedType::Track;
@chaserli I think this is a topic for a separate pull request.

2022-12-05 16:26 UTC, chaserli requested changes

2023-01-03 12:46 UTC, chaserli requested changes
First of all, I appreciate your willingness to contribute on this topic and the identification of such an anomaly. However your basic assumption wasn't exactly correct in your explanation of non-uniform sampling when spawning crates:

In my opinion it's hard to assert that the problem was due to isometric projection in a probabilistic point of view. If you have some basic knowledge of probability, [rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) is the way used in the vanilla routine, and proceed like that is the easiest way. The usage of `MapCoordBound` in the vanilla routine was therefore not wrong. The only missing part is checking whether the candidate cell is within the usable region.

If you no longer want to contribute to this PR, I can commit that directly and close this one.

2023-01-05 07:17 UTC, Super-StarX commented
> First of all, I appreciate your willingness to contribute on this topic and the identification of such an anomaly. However your basic assumption wasn't exactly correct in your explanation of non-uniform sampling when spawning crates:
> 
> In my opinion it's hard to assert that the problem was due to isometric projection in a probabilistic point of view. If you have some basic knowledge of probability, [rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) is the way used in the vanilla routine, and proceed like that is the easiest way. The usage of `MapCoordBound` in the vanilla routine was therefore not wrong. The only missing part is checking whether the candidate cell is within the usable region.
> 
> If you no longer want to contribute to this PR, I can commit that directly and close this one.

I don't quite understand your meaning. You can use Chinese in your private chat

2023-01-05 11:33 UTC, chaserli commented
> 
You can check my implementation regarding this issue here #818 
I gave my explanation, you can check it out from here https://discord.com/channels/338055131666972683/773636942775582720/1060219669908308080

2023-01-05 14:59 UTC, Super-StarX commented
> > 
> 
> You can check my implementation regarding this issue here #818 I gave my explanation, you can check it out from here https://discord.com/channels/338055131666972683/773636942775582720/1060219669908308080
Sorry I still not understand. It seems that you want to solve the problem that crate will generate on water, which may be useful in some land battle maps with less water. 
What I try to solve:
![image](https://user-images.githubusercontent.com/42611604/210809919-0f011939-b239-4a1d-b07b-1e96a8f7a476.png)

2023-01-05 15:19 UTC, chaserli commented
> What I try to solve:

You were right just until this point, but you did nothing but the isometric projection and forgot to limit it to the actual **visible** area, which may eventually take cell height/slope/etc into account.
Let's say before the fix, if you create a large map with medium size visible area, and draw a histogram of spawned crates' locations, you'll get something like this: 
![image](https://user-images.githubusercontent.com/9932846/210812217-b09ebbb7-a05f-4960-8570-1ec0b1e4dbe6.png)
Your so-called "error generation by WW area" fall back to (0,0) after being projected by `NearByLocation`, and all other off-visible-map region fall back to the 4 boundaries.

So after your fix, those off-map regions will still be taken into account, which results in a higher probability at the boundaries. The issue is still not resolved.

So there's 2 way: 
1: Use `VisibleRect` rather than `MapRect` for the isometric projection, just as I said previously. And you can just do the matrix multiplication yourself since it's already known.
2. Keep the original random point generation method and take advantage of the `while(true)` loop with the simple math fact that I said here https://discord.com/channels/338055131666972683/773636942775582720/1060225075187568650
#818 uses such an idea and can ensure a uniform distribution over the desirable region
![image](https://user-images.githubusercontent.com/9932846/210814867-e6d4b818-eb7b-498f-a87a-7e12225ad5d1.png)


If you still didn't get it, maybe I should write down the demonstration for you

2023-01-07 11:55 UTC, Super-StarX commented
> > What I try to solve:
> 
> You were right just until this point, but you did nothing but the isometric projection and forgot to limit it to the actual **visible** area, which may eventually take cell height/slope/etc into account. Let's say before the fix, if you create a large map with medium size visible area, and draw a histogram of spawned crates' locations, you'll get something like this: ![image](https://user-images.githubusercontent.com/9932846/210812217-b09ebbb7-a05f-4960-8570-1ec0b1e4dbe6.png) Your so-called "error generation by WW area" fall back to (0,0) after being projected by `NearByLocation`, and all other off-visible-map region fall back to the 4 boundaries.
> 
> So after your fix, those off-map regions will still be taken into account, which results in a higher probability at the boundaries. The issue is still not resolved.
> 
> So there's 2 way: 1: Use `VisibleRect` rather than `MapRect` for the isometric projection, just as I said previously. And you can just do the matrix multiplication yourself since it's already known. 2. Keep the original random point generation method and take advantage of the `while(true)` loop with the simple math fact that I said here https://discord.com/channels/338055131666972683/773636942775582720/1060225075187568650 #818 uses such an idea and can ensure a uniform distribution over the desirable region ![image](https://user-images.githubusercontent.com/9932846/210814867-e6d4b818-eb7b-498f-a87a-7e12225ad5d1.png)
> 
> If you still didn't get it, maybe I should write down the demonstration for you

Oh, it's my fault. I have actually made changes according to the first tip you list, but I forgot to push. I'm not very proficient in the operation of Git XD

2023-01-07 12:57 UTC, chaserli commented
> Oh, it's my fault. I have actually made changes according to the first tip you list, but I forgot to push. I'm not very proficient in the operation of Git XD

Even if you did, it shouldn't be simply replacing MapRect with VisibleRect. The range is incorrect. You can check my implementation at #818 and continue the discussion there.

2023-01-07 12:57 UTC, closed without merging