Warhead effects Verses change & custom tint effects
Phobos-developers/Phobos pull request #826
Opened 2023-01-22 23:29 UTC by Starkku

Phobos-introduced Warhead effects like shield modifiers, critical hits, disguise & mind control removal now require Warhead `Verses` to affect target to apply unless `EffectsRequireVerses` is set to false. Shield armor type is used if target has an active shield that cannot be penetrated by the Warhead.

-----------------------------

### Custom tint effects

- Some things like `Psychedelic=true` Warheads and Iron Curtain or airstrike target flare tint the affected objects with color. This effect can now be applied arbitrarily via any properly detonated Warhead via `Tint.Color` for duration of `Tint.Duration` frames. The colors of any active custom tints on an object are applied cumulatively, after the stock tint effects.
  - `Tint.VisibleToHouses` can be used to customize which houses can see the tint effect.

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]             ; Warhead
Tint.Color=               ; integer - R,G,B
Tint.Duration=0           ; integer - game frames
Tint.VisibleToHouses=all  ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
```

Theres also a couple of tinting-related bugfixes:

- Tint effects are now correctly applied to SHP vehicles and all types of aircraft as well as building animations regardless of their position.
- Iron Curtained / Force Shielded objects now always use the correct tint color.

-----------------

## NOTE:
There is a high likelihood that the custom tint effects feature is very performance-heavy due to hooking in drawing functions and `ExtMap.Find` calls. It may not be feasible for widespread usage until that latter issue is addressed in some manner.

2023-01-23 08:10 UTC, secsome commented on src/Ext/Techno/Body.h
> +	static int GetTintColor(TechnoClass* pThis, bool invulnerability, bool airstrike, bool berserk);
Call it `GetVanillaTintColor` should be better?
And `GetTintColor` should be the wrapper calling `GetVanillaTintColor` and `GetCustomTintColor`?

2023-01-23 08:10 UTC, secsome commented on src/Utilities/GeneralUtils.cpp
> +	if (Drawing::ColorMode() == RGBMode::RGB565)
Just call `Drawing::RGB_To_Int` I guess

2023-01-23 14:59 UTC, Starkku commented on src/Utilities/GeneralUtils.cpp
> +	if (Drawing::ColorMode() == RGBMode::RGB565)
So what I think `Drawing::RGB_To_Int` actually does is convert RGB888 color to whatever 16-bit format is currently in use by the game, practically always RGB565. The thing is, `[ColorAdd]` values are already in 16-bit RGB format (I think it is specifically RGB565 but not certain), but I didn't exactly have the conversion algo to shove the values into an integer at hand so I just took what game does with them.

2023-01-23 15:00 UTC, Starkku commented on src/Ext/Techno/Body.h
> +	static int GetTintColor(TechnoClass* pThis, bool invulnerability, bool airstrike, bool berserk);
Perhaps.

2023-01-23 19:51 UTC, Falaka21 commented
Do you remember that,  years ago, "Morale,Bravery,Panic" system request by someone that I can't remember the nickname but , "EvilRenegade" himself was very proud of the idea when Ares (AlexB) active... With the 'negative'verses on WHs, this could be awesome for "killer" units ,as well.... (while killer gets temporal AE improvements, dying units'  specific   'DeathWeapon'  can cause its comrades some negative AEs !    "DP" already has this ,but I am proud of Phobos has its own tags now...

2023-01-24 02:21 UTC, chaserli commented on src/Ext/Building/Hooks.cpp
> +DEFINE_HOOK(0x4519A2, BuildingClass_UpdateAnim_SetParentBuilding, 0x6)
We can merge this and the laser trail thing before the entire PR

2023-02-02 17:07 UTC, ZYJYGE commented
I tested the feature of "tint effects applied by Warheads". It worked correctly in normal situation but didn't work in the warhead of radiation like the default "RadSite" and other custom warheads for radiation.

2023-02-04 17:46 UTC, Starkku commented
Massively reworked the PR by basically reimplementing AttachEffect as explicit types.

- This system should be able to coexist with Ares' AttachEffect without a hitch, there might be some edge cases I have not caught though.
- `ROFMultiplier` is by default also applied on currently running reload timer here unlike with Ares' version. This can be customized via `ROFMultplier.ApplyOnCurrentTimer`.
- Note that `ForceDecloak` works differently here (it keeps the objects uncloaked for duration of the effect instead of uncloaking once when applied), Ares' implementation is not particularly useful.
- `WeaponRangeBonus` and weapons requiring or being blocked by target's AttachEffects are new logic I decided to throw in, should allow for some interesting things.

Due to the large amount of `TechnoExt::ExtMap.Find` calls necessiated by the custom tint logic, weapon range bonus as well AttachEffect as whole, this PR will likely run at less than optimal performance until that system is reworked.

2023-02-06 12:41 UTC, chaserli commented
Holy shit, the entire AutoDeath logic should be merged into this framework eventually

2023-02-06 12:46 UTC, chaserli commented on src/Ext/Techno/Body.h
> +		std::vector<std::unique_ptr<AttachEffectClass>> AttachedEffects;
why a vector of pointers instead of instances directly, like Ares?

2023-03-09 21:02 UTC, Starkku commented
Rebased on develop, as well as a couple of other changes.

- The weapon range modifier keys have been renamed to accomodate addition of a multiplier alongside the 'fixed' extra range bonus.
- Added critical hit chance multiplier.

2023-03-15 11:22 UTC, Starkku commented
Rebased on develop again, as well as introduced fixed critical hit chance bonus effect. Note that rest of the critical hit modifier keys have been renamed as well.

2023-03-15 12:11 UTC, Metadorius commented
Before I forget, a thought for the future (not necessarily this PR). To unify the attachability of different things what I think maybe the best approach would be splitting the concept of an AttachEffect into two entities:
- the component that can be attached (in this case the effect, the shield as well, maybe stuff like LaserTrails, interceptors etc.), without the lifetime/attachment/detachment conditions etc., just the component itself which won't have any self-management logic
- the attacher itself, which could manage multiple components at once using timers, conditions for attachment/detachment/activation/deactivation/etc.

Up to further discussion.

2023-05-28 07:00 UTC, reedom114514 commented
There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.

2023-05-28 09:38 UTC, Starkku commented
> There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.

Good catch, should be fixed now.

2023-05-29 15:13 UTC, reedom114514 commented
> > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> 
> Good catch, should be fixed now.

After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes,  EIP:5B767260

2023-05-29 15:38 UTC, Starkku commented
> > > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> > 
> > 
> > Good catch, should be fixed now.
> 
> After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes, EIP:5B767260

Is this on the most up to date build? For some reason the github-actions bot isn't updating the links correctly right now.

Here's the link https://github.com/Phobos-developers/Phobos/suites/13202812824/artifacts/718933906

2023-05-29 17:12 UTC, reedom114514 commented
> > > > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> > > 
> > > 
> > > Good catch, should be fixed now.
> > 
> > 
> > After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes, EIP:5B767260
> 
> Is this on the most up to date build? For some reason the github-actions bot isn't updating the links correctly right now.
> 
> Here's the link https://github.com/Phobos-developers/Phobos/suites/13202812824/artifacts/718933906

Oh, not the newest one, the one I downloaded is about 9 hours earlier
Ok, I shall try

2023-05-29 17:12 UTC, reedom114514 commented
> > > > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> > > 
> > > 
> > > Good catch, should be fixed now.
> > 
> > 
> > After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes, EIP:5B767260
> 
> Is this on the most up to date build? For some reason the github-actions bot isn't updating the links correctly right now.
> 
> Here's the link https://github.com/Phobos-developers/Phobos/suites/13202812824/artifacts/718933906

Oh, not the newest one, the one I downloaded is about 9 hours earlier
Ok, I shall try

2023-05-29 17:12 UTC, reedom114514 commented
> > > > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> > > 
> > > 
> > > Good catch, should be fixed now.
> > 
> > 
> > After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes, EIP:5B767260
> 
> Is this on the most up to date build? For some reason the github-actions bot isn't updating the links correctly right now.
> 
> Here's the link https://github.com/Phobos-developers/Phobos/suites/13202812824/artifacts/718933906

Oh, not the newest one, the one I downloaded is about 9 hours earlier
Ok, I shall try

2023-05-30 05:26 UTC, reedom114514 commented
> > > > There is a bug, when using these AEs on mobile buildings which is packing into vehicles, the game freezes.
> > > 
> > > 
> > > Good catch, should be fixed now.
> > 
> > 
> > After bug fix, there is another one about it: when building affected by new AE turns (in my test it is a SODAR) to vehicle, and adjust game speed in this step, after 1-2 sec the game freezes, EIP:5B767260
> 
> Is this on the most up to date build? For some reason the github-actions bot isn't updating the links correctly right now.
> 
> Here's the link https://github.com/Phobos-developers/Phobos/suites/13202812824/artifacts/718933906

With the newest one there is still a FE, EIP:5B33B669, randomly during packing/unpacking the SODAR, Firepower/Armor/Speed/Range

2023-05-30 10:01 UTC, Starkku commented
> With the newest one there is still a FE, EIP:5B33B669, randomly during packing/unpacking the SODAR, Firepower/Armor/Speed/Range

Could you provide the exact AttachEffect code used in this case? Mostly the duration and anything related is of interest to me because while I've been able to reproduce this crash, it isn't reliable and it occurs really rarely for me.

2023-06-01 08:49 UTC, Starkku commented
https://github.com/Phobos-developers/Phobos/suites/13280697552/artifacts/724636536

Refactored attaching/detaching code and changed how transfering works, I was unable to reproduce the crash afterwards.

2023-06-01 13:19 UTC, reedom114514 commented
> https://github.com/Phobos-developers/Phobos/suites/13280697552/artifacts/724636536
> 
> Refactored attaching/detaching code and changed how transfering works, I was unable to reproduce the crash afterwards.

After testing I cannot reproduce this too, but in multi-player the RE happens (using this PR branch), shall I post that on the other feedback?

2023-09-23 13:31 UTC, Starkku commented
`DiscardOnEntry` has been deprecated. Use the new key `DiscardOn` (f.ex `DiscardOn=entry`) instead, it also accepts to different values for discarding when object moves or becomes stationary, respectively.

Additionally fixed an issue with discarded attacheffects not being recreated even if they should after exiting from limbo.

2023-09-23 13:38 UTC, Metadorius commented
Means they are exclusive now? Maybe different tags or enum flags would work better for combination of different conditions?

2023-09-23 13:44 UTC, Starkku commented
> Means they are exclusive now? Maybe different tags or enum flags would work better for combination of different conditions?

I worded it badly, it takes a list of values

2024-01-21 11:13 UTC, Metadorius requested changes

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +	, NeedsDurationRefresh { false }
Same question here. Also I think `:` should be on newline, it's easy to lose it visually at the end of the line.

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +		KillAnim();
```suggestion
		this->KillAnim();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +	return IsSelfOwned() && this->Delay >= 0 ? false : !this->Duration;
```suggestion
	return this->IsSelfOwned() && this->Delay >= 0 ? false : !this->Duration;
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +	if (auto const pAE = CreateAndAttach(pType, pTarget, pTargetExt->AttachedEffects, pInvokerHouse, pInvoker, pSource, durationOverride, delay, initialDelay, recreationDelay))
Is CreateAndAttach a static function in this class or what? IMO all class function calls should have a qualifier for clarity.

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +		if (auto const pAE = CreateAndAttach(pType, pTarget, pTargetExt->AttachedEffects, pInvokerHouse, pInvoker, pSource, durationOverride, delay, initialDelay, recreationDelay))
Same here

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +	return Type;
```suggestion
	return this->Type;
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +bool AttachEffectClass::Attach(AttachEffectTypeClass* pType, TechnoClass* pTarget, HouseClass* pInvokerHouse, TechnoClass* pInvoker,
I'd add a separate section (pragma region?) for statics and other types of members for clarity.

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/AttachEffectClass.cpp
> +			if (auto const pAE = CreateAndAttach(type, pTarget, pTargetExt->AttachedEffects, attachEffect->InvokerHouse, attachEffect->Invoker, attachEffect->Source, attachEffect->DurationOverride))
Also lacks qualifier.

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +			UpdateTint();
```suggestion
			this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +			UpdateTint();
```suggestion
			this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +		UpdateTint();
```suggestion
		this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +	UpdateTint();
```suggestion
	this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +	UpdateTint();
```suggestion
	this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Entity/ShieldClass.cpp
> +		UpdateTint();
```suggestion
		this->UpdateTint();
```

2024-01-21 11:13 UTC, Metadorius commented on src/New/Type/AttachEffectTypeClass.h
> +		, Animation {}
Can't remember for sure if documented, did we have any consensus regarding `{}` vs `{ }`?

2024-01-21 11:16 UTC, Starkku commented on src/New/Entity/AttachEffectClass.cpp
> +, NeedsDurationRefresh { false }
VS document formatting on current settings does this.

2024-01-21 11:17 UTC, Starkku commented on src/New/Type/AttachEffectTypeClass.h
> +		, Animation {}
Not in style guide and I cannot recall it being discussed.

2024-01-21 11:25 UTC, Starkku commented on docs/New-or-Enhanced-Logics.md
> +  - Attached effects can be removed from objects by Warheads using `AttachEffect.RemoveTypes`.
Maybe. It would require more lines in INI but might be clearer.

2024-01-21 15:43 UTC, chaserli requested changes

2024-01-21 15:43 UTC, chaserli commented on src/Ext/Techno/Body.h
> +		std::vector<std::unique_ptr<AttachEffectClass>> AttachedEffects;
```suggestion
		std::vector<AttachEffectClass> AttachedEffects;
```
[a container of instances](https://github.com/Ares-Developers/Ares/blob/master/src/Ext/Techno/Body.h#L64) of instances should suffice (

2024-01-21 15:43 UTC, chaserli commented on src/New/Type/AttachEffectTypeClass.cpp
> +Enumerable<AttachEffectTypeClass>::container_t Enumerable<AttachEffectTypeClass>::Array;
```suggestion
```

2024-01-21 15:43 UTC, chaserli commented on src/New/Type/AttachEffectTypeClass.cpp
> +const char* Enumerable<AttachEffectTypeClass>::GetMainSection()
```suggestion
template<>
const char* Enumerable<AttachEffectTypeClass>::GetMainSection()
```

2024-02-26 10:49 UTC, Metadorius commented on docs/New-or-Enhanced-Logics.md
> +  - Attached effects can be removed from objects by Warheads using `AttachEffect.RemoveTypes`.
Let's roll with that change then.

2024-02-26 10:50 UTC, Metadorius reviewed
Considering it's a replacement for Ares' AttachEffect - it may be good to add a note stating what changes are required to migrate to Phobos one.

2024-02-26 10:53 UTC, Starkku commented
> Considering it's a replacement for Ares' AttachEffect - it may be good to add a note stating what changes are required to migrate to Phobos one.

It doesn't stop any of the Ares' AttachEffect features from working though.

2024-02-26 10:55 UTC, Metadorius commented
> It doesn't stop any of the Ares' AttachEffect features from working though. It simply offers new system alongside the old one.

Correct, I didn't mean this in fact. I mean it as just an upgrade scenario, if the user would want to migrate from Ares to Phobos AE and/or back, and we could point them to the note.

2024-04-23 13:00 UTC, Starkku commented on src/Ext/Techno/Body.h
> +		std::vector<std::unique_ptr<AttachEffectClass>> AttachedEffects;
Not implementing for now due to amount of code refactoring required beyond the suggested change.

2024-04-23 13:04 UTC, Starkku commented
Added some additional features to AttachEffect, mostly things that have been requested from me (grouping & group filters, Cumulative stack filters/animations, expire weapon). I will not expand the current functionality any further in this PR and consider this PR finished, save for potential bugfixes.

2024-04-26 16:46 UTC, Starkku commented
> `AttachEffect.RequiredTypes=;` on weapons make the unit not able to attack the target until the AE is on it (as intended), but the weapon can still be fired on the ground, so in a way it's still able to damage said target if it moves to the ground cell being attacked. This can be "fixed" with `CanTarget=` but doesn't feel like it interacts well.

Noted but not the easiest 'problem' to solve, `CanTarget` itself also technically can have same issue depending on values.

> Having an AttachEffectType with an `ExpireWeapon=` that triggers another AttachEffectType crashes the game.

This needs a crash dump.

> `ExpireWeapon=` does not damage the owner/invoker, but does damage friendly units, would be good to control this. Effects such as (Ares AE) do get applied to the owner/invoker though.

Use `AllowDamageOnSelf` on Warhead, technos don't take damage from weapons/warheads that are considered to be fired by themselves normally.

> `Powered=true` does not work on low power as described, but it does work when the unit is disabled e.g. EMP

Will investigate.

> `Crit.ExtraChance` does not work if the Warhead has 0.0 crit to begin with, which it should, e.g.

Noted.

2024-04-27 00:19 UTC, ayylmaoRotE commented
>This needs a crash dump.
>
Attached.
https://1drv.ms/u/s!Ah86cVoN9dYikZJA5vSbP6yWYCRwJA?e=1uQJh9
>Cannot reproduce. This is technically not a 'low base power' check and it is not advertised as such in the documentation either, but rather simply if the techno it is attached to is 'offline' or not. For buildings that require power it does work as intended.
>
Oh yep that makes sense, didn't look into buildings

Will do MP testing later too

2024-05-04 17:44 UTC, Starkku commented
I could change it to use vector of instances like @chaserli suggested earlier, but besides having to go through the effort to refactor a bunch of code are there any other actual concerns I should take into account if I do that? Is it even a feasible approach for something like this, I know shields use `unique_ptr` so that is why I picked it in the first place. If I nuke the vector (e.g techno dies) will it automagically delete the objects contained as well even if I don't use `unique_ptr`?

2024-05-05 12:24 UTC, Metadorius commented
I personally think that for consistency sake it's better to use pointer vector for now, after all everything uses that. If there are benefits for instance vectors - the refactoring should be separate.

2024-05-18 17:02 UTC, Metadorius commented on src/Ext/Techno/Hooks.Tint.cpp
> +}
Okay nevermind, I missed a part of the changes. Would be good to have this and the next hooks not mixed with the rest but left in a separate block so they don't mix with unrelated changes.

2024-05-18 18:07 UTC, merged