Gain Experience in "Automatic passenger deletion" logic (#806)
Phobos-developers/Phobos pull request #833
Opened 2023-01-30 19:25 UTC by Envoidener

Also added AffectedByVeterancy boolean

2023-01-30 20:39 UTC, Metadorius commented on src/Ext/Techno/Body.cpp
> +					pPassenger->GetTechnoType()->Size > 1.0)
```suggestion
				if (pTypeExt->PassengerDeletion_Rate_SizeMultiply
					&& pPassenger->GetTechnoType()->Size > 1.0)
```

2023-01-31 00:38 UTC, chaserli requested changes
Do it in #654 instead

2023-01-31 13:23 UTC, Metadorius commented
Yeah it might be good to rebase it onto #654 for consistency.

2023-01-31 13:41 UTC, ek-development commented
Might as well close this PR as most of this is redundant; will continue on #654

2023-01-31 13:44 UTC, Envoidener commented
Might as well close this PR as most of this is redundant; will continue on #654

2023-01-31 13:44 UTC, closed without merging