TechnoType conversion warhead (split)
Phobos-developers/Phobos pull request #841
Opened 2023-02-09 18:25 UTC by MortonPL

Moved code from #369. **Note: this PR requires #840 to compile and work.**

## Super Weapons

### Convert TechnoType

- Superweapons can now change TechnoTypes of affected units to other Types in the same category (infantry to infantry, vehicles to vehicles, aircraft to aircraft). This feature has the same limitations as [Ares' Type Conversion](https://ares-developers.github.io/Ares-docs/new/typeconversion.html). ***This feature does not support BuildingTypes.***
  - `Convert.From` specifies which TechnoTypes are valid for conversion. This entry can have many types listed, meanging that many types will be converted at once. When no types are included, conversion will affect all valid targets.
  - `Convert.To` specifies which TechnoTypes are the result of converion. This entry should have the same length as `Convert.From` (when the latter is not empty), because entries are grouped in pairs.
  - `Convert.AffectedHouses` specifies whose units can be converted.
  - Conversion affects *all* existing units of set TechnoTypes, this includes units in: transports, occupied buildings, buildings with `InfantryAbsorb=yes` or `UnitAbsorb=yes`, buildings with `Bunker=yes`.

In example, this superweapon would convert all owned and friendly SOLDIERA to SOLDIERB and TANKA to TANKB.
```ini
[SOMESW]
Convert.From=SOLDIERA,TANKA
Convert.To=SOLDIERB,TANKB
Convert.AffectedHouses=team
```

```{warning}
This feature requires Ares 3.0 or higher to function! When Ares 3.0+ is not detected, not all properties of a unit may be updated.
```

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]
Convert.From=                   ; list of tehnoTypes
Convert.To=                     ; list of TechnoTypes
Convert.AffectedHouses=owner    ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
```

## Warheads

### Convert TechnoType on impact

- Warheads can now change TechnoTypes of affected units to other Types in the same category (infantry to infantry, vehicles to vehicles, aircraft to aircraft). This feature has the same limitations as [Ares' Type Conversion](https://ares-developers.github.io/Ares-docs/new/typeconversion.html). ***This feature does not support BuildingTypes.***
  - `Convert.From` specifies which TechnoTypes are valid for conversion. This entry can have many types listed, meanging that many types will be converted at once. When no types are included, conversion will affect all valid targets.
  - `Convert.To` specifies which TechnoTypes are the result of converion. This entry should have the same length as `Convert.From` (when the latter is not empty), because entries are grouped in pairs.

In example, this warhead would convert all affected SOLDIERA to SOLDIERB and TANKA to TANKB.
```ini
[SOMEWARHEAD]
Convert.From=SOLDIERA,TANKA
Convert.To=SOLDIERB,TANKB
```

```{warning}
This feature requires Ares 3.0 or higher to function! When Ares 3.0+ is not detected, not all properties of a unit may be updated.
```

In `rulesmd.ini`:
```ini
[SOMEWARHEAD]
Convert.From=         ; list of TehnoTypes
Convert.To=           ; list of TechnoTypes
```

2023-02-19 13:59 UTC, FS-21 commented on src/Ext/SWType/FireSuperWeapon.cpp
> +	if (this->Convert_To.size())
Maybe I'm wrong, I asumed that Convert_To is a std::vector<T> so if I'm wrong skip this message.

Instead of:
```
if (this->Convert_To.size())
{
  /*More code nested*/
}
```

Isn't better?
```
if (this->Convert_To.size() == 0)
  return;

/* Here the rest of the code but decreasing 1 level of nesting*/
```

2023-02-19 14:00 UTC, FS-21 commented on src/Ext/SWType/FireSuperWeapon.cpp
> +				TechnoExt::ConvertToType(pTarget, this->Convert_To[0]);
Leave a blank line here.

2023-02-19 14:15 UTC, FS-21 commented on src/Ext/Techno/Body.cpp
> +	pOwner->RemoveTracking(pThis);
Leave a blank like between the if and the next call?

2023-02-19 14:19 UTC, FS-21 commented on src/Ext/WarheadType/Detonate.cpp
> +		if (this->Convert_To.size())
Maybe you should combine the 2 ifs to reduce 1 level of nesting

2023-02-19 14:22 UTC, FS-21 commented on src/Ext/WarheadType/Detonate.cpp
> +		if (this->Convert_To.size())
Regarding:


```
if (auto pTargetFoot = abstract_cast<FootClass*>(pTarget))
	{
		if (this->Convert_To.size())
```

"Maybe" the nesting should be decreased with something like:

```
auto pTargetFoot = abstract_cast<FootClass*>(pTarget);

if (pTargetFoot && this->Convert_To.size())
{
/*Everything else*/
}
```

2023-06-03 12:03 UTC, Metadorius requested changes

2023-06-03 12:03 UTC, Metadorius commented on CREDITS.md
> +   - TechnoType conversion placeholder
Isn't the conversion code done by Ares team / AlexB?

2023-06-03 21:33 UTC, MortonPL commented on CREDITS.md
> +   - TechnoType conversion placeholder
Conversion code has a fallback/placeholder by Trsdy for when Ares can't be used. See Ext/Techno/Body.cpp:209.

2023-06-10 15:20 UTC, Metadorius commented on CREDITS.md
> +   - TechnoType conversion placeholder
https://github.dev/Phobos-developers/Antares/blob/7241a5ff20f4dbf7153cc77e16edca5c9db473d4/src/Ext/WeaponType/Body.cpp#L272

2023-06-10 15:30 UTC, Metadorius approved these changes
Maybe reducing code duplication between the SW and the WH activation/detonation code wouldn't hurt (and also look into the code on the link), but up to you on whether that's feasible or nah. LGTM otherwise

2023-06-10 17:12 UTC, merged