ExtMap optimization
Phobos-developers/Phobos pull request #843
Opened 2023-02-10 19:33 UTC by Starkku

This is mostly @Otamaa's work, I just ported it over and did some tweaks.

Basically replaces the existing `ExtMap / Container` implementation that relies on `std::map` with storing the extension class pointers in unused data in game classes. The offset at which the pointers are stored is determined by `ExtPointerOffset` field in the extension classes, or if not present, a constant set to `0x18` is used which corresponds to an unused field in `AbstractClass`.

There's bunch of changes to existing code outside `Container.h` to accomodate these changes, mostly to do with pointer invalidation which is now mostly called from type-specific hooks in game's `Detach()` functions and fixing incompatibilities with the way `ExtMap.Find()` now works, as calling it with corrupted pointers now crashes instead of returning nullptr.

`TypeExtData` field in some of the extension classes is also now deprecated in favour of calling `ExtMap.Find()` to get the type on demand to eliminate any possibility of conflicts with type conversion logics.

2023-02-17 13:18 UTC, MortonPL reviewed
Out of curiosity, have you measured performance before and after?

2023-02-17 13:18 UTC, MortonPL commented on src/Ext/Building/Body.cpp
> +		Debug::Log("Test\n");
```suggestion
```
Marking for later clean-up

2023-02-17 13:18 UTC, MortonPL commented on src/Ext/WarheadType/Detonate.cpp
> +			if (pTypeExt && pTypeExt->Interceptable)
What's the reason for this?

2023-02-17 13:33 UTC, Starkku commented on src/Ext/WarheadType/Detonate.cpp
> +			if (pTypeExt && pTypeExt->Interceptable)
Just a really minor optimization, moved the check before all the other code since it can be done earlier.

2023-02-17 13:34 UTC, Starkku commented on src/Ext/Building/Body.cpp
> +		Debug::Log("Test\n");
😔

2023-02-17 13:37 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +		Debug::Log("Test\n");
*You have been marked for termination*

2023-02-17 13:39 UTC, Starkku commented on src/Ext/Building/Body.cpp
> +		Debug::Log("Test\n");
🙃🔫

2023-02-17 14:00 UTC, Starkku commented
> Out of curiosity, have you measured performance before and after?

I did do some tests but I don't know how conclusive they were, I got around 15-20% improvement in average FPS in those tests.

2023-02-17 14:06 UTC, chaserli commented
Didn't look into the very details yet given the quantity, a few overall personal opinions
1.
> `TypeExtData` field in some of the extension classes is also now deprecated in favour of calling `ExtMap.Find()` to get the type on demand to eliminate any possibility of conflicts with type conversion logics.
Don't think that's even necessary. 
Also, iterating ExtMap should be as fast as (or even faster) than your current one.
2. Just as Morton said, profile first using tools like verysleepy and see which ones matter most, afaik primarily `TechnoExt`,`TechnoTypeExt` ,`BuildingExt`, `BuildingTypeExt` and `AnimExt`. 
3. For base types having `ArrayIndex`(namely `SWTypeExt`, `HouseExt`, `SideExt`,etc...) you can create a static array and fetch the ext based on the `ArrayIndex`.

2023-02-24 12:56 UTC, Starkku commented
Reverted the pointer invalidation changes because it seems doing it with specific hooks vs. mass actions on a single hook is actually slower. I guess it makes sense since there's less hooks in latter.

2023-06-03 12:41 UTC, Metadorius requested changes
ExtMap wise I don't see much issues, but all the other seemingly random changes lack context and are unobvious, and it also would be better if they were split.

2023-06-03 12:41 UTC, Metadorius commented on src/Ext/Anim/Body.cpp
> +}
What does this do? Probably an explanation comment or a better hook name wouldn't hurt.

2023-06-03 12:41 UTC, Metadorius commented on src/Ext/Building/Body.cpp
> +DEFINE_JUMP(LJMP, 0x41D9FB, 0x41DA05);
Does any other ext. use this field?

2023-06-03 12:41 UTC, Metadorius commented on src/Ext/Anim/Body.cpp
> +*/
Why is the code commented out?

2023-06-03 12:42 UTC, Metadorius commented on src/Ext/Anim/Body.cpp
> +*/
Likewise with other code blocks like this one

2023-06-03 12:49 UTC, Starkku commented on src/Ext/Anim/Body.cpp
> +}
Makes sure the otherwise unused field isn't set in constructor because it is used for the `ExtPointerOffset` of `AnimExt`.

https://github.com/Phobos-developers/Phobos/pull/843/files#diff-a74a98d60066e2d7da1fefb6c90efd397d66a7cbbb5551f45d68a4f9cdd8e034R16

But yeah will clarify I guess.

2023-06-03 12:51 UTC, Starkku commented on src/Ext/Building/Body.cpp
> +DEFINE_JUMP(LJMP, 0x41D9FB, 0x41DA05);
> Does any other ext. use this field?

Ext as in class or another extension DLL? No to former, no clue about the latter.

Same case as with the first comment, this is used for `BuildingExt` `ExtPointerOffset`.

2023-06-03 12:52 UTC, Starkku commented on src/Ext/Anim/Body.cpp
> +*/
Mass-action based pointer invalidation turned out to have better performance so obsolete code. Can probably clear it out before merging.

2023-07-15 10:17 UTC, Metadorius approved these changes

2023-07-15 10:18 UTC, merged