[Minor] Improve INI inheritance performance & add a toggle
Phobos-developers/Phobos pull request #857
Opened 2023-03-26 15:52 UTC by MortonPL

Toggle and docs for toggle soon.

2023-03-29 12:39 UTC, Metadorius commented
Maybe it's better to make it *opt-out* instead?

2023-03-29 12:49 UTC, MortonPL commented
> Maybe it's better to make it _opt-out_ instead?

I was under the impression that this mechanism is not well received, hence opt-in.

2023-04-16 20:31 UTC, DOOMGUY2K approved these changes
As fast, if not slightly faster than 33. Numbers are subjective timewise. For reference I did not use $Includes but do use #Includes

Tested with DP-Kratos Ares 3.01p and this build of Phobos.

2023-05-22 09:42 UTC, Metadorius requested changes
Minor doc nitpicks, everything else looking good.

2023-05-22 09:42 UTC, Metadorius commented on docs/Miscellanous.md
> +  - This feature must be enabled via a command line argument `-Include`.
````suggestion

```{note}
This feature must be enabled via a command line argument `-Include`.
```

- INI files can now include other files (merge them into self) using `[$Include]` section.
````

2023-05-22 09:42 UTC, Metadorius commented on docs/Miscellanous.md
> +  - This feature must be enabled via a command line argument `-Inheritance`.
````suggestion

```{note}
This feature must be enabled via a command line argument `-Inheritance`.
```

- You can now make sections (children) inherit entries from other sections (parents) with `$Inherits` entry.
````

2023-05-22 09:42 UTC, Metadorius commented on docs/Miscellanous.md
> +When this feature is enabled, the Ares equivalent of $Inherits (undocumented) is disabled!
```suggestion
When this feature is enabled, the Ares equivalent of `$Inherits` (undocumented) is disabled!
```

2023-05-22 09:42 UTC, Metadorius commented on docs/Whats-New.md
> +- INI inclusion and inheritance are now turned off by default and need to be turned on via command line flags `-Include` and `-Inheritance`.
Unsure if this is the right place? 0.3 didn't have this.

2023-05-22 10:33 UTC, Starkku commented on docs/Whats-New.md
> +- INI inclusion and inheritance are now turned off by default and need to be turned on via command line flags `-Include` and `-Inheritance`.
Add a new section called either post-0.3 or pre-0.4 dev builds (probably depends on what the plan for next version is, but it can always be amended later, it is just a label) like there is one for pre-0.3 ones and put it under that.

2023-05-22 11:15 UTC, Metadorius approved these changes

2023-05-28 12:53 UTC, merged