Fix PR #139
Phobos-developers/Phobos pull request #865
Opened 2023-04-29 07:02 UTC by chaserli

More ass wiping:

* Your EVA event was suppressed in a bad way. 
* You should have suppressed all capture events for buildings considered vehicles.
* `MindControl.Anim` wasn't used and the anim always falls back to the default one.

2023-05-11 18:00 UTC, Starkku commented
There are a couple of issues with the MC ring transfer fix here.

1. Checking weapon via `SelectWeapon` to figure out the mind control ring animation to use is not reliable. It is possible for the weapon used against specific target to change on the fly (f.ex shields, NoAmmoWeapon, eventually AE) and thus it can give wrong results. It is better to remember the ring animation used prior to deploy and use that.

2. Permanent MC ring anim is not correctly recreated or adjusted and thus is only transferred one way and it will have wrong offset.

Something like the following can be used to ensure correct animation is used, and that permanent MC has the ring animation set correctly (it is recreated here instead of simply transferred over for consistency with regular MC). When deploying from vehicle to building, the vehicle will still have `TechnoClass->MindControlRingAnim` but other way around the pointer has been invalidated because the structure has been limboed, hence why one of the hooks in undeploying/selling function has been adjusted to remember the MC anim (by reusing the mechanism added for recreating MC anims when cloaking/decloaking, which will also allow the correct MC anim to be used in case unit is deployed when cloaked and the ring is not currently present).

```cpp
void TechnoExt::TransferMindControlOnDeploy(TechnoClass* pTechnoFrom, TechnoClass* pTechnoTo)
{
	auto const pAnimType = pTechnoFrom->MindControlRingAnim ?
		pTechnoFrom->MindControlRingAnim->Type : TechnoExt::ExtMap.Find(pTechnoFrom)->MindControlRingAnimType;

	if (auto Controller = pTechnoFrom->MindControlledBy)
	{
		if (auto Manager = Controller->CaptureManager)
		{
			CaptureManagerExt::FreeUnit(Manager, pTechnoFrom, true);

			if (CaptureManagerExt::CaptureUnit(Manager, pTechnoTo, false, pAnimType, true))
			{
				if (auto pBld = abstract_cast<BuildingClass*>(pTechnoTo))
				{
					pBld->BeginMode(BStateType::Construction);
					pBld->QueueMission(Mission::Construction, false);
				}
			}
			else
			{
				int nSound = pTechnoTo->GetTechnoType()->MindClearedSound;
				if (nSound == -1)
					nSound = RulesClass::Instance->MindClearedSound;
				if (nSound != -1)
					VocClass::PlayIndexAtPos(nSound, pTechnoTo->Location);
			}

		}
	}
	else if (auto MCHouse = pTechnoFrom->MindControlledByHouse)
	{
		pTechnoTo->MindControlledByHouse = MCHouse;
		pTechnoFrom->MindControlledByHouse = nullptr;
	}
	else if (pTechnoFrom->MindControlledByAUnit) // Perma MC
	{
		pTechnoTo->MindControlledByAUnit = true;

		if (pTechnoTo->MindControlRingAnim)  // This check might not be necessary as there shouldn't be a prior anim on the techno.
			pTechnoTo->MindControlRingAnim->TimeToDie = 1;

		auto const pBuilding = abstract_cast<BuildingClass*>(pTechnoTo);
		CoordStruct location = pTechnoTo->GetCoords();

		if (pBuilding)
			location.Z += pBuilding->Type->Height * Unsorted::LevelHeight;
		else
			location.Z += pTechnoTo->GetTechnoType()->MindControlRingOffset;

		if (auto const pAnim = GameCreate<AnimClass>(pAnimType, location, 0, 1))
		{
			pTechnoTo->MindControlRingAnim = pAnim;

			if (pBuilding)
				pAnim->ZAdjust = -1024;

			pAnim->SetOwnerObject(pTechnoTo);
		}

	}
}

DEFINE_HOOK(0x449E2E, BuildingClass_Mi_Selling_CreateUnit, 0x6)
{
	GET(BuildingClass*, pStructure, EBP);
	R->ECX<HouseClass*>(pStructure->GetOriginalOwner());

	// Remember MC ring animation.
	if (pStructure->IsMindControlled())
	{
		auto const pTechnoExt = TechnoExt::ExtMap.Find(pStructure);
		pTechnoExt->UpdateMindControlAnim();
	}

	return 0x449E34;
}
```

2023-05-11 18:01 UTC, Starkku requested changes
There are a couple of issues with the MC ring transfer fix here.

1. Checking weapon via `SelectWeapon` to figure out the mind control ring animation to use is not reliable. It is possible for the weapon used against specific target to change on the fly (f.ex shields, NoAmmoWeapon, eventually AE) and thus it can give wrong results. It is better to remember the ring animation used prior to deploy and use that.

2. Permanent MC ring anim is not correctly recreated or adjusted, also the MC status was not actually properly transferred.

Something like the following can be used to ensure correct animation is used, and that permanent MC has the ring animation set correctly (it is recreated here instead of simply transferred over for consistency with regular MC). When deploying from vehicle to building, the vehicle will still have `TechnoClass->MindControlRingAnim` but other way around the pointer has been invalidated because the structure has been limboed, hence why one of the hooks in undeploying/selling function has been adjusted to remember the MC anim (by reusing the mechanism added for recreating MC anims when cloaking/decloaking, which will also allow the correct MC anim to be used in case unit is deployed when cloaked and the ring is not currently present).

```cpp
void TechnoExt::TransferMindControlOnDeploy(TechnoClass* pTechnoFrom, TechnoClass* pTechnoTo)
{
	auto const pAnimType = pTechnoFrom->MindControlRingAnim ?
		pTechnoFrom->MindControlRingAnim->Type : TechnoExt::ExtMap.Find(pTechnoFrom)->MindControlRingAnimType;

	if (auto Controller = pTechnoFrom->MindControlledBy)
	{
		if (auto Manager = Controller->CaptureManager)
		{
			CaptureManagerExt::FreeUnit(Manager, pTechnoFrom, true);

			if (CaptureManagerExt::CaptureUnit(Manager, pTechnoTo, false, pAnimType, true))
			{
				if (auto pBld = abstract_cast<BuildingClass*>(pTechnoTo))
				{
					pBld->BeginMode(BStateType::Construction);
					pBld->QueueMission(Mission::Construction, false);
				}
			}
			else
			{
				int nSound = pTechnoTo->GetTechnoType()->MindClearedSound;
				if (nSound == -1)
					nSound = RulesClass::Instance->MindClearedSound;
				if (nSound != -1)
					VocClass::PlayIndexAtPos(nSound, pTechnoTo->Location);
			}

		}
	}
	else if (auto MCHouse = pTechnoFrom->MindControlledByHouse)
	{
		pTechnoTo->MindControlledByHouse = MCHouse;
		pTechnoFrom->MindControlledByHouse = nullptr;
	}
	else if (pTechnoFrom->MindControlledByAUnit) // Perma MC
	{
		pTechnoTo->MindControlledByAUnit = true;

		if (pTechnoTo->MindControlRingAnim)  // This check might not be necessary as there shouldn't be a prior anim on the techno.
			pTechnoTo->MindControlRingAnim->TimeToDie = 1;

		auto const pBuilding = abstract_cast<BuildingClass*>(pTechnoTo);
		CoordStruct location = pTechnoTo->GetCoords();

		if (pBuilding)
			location.Z += pBuilding->Type->Height * Unsorted::LevelHeight;
		else
			location.Z += pTechnoTo->GetTechnoType()->MindControlRingOffset;

		if (auto const pAnim = GameCreate<AnimClass>(pAnimType, location, 0, 1))
		{
			pTechnoTo->MindControlRingAnim = pAnim;

			if (pBuilding)
				pAnim->ZAdjust = -1024;

			pAnim->SetOwnerObject(pTechnoTo);
		}

	}
}

DEFINE_HOOK(0x449E2E, BuildingClass_Mi_Selling_CreateUnit, 0x6)
{
	GET(BuildingClass*, pStructure, EBP);
	R->ECX<HouseClass*>(pStructure->GetOriginalOwner());

	// Remember MC ring animation.
	if (pStructure->IsMindControlled())
	{
		auto const pTechnoExt = TechnoExt::ExtMap.Find(pStructure);
		pTechnoExt->UpdateMindControlAnim();
	}

	return 0x449E34;
}
```

2023-05-28 15:34 UTC, Starkku approved these changes

2023-05-28 15:35 UTC, Starkku approved these changes
Took a liberty of implementing the feedback from my prior review and attempted to address the problem with building anims playing prematurely etc. after deploying a mind controlled vehicle. Unsure if the fix for that is complete but it appears to do the job.

2023-05-28 15:47 UTC, MortonPL reviewed
A minor comment about names - we don't use the Hungarian notation.

2023-05-28 15:47 UTC, MortonPL commented on src/Ext/CaptureManager/Body.h
> +		bool bRemoveFirst, AnimTypeClass* pControlledAnimType = RulesClass::Instance->ControlledAnimationType, bool bSilent = false);
```suggestion
		bool bRemoveFirst, AnimTypeClass* pControlledAnimType = RulesClass::Instance->ControlledAnimationType, bool silent = false);
```

Aside from p for pointers, I don't think we use (and should use) the Hungarian notation for variables/arguments.

2023-05-28 15:47 UTC, MortonPL commented on src/Ext/CaptureManager/Body.h
>  	static bool FreeUnit(CaptureManagerClass* pManager, TechnoClass* pTarget, bool bSilent = false);
```suggestion
	static bool FreeUnit(CaptureManagerClass* pManager, TechnoClass* pTarget, bool silent = false);
```

2023-05-28 15:47 UTC, MortonPL commented on src/Ext/CaptureManager/Body.cpp
> +			if (pTarget->SetOwningHouse(pManager->Owner->Owner,!bSilent))
```suggestion
			if (pTarget->SetOwningHouse(pManager->Owner->Owner, !silent))
```

2023-05-28 15:47 UTC, MortonPL commented on src/Ext/CaptureManager/Body.cpp
> +	bool bRemoveFirst, AnimTypeClass* pControlledAnimType, bool bSilent)
```suggestion
	bool bRemoveFirst, AnimTypeClass* pControlledAnimType, bool silent)
```

2023-05-28 15:47 UTC, MortonPL commented on src/Ext/CaptureManager/Body.cpp
> +				pTarget->SetOwningHouse(pOriginOwner, !bSilent);
```suggestion
				pTarget->SetOwningHouse(pOriginOwner, !silent);
```

There are more uses of `bSilent` above this diff, but I can't mark them in suggestions, so they have to be changed manually.

2023-07-09 09:30 UTC, merged