vxl turret shadow
Phobos-developers/Phobos pull request #868
Opened 2023-05-08 12:27 UTC by Super-StarX

2023-05-08 12:35 UTC, Super-StarX commented
![TurretShadow](https://user-images.githubusercontent.com/42611604/236825005-94992628-445f-4f82-83bf-36555626d8b8.gif)

2023-05-09 08:34 UTC, chaserli submitted a review, later dismissed
1. I don't think a toggle is even needed
2. Consider units only should suffice
3. The algo seems to be a bit flawed:
Your version:
![ezgif com-optimize (6)](https://user-images.githubusercontent.com/9932846/237040737-802dbb81-e82c-48d6-8169-cc957e624894.gif)

Corrected version:
![ezgif com-optimize (7)](https://user-images.githubusercontent.com/9932846/237040839-cd55293b-a2f4-49b0-a313-e0bb5322b32e.gif)

2023-05-09 08:39 UTC, Metadorius commented
IDK I think being able to toggle shadows is a good thing. Maybe even expand it onto a per-voxel basis.

2023-05-09 10:22 UTC, Super-StarX commented
> 1. I don't think a toggle is even needed
> 2. Consider units only should suffice
> 3. The algo seems to be a bit flawed:
>    Your version:
>    ![ezgif com-optimize (6)](https://user-images.githubusercontent.com/9932846/237040737-802dbb81-e82c-48d6-8169-cc957e624894.gif)
>          
>            [
>              
>            
>                ![ezgif com-optimize (6)](https://user-images.githubusercontent.com/9932846/237040737-802dbb81-e82c-48d6-8169-cc957e624894.gif)
>              ](https://user-images.githubusercontent.com/9932846/237040737-802dbb81-e82c-48d6-8169-cc957e624894.gif)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://user-images.githubusercontent.com/9932846/237040737-802dbb81-e82c-48d6-8169-cc957e624894.gif)
> 
> Corrected version: ![ezgif com-optimize (7)](https://user-images.githubusercontent.com/9932846/237040839-cd55293b-a2f4-49b0-a313-e0bb5322b32e.gif) [ ![ezgif com-optimize (7)](https://user-images.githubusercontent.com/9932846/237040839-cd55293b-a2f4-49b0-a313-e0bb5322b32e.gif) ](https://user-images.githubusercontent.com/9932846/237040839-cd55293b-a2f4-49b0-a313-e0bb5322b32e.gif) [ ](https://user-images.githubusercontent.com/9932846/237040839-cd55293b-a2f4-49b0-a313-e0bb5322b32e.gif)

我认为这是一个逆天行为, 你可以在你自己的分支上硬编码宇宙万物

2023-05-09 10:31 UTC, Super-StarX commented
Slope and other turret work will be done in next. Of course,Specifying whether displays the shadow of each body can also be done easily here

2023-05-09 13:42 UTC, chaserli commented
> 我认为这是一个逆天行为, 你可以在你自己的分支上硬编码宇宙万物

I don't see why you are getting so irritated. This is a bug fix, and giving each bug fix a global and a local toggle is no less ridiculous than not having a toggle at all.

I agree with @Metadorius, more specifically 
* The toggle should be on a per **voxel** basis, i.e. parsing the art entries
* The toggle should also include the option to disable the shadow of the **body**

![ezgif com-optimize (8)](https://github.com/Phobos-developers/Phobos/assets/9932846/841e3620-f9b6-4c2e-bf4e-b84852c98a42)

2023-05-09 15:34 UTC, Super-StarX commented
不知道你为何觉得我是在irritated, 群里的大家笑得都可开心辣, 我觉得你先别急着阴阳, 要是戳着你那内心了我抱歉, 我只是单纯的觉得在一个公开平台上跟当自己家似的改属实挺逆天的罢了。看起来你也挺喜欢帮助别人完成没做完的工作, 我寻思你也可以把这个pr关了

2023-05-09 15:44 UTC, Metadorius commented
Guys, cool off please, conflicts won't do any good. Both a global toggle and a per-unit toggle are useful. I also don't think there's any ill intention in helping finish the PR, but if you want to finish it yourself just say so.

2023-05-09 15:46 UTC, Metadorius commented
> This is a bug fix, and giving each bug fix a global and a local toggle is no less ridiculous than not having a toggle at all.

It's not, a global toggle is a "default" toggle, many things in the engine are done like this.

2023-05-09 16:02 UTC, chaserli commented
> 不知道你为何觉得我是在irritated, 群里的大家笑得都可开心辣, 我觉得你先别急着阴阳, 要是戳着你那内心了我抱歉, 我只是单纯的觉得在一个公开平台上跟当自己家似的改属实挺逆天的罢了。看起来你也挺喜欢帮助别人完成没做完的工作, 我寻思你也可以把这个pr关了

你厉害，我给你大拇哥。论逆天没你们这个圈子你们这些小团体逆天，这是贴吧B站逛多了上来讨论问题不对事先人身攻击一波心里不爽是不是。我本来还想着这么重要的功能不能再直接给你代码细节提意见，所以只是大概提两点想法。怎么着？”公共平台当自己家似的改“这话都说出来了，那好啊，你这么看不惯我参与维护这个项目，直接把我从Phobos-developpers里面踢出去不就得了吗。

红警2这个游戏只是我生活中的一小部分，我又不做mod也不玩对战，你破防不了我。我可以从现在开始再也不碰这个游戏，你能吗

2023-05-10 02:30 UTC, Super-StarX commented
乐啦, 自己先一句 "我不知道你为啥急了" 现在又标以是我喜欢 "不对事先人身攻击", 倒是丝毫不提是不是自己有什么问题, 转而攻击是我组建攻击性的封闭小团体在攻击你。"你破防不了我" 但是这里与discord上倒是通篇充斥标准破防言论, 简直爆笑, 现在可不止群友辣, 到处都在讨论了。
没想到我两句话破防mo圈魔改第一人倒是广泛引起了广大mod爱好者对这位phobos掌门人·mod规范制定者·爱心帮忙完善逻辑的善人·mod圈唯一清醒的到的标杆的讨论与不满。
不过谁敢看不惯你啊, 谁敢对phobos贡献巨佬提出质疑嗷, 倒是你玩不玩游戏管我啥事, 你又干啥不让我玩游戏？谁还不是打游戏是为了自娱了, 你不做mod还可劲指点mod制作还挺自豪嗷, 怎么破防了说话都不清醒了。我可不敢自称什么红警圈大牛, 这称号不就是你一直在心中自诩的吗
应舆论再补充几句: 事实上大家做红警mod都是业余的，也就你一个人在这里认为别的mod制作者离了红警就会嗝屁吧。也就他一个人在这里认为别的mod制作者离了红警就活不成了。还搁这儿闹退坑威胁, 我看他是觉得mod圈离了他就不行了。太酷辣, irritator

2023-05-10 05:25 UTC, chaserli commented
> 您猜怎么着，我还没用力，他就全招了

我还纳闷呢，就这么点小事至于对我上攻击性，原来如此。那你应该早点撕啊，何必等到现在。

> 乐啦, 自己先一句 "我不知道你为啥急了" 现在又标以是我喜欢 "不对事先人身攻击", 倒是丝毫不提是不是自己有什么问题,

乐啦，贵圈的大字报小作文虽迟但到，有一天终于打到我头上来了啊。这回看看是什么情况，拆包，挪用，还是悬崖不会画？

> 转而造谣是我组建攻击性的封闭小团体在攻击你
> 群里的大家笑得都可开心辣, 
> 现在可不止群友辣

”众所周知，中国的红警圈子就是一个论坛加上乱七八糟的qq群，剩下的全是边缘的组团取暖的拆包小鬼和菜逼“ 醒醒，世界不是围着你转的，游戏圈子不是以你们为中心的，口嗨一波自我麻醉真当全中国除了你们没人玩没人改这个游戏玩了是吧。

> 没想到我两句话破防mo圈魔改第一人倒是广泛引起了广大mod爱好者对这位phobos掌门人·mod规范制定者·爱心帮忙完善逻辑的善人·mod圈唯一清醒的道德标杆的讨论与不满

没见过世面这可真是太酷啦，一个在中文论坛上没说过几句话的，一个不用qq的没加过什么乱七八糟群的，只在discord上的某个频道发言的，练习红警两年半的，学习编程时长不到一年的，说出去都没人听说过的玩家能被贵圈注意到其存在，而且还对其如此睁眼说胡话，只能说是游戏修改的门槛过于低，稍微有点成就感就不知道天高地厚了。

> mo圈魔改第一人

谁是你们摸圈的了，魔改第一人是你封的吧，我改过什么了，改过什么有技术含量有营养有新意的东西了，还第一人，怕是你说的这个圈子只有一个人吧。这个mod玩家体量有多大你比我清楚吧，什么时候我能在这上面排得上号

> phobos掌门人·mod规范制定者·

时无英雄，竖子成名，如果不是没人维护了会轮到我这种人上来当maintainer吗？翻翻我提交过的代码，有哪个是有技术难度的，有哪个跟你们所谓的”私人修改整合包“沾过边的，什么不写标签，护盾，AG=no，AI脚本索敌逻辑什么的是我写的吗，什么Ares逻辑覆盖是我这种水平的人会写的吗。我迄今为止贡献的新功能你一直手就数的过来，哪一个跟这些沾边了，有哪一个指定什么所谓的规范了。

Phobos是社区项目，不是我一个人的，凝结所有贡献者和维护人员的尝试和思考。每个提新功能的我不可能会去反对，我自己不感兴趣或看不懂的或拿不定主意的我不会发表任何意见。如果合并到主分支后出现问题我会尽量地去修复。
Phobos is a community project, the house is not just mine, it represents the efforts and ideas of all contributors and maintainers. I woudn't oppose anyone who proposes new features, and I will not comment on those that I am not interested in, cannot understand, or cannot make up my mind about. If there were issues after merging into the main branch, I would try my best to fix them.

> 爱心帮忙完善逻辑的善人mod圈唯一清醒的道德标杆

看不惯你当初直接提啊，要上攻击性早点上，我不带改你一个字母的。
另外你们明明什么都懂，出了问题一个个袖手旁观。

>  你不做mod还可劲指点mod制作还挺自豪嗷

敢问哪路modder知道我的存在？我又知道哪位做mod了？哦哦，原来是在PR下提交review意见啊，那抱歉，且不说我稍微懂点mod制作皮毛，就算我是什么都不懂的，作为普通玩家我也照样有理由有资格提意见，采不采纳是你的事情，合不合理可以讨论，觉得我说的不对就事论事批评我说服我。
上来第一句先来波攻击，再扣一波帽子，啧啧，好眼熟啊

> 我可不敢自称什么红警圈大牛, 这称号不就是你一直在心中自诩的吗

给着一个边缘人捧上大牛的头衔，这不是直接戳中你心中所想了嘛，你们看不惯我无非是我既不是活跃的玩家又不是modder没什么水平还忝列项目开发者

> 事实上大家做红警mod都是业余的，也就你一个人在这里认为别的mod制作者离了红警就会嗝屁吧。也就他一个人在这里认为别的mod制作者离了红警就活不成了。还搁这儿闹退坑威胁, 我看他是觉得mod圈离了他就不行了

同样的话从你们嘴里说出来和被你们攻击的人嘴里说出来，普通人会信哪个，刚入门做了点不完美的东西直接被喷到体无完肤的转头拥抱新生活的，还是一天到晚鼓捣这个游戏活跃到不行的动辄拿着规矩去压人的。这个游戏缺了谁都照样玩，这个”圈子“缺了谁都照样转，新功能新特性新修复，该有的东西不会少。一个无名之辈说不玩了，还让圈子大佬感觉到是在”退圈威胁“，这眼神真是好。

最后提醒一下，你们说的问题不是我弄的，如果真的有请指出来我会进行改正，如果不是的，指出来在哪我也会尽量帮助改。提PR我也不带审的能过就过。具体问题请找具体的代码位置，搁这攻击我于事无补。当然，如果你非要认为造成你们认为的不稳定性的根源都在我，那我悉听尊便卸甲归田，还望贵圈大佬们能扛起大旗，重振往日雄风

2023-05-10 05:34 UTC, Thrifinesma commented
> 时无英雄，竖子成名，如果不是没人维护了会轮到我这种人上来当maintainer吗？翻翻我提交过的代码，有哪个是有技术难度的，有哪个跟你们所谓的”私人修改整合包“沾过边的，什么不写标签，护盾，AG=no，AI脚本索敌逻辑什么的是我写的吗，什么Ares逻辑覆盖是我这种水平的人会写的吗。我迄今为止贡献的新功能你一直手就数的过来，哪一个跟这些沾边了，有哪一个指定什么所谓的规范了。
既然提到了我写的东西，那我说一句，我可没说你，我只是趁此机会发表一下我对Phobos的观点罢了

2023-05-10 06:21 UTC, Super-StarX commented
能看得出来你是深受广大网友"迫害"想偏安一隅结果偏碰上我这么个看不惯就爱直说的人,结果被你恶心的广大网友均出来叙述你那种种历史,有一说一我之前还真不知道你这事迹这么多,瓜吃不少,我本来就单纯的看你这说话刺头罢了。
顺便看了两眼你的大作文,这么长还特意虚构篡改回复,此番恶意揣测也的确很符合你给我的印象
> 乐啦，贵圈的大字报小作文虽迟但到，有一天终于打到我头上来了啊。
> 醒醒，世界不是围着你转的，游戏圈子不是以你们为中心的，口嗨一波自我麻醉真当全中国除了你们没人玩没人改这个游戏玩了是吧。
原来我是在挂人？原来我是代表什么圈？噢噢我看懂了,别别别,您这自骂没必要给我看,我不爱听,不过您的这自我描述确实颇有一点之前还完全看不到的自知之明
> 说出去都没人听说过的玩家能被贵圈注意到其存在
窝趣!你可出名辣,你不知道吗,不过雀氏,我也是才知道你这么出名的,毕竟马甲多
> 谁是你们摸圈的了，魔改第一人是你封的吧，我改过什么了
窝趣!我原来是摸圈的哈哈哈哈我头一次听说。我是在心灵终结3ini吧发逻辑图了还是成天二改心灵终结测试gif了,哦三轮还得求你做逻辑呢,那没事了,我不知道你改啥了
> 有哪一个指定什么所谓的规范了。
快把这个页面翻到最上面,看看你自己说的第一句话是啥,每4句话清空一次记录,你是文心一言？
> 上来第一句先来波攻击，再扣一波帽子，啧啧，好眼熟啊
> 你们看不惯我无非是我既不是活跃的玩家又不是modder没什么水平还忝列项目开发者
这句更是笑喷,您太看得起自己了,首先其他玩家我不清楚,但我至少对你是哪的什么开发者丝毫不在意,从第一句话我就只是在表达我看不惯拿公共平台phobos当自家后院的行为罢了,倒是你先捡骂然后说我irritated,然后偷换概念说我针对你,甚至我还是代表什么圈子在针对你,您也太同样看得起我啦,我很赞赏你这种尊敬你我他的行为,给你大拇哥。
倒是听说您很喜欢对别人评头论足,所以是mod圈唯一清醒的道德标杆
> 刚入门做了点不完美的东西直接被喷到体无完肤的转头拥抱新生活的
是新瓜!快讲讲!!
> 这个游戏缺了谁都照样玩，这个”圈子“缺了谁都照样转
你这不是很明白吗
> 还让圈子大佬感觉到是在”退圈威胁“
啊？不是你自己说的吗, 听说你也不是第一次喊着要什么退坑退圈退游了, 我不清楚嗷
> 你们说的问题不是我弄的……搁这攻击我于事无补。当然，如果你非要认为造成你们认为的不稳定性的根源都在我，那我悉听尊便卸甲归田，还望贵圈大佬们能扛起大旗，重振往日雄风
与本文内容无关的内容请去该去的地方回复, 这里不受理你收到的那广大网友的不满

2023-05-11 09:33 UTC, Metadorius commented on YRpp
I think you don't need to update YRpp, that's why the compilation fails.

2023-05-15 19:42 UTC, Metadorius requested changes

2023-05-15 19:42 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		ValueableVector<bool> ShadowIndexs;
1. This tag lacks documentation.
2. The correct spelling is `ShadowIndices`.

2023-05-15 19:42 UTC, Metadorius commented on src/Ext/TechnoType/Hooks.cpp
> +		}
```suggestion
	if (!pExt->ShadowIndexs.size())
	{
		pThis->DrawVoxelShadow(pVXL, idx, angle, a5, a4, &a3, pMatrix, a9, pSurface, pos);
	}
	else
	{
		for (auto index : pExt->ShadowIndexs)
		{
			auto hva = pVXL->HVA;
			Matrix3D idxmtx = *pMatrix;
			idxmtx.TranslateZ(-hva->Matrixes[index].GetZVal());
			pThis->DrawVoxelShadow(pVXL, index, angle, a5, a4, &a3, pMatrix, a9, pSurface, pos);
		}
	}
```

2023-05-23 13:25 UTC, Super-StarX commented on src/Ext/TechnoType/Body.h
> +		ValueableVector<bool> ShadowIndexs;
> 1. This tag lacks documentation.
> 2. The correct spelling is `ShadowIndices`.

Thanks for pointing out the problem

2023-05-23 22:22 UTC, Metadorius commented on src/Ext/TechnoType/Body.h
> +		ValueableVector<bool> ShadowIndexs;
No problems. Still have to add documentation though 😛

2023-06-15 16:34 UTC, Starkku commented
Took a liberty of fixing the issues with documentation and a couple of other small code style things.

This feature is currently only coded to work with VehicleType turrets so documentation reflects that.

------------------------

### Voxel turret shadows & body multi-section shadows

- Vehicle voxel turrets can now draw shadows if `[AudioVisual]` -> `DrawTurretShadow` is set to true. This can be overridden per VehicleType by setting `TurretShadow` in the vehicle's `artmd.ini` section.
- It is also now possible for vehicles to display shadows for multiple sections of the voxel body at once, instead of just one section specified by `ShadowIndex` by specifying the section indices in `ShadowIndices`, which defaults to `ShadowIndex`.

In `rulesmd.ini`:
```ini
[AudioVisual]
DrawTurretShadow=false  ; boolean
```

In `artmd.ini`:
```ini
[SOMEUNIT]      ; UnitType
TurretShadow=   ; boolean
ShadowIndices=  ; list of integers (voxel section indices)
```

-------------------------

There's also currently a bug (at least on my end) where the turret shadows for non-jumpjet units are drawn at clearly wrong coordinates. In addition the shadows overlap each other (very notable with turret + barrel combos) and create darker than normal patches of shadow)
![spin](https://github.com/Phobos-developers/Phobos/assets/1392346/3d61e09a-0271-4187-a76b-b0f72d60c66b)
![image](https://github.com/Phobos-developers/Phobos/assets/1392346/81e36b0f-3571-48ce-99f9-801d4d3d16f3)

2023-06-16 02:20 UTC, Super-StarX commented
> ok I will check, tks. 
I think the shadows overlap seems not should not be the responsibility of this PR, it is an vanilla problem occurs when you overlap multiple units/voxels together. Player can use this to find out if there are many jumpjet gathering there.

2023-06-16 17:37 UTC, Starkku commented
The offset issue is resolved, it had to do with TurretOffset values not being divided by 8 like game usually does.

2023-06-16 19:55 UTC, Metadorius approved these changes

2023-06-17 00:11 UTC, merged